<html>
<head>

<title>
No nukes!
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<p><font face="Times New Roman, Times, serif" size="4">Bush pushes deadliest form of energy ever devised</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>No nukes!</b></font></p>
<p><font face="Arial, Helvetica, sans-serif" size="2">July 6, 2001 | Page 10</font></p>

<p><font face="Times New Roman, Times, serif" size="3">GEORGE W. BUSH'S energy plan is a disaster for the environment. Its goal is to gut regulations and let the oil and gas industry run wild. But even worse in some ways is its encouragement of the nuclear power industry--the deadliest form of energy ever devised.</P>
<P>Here, STEVE LEIGH explains what's wrong with nuclear power--and how the "No Nukes" movement fought the power bosses the last time around.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<P>DICK CHENEY fell over himself praising nuclear power in a speech to atomic industry bosses on May 22.</P>
<P>"One in five homes in America runs on electricity generated by the nuclear industry...efficiently, safely, with no discharge of greenhouse gases or emissions," Cheney declared. Cheney went on to favor "the expansion of nuclear energy in the United States as a major component of our energy policy." His plan would "streamline" regulations, especially for new plants at currently existing sites.</P>
<P>You would never know it to hear Cheney, but for more than 20 years, the nuclear power industry has been in decline. And for good reason.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<P>IN 1979, the industry experienced its worse accident to that point--the partial meltdown of a nuclear reactor at Three Mile Island, near Harrisburg, Pa.</P>
<P>The impact was enormous. More than 100,000 people had to be evacuated from the area. A recent study has found much higher rates of cancer and leukemia among people who lived downwind of the plant during the accident.</P>
<P>After Three Mile Island, opposition to nuclear power--promoted by an active and vibrant antinuclear movement--became the majority opinion in the U.S. Antinuclear activists and unions of atomic workers spearheaded demands for tougher safety regulations that helped raise the cost of doing business for the bosses--to the point that new plants stopped getting built.</P>
<P>In spite of the claims that atomic energy would eventually become "too cheap to meter," it's now plain that nukes are more expensive than coal, oil, gas or wind power.</P>
<P>Cheney and Bush want to reverse nuclear power's decline by handing out subsidies to the bosses. </P>
<P>Among other proposals, they want to extend the Price-Anderson Act, a 1950s law that limits the bosses' liability for nuclear accidents to $7 billion. Without that law, no nuclear plant would ever have been covered by an insurance company--and there would be no nuclear power industry today. In fact, experts estimate that damage from a full-blown nuclear accident could run as high $300 billion. </P>
<P>But thanks to Price-Anderson, a nuclear accident could leave an entire state uninhabitable--but the nuclear industry wouldn't have to pay for it. No other industry has this kind of protection--because no other industry is as potentially dangerous as nuclear power.</P>
<P>The nuclear industry, of course, claims that its new reactors are safe. But it's been saying that for years. Its claims about safety were lies 20 years ago. And they're lies today.</P>
<P>The safety problems are built in to this form of power production. "The colossal amounts of heat generated in reactors, by the splitting of uranium fuel, is kept carefully regulated by large amounts of cooling water and by special control rods," wrote John Berger in his Nuclear Power: The Unviable Option. "Without its cooling water, a reactor core gets so intensely hot that even if shut down, it continues to get vastly hotter until it melts. This can lead to a major catastrophic discharge of radioactivity to the environment."</P>
<P>Three Mile Island is far from the only catastrophic accident recorded by the nuclear industry. </P>
<P>The worst ever took place in 1986 in Chernobyl, Ukraine. Hundreds of thousands of people were directly affected. Radiation eventually spread to every country in the Northern Hemisphere, and a whole generation of Eastern Europeans is still suffering the results. The economic cost of this one accident was three times higher than all the gains of the entire nuclear industry during the history of the former USSR.</P>
<P>There were many other misses and near misses. The Enrico Fermi plant in Michigan nearly suffered a catastrophic meltdown, leading to a song titled "We Almost Lost Detroit."</P>
<P>Even today, the nuclear industry's safety record is no better. Between 1996 and 1999, an estimated 90 percent of reactors in the U.S. operated in violation of government safety regulations, according to a Public Citizen study. As late as 1997, flammable silicon foam was used as a fire barrier penetration seal in virtually all operating nuclear plants in the U.S.!</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<P>AND IT isn't just plant meltdowns that threaten the environment and human life. Nuclear waste is equally dangerous. </P>
<P>One waste accident destroyed thousands of acres in the southern USSR decades ago.</P>
<P>A nuclear waste accident could "cause 140,000 cancer deaths, contaminate thousands of square miles and cause over $500 billion in offsite property damage, not including the financial costs of health damage," a Brookhaven National Laboratory study concluded.</P>
<P>The likelihood of such an accident is much greater than the industry claims. Brookhaven estimates that the probability of a nuclear waste accident causing 20,000 deaths is about 1 in 125. The likelihood of the kind of accident that took place at Chernobyl was estimated at 1 in 18,000.</P>
<P>This is one of the main problems with nuclear power--the disposal of waste products. In spite of industry claims, no one has discovered a safe way to keep this material away from humans for the tens of thousands of years necessary before it is no longer dangerous. The transportation of waste to a disposal site is also very risky for all areas that it passes through.</P>
<P>In fact, atomic energy is dangerous at every stage of its development. Uranium mining is devastating for miners and their families, who regularly get cancer from breathing radon gas and whose homes are often surrounded by or built on uranium waste, called "tailings."</P>
<P>Plus, each stage of nuclear power development puts more radiation into the air and water, raising the risk of cancer for everyone.</P>
<P>While giving lip service to conservation and the use of renewable energy sources like solar and wind power, Bush wants to cut the budget for these programs by as much as 50 percent next year.</P>
<P>So if nuclear power is so dangerous and is only kept alive by government subsidy, why are Bush and Cheney pushing it? </P>
<P>One reason is that their friends stand to make a great deal of money from producing it. The nuclear industry is big business. It's closely tied to the rest of the energy industry, with Exxon and General Electric being two of the biggest players.</P>
<P>"GE, which supplied many of the reactors when U.S. plants were being built in the 1970s and 1980s&#133;is ready with its licensed Advanced Boiling Water Reactor," <I>Forbes </I>magazine reported recently. "GE Nuclear is a segment of GE Power Systems, which raked in $15 billion in revenue for the company in 2000."</P>
<P>Obviously, it's harder for these bosses to sell a free fuel like the sun or wind. But the push for nuclear power goes even deeper. </P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<P>THE NUCLEAR power industry also functions as a kind of public relations wing for the nuclear weapons industry.</P>
<P>For example, President Dwight Eisenhower claimed during the 1950s that his "Atoms for Peace" plan would "hasten the day when the fear of the atom will begin to disappear from the minds of the people." In spite of the rhetoric at the time, scientists knew that nuclear power would never be economically viable. The only reason it was developed at first was to justify the horrifying results of nuclear research that led to the atomic bomb.</P>
<P>With the Cold War against the ex-USSR over, the U.S. needs an even stronger justification to maintain nuclear weapons. If U.S. rulers are to remain the world's top cop, they need nuclear weapons--and nuclear power is seen as a way of convincing people of the need for continuing the nuclear industry. </P>
<P>Nuclear power is the most dangerous form of energy production possible. But even more benign sources of power--such as solar and wind and different methods of conservation--will be distorted as long as we have a system based on profit instead of human need.</P>
<P>In the short term, we need to oppose the Bush-Cheney energy plan that promotes profit at the expense of the environment and human life. In the long run, we need a rational energy policy. </P>
<P>But to achieve that, we need a society with different priorities--ultimately, one controlled and run by working people to meet their own needs instead of corporate profit. We need democratic control of all aspects of the economy, including energy.</P>

<?php include "../../legacy-includes/BottomNavLinks.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
