<html>
<head>

<title>
Labor against war
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="4">Veterans speak out at Chicago labor meeting</font><BR>
<font face="Times New Roman, Times, serif" size="5"><b>Labor against war</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">January 24, 2003 | Page 5</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>THE BUSH administration's war drive against Iraq is bound up with a war at home. And U.S. unions are one of the main targets. From Bush's use of Taft-Hartley against the West Coast dockworkers, to the post-September 11 bailout offer to airlines that gave management another stick to demand concessions, the White House has been ready and willing to use the "war on terrorism" as an excuse for stepping up attacks on organized labor.</P>
<P>And as always, if Bush gets to launch his new assault on Iraq, the U.S. soldiers on the front lines whose lives will be at risk will be mostly working class.</P>
<P>In early January, more than 100 unionists--elected officials, staffers and rank-and-file members--came together in Chicago to form a new organization, U.S. Labor Against War, that plans to organize a union presence in the wider antiwar movement. The group's formation is a reflection of the coming together of antiwar unionists in New York and other cities, as well as the wave of antiwar resolutions passed by different union bodies.</P>
<P>The night before the founding meeting, more than 100 people came together to hear a discussion of the issues and challenges facing labor's new antiwar movement. Here, <I>Socialist Worker</I> prints excerpts from the presentations of two of the speakers, Dan Lane and Bill Davis.</P>
<B><P>DAN LANE</B> is a veteran of the Vietnam War. During the mid-1990s, he was a leading rank-and-file activist in the struggle against A.E. Staley in Decatur, Ill.--one of several battles in the Illinois "war zone" that electrified the labor movement. <B>BILL DAVIS</B> is the former national coordinator of Vietnam Veterans Against the War. Today, he is chief steward for International Association of Machinists Local 701 at UPS in Chicago.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3">
<B><P>DAN LANE</P></B>
<P>IN JULY of 1965, I joined the Marine Corps. At that particular time, I actually lived in a boys' home. This was the way out for most of us--I would say 80 or 90 percent of the young men went into the service. It didn't have anything to do with the fact that there was a war going on or being brave or anything. It was just a natural progression of things for us coming out of that situation. </P>
<P>But at the same time, I don't think I can ignore the fact that growing up, especially in an almost military atmosphere, I remember seeing quite frequently the John Wayne movies about World War II and the Korean War and all the glamour and the heroism. I think that's important to mention.</P>
<P>That's why people from George Bush's staff went to Hollywood right after 9/11, and said, "This is what the agenda is." And if everybody checks out the movies or TV, there's a very strong pro-government, pro-war mood. </P>
<P>At the same time, the experience I went through was that it wasn't only what I was seeing on Saturday afternoon, but what was also going into the classroom--how history was taught, and what wasn't talked about, and that whole perspective you get as a young adult.</P>
<P>Just like a lot of other people at 17 years old, you believe the government is doing the right thing, and you see the movies, and you listen to your history teachers, or just about anyone in power. So I went into the war believing that this was where I should be. </P>
<P>Shortly after finishing basic camp, I ended up in Vietnam. I was in the infantry, part of the Rangers. I saw a lot of things. I was wounded a couple times. Some very dear friends of mine who were in my outfit got hit pretty bad. Anyway, I was evacuated, not because I was wounded physically. I just couldn't deal with it anymore. I couldn't deal with seeing people die, with seeing children die. </P>
<P>But how fucked up they've got your mind! Less than 48 hours after leaving the hospital, I reported to Camp Lejeune and signed a waiver back to Vietnam, because I didn't feel that I had completed what I needed to complete--that I hadn't lived up to the expectations of being a Marine and a man. </P>
<P>So I spent another year over there. The first seven months I somehow got through. This was during 1968 and the Tet offensive. I was at the battle of Khe Sanh and a couple other places.</P>
<P>Before it was all over, during my last months, I was having a very difficult time. But instead of keeping it in, it came out. And the way it came out was I ignored the officers. I ended up being court-martialed before all was said and done. Thirty days in the brig, and I was busted from a sergeant down to a private. </P>
<P>I ended up coming back to the United States. The bad thing is that what you see over there and what you feel over there, you can't talk about. I expressed it in certain ways. And the only help at that time was to go into the VA system--and electrical shock treatment was how they dealt with people with post-traumatic stress. </P>
<P>So I went into isolation--into myself. And the difficult thing about it was that people didn't want to have anything to do with me. I literally had people that I ran into on the street occasionally who said, "I heard about what you guys did." That was the generalization. And there was basically no support system that I was aware of at the time--although I found out later about groups like Vietnam Veterans Against the War.</P>
<P>That was where it stayed, down inside of me. I had a very difficult time holding a job. Part of the symptoms of post-traumatic stress disorder is that it's very difficult to stay anywhere very long. I went though probably 22 jobs in a matter four years. Anyway, that is where Vietnam took me.</P>
<P>I don't want to spend a lot of time on my activities around Staley, but I do want to mention a couple things. I was personally involved at Staley, and to me, it was like another war. It was like I was fighting for my life to survive. It's tough being locked out for three or three-and-a-half years, trying to exist on $60 a week. And thank goodness there were a lot of people out there who helped financially, but it's still is a very dramatic thing to go through. </P>
<P>But it wasn't just Staley. At the time that we were locked out, Caterpillar went out not too long after that, and not too long after that, Bridgestone went out. And this is just in the community of Decatur. I remember coming up to a meeting up here with folks in the ISO and some other organizations, and we were talking about the "war zone." And the "war zone" at that time was not only Decatur. If you went south, the miners were on strike. And if you went north, there were other Caterpillar plants that were on strike. </P>
<P>There were 25,000 people who were on strike--25,000 people who worked for corporations that were doing quite well, but that had decided: "Hey, we can make more money." And it didn't matter what people went through.</P>
<P>In the last three decades, there has been a horrible shift in workers' jobs--jobs that have been eliminated in this country and taken somewhere overseas or turned over to technology. And for those who remain with jobs, it's just like at Staley, where the big offer was that they had 800 people there, and there was going to be 300 when all was said and done, and the 500 they'd replace with scabs. </P>
<P>That's what people deal with every day when they go into negotiations now. It isn't about negotiations. It is about them trying to dictate to you what you're going to have. And the unfortunate thing about this is that all too often, we hear about the Staleys, the Caterpillars, the mineworkers and those struggles, but those are just a few. What we don't hear about is the situations where workers basically accept it and go on. </P>
<P>I guess the message behind that is that this is about all workers. It doesn't matter if you drive a school bus, it doesn't matter if you're out in the fields picking cherries or vegetables, or if you're working in the service sector. We all suffer. We're all being dragged down. </P>
<P>And it's important to say that this didn't just happen yesterday. It's all too easy to say that Bush did it. I'm not asking you to vote for Bush. But what I'm saying is that this is the way of life in this country and has been for a long time. </P>
<P>The fact is that there's a war that is continually waged against workers. And it's not only against those who are actively at a job. It's being waged against the elderly, it's being waged against those who are on fixed incomes, against people who are poor. It's a war where not everything happens when people come out on strike. It's also a war where some politician signs off on a piece of legislation, like they did under the Clinton administration, and they tear up the welfare system. </P>
<P>I remember reading about how in New York, they would lay off one group of people and send in another group who had formerly been on welfare to do the work for less. And when it was all said and done, they were making less money than they were on welfare, because they didn't have insurance anymore, and they weren't getting help with food.</P>
<P>In this new era of global capitalism, you have the president of the United States say not only that we're the superpower, but don't even try to resist in any shape or form. The fact is that what they're saying to the people of the United States and the world is that they have the right to make a decision about what piece of the pie that everybody's going to get. And if you disagree with that, we'll take any measures to stop you.</P>
<P>That's the era that I think that we're in right now. It's nothing new--it's just much more arrogant and out front. It's very clear what George's intentions are. And they're no different from anybody in the past. But they have gotten to a place where they don't have to use the cloak and daggers and the smokescreens. </P>
<P>The other thing that just amazes me is that the media has bought into this completely. Not that the media isn't bought and paid for, but there's no questioning at any level from the major media. And that's what people are buying--not everybody, but people are buying it. </P>
<P>I think that the biggest thing I would underline tonight, more than anything else, is the importance of connecting the dots--connecting them for yourselves and connecting them for other people. It's important to take that message out and go beyond just simply passing a resolution. Resolutions are a first step, but it needs to go further than that. One of the things that we saw at Staley is that when we shut the company down during the in-plant strategy, it wasn't because somebody sent a paper out, but because we went out and talked to people and organized them.</P>
<P>There's one impression that I have a hard time getting out of my mind--one of the most horrific things since I returned from Vietnam. It was when I turned on CNN back in 1991, and I watched Baghdad being hit by bomb after bomb after bomb. And as horrible as that looks, I saw that happen in Vietnam. I saw what those kind of bombs can do. I could feel the ground vibrating, I could hear the explosions. </P>
<P>But what was more horrifying is that in a matter of less than 100 hours, 40,000 people were killed immediately as a result of those bombings. Not to minimize what happened at the World Trade Center, but that's over 10 times as many people killed.</P>
<P>And that doesn't count the people after that--who died over the next weeks or months. And it doesn't talk about the devastation that's been done since 1991 with sanctions and boycotts. That's what's horrifying when you put all this in perspective.</P>
<P>And what did George say? When he was giving all his speeches, especially early on, he said you have to be ready to go. This is not something that we're going to back down on, and it may take generations. In other words, it will be your children as well as you that have to commit to this battle against terrorism. That's scary. Because that says that there's been a declaration of war on the world for an indefinite period of time. </P>
<P>Recently, in Britain, two men who were supposed to drive a locomotive with military supplies refused to. And I have to believe that they knew when they did that, there was the potential that they were going to lose their jobs. But what they didn't want to be involved with was taking that train down there, loading up munitions and driving it somewhere else, because those munitions were going to be used to bomb Baghdad. </P>
<P>We should recognize the courage that it took for those people to do that. And we also have to look at that and say that we need to take those steps. Sometimes, those are not steps that we look forward to. Nobody appreciates spending time in jail because of a sit-in. But the fact is that direct action in the plants and the federal buildings and in the streets--that is what's going to happen. </P>
<P>I don't know if it's going to stop the bombs from being dropped--the airplanes may be on their way right now. And I don't want that to happen. But I also know that this is just the beginning of this new era. </P>
<P>We have to get that message out, and we have to be prepared to take whatever steps are necessary. We need to get out there, get in front of the capitalists and show them that workers do control this country and they do control the world.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3">
<P><B>BILL DAVIS</B></P>
<P>This is like a dream come true, being here tonight among people who are union members and are also against the impending war.</P>
<P>I was a staff sergeant in the U.S. Air Force and served from 1966 to 1970. I spent a year in Vietnam in 1968 and a year after that in Thailand in 1969. I returned to the United States in 1970, and I joined Vietnam Veterans Against the War--while I was still active in the military.</P>
<P>I really appreciate being here tonight. I always wanted to see more antiwar activity going on during the Vietnam War and all the successive U.S. invasions or incursions abroad. So this is something that by itself is a very historic occasion.</P>
<P>I come from a family of people who have been in the U.S. military since the Revolutionary War. And the Vietnam War was when that all ended--as far as I know, nobody in either branch of my family went into the military after that particular war. </P>
<P>The military as it's comprised today is different from the military that I was in. That military was fueled by a draft, first the quota system, and later by the lottery. But that military had similarities with today--in that the majority of the people doing the dirty work and suffering the casualties are children of the working class and children of the poorest elements of this society. </P>
<P>The military is, and always has been, a microcosm of our society. Unfortunately, it focuses the worst elements of our society. In essence, it's the sewer that runs through our society. It's fueled by racism, sexism and homophobia. It encourages excessive use of drugs and alcohol. This is a place that we don't want to send our friends and our children. It's the most dangerous job in the world. There's no OSHA overlooking what goes on, and there's no EPA. </P>
<P>In fact, there's not really any justice at all. The Uniform Code of Military Justice is neither uniform, nor just. There's no appeal in the courts. Once something's happened to you in the military, it goes on and on. There are people who are in Fort Leavenworth from the Vietnam War for fragging officers and a variety of other things, and they'll spend their lives in this military prison. We used to say that spending your time in the military was like being a living beverage bottle--once they were finished with you, they just toss you out, no deposit, no return. </P>
<P>There's a lot of discussion about veterans' benefits. Veterans' benefits have always been given out with an eyedropper and taken away with a steam shovel. Every year, they get slimmer and slimmer, and it has nothing to do with whether it's a Republican or a Democratic government. Year after year, administration after administration, those benefits are shredded and cut to nothing. Benefits that were given to World War II veterans would be a substantial way of life now for a lot of veterans.</P>
<P>They place so many restrictions on benefits that it's impossible to follow the routine and maximize them. Those benefits are not enough to pay, obviously, to go to Harvard or MIT. Those benefits will put you in the community colleges, where you would have went anyway. </P>
<P>The recruiters border on pathological in terms of their ability to be honest with the people that they're recruiting into the military. They'll lie to you when they don't even have to. They'll tell your parents, your brothers and your sisters anything that they think they want to hear in order to get you to join the military. Even if you sign papers and decide that you don't want to be in, of course, you get out, but don't trust them to tell you that. </P>
<P>I'm told that it's a lot better now. A person goes in the military and if they're not fit, they get rid of them right away. I say, well, isn't that great--they leave the military with a piece of paper that says they weren't fit to serve, and that they have no useful place in society. That's something they carry with them the rest of their lives. </P>
<P>In the Vietnam era alone, 375,000 men and women received a variety of discharges, all coded less than honorable. There was no hearing, no trial, no review. They were just given this bad paper and turned loose on the street. I had an honorable discharge and had a very difficult time finding work. I know for a fact how difficult it is for people who were given these bad papers. </P>
<P>The draft probably won't come back, but they have an economic draft. The military is looked upon as one of the few ways out of the inner city, one of the few ways out of Appalachia, one of the few ways out of Wyoming or West Virginia. If you look at states with decreasing population and lowest mean incomes, that's where you'll see the highest number of people joining the military. It's an alternative to nothing. </P>
<P>And frankly, it's very difficult to tell a young man or a young woman who faces no life and no probability of life and a very difficult road to hoe that they shouldn't go in the military. It's very hard. The best you can do is give them all the advice. We don't call it counter-recruiting. The high schools and the colleges don't like to hear "counter" anything. So we call it pre-enlistment counseling. </P>
<P>This bunch that are in power now want to do for foreign policy and the future of this nation far beyond what the Dulles brothers accomplished in the 1950s. Any devious and outlandish sort of thing that's possible will be done. They're going to do whatever they want to do, unless people in this country say they can't. </P>
<P>And we have much broader opposition to war going into this era then we had going into the Vietnam War. This time, a much broader section of the American people will be in the streets and already are. And I'm so proud that the American union movement is part of that. I know we're all going to be working with our locals and our councils, trying to get more involvement. </P>
<P>One of the slogans that we've been using since 1967, when the organization was founded, is "Decent benefits for all veterans." We do a lot of work with the homeless--one in every three homeless men that you see on the streets in Chicago is a veteran.</P>
<P>They're either Vietnam or Vietnam-era veterans, but then we were appalled at the quick turnaround after the Gulf War--how many of these guys literally got off the plane and were homeless immediately. It points out that they had nothing going for them when they went in the military, and the same chances were available to them once they came back. We want to see an end to that.</P>
<P>Veterans have always been a two-edged sword in our society. They're a voice of reaction, such as the American Legion, and later on, the VFW, which was formed, by the way, as a progressive alternative to the American Legion. The American Legion was never a friend of unions. In a lot of places in West Virginia, where I come from, people wouldn't join the American Legion, because they were strikebreakers and vigilantes and Ku Klux Klan--all one in the same. </P>
<P>But veterans have also become a progressive voice. Working-class veterans comprised the movement during the Depression of the 1930s that marched on Washington. And they didn't just demand for themselves, they demanded for the entire class--housing, food and the basic things that are guaranteed us as human beings. The back home movement after World War II, the veterans' antiwar movement during and after the Vietnam War--these are all legacies of veterans and the working class, and they're something that we should be proud of. So we say, "Decent benefits for all veterans" and "No blood for oil."</P>

<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
