<html>
<head>

<title>
Rebellion in Bolivia
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="4">Protests topple a president</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>Rebellion in Bolivia</b></font></P>
<P><font face="Times New Roman, Times, serif" size="2"><b>By Tom Lewis</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | October 24, 2003 | Page 12</P>

<P><font face="Times New Roman, Times, serif" size="3">BOLIVIAN PRESIDENT Gonzalo S&aacute;nchez de Losada fled La Paz October 17 as hundreds of thousands of Bolivians overran the capital city demanding his resignation and prosecution. Like so many other of Washington's fallen henchmen in Latin America, S&aacute;nchez de Losada scrambled aboard an airplane and scurried to safe haven in the U.S.</P>
<P>The ex-president had been a gung-ho supporter of "neoliberalism"--the name for the free-market policies of privatization, "labor flexibility" and savage budget cutting championed by U.S. officials and their servants at the International Monetary Fund and World Bank. S&aacute;nchez de Losada left behind a country in turmoil--where the stakes remain high, not only for Bolivia's rulers, but also for Washington and its imperialist interests in Latin America.</P>
<P>On the heels of S&aacute;nchez de Losada's resignation, the Bush administration issued a travel warning for Bolivia. Ominously, the Pentagon also announced that it was sending an "assessment team" to investigate whether U.S. troops would be necessary "to protect American citizens" living in Bolivia.</P>
<P>At the center of the three weeks of mass protests that forced out S&aacute;nchez de Losada was the popular rejection of the government's contract with a transnational consortium to export natural gas to the U.S by way of Chile and Mexico. The consortium, Pacific LNG, is made up of British, Spanish and Argentine corporations. A U.S. company holds the contract to transport Bolivian gas from Chile to Mexico.</P>
<P>The PNG contract legalizes the foreign pillage of Bolivia's most important natural resource. Under its provisions, Bolivia would keep only 18 percent of the $1.5 billion in annual income expected to be generated by gas exports to the U.S.--nowhere near the standard 50 percent, say Bolivian economists.</P>
<P>The gas sold to PNG, moreover, was fixed at a price well below current market value. The difference means a loss of additional billions of dollars to Bolivia over the life of the contract.</P>
<P>It was S&aacute;nchez de Losada who, two days before his first presidential term ended in August 1997, signed the PNG deal. Ironically, the current protests against gas privatization toppled him less than one year into his second term--after spending five years out of office.</P>
<P>Demonstrators won significant concessions from the besieged president before driving him from office. S&aacute;nchez de Losada agreed to hold a national referendum by the end of 2003 for Bolivians to decide whether to renationalize the country's natural gas--and he agreed to modify existing legislation to make renationalization possible.</P>
<P>S&aacute;nchez de Losada also said yes to establishing a Constituent Assembly as a regular component of the Bolivian political system. These gains had actually been won by early Wednesday evening, October 15. </P>
<P>But the protests didn't stop. Popular anger at the brutal slayings carried out by S&aacute;nchez de Losada's troops--as more than 70 people were killed in the uprising--demanded retribution.</P>
<P>Felipe Quispe, head of the Bolivian Peasant Workers Union (CSUTCB), declared, "We will not negotiate with a murderer." On October 16 and 17, wave after wave of indigenous fighters descended on La Paz from El Alto, the poverty-stricken satellite city of La Paz situated higher up in the Andes.</P>
<P>Miners from the same region, marching under the banner of the Bolivian Labor Confederation (COB), also advanced on the city. From the south and east came workers, peasants and coca growers, all focused on getting rid of S&aacute;nchez de Losada.</P>
<P>By the afternoon of October 17, downtown La Paz was overflowing. The workers' neighborhoods of the capital also emptied into the streets, and everyone pushed toward the presidential mansion. S&aacute;nchez de Losada snuck away into the night.</P>
<P>The insurrection resulted from several ongoing struggles that rapidly came together into a mass movement united around a common goal: recovering Bolivian gas.</P>
<P>On September 19, the Coalition for the Defense and Recuperation of Gas--the successor to the Coalition in Defense of Water and Life that successfully turned back water privatization in Cochabamba in April 2000--called a nationwide protest. More than 150,000 turned out in Bolivia's major cities, demanding that S&aacute;nchez de Losada break the contract with PNG.</P>
<P>The next day, military police attacked road blockades set up as part of an uprising by the indigenous Aymaras in Bolivia's high plain region. The soldiers' aim was to "rescue" a group of tourists who could not return to La Paz.</P>
<P>But the military's action resulted in seven deaths, including the killing of an eight-year-old girl. This atrocity led the Coalition in Defense of Gas to announce that it would support the indigenous rebellion.</P>
<P>It also prompted the COB to call for a general strike beginning September 29. The COB's general strike achieved spotty success at first. But as the strike became increasingly identified with the fight to reclaim natural gas from the multinationals--and as anger grew at the mounting numbers of indigenous protesters gunned down by the military--other social sectors joined in.</P>
<P>The struggle then quickly generalized throughout Bolivia's working class. By October 13, much of the middle class, too, came on board. The Catholic Church opened its doors to middle-class hunger strikers and joined the call for S&aacute;nchez de Losada to resign.</P>
<P>Among the immediate results of the mass protests was the COB's recovery of legitimacy after years of passivity and kowtowing to the political parties. The former COB leadership was voted out at its last national congress in April.</P>
<P>The new leadership proved itself under fire through its role in the current revolt. According to the progressive news service Econoticiasbolivia, the COB has been "converted into the undisputed head of the popular uprising."</P>
<P>The struggle will continue as opposition forces wait to see if Bolivia's new president Carlos Mesa--S&aacute;nchez de Losada's vice president--complies with several demands. These include repeal of laws privatizing hydrocarbons and agriculture; repeal of legislation that introduced labor flexibility into Bolivia; the rebuilding of Bolivian industry; and the repudiation of the U.S.-backed Free Trade Area of the Americas. Protesters are also demanding the prosecution of those responsible for the deaths among the protesters and cancellation of the law that criminalizes social protest.</P>

<p><font face="Times New Roman, Times, serif" size="4"><b>Oscar Olivera on the revolt:</b></font><BR>
<font face="Times New Roman, Times, serif" size="5"><b>"Neoliberalism has robbed us blind"</b></font></P>

<B><P><font face="Times New Roman, Times, serif" size="3">OSCAR OLIVERA is a national spokesperson for the Coalition for the Defense and Recuperation of Gas, based in Cochabamba. He became known around the world as a leader of the struggle that stopped Bechtel from taking over a privatized water system in Cochabamba.</P>
</B>
<P>THE FIRST great march to protect Bolivian gas took place September 19 and was called by us. More than 150,000 turned out nationwide. In Cochabamba, the Gas Coalition has subsequently provided the framework of the ongoing mobilization.</P>
<P>In reality, though, we shouldn't speak of the leadership of any of the major organizations. The people who have taken over the streets and highways have basically organized themselves.</P>
<P>Neoliberalism has robbed us blind. In his first term as president, S&aacute;nchez de Losada privatized everything except the air--all for the benefit of international capital and the Bolivian oligarchy.</P>
<P>The wealth represented by natural gas is our last hope to pull ourselves out of poverty and strengthen our own economic base. Bolivian gas should be used first and foremost to build a better life and a secure future for the Bolivian people. But this won't happen if the transnationals continue to own it.</P>


<?php include "../../legacy-includes/BottomNavLinks.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
