<html>
<head>

<title>
Report from the Gulf Coast
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<font face="Times New Roman, Times, serif" size="4">A <i>Socialist Worker</i> journal</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>Report from the Gulf Coast</b></font><p>

<font face="Times New Roman, Times, serif" size="3">THE DEVASTATION caused by Hurricane Katrina will be felt for decades on the Gulf Coast. So will the unnatural disaster that followed&#8212;the U.S. government's inept and inadequate response that doomed untold numbers of people. But the aftermath of Hurricane Katrina has also seen a remarkable grassroots relief effort, involving people throughout the region and across the country. <p>
<i>Socialist Worker's </i>Paul D'Amato, Meredith Kolodner and Eric Ruder traveled to the Gulf Coast to witness the devastation&#8212;and the grassroots relief effort. These are their reports, as they sent them to <i>SW </i>Online<p>

<font face="Times New Roman, Times, serif" size="3"><b>Daily journals below:</b><br>
<A HREF="#Day5">Day 5: Leaving Louisiana</A><br>
<A HREF="#Day4">Day 4: In Baton Rouge, La.</A><br>
<A HREF="#Day3">Day 3: In New Orleans</A><br>
<A HREF="#Day2">Day 2: In Covington, La.</A><br>
<A HREF="#Day1">Day 1: From Memphis to Jackson</A><p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<a name="Day5"></a><font face="Times New Roman, Times, serif" size="3"><b>Sunday, September 11</b></font><br>
<font face="Arial, Helvetica, sans-serif" size="4" color="#990000"><b>Day Five:</b></font><font face="Times New Roman, Times, serif" size="4"><b> Leaving Louisiana</b></font><p>

<font face="Times New Roman, Times, serif" size="3"><b>Entries for Day 3:</b><br>
<A HREF="#11-09a">9 a.m.: On the road north</A><p>

<a name="11-09a"></a><b>9 a.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>On the road north</b></font><br>
<font face="Times New Roman, Times, serif" size="3">After dropping Meredith at the airport the next morning, we continue northward. Along for the ride is Tim, the college student who along with Andy had found himself surrounded by troops pointing guns at him. He was also staying at Buddy and Annie's place in Covington and needed a ride back to his school in Memphis. Tim hitchhiked to the Gulf Coast after Katrina to volunteer. <p>
His story of the week he spent in the area confirms everything that we've experienced. Tim said that the Red Cross had plenty of supplies, but that their network to distribute it was inadequate. Red Cross volunteers, he explained, end up working about four hours a day, and then sitting around, because there aren't enough trucks and other vehicles to move the relief supplies to the hard-hit localities outside of bigger city centers.<p>
So instead, Tim went directly to the flood zone on Days 7 and 8 after the hurricane had hit&#8212;to help people trapped in those areas. He said that there were two docking areas where flat-bottomed boats were being launched to go out on "search and rescue" patrols. One was run by the Department of Natural Resources, which was doing its own thing that he felt was too slow, and not cooperating with citizens who were pitching in to help. <p>
At the other dock, boats were coming and going, manned by private owners&#8212;fisherman, locals who had boats for recreation, and those who bought boats and just came to pitch in. In his opinion, more people were being rescued by the private boats than the DNR boats, though he said he couldn't comment on the helicopter airlifting efforts because he wasn't involved in that. <p>
Tim said that on one day, he went out with some boats to help pull people in, saving 12 people. And the next day, clad in a bathing suit and without any shoes, he stood for several hours in the toxic soup to help guide boats and people with their belongings in and out of the makeshift harbor (really a freeway ramp dipping into the water).<p>
Tim's story illustrated what we had seen all week. Despite the immense capacity at the disposal of the federal government&#8212;the National Guard and Army troops, with all their vehicles and resources&#8212;their arrival in New Orleans didn't help people struggling to survive Katrina's wake. They came to perform a police function&#8212;to protect the homes of the well to do in rich neighborhoods and establish "order." <p>
It wasn't simply incompetence that hampered the government's response to Katrina. In reality, the government's response reflected the priorities of a system in which some people are more equal than others. <p>
Those who had the resources evacuated, and the police and National Guard came in to make sure that whatever they left behind was protected. And the city's poor residents&#8212;mostly Black, but also white&#8212;were left to fend for themselves. They had no choice but to band together&#8212;along with the volunteers who came from far-flung places&#8212;to save each other and defend their way of life from the natural and social disasters that engulfed them.<p>

<a name="Day4"></a><font face="Times New Roman, Times, serif" size="3"><b>Saturday, September 10</b></font><br>
<font face="Arial, Helvetica, sans-serif" size="4" color="#990000"><b>Day Four:</b></font><font face="Times New Roman, Times, serif" size="4"><b> In Baton Rouge, La.</b></font><p>

<font face="Times New Roman, Times, serif" size="3"><b>Entries for Day 3:</b><br>
<A HREF="#10-10a">10 a.m.: St. John's Coffee, Covington, La.</A><br>
<A HREF="#10-02p">2 p.m.: Southern University, Baton Rouge, La.</A><p>

<a name="10-10a"></a><b>10 a.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>St. John's Coffee, Covington, La.</b></font><br>
<font face="Times New Roman, Times, serif" size="3">The workers at the coffee shop where we worked on writing down the prior's day observations have been working without pay to keep the place open. It provides an air-conditioned place to sit, use the Internet and chat with people coming and going&#8212;which is a blessing for many Covington residents whose power has still not been restored. <p>

<a name="10-02p"></a><b>2 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Southern University, Baton Rouge, La.</b></font><br>
<font face="Times New Roman, Times, serif" size="3">In the afternoon, we drove to Baton Rouge to attend a meeting called by a labor-community group from New Orleans to begin discussions on how to respond to Katrina in terms of grassroots relief and fundraising, as well as getting the word out on what's really happening. <p>
Though we had to leave early to get to Jackson, Miss., by the end of the day, we got a chance to talk with activists and community organizers grappling with how to address the many dimensions of the crisis. One young woman pointed out that 40 percent of New Orleans residents are functionally illiterate, making it impossible for them to navigate the maze of FEMA forms they must fill out or read Web postings so they can be reunited with their families. <p>
Scott Weinstein, a Canadian nurse who came down after the hurricane to work in New Orleans, said that the country has become militarized, and so, instead of a competent response from civil agencies, which are severely hampered by spending cuts, the federal government provides a military response. <p>
In his opinion, what the Gulf Coast really needed was not Humvees but garbage trucks. The place is swarming with troops, but lacks trucks to haul out the rotting garbage everywhere, which constitutes a grave health hazard. <p>
The military with its bureaucratic organization, in fact, is contributing to the chaos. But he explained how the strong military presence in New Orleans had another purpose. Quoting Israeli Prime Minister Ariel Sharon, he said that the point was to establish "facts on the ground." The military occupation of New Orleans was one part propaganda and another part intimidation. The propaganda factor is to establish the idea that to get jobs done in an emergency, the military should step in&#8212;and that it's legitimate for troops to occupy cities routinely during disasters.<p>

<a name="Day3"></a><font face="Times New Roman, Times, serif" size="3"><b>Friday, September 9</b></font><br>
<font face="Arial, Helvetica, sans-serif" size="4" color="#990000"><b>Day Three:</b></font><font face="Times New Roman, Times, serif" size="4"><b> In New Orleans</b></font><p>

<font face="Times New Roman, Times, serif" size="3"><b>Entries for Day 3:</b><br>
<A HREF="#09-09a">9 a.m.: On the road to the West Bank</A><br>
<A HREF="#09-10a">10 a.m.: Algiers neighborhood in New Orleans</A><br>
<A HREF="#09-02p">2 p.m.: Algiers neighborhood in New Orleans</A><br>
<A HREF="#09-023p">2:30 p.m.: East Bank of New Orleans</A><br>
<A HREF="#09-04p">4 p.m.: Algiers neighborhood in New Orleans</A><p>

<a name="09-09a"></a><b>9 a.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>On the road to the West Bank</b></font><br>
<font face="Times New Roman, Times, serif" size="3">During our trip so far, we've met all sorts of people--needy evacuees who by turn are tired, dazed, stoic and simply happy to be alive. <p>
We've met generous volunteers from all over the country, such as the professional tree cutter who came from Michigan's Upper Peninsula to help people get their homes out from under the heavy timber. Or the global justice street medics from New England who made their way to the Gulf Coast to set up medical relief. We've seen the most incredible knots of trees, telephone wires and damaged homes in Covington. <p>
But today we were nervous. We were heading into New Orleans, where parts of the city were still under 10 feet of water--a toxic soup of raw sewage and floating bodies that the media reported on for the last week. What made us most jittery, though, was the heavy presence of armed forces--and the "you loot, we shoot" attitude, backed up by trigger-happy police as well as soldiers fresh from the streets of Baghdad and Falluja. <p>
We wondered whether we'd be turned away as we approached the causeway bridge that connects the north shore of Lake Pontchartrain to New Orleans. But the police and military guards at the bridge checkpoint waved us through with little hassle, after a quick look at our press passes. <p>
The causeway itself--a 20-mile engineering wonder&#8212;was eerily quiet at a time of day when it's usually packed with a steady stream of commuters heading to work. Other than one or two media trucks, we were basically surrounded by all sorts of police, Drug Enforcement Agency, Homeland Security, National Guard and Army vehicles.<p>
As the city came into view, we could see a half dozen helicopters in the distance, flitting from place to place. But from a distance, the city's skyline gives the impression that this city was like any other. <p>
As the elevated roadway we were traveling finally begins hovering over land instead of water, we were struck that the physical damage from the wind was worse in Covington than in New Orleans, underlining the fact that New Orleans' catastrophe was manmade. New Orleans escaped the worst of Katrina's high winds and torrential downpour. Even the storm surge was largely contained. What caused New Orleans' misery is the disaster behind the disaster--the city's non-plan for evacuation, the levee breach that happened when the weather was calm, FEMA and the Bush administration's bungling of relief efforts, and the iron repression handed out by the police and military to the city's poor residents who had the hardest time evacuating in the first place.<p>
As we hit the Huey P. Long Bridge that would take us to New Orleans' West Bank--where we planned on meeting up with Malik Rahim, a founder of Louisiana's Green Party, who is running a grassroots relief effort in the neighborhood of Algiers Point&#8212;we were scanning the AM radio dial for news. It turned out that every channel was carrying a live interview with the U.S. Secretary of Commerce, who repeated over and over again that the first priority for the city was to "create a healthy business climate." No mention of restoring electricity or water to the tens of thousands of homes in the parts of the city that didn't flood; no mention of making sure that food, water and ice get to people who still don't have adequate supplies; and no mention of medical help for the people stranded in those neighborhoods.<p>

<a name="09-10a"></a><b>10 a.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Algiers neighborhood in New Orleans</b></font><br>
<font face="Times New Roman, Times, serif" size="3">The historic neighborhood of Algiers is made up of row upon row of houses whose bright colors have faded--it's a divided neighborhood, racked by poverty and lusted after by developers. Of its 70,000 residents, probably 3,000 remain. <p>
As we were forced to turn off our route by a power line obstructing the next block, we realized that we had turned onto Ira and Tempie's street--the people we met in Mississippi. We threw the car in reverse to check on their house for them, as they asked us to do if we happened by. Thankfully, it looked okay.<p>
When we arrived at Malik's house, we were greeted by his partner Sharon, who beckoned us inside, offered us water and fruit, and thanked us for coming. She told us that Malik was out with some Danish filmmakers, and that he would be back soon. She was answering the phone, which was ringing off the hook, and trying to keep a semblance of civilized life despite doing without electricity for close to two weeks now. Her bright personality and strength, despite the circumstances, shone through, but it was clear that the situation had taken its toll. She explained that she hadn't really left their home for three days running. It was just too much to take in, she explained, seeing their neighborhood like this. <p>
Sharon had reason to be rattled. Four days earlier, a ship from the other side of the river broke loose and started barreling towards the levee that protects Algiers Point. Several tugboats, horns blaring, began trying to keep the ship from driving a hole in the levee. They did manage to protect the levee, and now a tugboat, beached and jutting into the air at a severe angle, stands as a monument to the episode. But the event scared many more people out of the neighborhood.<p>
Block by block, Algiers felt like a strange amalgam of creepy ghost town, police state and grassroots relief operation. On one deserted block, a storeowner had posted a sign reading, "We shoot looters." On another, residents sat in the shade of their porches, trying to escape the midday heat. <p>
Malik and the Danish journalists returned for a moment, and Malik invited us to tag along as he checked on residents and got in touch with others like him who are coordinating the delivery of supplies to those who don't have the vehicles or health to find their own. We followed him to a local free school to deliver some supplies. We talked to Suma, an older woman with beautiful graying dreadlocks who runs the People's Village Cultural Arts center school. She said she was going to have to leave to get some medical care. <p>
"I have seven children," said Suma. "I have grand- and great-great grand children. We'll regroup. Life's got to go on. Algiers Point, they want this whole thing. Who wants it? Developers. And who are developers? White folks. They can make a nice retirement area. I travel, and I've never seen houses stacked so close. They're going to bulldoze all these houses down. They don't want us here."<p>
Asked about how long the school has been in operation, Suma explained, "Our school goes way back to Jonathan Kozol. Children excel here. They excelled in the preschool, with the open classrooms. In the schools, the classrooms are so crowded--how can a child learn? And then they keep them drugged up on Ritalin. And when you have energetic children, they call them ADD. But that's what you want, you want energetic children. I'm a storyteller--I can quiet down a whole roomful of children.<p>
"We're just like the rats in a tank. They did research on rats by putting up these project buildings. You should've been here when the wind blew them down. And they're going to put up houses. How can houses house all the people that come out of project buildings that look like prisons? <p>
"There was a lot of looting here at the beginning, then all of a sudden, it was quiet. All the looters were gone. There was all kinds of shooting. I didn't see it, but word gets around. Police shooting people, people shooting people. And there were vigilantes in Algiers Point. It's a white area...They want to keep that area strictly Point. You go in there, and there's still houses that were plantations. We know better than to go in there at certain times."<p>
Chico, a tall and powerful-looking man wearing a colorful knitted hat, was standing and listening to the conversation. He suddenly burst in: "I've been all in there. I've been down all through it. When they had the barricades, and the woman kept calling on the phone, saying that people were shooting at them, that was a lie. That was a bald-faced lie. I've been all through there, and I've distributed food to elderly white people back there. I must have distributed over half a million dollars worth of food. <p>
"I've been everywhere even before FEMA and all that came. So they can't tell me...We've seen it all. We've got a body still, over by Arthur Monday Clinic, and they never moved it. They know about diseases and all this other stuff. I crossed that bridge [into the East Bank]-- my sister was trapped, and I got through the checkpoint and got them out. So I've been everywhere.<p>
When we asked if the most of the help had come from residents or the Red Cross and FEMA, a smile flashed across Chico's face.<p>
"Oh, yeah," he said. "We live for this. This is our home. We aren't going nowhere. I was here when the storm hit, and I've been here. They can't tell it better than I can tell it. They weren't even here when the storm came. It hit us, and we felt it. You want to hear some stories. We got elderly people who went out to the shelter, and they're all back here. My momma went through it all.<p>
"People have asked me, 'How could you get all this stuff.' I told them it was top secret, but I got it. I told the military, 'I can feed you better than you feed yourself.'"<p>
Malik came along and asked us to follow him again. He wanted to show us something. He took us to the Arthur Monday clinic. "This is the health clinic, you know," he said. "It's got a chain on it. We have a dead body right here that's been here for 12 days. They can't even come up with a body bag. We've been covering it up [with a piece of corrugated metal], and that's all it is. All they've done is put an 'X' on it. It's not like it's floating in the water, or they can't get to it. They just refuse to pick it up. And this has terrified people. That's all they did, come and put that 'X' on there."<p>
Malik went to the body and removed the piece of corrugated metal with a big red "X" on it, and then pulled off some of the blanket. We saw the decomposing body of what appeared to be a man, maybe in his 30s or 40s.<p>
"You can see the maggots eating his corpse up," he said. "It's been 12 days out in this hot sun, and they won't move him. There's no reason for this. It's just blatant neglect. If it was a white guy, this would have been up. This is the kind of stuff that's terrifying people and making them not want to stay here. Right by a health clinic, and they won't even pick it up. And it's getting hotter and hotter. And I know you all smell it."<p>
He put the blanket and the metal back on. "We put this on to stop the wind, because every day, the wind would blow the blanket off, and the kids pass by here and are seeing this," he said. "So we put this on. We called the police. And all the police did was put that X there. They didn't even try to move it. Just put a little 'x' on it, like 'x' marks the spot, and we're going to leave it. <p>
"They got about 18 bodies like this around Algiers, and there's no reason for them to be here. We've got the military walking around, and they're securing everything. And they're talking about the health crisis. They're <i>creating</i> the health crisis."<p>
But the really terrifying question is what caused these 18 deaths. Algiers, on the West Bank of the Mississippi River, hasn't had the catastrophic flooding of the East Bank. No one drowned or was trapped in a house on this side of the river. So we asked Malik how these bodies came to be here.<p>
"Most of them were killed by the police, or by these vigilante groups, when they were around," he said. "There wasn't any flooding. Most people killed over in Algiers were killed either by the police or by vigilante groups. Because if you're Black, and you have a weapon, you're dead. They would literally shoot you down. <p>
"The only time we had order is when the National Guard and army came in. Before that, it was pure chaos. I cannot express how evenhanded they've treated everybody. It isn't like the police, where there's one set of justice for whites, and another set of justice for Blacks.<p>
"We have Black doctors who tried to get in here from Atlanta, and they were turned around. And then we had a group of white guys who came in to give us a hand, and they were allowed to come through. <p>
"And we had some other white guys come in from Texas, and they could cross the bridge where none of us could cross--to go over and rescue Robert King Wilkinson, a member of the Angola 3. They swam to his house to get him. He had spent 10 days in his house living off peanut butter. And he was in much better shape than many others. But he spent 10 days with no way of contacting anybody. These guys were told by the Coast Guard that they had checked the area and nobody was there. Brandon, he just took it upon himself to swim there, and go check, and that's how King was rescued. It's just sad the way they're doing this."<p>
Malik served in Vietnam in 1965, going over with the first U.S. combat troops. He was a member of the Black Panther Party, and more recently, he ran for city council as a Green Party member. His house is on the side of Algiers Point that is predominantly Black. Across the street (his side of the street is filled with modest working-class homes) is a new development--a gated community with several big houses in various states of construction--which he told us divides the side he lives on with the other side of the point that is predominantly Black. <p>
Malik told us that the average income of a white family is about $48,000 (a low figure in itself), and the average income of a Black is just under half of that. We went into Malik's house and talked some more. <p>
"Before the storm, we had two-and-half days to evacuate 120,000 people," said Malik. "When they gave the evacuation order, they knew there were over 100,000 people that had no way of getting out of the city. So the city just abandoned them. They could have provided public service buses. They could have made two trips and got everybody out of there. Everybody could have gotten out. <p>
"Then they go and tell them at the last minute that they're going to open up the Superdome. When they opened up the Superdome, we had 12 hours before the hurricane, and it was already raining. And they made people stand out in the rain for four hours to get in there.<p>
"Everybody know that the sanitation problem was going to be horrific in the Superdome, because studies had been done about what happened if a category 4 or 5 storm hit New Orleans. We were blessed that it didn't hit us, alright. The eye of that hurricane didn't come through New Orleans. Because if it hit here, there would have probably been at least 100,000 people dead, easily. <p>
"They told you when you went to the Superdome to bring food for five days. But this happened at the end of the month, and at the end of the month, poor people don't have any food. How did they expect people to bring food when they knew they didn't have any? So, they created the atmosphere of looting, because everybody said, 'Damn, I'm not going to get caught like this, I'm going to find something.' <p>
"First, they went and stole the food, then after that, they started taking anything that they could barter with. If I can steal some TVs, I'll steal some TVs, because I need to get my family out of here. And if I've got to give you some TVs, some rings, some watches or whatever, I'm going to barter to get out of here. If I've got to puncture a whole in your gas tank to get gas so I can get out of here, that's what I'm going to do. <p>
"And that's what it was. More people were shot by shooting in the air trying to get attention, than were shot by looters, and most of the looters were shot and killed by vigilantes. I had a confrontation, first, around the corner and, second, in front of my door with a group of white vigilantes. The police came and didn't tell them nothing. In fact, they were able to walk out with their weapons. <p>
"I mean, that's just the way it was, you know. Again, the hard part about it was that we had a group of doctors coming in, but because the doctors were Black, they were turned around. In this area, maybe between three and 12 people were killed by vigilantes. It's sad because it's some of the people I knew, and I never would have thought they would have done this kind of thing. And I said, 'What are you all trying to do? Are you trying to start a race riot?' <p>
"A few of us came out here and tried to prevent it from turning into a race riot. And when they saw that whites were coming in to help us, they saw that it wasn't a Black and white thing."<p>
Buddy Spell, a radical lawyer and activist in the Louisiana Activist Network, who lives in Covington across Lake Ponchartrain, stopped by with Andy Stern after failing to procure a boat to go into East New Orleans to check on a rumor that 1,500 people trapped in a local high school had drowned. He gave Malik his card and said that he was ready to defend anyone who had been framed. Malik said there were already a "bunch of them." He said that a young guy was accused of shooting at a Blackhawk helicopter with a .22, and may be facing treason charges. <p>
Malik then talked about his relationship to the Green Party. "I'm one of the founding members of the Louisiana Green Party," he said. "Soon as I came back to New Orleans, it was the very first thing I did, working with the little Green groups to organize and form a Green Party. I ran for city council under the Green Party, and I got 6,000 votes. And we spent maybe $5,000. In August, we went and became a registered Louisiana political party."<p>
Malik said that during the presidential election, the Greens were split between Ralph Nader, David Cobb and John Kerry. Malik said that he didn't endorse one or the other because he didn't want to divide his community. But he particularly wasn't happy with Kerry. <p>
"I couldn't see telling anyone to go with Kerry," he said. "Skull and Bones, and too much power. I just can't see going with some Democrat. I just can't see supporting a Democrat." <p>
Buddy Spell chimed in: "I can't believe we haven't met yet. I was just telling these folks that there was good news and bad news. The good news is the Republicans are going to lose Congress. The bad news is the Democrats are going to win." Malik practically finished Buddy's sentence and laughed. <p>
One of the first things you notice about Malik is his deep, booming laugh, which you hear often if you spend even an hour with him. Sharon, his partner, is by contrast quiet, but you can see compassion and strength in her eyes. While Malik has been out doing various runs to deliver aid, bring aid back, set up makeshift clinics and so on, Sharon has handled all incoming phone calls, organized all media contacts, and quietly made sure that the house/relief center is maintained on a daily basis. She told us that God has helped her the whole way to keep strong. "Whenever I have started to run out of something that we need here, every time someone shows up with it," she said.<p>
She and Malik seemed to be rushing around, nonstop, all day until curfew. The last run every day is the ice run. As we left, though, we helped them set up a generator that had been brought over from Camp Casey in Covington that afternoon. But they'll still be doing the ice run, to deliver ice to the dozens of families that need it.<p>

<a name="09-02p"></a><b>2 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Algiers neighborhood in New Orleans</b></font><br>
<font face="Times New Roman, Times, serif" size="3">Again and again, throughout the day, we watched the heavy presence of armed forces everywhere. We saw giant convoys of Army trucks, and smaller convoys of guys with their helmets on, their rifles standing up by their knees. <p>
At Malik's house around 2 p.m., a tan Army Humvee pulled up and asked where the "relief center" was. Not long after, a foot patrol of 10 soldiers, some of them looking like 18- or 19-year-olds, came through, going house to house on a foot patrol, M-16s slung on their backs. They again asked where the "relief center" was, and we referred them to a Veterans for Peace activist, who explained that, yes, Malik's place was a relief center. <p>
Then, to our surprise, they asked Sharon, who was now talking to them, if they could refer cases of people in need of aid or medical help to them--because, they said, they weren't equipped to deal with it. They also said that they hadn't yet received any order to evacuate the area. <p>
We talked to one soldier, who was from Oklahoma and 19 years old. He said that he hadn't been to Iraq, but that most of the other guys in his patrol had gone. Later in the afternoon, another big military truck came by, and a couple soldiers got out and asked Malik if they could send people who needed help to his house to get supplies, or to the clinic he was helping set up at a nearby mosque. <p>
After we returned to the house, Sharon took us out back to the garage and showed us huge stacks of water, food, baby supplies and other donated goods. For the next hour or so, Paul and Eric helped reorganize everything so that it's accessible, and to clear the way for more stuff that's being delivered that afternoon from the new Camp Casey that's sprung up in Covington. Meredith joined one of the Danish reporters to check out the flooded East Bank.<p>

<a name="09-023p"></a><b>2:30 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>East Bank of New Orleans</b></font><br>
<font face="Times New Roman, Times, serif" size="3"><i>Meredith writes: </i>A Danish documentary maker we met at Malik's was planning to drive into the flooded parts of the city. He made room for me in his car, and we set off for the Greater New Orleans Bridge.<p>
Military checkpoints were preventing non-emergency vehicles from entering the flood zone in downtown New Orleans, but at some access points, they had left only unmanned trucks and school buses parked across the road. The off-road capability of the filmmaker's rented SUV finally got some use, and we made our way around the blockades and over the bridge.<p>
The streets around the New Orleans Convention Center were saturated with military vehicles. There were jeeps riding solo, open-air trucks carrying a few dozen soldiers, and enormous convoys that went on for blocks. Every federal agency you can name had trucks rolling around, including U.S. Customs, the DEA, and the ATF. <p>
We walked over to the Convention Center, which was swarming with law enforcement from various states, cities and counties. Four soldiers from the Oklahoma National Guard were providing security for the military command and control center located in front of the Convention Center. <p>
"I just got back from Iraq a few months ago," one of the younger guys told me. "I did a year tour there. I was stationed mostly around Falluja, and we were in a combat battalion, escorting convoys, searching for bombs and weapons. We were lucky--we didn't lose anyone out of my unit. <p>
"To be honest, this has been harder than being in Iraq. We got to the Superdome about 10 days ago, and we weren't supposed to be doing security, but it was a mess--really horrible. There were all these people looking at you, and they haven't done anything wrong, and they just look destroyed--you can just see it in their eyes. And we couldn't really do anything for them." <p>
A higher-ranking soldier from the Oklahoma National Guard came over and joined our conversation. "I was in the Superdome," he said. "It was a bad deal. People were dying right in front of us. I'd go out through my line and tell people to drink water, but people were just dying from heat exhaustion. People were holding up their babies, a woman showed me her three-month-old baby, and she was just dying right there in front of me, and there was nothing I could do. It was like being in an insane asylum."<p>
After we spoke for a while, the younger soldier came back and asked me not to use either of their names because his captain had just told him off for talking to "the media."<p>
We drove away from the Convention Center, and down Bourbon Street into the French Quarter. This area escaped the flooding, and wind and tree damage was much less severe than in other parts of the city. There was one bar that had stayed open through the hurricane and was continuing to defy the no-liquor ban imposed under martial law. Several people who stayed in the city through the hurricane were sitting unsteadily on bar stools. They said they had been drinking since the day after the storm passed through. <p>
Joe, the bartender, said he had been working 12-hour days since the hurricane and would keep on doing it to make sure the bar didn't close. He said the cops tried to shut down the bar a few times, but had backed off in the face of video cameras and reporters taking notes. One night, the cops came into the bar and pepper-sprayed a few people to try to get them to walk outside the bar and break curfew, so they could arrest them, but everybody stayed put.<p>
A man in his 50s who worked construction, known as "the ladder man," said he had walked 15 miles to get out of the city. He had tried to get the $2,000 promised to disaster victims by the Red Cross, but he didn't have proof of residence, and he was told he would have to go to Houston. Most people in the bar said they weren't leaving the city because they knew it would be impossible to get back in.<p>
A guy named Jim walked up and announced to the bar that FEMA chief Michael Brown had been replaced "by some general." "About fucking time, fucking idiot," said Tim, sitting outside, with a shot of Jameson and a bottle of Amstel Light next to him, trying to hold back his long grey hair with a paper clip. "Who's the next idiot going to be?" <p>
A young white guy named Paul, who told me he usually wouldn't be caught dead in the bar, because it was a sports bar and hardly had any women in it, wanted to make sure I knew that New Orleans was 70 percent Black. "At least it used to be," he said. "All them niggers got stuck up in that stadium, and I don't think they're coming back." The two guys sitting next to him seemed to share his racist hopes for a transformed post-flood New Orleans. <p>
Jacob, who was leaning against a lamp post, sipping a beer, responded, "The storm didn't hit like that, it didn't go like that, and we shouldn't go like that. We're all in the shit. We're all rebuilding here."<p>
We left the bar and headed south towards the Mississippi River. There were Army Rangers, wearing their signature maroon berets, moving slowly in formation, patrolling the empty streets. There were more New York City Police Department cars cruising around the deserted neighborhood than I've seen in New York all summer. <p>
Military encampments were set up all along St. Charles Avenue, with dozens of soldiers leaning on their guns outside the abandoned high schools where they were staying. A group of New Orleans cops were grilling burgers outside a station that had a banner hanging on the wall reading "Fort Apache." <p>
A few blocks south of the avenue was submerged in water. Trees covered the houses, many of them collapsed and ripped apart. A few Black residents, just blocks from the unoccupied law enforcement officers, were climbing over branches, trying to avoid the toxic water and pull the branches, by hand, off of their crushed homes. They looked frightened and overwhelmed. <p>
The sweet, sick, nauseating smell of rotting flesh was everywhere. It wasn't wafting around like most smells, coming and going in waves. It hung over the entire area, so strong that it seemed permanently embedded in the city's air.<p>

<a name="09-04p"></a><b>4 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Algiers neighborhood in New Orleans</b></font><br>
<font face="Times New Roman, Times, serif" size="3"><i>Paul and Eric write: </i>With only a couple hours until people started preparing to get inside to safety before the 6 p.m. curfew, Malik, Eric and one of the Dutch reporters went looking for ice. One business by the lake that makes large floats for the annual Mardi Gras parade was passing out bags, but when Malik told the man in charge that we needed enough for 15 people, he looked at us as if we were trying to hoard the ice--a totally pointless idea, of course, as futile as hoarding air. After all, ice in a cooler doesn't last but a day or so in this heat without electricity. <p>
"These guys are treating us like we're criminals," said Malik. "I'm never going back there, no matter how desperate I get for ice." Starting to get a little alarmed at the late hour, we rushed to another place that Malik thought might have ice. As we pulled up, Malik says we would have no trouble because he saw someone he knows. "Watch how different this will be," he told us.<p>
They directed us to back our vehicle in, and we loaded 40 or so bags of ice in. Malik was relieved, and we rushed--after a round of embraces, thank-yous and handshakes--to deliver to those in need. We drove to the houses where Malik knows people, and we asked everyone we saw along the way if they needed ice. Malik had obviously built up a great deal of trust and respect with the people in his neighborhood, even before the hurricane. Since the hurricane, his reputation has only grown.<p>
With the hour approaching 5 p.m., we needed to get on the road. But Malik asked if anyone knew how to get a generator running. So we stayed a bit longer to get the generator up and running, and then say our goodbyes. We told Malik that we would talk to people about his fantastic work. We all hugged and agreed to keep in touch. We drove away with some urgency to make sure that we got across the bridge before the troops fanned out to enforce the 6 p.m. curfew.<p>

<a name="Day2"></a><font face="Times New Roman, Times, serif" size="3"><b>Thursday, September 8</b></font><br>
<font face="Arial, Helvetica, sans-serif" size="4" color="#990000"><b>Day Two:</b></font><font face="Times New Roman, Times, serif" size="4"><b> In Covington, La.</b></font><p>

<font face="Times New Roman, Times, serif" size="3"><b>Entries for Day 2:</b><br>
<A HREF="#08-08a">8 a.m.: Newton, Miss.</A><br>
<A HREF="#08-01p">1 p.m.: Pine View Middle School, Covington, La.</A><br>
<A HREF="#08-04p">4 p.m.: Home of Buddy and Annie Spell, Covington, La.</A><br>
<A HREF="#08-09p">9 p.m.: Home of Buddy and Annie Spell, Covington, La.</A><p>

<a name="08-08a"></a><b>8 a.m.</b></font><br>
<font face="Times New Roman, Times, serif" size="4"><b>Newton, Miss. </b></font><br>
<font face="Times New Roman, Times, serif" size="3">When we saw Tempie and Ira the next morning, they greeted us warmly. But when we suggested that we go to a restaurant, they seemed reluctant. Then Tempie looked at us and sighed: "You know, it's probably not a good idea for us to go to breakfast together. This isn't Chicago, you know. This is rural Mississippi. You know, those civil rights workers were found the next town over&#8212;Philadelphia." Then she shuddered. <p>
Tempie grew up in another rural town in southwest Mississippi. "I ran a restaurant for white people, and I always had to enter through the back door," she said. "It's a good thing I'm a nice person. Of course, things aren't this bad in the bigger cities like Jackson, Meridian or Hattieburg." Things had changed a great deal since the civil rights movement, she said. But others remained a great deal the same. "Black people and white people in this part of Mississippi don't go to the same churches or get buried in the same cemeteries," she said.<p>
No doubt, James Chaney, Michael Schwerner and Andrew Goodman would be saddened to hear this some 41 years after they died together on a dark Mississippi night.<p>
The day before, Tempie and Ira had returned to their home for one hour to check on their belongings, and then left again to seek out a place&#8212;anyplace&#8212;to spend a few nights. New Orleans' West Bank didn't flood, but the wind damage was so severe that all electricity and water service was interrupted&#8212;potentially for several more weeks. <p>
Nature conjured up the hurricane-force winds that slammed into New Orleans, but the social diseases of racism and poverty largely determined who would survive and who would die, who lost property and who lost their entire livelihoods.<p>
Tempie hadn't spoken with her 90-year-old mother since the day before Katrina swept through. She called the nursing home where "Mama" was staying five different times, and each time they told her a different story&#8212;she was being airlifted, she was being bussed out of the area, she was being transferred to a hospital, and so on and so forth. "Lies. It was all lies," said Tempie. "The government let us down. FEMA is still letting us down."<p>

<a name="08-01p"></a><b>1 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Pine View Middle School, Covington, La. </b></font><br>
<font face="Times New Roman, Times, serif" size="3">When we got to Covington&#8212;a town on the north side of Lake Pontchartrain, across from New Orleans, and heavily damaged by the storm&#8212;we saw more examples of grassroots relief. <p>
Pine View Middle School had been converted into a relief and refugee center by antiwar activists and veterans on the bus from Camp Casey, after leaving the site of the vigil started by Cindy Sheehan in Crawford, Texas. <p>
There was a school bus from Tennessee, brought in by Plenty International, a grassroots relief organization based in Tennessee that brought volunteers. The bus was now being used to ferry supplies from another school in Covington (also a refugee center) to places such as Algiers Point on the West Bank in New Orleans. <p>
When we pitched in to help sort out piles of clothes that had been dropped off at the school, we met a woman from Tennessee, one from Oklahoma and another from Washington state. <p>
But we also saw the flipside to the many acts of generosity and the sense of solidarity expressed by locals and volunteers from across the country. Some people have been seen riding around in trucks at night with "looter-shooter" stenciled on the side, and we drove by a house that had a big American flag and a sign scrawled in black spray-paint: "You loot, we shoot." <p>
Gordon Soderberg, a member of the Mendocino County chapter of Veterans for Peace, who was a Navy medic from 1982 to 1991, is part of a team of veterans who have coordinated a major relief effort based in Covington. "This is murder by apathy," he said. He described FEMA as "just a bunch of $100,000 clipboard holders.<p>
"We got here seven days ago," said Gordon. "We first started at Rev. Atkins Park, about four blocks from the school. We set up during the day, and we started giving out all the supplies we had left over from Camp Casey. We set up a little kitchen there, made some rice and beans, and had hot food from people. <p>
"Down by the park is the poorest part of the community of Covington. They had no power, no water, no transportation. And they knew about this place, but they didn't think they were welcome because this place (Pine View Middle School) was only taking people from the most affected areas. The effect around here has been all tree damage, not houses flattened. A lot of death as well, but most inflicted by trees. <p>
"So the infrastructure's down. All the power's down, and the water is bad. Finally we're starting to get power, and the water will come up next. But when we first got here, there wasn't any power. You could get around because they had the streets cleaned, but no power and no water. We stayed there all day into dusk, and we started getting drive-by visits from people who weren't looking to get anything, they were just looking at what we had&#8212;the generator, etc. So we were feeling a little uncomfortable that the same people weren't coming around any more. And so then the police officer that's here now, she came by and said that we could help. So they invited us up to Pine View Middle School (where the Red Cross was set up).<p>
"We set up our generators, started cooking for them, brought the rest of our supplies in and backed them up on medical and stuff they didn't have. Then we started getting an influx of people who were coming in from the special needs shelter at the high school. We jacked up our Internet satellite setup and started sending out requests for help, saying, 'Here's what's really going on here, folks.'<p>
"Because of what we had done with Cindy Sheehan, Michael Moore picked up on it right away, and the thing's gone through the roof. We've rented a storage facility that we'll do the food bank out of. We're serving some eight to 10 cities with food drops every day. We're sending out independent medical people to go to places the Red Cross isn't getting to, and we're also reaching Mississippi.<p>
"In Covington, we're serving several hundred a day. There's a hundred people here today, and we're still doing drops at the park we started in. We're going to cities that have drop points for the Red Cross. They can't get it out, so they're allowing us to come in and grab it and move it for them. <p>
"So this is a grassroots effort. We're trying to dovetail right into what's left of Red Cross and FEMA that hasn't been destroyed by the Bush administration. When we got here and did what we did, the Red Cross people on the ground were overwhelmed. The people above them were trying to figure out how to help them deal with the crunch, and the upper-ups&#8212;the people above the people on the ground&#8212;didn't care. <p>
"The police department came here and told the local Red Cross site director to get rid of us. The Red Cross people on the site said, 'If they go, we go.' They could see that we were saving their fucking ass. So they went away, thought about it, came back the next day and shook our hand. We were already engrained, and there was no way to un-embed us. We haven't spoken to the upper-ups since."<p>

<a name="08-04p"></a><b>4 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Home of Buddy and Annie Spell, Covington, La. </b></font><br>
<font face="Times New Roman, Times, serif" size="3">Buddy Spell is a longtime Louisiana hellraiser, antiwar activist and defense lawyer. He was at Camp Casey in Crawford, Texas, until the hurricane hit his house in Covington, wrecked his car and&#8212;most alarmingly&#8212;separated him and his wife Annie from their 7-year-old for five harrowing days. Thankfully they are all reunited&#8212;and safe. <p>
Buddy is a member of the Louisiana Activist Network (LAN). LAN has organized a Peace Train to carry activists to Washington, D.C., for the September 24 national antiwar mobilization, but because no trains are getting into New Orleans, people will have to make their way to Meridian to board. "We may have less people than we would have, but we'll be there," pledged Buddy.<p>
The Louisiana Activist Network succeeded last year in making their state the only one in the nation to require depleted uranium testing for all deployed National Guard members. After the hurricane passed through, Buddy and his wife and fellow activist Annie hung a banner in front of their house that read, "Our National Guard is in Iraq and WE ARE HERE." <p>
"It was ethnic cleansing," said Buddy, referring to the government's response to Katrina's wake. "The good news is that the Republicans will lose Congress. The bad news is that the Democrats are going to win." <p>

<a name="08-09p"></a><b>9 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Home of Buddy and Annie Spell, Covington, La. </b></font><br>
<font face="Times New Roman, Times, serif" size="3">Andrew Stern, a freelance photographer who's been to Iraq a couple times on assignment, has been staying at Buddy and Annie's place at night and going into New Orleans during the day. He described horrible scenes of bodies floating in the murky water&#8212;or washed up and decomposing over the course of days.<p>
At one point, when Andy and his companion Tim were in the 9th Ward, Tim couldn't find his keys and, becoming alarmed, started to jog towards the place he thought he had left them. Also with them was a local resident, Jose, a Black man from the area who was acting as their guide in the city and has since evacuated to Houston.<p>
When Tim ran, an unmarked white Humvee down the road a bit suddenly made its way towards them and disgorged two armed men, who pointed shotguns at their chests. Their T-shirts said POLICE, but they had nothing else that identified them. "Do you understand that looters will be shot?" screamed one of the men, most likely from the New Orleans Police Department.<p>
"I've been in situations like this before&#8212;with police pointing guns at me&#8212;and I wasn't really afraid that I was going to get shot," said Andrew. "But this time, it really seemed like they were going to shoot me. I feel like their first impulse was to shoot unless we did some really fast talking.<p>
"I said, 'We are not looters!' And I don't know why, but I froze up and didn't say anything more. My friend Jackie, who shoots for <i>DemocracyNow! </i>said that we were press, and then we were surrounded pretty quickly by a couple guys from Border Patrol, a couple guys from DEA, and some soldiers&#8212;about 10 men altogether, all heavily armed and pointing their guns at us. We were totally surrounded. <p>
"Afterwards, I thought to myself that you'd have to be a pretty serious criminal to have this group of people surrounding you. They seemed to be debating whether to shoot us. They were accusing us of being looters, but we weren't carrying anything other than a video camera&#8212;we looked like media. The only thing that I could see that would make them think we were looters was that we had a Black guy with us, and that Tim was running. <p>
"There was a <i>Readers Digest </i>reporter that I was working with, and they had him come forward and had him pull up his shirt, and they were asking for ID. I just shuddered, thinking that if we coughed or sneezed, that would be it. <p>
"There was one point where our stories didn't match up, because we were saying we were press, and Tim was saying that he was with Veterans for Peace, and that was causing problems. Eventually they calmed down, probably because they saw our press IDs, and then they told us to get the fuck out of dodge, and left. <p>
"Jose said that he had been in situations like that many times in his life, but that particular one was the scariest. 'They were going to shoot you, and you're white,' he said. To him, that was just the most crazy situation he had ever seen."<p>

<a name="Day1"></a><font face="Times New Roman, Times, serif" size="3"><b>Wednesday, September 7</b></font><br>
<font face="Arial, Helvetica, sans-serif" size="4" color="#990000"><b>Day One:</b></font><font face="Times New Roman, Times, serif" size="4"><b> Memphis to Jackson</b></font><p>

<font face="Times New Roman, Times, serif" size="3"><b>Entries for Day 1:</b><br>
<A HREF="#07-11a">11 a.m.: South of Memphis, Tenn.</A><br>
<A HREF="#07-01p">1 p.m.: On the road to Jackson, Miss.</A><br>
<A HREF="#07-04p">4 p.m.: Jackson, Miss., airport</A><br>
<A HREF="#07-05p">5 p.m.: Jackson, Miss., Coliseum</A><br>
<A HREF="#07-08p">8 p.m.: Newton, Miss.</A><p>

<a name="07-11a"></a><font face="Times New Roman, Times, serif" size="3"><b>11 a.m.</b></font><br>
<font face="Times New Roman, Times, serif" size="4"><b>South of Memphis, Tenn. </b></font><br>
<font face="Times New Roman, Times, serif" size="3">An elderly white woman at the Wal-Mart just south of Memphis, off I-55, was checking the receipts of people leaving the store. As we left the store with supplies for Louisiana (diapers, baby formula, etc.), we told her that we were delivering the stuff to Covington, La. She told us that she had only left New Orleans a few weeks before, and shook her head as she pondered all the hardship that her friends and family were now suffering. <p>
As she was checking our receipt for the baby formula, diapers and feminine products that folks in Covington had requested, we told her jokingly: "You're not just going to let us walk off with this stuff?" Suddenly, she got a serious look, and whispered to us, "If it was my choice, I would."<p>

<a name="07-01p"></a><b>1 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>On the road to Jackson, Miss. </b></font><br>
<font face="Times New Roman, Times, serif" size="3">On the way to Jackson, we saw two military convoys, totaling about 18 small vehicles. It didn't seem all that impressive. <p>
On the other hand, we saw many examples of the kind of do-it-yourself relief that seems to have sprouted up everywhere. It is a response to the realization that nothing was being done by national, state and local officials to bring help in a timely manner. <p>
Evidence of grassroots relief was everywhere. For example, we saw about five cars pulling trailers, with a makeshift sign announcing that it was for relief. We saw a couple of trucks dragging generators and other supplies that clearly were headed for the disaster area. <p>

<a name="07-04p"></a><b>4 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Jackson, Miss., airport </b></font><br>
<font face="Times New Roman, Times, serif" size="3">The urgent response to the hurricane disaster by 19 New York firefighters in the Jackson airport stood as a stark contrast to the apathy of the federal government.<p>
The all-volunteer Disaster Assistance Response Team (DART) were headed to Baton Rouge for three weeks. All of the firefighters were using their personal vacation time to help out with the disaster relief effort. The FDNY will require them to work an extra 120 during the coming year to make up for the lost time, or the time will come out of their vacation allowances. <p>
Several of the men worked day and night at Ground Zero after September 11, 2001, and thought that Katrina was an even more massive human tragedy. "We're here to pay everyone back," said Brian Clifford who works in Brooklyn with the Engine 231. "Everybody wants to go down, everybody's volunteering. What we really want to do is get in there and fight the fires, but we'll do whatever's needed."<p>
Bob McCormack, who lives in Brooklyn said, "Seeing those little kids on the overpass, that's what motivated me. No obvious crying, just tears and more tears rolling down their faces, and they had nowhere to go. I had to come."<p>

<a name="07-05p"></a><b>5 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Jackson, Miss., Coliseum</b></font><br>
<font face="Times New Roman, Times, serif" size="3">Relief efforts were in full swing at the Jackson Coliseum, where the biggest problem wasn't housing the evacuees, but getting piles of goods to outlying towns where the need is most desperate. Red Cross volunteers were receiving dozens of unannounced deliveries every day. <p>
Volunteers came from as far away as California. Five fully loaded open-air trucks had arrived the day before from Indiana. A man had driven down from Illinois with a carload of food&#8212;and then took a family of four back with him to live. People with empty apartments and houses had come by, offering permanent housing to people who wanted to stay in Jackson, promising to defer all rent until people found jobs. Flyers were posted with job possibilities&#8212;local people who were hiring plumbers, carpenters and electricians. <p>
Another flier posted on the entrance read: "Attention, families of Mississippi National Guard soldiers deployed to Iraq. Soldiers are desperate to know the welfare of their loved ones in the aftermath of Hurricane Katrina. Family members who live south of I-20 interstate can help to relieve their anxiety by phoning one of the following numbers." <p>
The volunteers spoke with compassion and anger. Paul Gaskin, who came from central Tennessee, said, "The government expressed their contempt for the victims when they said they should have heeded the warning to get out of the area. They blocked buses trying to get in, they refused trucks full of water, and they turned down assistance from people in this country and others. This disaster will be ongoing until the people at the top are relieved of their responsibilities."<p>

<a name="07-08p"></a><b>8 p.m.</b><br>
<font face="Times New Roman, Times, serif" size="4"><b>Newton, Miss.</b></font> <br>
<font face="Times New Roman, Times, serif" size="3">After inquiring at several hotels, we finally found a room about 45 miles east of Jackson. The couple who checked in just before us had fled the West Bank of New Orleans the day before the hurricane and had been driving through Texas, Louisiana and Mississippi ever since. <p>
The night before, Ira and Tempie had slept in their car. They had been trying all evening to find a place to stay. They told us that one hotel had turned them away, saying they had no vacancies&#8212;even though they had just provided a room for some whites. They agreed to let us take them out to breakfast the next morning.<p>

<?php include "../../legacy-includes/BottomNavLinks.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
