<html>
<head>

<title>
Does Iraq's main union support the U.S. occupation?
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<font face="Times New Roman, Times, serif" size="4">Behind the IFTU controversy:</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>Does Iraq's main union support the U.S. occupation?</b></font><p>
<font face="Times New Roman, Times, serif" size="2"><b>By Lee Sustar</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | June 17, 2005 | Pages 6 and 7</font><p>

<font face="Times New Roman, Times, serif" size="3">A TOUR of the U.S. by Iraqi labor leaders has highlighted a controversy about that country's best-known labor federation&#8212;the Iraqi Federation of Trade Unions (IFTU). <p>
The debate hinges on the IFTU's support for the U.S. occupation, its close ties to the former occupation-appointed government of Iyad Allawi, its takeover of assets and membership lists from Saddam Hussein's government-controlled unions, and its status under the occupation-appointed regime's Decree Number 16 as the sole legal union federation in Iraq today.<p>
The IFTU's participation in a tour organized by U.S. Labor Against the War (USLAW) led the steering committee for Boston United for Justice with Peace to issue an open letter on the matter. "We have to think about the consequences our alliances will have not only on our own work here in the United States, but also on the efforts of Iraqis inside Iraq to organize resistance to both the military and economic occupation of their country," wrote Jennifer Horan, on behalf of the steering committee of the group, which is an affiliate of United for Peace and Justice, a national antiwar organization.<p>
USLAW leaders sought to allay such concerns in advance of the tour with a statement that presented the IFTU as an opponent of the occupation, along with the other union organizations involved&#8212;the Federation of Workers Councils and Unions of Iraq (FWCUI) and the General Union of Oil Employees (GUOE), based in the southern oilfields near the city of Basra.<p>
"We recognize that our labor movement has an unfortunate history of picking and choosing which unions it will grant legitimacy to in parts of the world where our government is interfering with national sovereignty," the USLAW co-conveners wrote. "We refuse to act in that tradition."<p>
Yet the issue of trade union legitimacy in Iraq is likely to be inescapable&#8212;not only because Iraqi unions themselves are forcing the issue, but because major union federations internationally, including the AFL-CIO, have launched an intense effort to train and influence the renascent Iraqi labor movement. A series of interviews with labor movement officials and activists in Iraq, Europe and the U.S. on both sides of the debate indicates that the dispute over the IFTU and the character of the Iraqi trade unions is likely to intensify. <p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">THE CONTROVERSY over the IFTU erupted in Britain in October 2004 when the federation's representative Abdullah Muhsin intervened at the annual Labour Party conference to help head off a resolution calling for withdrawal of occupation troops.<p>
In a recent phone interview from London, Muhsin denied advocating any position on the occupation to the Labour Party or British unions. "Our demand is for the [United Nations-created] political process in Iraq to succeed, to have a permanent constitution, and peace," he said. "If the labor movement in the U.S. wants to campaign and say troops should be removed [from Iraq], it is their right, and who are we to say no?"<p>
But Muhsin did argue against the out-now position in Britain. He distributed an open letter to union delegates at the Labour Party conference, saying that an early withdrawal of troops "would be bad for my country, and play into the hands of extremists."<p>
Such a characterization of the resistance is a regular theme for Muhsin. In the interview, he attacked Iraq's insurgents for "indiscriminately killing" innocent people. "This is no resistance," he said.<p>
Along with his denunciations of the resistance has come praise for Allawi, the Baathist apparatchik-turned-CIA asset who in 2004 was put in charge of Iraq by the U.S.-run Coalition Provisional Authority. Muhsin proposed inviting Allawi, then prime minister in the U.S.-appointed government, to address the Labour Party conference. This, Muhsin wrote, presented an "opportunity for those who honorably opposed the war to extend support to Iraqi democrats who are trying, in the most difficult circumstances, to construct a vibrant civil society." <p>
Muhsin's speech to a fringe meeting at the party conference was organized by Labour Friends of Iraq, which is co-chaired by a retired union official who is antiwar&#8212;and the prowar Ann Clwyd, Prime Minister Tony Blair's human rights envoy to Iraq.<p>
The aim of the group, says its director, Gary Kent, is "to move beyond the war, uniting those who were for the war and those opposed to the war in grassroots solidarity with what we call grassroots Iraq&#8212;chiefly, the trade unions." He added: "We are very struck by the argument that the democratization of Iraq could have positive repercussions throughout the Middle East. It is very important that we don't cede the flag for democracy and freedom in Iraq to the neocons."<p>
In fact, the group is proposing to support a contributor to the neoconservative <i>Weekly Standard </i>newspaper &#8212;the ex-leftist Christopher Hitchens&#8212;in a debate with antiwar member of Parliament George Galloway, who recently shook up a U.S. Senate hearing with his challenge to the Bush administration's occupation of Iraq.<p>
Material on the Labour Friends of Iraq Web site slams Galloway&#8212;and squarely supports the continued occupation of Iraq. Its mission statement declares, "We will encourage support for the IFTU."<p>
For its part, Britain's union federation, the Trades Union Congress (TUC)&#8212;which opposed the war and voted at its conference for an end to the occupation&#8212;has an officially evenhanded approach to Iraqi unions. A TUC conference on Iraq in February included representatives from both main federations&#8212;the IFTU and FWCUI&#8212;as well as the oil workers' GUOE, teachers unions and a Kurdish union. Even the General Federation of Trade Unions (GFTU), a remnant of the state unions under the former regime, sent a representative.<p>
Nevertheless, the IFTU has emerged as the main focus of TUC solidarity efforts. The TUC Aid for Iraq campaign was launched with an explanation that "initiatives could include paying for an IFTU theater bus to tour Iraqi workplaces and explain the case for joining trade unions" and other material aid, although a TUC spokesperson said no aid money has yet been disbursed. <p>
Individual TUC affiliates also play a role in supporting the IFTU. The federation's Muhsin operates from an office at the headquarters of UNISON, Britain's biggest union, which represents public-sector workers. <p>
Muhsin has made frequent appearances at TUC meetings, and this year accompanied a TUC fact-finding mission to Iraq.<i> Financial Times </i>journalist John Lloyd described the scene in Kurdistan when the IFTU's Mosul leader Saady Edan sought to convince leading British trade unionists to drop their demands to end the occupation. "We want the occupation to end," Edan said. "But if it ends now, it will bring chaos. Once the Iraqi security forces are capable, then the occupation should leave. But they are not yet." This is essentially the official position of the Blair government and the Bush administration. <p>
Lloyd&#8212;whose article was strongly sympathetic to the IFTU&#8212;added: "The visitors wonder why a union movement that is poor and needs funds as well as training is able to drive them about in big Toyota Land Cruisers and BMWs." The delegation's recommendations, posted on the UNISON Web site, recommended "[developing] training for the leaderships of the IFTU and Kurdish federations" and "[arranging] a fact-finding visit to the UK."<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">MUCH OF the international labor movement's role in Iraq is coordinated by the International Confederation of Free Trade Unions (ICFTU), a grouping with origins in the pro-U.S. side of the Cold War labor divide between the U.S. and Russia. According to a document on the ICFTU Web site, its role in Iraq has largely been training in trade-union basics&#8212;lectures on the history and politics of the labor movement, International Labor Organization (ILO) standards, organizing and bargaining.<p>
A February 2005 session&#8212;held across the Jordanian border in Amman&#8212;gave the ICFTU's desk officer for Asia and the Middle East, P. Kamalam, the opportunity to meet Iraqi trade unionists from all the federations, including the old state-run federation and a splinter under the influence of the Supreme Council for the Islamic Revolution in Iraq, a leading party in the current government.<p>
The IFTU, she said, has "good unions on the ground" but "does not properly attend to the issue of gender and women." The FWCUI, in her view, has a record of organizing workers and does a better job of stressing women's rights.<p>
A major issue for Iraqi labor, she said, is the scramble to control the assets of the old state-run General Federation of Trade Unions. "Everyone wants a piece of that cake," she said from her office in Brussels. "Because it's a big amount of money and of infrastructure."<p>
That struggle was won by the IFTU&#8212;outside Kurdistan, at least&#8212;in January 2004 when the U.S.-appointed Iraqi Governing Council passed Decree Number 16.<p>
That, Kamalam said, is a "problem" for the ICFTU. "We have spoken to IFTU about it to say that, you know, there cannot be one legitimate union, because that goes against freedom of association," Kamalan said. The IFTU, she added, "has not publicly taken that position, even though they tell us that they are all for the ILO conventions."<p>
How did the IFTU secure its status as the sole legal federation? According to Kamalam, "because they had people who were in common with the union and the Interim Government, from the same political parties"&#8212;that is, the Iraqi Communist Party (ICP) and Allawi's Iraqi National Accord. In fact, when Allawi's interim government reaffirmed the IFTU's status, the federation's president was Rasim Al-Awadi, described in the April 25 <i>New York Times </i>as a "senior Allawi aide," and according to some Iraq analysts, his second in command.<p>
Most IFTU leaders have close ties to the ICP, which has played a central but highly contradictory role in the history of the Iraqi working class movement. Founded in 1935, it drew its initial membership from those who struggled against British colonial rule in the 1920s and later puppet regimes established by London.<p>
The ICP became a mass organization&#8212;the biggest Communist Party in the Middle East. In the 1970s, it made an alliance with the ruling Baath Party; later, Saddam Hussein's regime turned on the party, jailing, torturing and killing party cadre and driving many into exile.<p>
After the 1991 Gulf War, the ICP was able to operate legally in Iraqi Kurdistan, which enjoyed quasi-independence under the protection of the U.S. no-fly zone. It opposed the 2003 invasion and quickly emerged from the underground to become one of the first parties to function after the fall of Baghdad.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">BUT AT this point, the role of the ICP became increasingly controversial on the international left. The party accepted a post in the governing council under Paul Bremer's Coalition Provisional Authority, then two ministerial posts in the Interim Governing Council. A right-wing Web site dug up a document from the National Democratic Institute, the Democratic Party's affiliate to the government-funded National Endowment for Democracy, praising the ICP.<p>
At the same time, the ICP was organizing the IFTU. But according to its critics in the Iraqi labor movement, the IFTU never matched its rhetorical opposition to privatization and low wages&#8212;both imposed by Bremer's orders&#8212;with action.<p>
In the recently published <i>A People's History of Iraq, </i>Italian author Ilario Saluci argued that the party's balancing act had disastrous consequences. "Thinking it could become a 'party of struggle and of government'&#8212;even in a puppet government totally devoid of power&#8212;the ICP has increasingly become a 'left' cover for Anglo-American forces," he wrote.<p>
Defenders of the IFTU and/or the ICP, of course, reject this analysis. They point to numerous speeches, articles and interviews about and by ICP and IFTU members that appear in left-wing publications, such as the Communist Party USA's magazine, <i>Political Affairs</i>.<p>
Those words don't impress Sabah Jawad, a British journalist and member of Iraqi Democrats Against the Occupation and an exile from Saddam Hussein's Iraq. "These people [the ICP] have an incredible capacity to say two different things to two different people," he said. "It's always been an opportunist party&#8212;and I used to belong to that party."<p>
The IFTU is often criticized on similar grounds by antiwar activists in the labor movement. "The IFTU vilifies and condemns the resistance, but is in bed with the brutal U.S. occupation that generates that resistance," said Michael Letwin, co-convener of New York City Labor Against the War, a USLAW affiliate that has refused to endorse a meeting with IFTU leaders in New York.<p>
One piece of evidence is often put forward by its supporters in defense of the IFTU as an opponent of the occupation&#8212;a raid by U.S. forces on the IFTU's offices in December 2003. But this appears to have been an isolated incident. The IFTU achieved its status as the sole legal union in Iraq the following month.<p>
More seriously, several IFTU activists have been murdered&#8212;16 since October, according to Muhsin. The best-known case was the brutal torture and killing in January of Hadi Salih, a longstanding ICP cadre and IFTU international representative.<p>
Labor leaders around the world condemned the murder of Salih, often adding a statement of solidarity with the IFTU. But one can condemn the murder of Salih without endorsing the IFTU. Moreover, said Sami Ramadani, another left-wing exile from Saddam Hussein's Iraq, "Neither the IFTU or anyone else has produced a shred of evidence on who killed Hadi Salih. We are in the realm of speculation."<p>
Ramadani, now a sociologist in London, was central in making an issue of Abdullah Muhsin's intervention at the British Labour Party conference, writing a lengthy critique of the IFTU that appeared in the <i>Guardian </i>newspaper. <p>
"All these [Iraqi] federations are party organizations, but the IFTU stole a march on them because of Allawi's involvement," he said in an interview. "There isn't a single trade union federation that is truly a federation of genuinely elected trade unions, unfortunately. Grassroots trade unionism is being snuffed out, in a sense, by these ad hoc federations."<p>
But Falah Alwan, general secretary of the FWCUI, argues that there's no comparison between his federation and the IFTU. "The IFTU is an official union"&#8212;that is, a government-supported one, he said from Baghdad before traveling to the U.S. for the USLAW tour. By contrast, he said, "We created our unions without participation of the government." <p>
The impetus for the formation of the federation came from the unemployed workers movement that exploded onto the streets of Iraq in 2003. The Union of the Unemployed later merged with the Workers Councils initiated by another left-wing party, the Workers Communist Party, to form the FWCUI.<p>
The FWCUI has taken a policy of non-collaboration with the occupation and the various governments installed by the U.S., and it calls for an immediate withdrawal of U.S. troops and their replacement by United Nations peacekeepers. Despite the January 30 election, U.S. pressure on Iraqi parties has led to what is still effectively an "appointed government" said Amjad Ali, the FWCUI's Canada-based international representative. But like the IFTU, the FWUCI condemns the Iraqi resistance.<p>
Ramadani&#8212;himself a trade unionist&#8212;concedes that the FWUCI has held some local union elections. He said he has found no evidence of such efforts by the IFTU, however. Instead, he contends, the federation was imposed from above once the IFTU got control of the assets of the old government unions. "The membership lists were crucial," he said. "When they say they have 200,000 or 300,000 members, this is what they mean."<p>
In Ramadani's view, the only significant legitimate union in Iraq is the oil workers' union&#8212;the GUOE, which has its origins in a strike by workers at Iraq's Southern Oil Company against the Haliburton subsidiary Kellogg, Brown &amp; Root. "It's a sure thing they held an election," he said. "They have rules, they are visible, and they go on strike, for goodness' sake. You can see their organization on the ground. You don't see any of that in the others. And trade unionism shows itself on the ground in wages and working conditions."<p>
In a visit to Britain in February, GUOE leader Hassan Jumaa forcefully denounced the occupation in a speech reprinted in the <i>Guardian</i>. "Those who claim to represent the Iraqi working class while calling for the occupation to stay a bit longer, due to 'fears of civil war,' are in fact speaking only for themselves and the minority of Iraqis whose interests are dependent on the occupation," he wrote.<p>
This could be interpreted as a swipe at the IFTU. But two top IFTU representatives spoke at a privatization conference hosted by the GUOE in Basra on May 25-26. There, union members and academics discussed the plans for Iraq's transformation normally kept quiet in the occupation's Green Zone. The leading parties of Southern Iraq&#8212;which include the main ruling Shiite Muslim parties of the national government following the January elections&#8212;sent representatives to the conference, an indication of the importance of the GUOE in Iraq's all-important oil industry.<p>
In an interview from Basra, Farouk Muhammad Sadiq, international secretary for the GUOE, was diplomatic about the IFTU and the other federations. "We heard about Muhsin at the Labour Party, and we don't agree with him," he said, adding that he believed the IFTU in Iraq is genuinely working to end the occupation.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">THOSE WHO want to build genuine trade unions in Iraq&#8212;and the workers they seek to organize&#8212;face tough going.<p>
A government counteroffensive against the resistance, led by U.S. forces and carried out by mostly Shiite militias, has intensified the tendency toward religious sectarianism and ethnic conflict. Government commando units, modeled on the 1980s counterinsurgency in El Salvador and led by former officers under Saddam Hussein, are widely accused of assassination, kidnappings and torture.<p>
All this is infinitely removed from the Western trade union establishment world of white papers, formalized collective bargaining and social partnership. What does it mean to talk about ILO conventions on union rights in Falluja&#8212;where eight months after the U.S. leveled the city, tens of thousands remain displaced, residents are forced to submit to eye scans as IDs by U.S. troops, and young men are routinely rounded up with no cause?<p>
After the torture scandal at Abu Ghraib, is it really possible to argue that the occupation is creating a "civil society" in which Iraqi unions can take root, as the pro-occupation elements in the British Labour Party would have it? <p>
Building trade unions that can fight for the interests of working people in Iraq will necessarily mean taking on the most difficult issues: religious sectarianism, the Kurdish national question, women's rights and Iraqis' right to self-determination. <p>
Above all, building a labor movement in Iraq means not collaborating with the U.S. occupation&#8212;which denies Iraqis the means to control their own fate.<p>

<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
