<html>
<head>

<title>
The road to victory
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="4">Death row emptied in Illinois</font><BR>
<font face="Times New Roman, Times, serif" size="5"><b>The road to victory</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">January 31, 2003 | Pages 7 to 10</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>ON FEBRUARY 5, 1999, Anthony Porter walked off Illinois' death row and into a cold winter's day to hug relatives and supporters who had helped him win his freedom. Almost four years later, on January 10, Madison Hobley walked to freedom, too--one of three men released that day from the nightmare of wrongful imprisonment on death row.</P>

<table width="210" align="right"><tr><td>
<table width="198" cellpadding="10" cellspacing="0" align="right" border="2" bordercolor="006699" bgcolor="#FFCC66"><tr><td>
<P><font face="Arial, Helvetica, sans-serif" size="4"><b>Voices from the struggle</b></font><br>
<font face="Arial, Helvetica, sans-serif" size="3"><a href="438_07_Voices.shtml">Read</a> interviews with former Illinois death row prisoners, family members and anti-death penalty activists.
</td></tr></table>
<p>&nbsp;</p>
</td></tr></table>

<P>Between these two events lies a story of struggle that ended in victory three weeks ago--when Gov. George Ryan pardoned four death row prisoners and commuted the sentences of every other prisoner facing execution in Illinois.</P>
<P>After four years of mounting pressure that exposed the cruel injustices of the system, a pro-death penalty Republican has dealt the sharpest blow to America's machinery of death in the quarter century since the reinstatement of capital punishment. ALAN MAASS reports on how this tremendous victory came about--and the fight ahead to put an end to the death penalty.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<p><font face="Times New Roman, Times, serif" size="4"><b>A broken system</b></font></p>
<font face="Times New Roman, Times, serif" size="3"><P>HE WAS asked about his last meal, and his relatives had been told how to retrieve his body. Illinois' executioners were practicing with their equipment at the brand-new "super-max" prison in downstate Tamms, before using it for the first time on Anthony Porter. But with less than 48 hours to go, the phone call came. Porter was saved from the death chamber by the Illinois Supreme Court.</P>
<P>None of the justices questioned his guilt--they were among the 30 judges at all levels of the court system who signed off on the evidence that Porter had committed a 1982 double murder in Chicago. The execution was only stopped in September 1998 for a "fitness hearing"--to determine whether Porter's IQ was high enough for him to be put to death.</P>
<P>It wasn't until four-and-a-half months after Porter was scheduled to die that a group of college journalism students and their professor uncovered the evidence that proved Anthony Porter was innocent.</P>
<P>Porter's exoneration--well after he was supposed to be dead--exposed the appalling state of the Illinois death penalty system like no other case before it. In one court after another for 17 years, that system failed completely to discover that he was an innocent man.</P>
<P>"This wasn't a matter of the police and the prosecution and the courts or the defense lawyers establishing the innocence of someone," says Stephen Bright, one of the country's top death penalty lawyers and head of the Southern Center for Human Rights. "It really was people from outside the system who demonstrated that."</P>
<P>"There are lots of cases where there isn't a journalism class, and there's no competent lawyer to take a second look. And so the nightmare is how many of these cases are there that we don't know about--that have the same miscarriages of justice." </P>
<P>Over the next year, three more men--Steven Smith, Ronald Jones and Steven Manning--would be proven innocent, making a total of 13 prisoners set free from death row in 13 years. The innocence cases highlighted the indictment of the death penalty system from a number of directions.</P>
<P>Shortly before Porter was freed, the Northwestern University law school held a national conference on wrongful convictions that brought together legal experts and activist opponents of capital punishment from around the country. </P>
<P>The traditionally Republican <I>Chicago Tribune </I>published multi-part investigative series that focused on one injustice after another--from the incompetent lawyers who represented dozens of death row prisoners, to the use of snitch testimony against others, to cases of mishandled scientific evidence against still others.</P>
<P>Meanwhile, grassroots organizations continued to reach out to a growing audience of people with doubts about the death penalty, holding neighborhood discussions, public forums and demonstrations.</P>
<P>"We haven't been a mass movement, in the sense of the civil rights movement," says Marlene Martin, national director of the Campaign to End the Death Penalty. "But we do have elements of that movement. Over the years, the grassroots activism had an impact. When Ryan came into office, the legitimacy of the justice system was at stake, and that's where the efforts of people to keep the issue in the public eye were important--in making the case of what he had to do about it."</P>
<P>All this led up to Gov. George Ryan's announcement on January 30, 2000, that he was halting all executions. "Until I can be sure that everyone sentenced to death in Illinois is truly guilty," Ryan said, "until I can be sure with moral certainty that no innocent man or woman is facing a lethal injection, no one will meet that fate."</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<p><font face="Times New Roman, Times, serif" size="4"><b>Justice for the Death Row 10!</b></font></p>
<font face="Times New Roman, Times, serif" size="3"><P>DURING THE summer of 1998, while George Ryan was still on the campaign trail, Stanley Howard and Aaron Patterson were discussing the Death Row 10. It wasn't easy. Howard and Patterson were prisoners on death row in Pontiac, Ill., spending 23 hours a day in their cramped cells--so yelling down the tiers was the main way to communicate.</P>
<P>The Death Row 10--which eventually numbered 13 when all its members were discovered--are a group of African American men who were tortured by Chicago police into making confessions that were used to send them to death row.</P>
<P>Howard was suffocated with a plastic typewriter cover while he was continuously beaten. Patterson was beaten, suffocated and threatened with a gun. Leroy Orange and Leonard Kidd were electro-shocked with a black box device attached to their genitals. Grayland Johnson was hung halfway out an open window.</P>
<P>The torture chambers, run by Lt. Jon Burge at Area 2 and 3 police headquarters on Chicago's South Side, weren't a secret. The department even forced Burge to resign because of the allegations in 1993--though only after a confidential internal report surfaced, detailing more than 50 cases of "systematic" torture by Burge and the animals that he commanded.</P>
<P>That Burge was kicked out was the result of a long struggle by anti-police brutality activists, begun in the early 1980s by mothers of torture victims. But Burge got to retire on a full police pension in Florida, spending his days on his fishing boat <I>The Vigilante--</I>while his victims remained behind bars. Though the cops' record of torture was an acknowledged fact, not a single one of the Death Row 10 won a new trial or sentencing hearing.</P>
<P>With questions about the death penalty system building, Howard contacted the Campaign to End the Death Penalty to be the voice of the Death Row 10 on the "outside." From death row, the prisoners called the first Death Row 10 rally for September 1998, making a leaflet with a typewriter and headlines cut out of the Campaign's <I>New Abolitionist </I>newsletter and <I>Socialist Worker, </I>among other publications.</P>
<P>Since then, Death Row 10 members have spoken out around the country--via speakerphone at "Live from Death Row" events organized by the Campaign and other organizations. In Chicago, activists organized petitioning and demonstrations to put pressure on the prosecutor, Cook County State's Attorney Dick Devine, to look into the torture allegations.</P>
<P>But Devine has been desperate to head off an investigation. And no wonder--he was an assistant prosecutor when Burge's torturers were operating at full steam, and he later worked for a private law firm that defended Burge during the police investigation.</P>
<P>"[Burge] was certainly the ringleader of the torture," says Flint Taylor, a lawyer with the People's Law Office, who led the effort to expose Burge back in the 1980s. "But there were ringleaders of the cover-up, too."</P>
<P>The cases of the Death Row 10 began to gain media attention. But more generally, the torture issue showed how police and prosecutors grease the rails to the death chamber, whether to satisfy their sadism or to build up political reputations.</P>
<P>"The call had been going out for many years, and there was community interest, but there just wasn't a critical mass," Taylor says. But when Ryan declared a moratorium, the torture issue "came together at a time when the momentum was building with regard to the death penalty." Last April, a state appeals court judge appointed a special prosecutor to look into the Burge torture cases and the cover-up that followed.</P>
<P>And the struggle for the Death Row 10 that began with a typewritten leaflet made inside Pontiac prison plainly had a huge impact on Ryan. His pardons for death row prisoners went to four of the Death Row 10, and his speeches explaining his decision returned again and again to the torture chambers at Area 2 and 3 headquarters as an example of what's wrong with the death penalty system.</P>
<P>"Who knows if Governor Ryan would have even known about the Death Row 10 if not for the activism around these cases?" says Alice Kim, an organizer for the Campaign to End the Death Penalty.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<p><font face="Times New Roman, Times, serif" size="4"><b>Opening up a national debate</b></font></p>
<font face="Times New Roman, Times, serif" size="3"><P>RYAN'S DECLARATION of a moratorium in January 2000 expanded the growing national debate on the death penalty. True to form, some Illinois politicians dismissed the halt on executions as a publicity stunt by Ryan--to draw attention away from a rapidly developing corruption scandal that eventually forced him to give up on re-election.</P>
<P>But the depth of questioning could be seen across the country--reflected, for example, in surprisingly frank newspaper editorials against capital punishment, though they came after years of silence on the subject in many cases.</P>
<P>"To support the death penalty is, in effect, to support the state-sanctioned killing of innocent people," wrote the <I>Milwaukee Journal-Sentinel. </I>Florida's <I>Gainesville Sun </I>added: "Gov. Ryan has said he wants no innocent blood on his hands as a result of human error. The hurry-up-and-kill-em politicians would rather apologize after the fact."</P>
<P>But another factor was at work in pushing the death penalty into the national spotlight--the presidential campaign of the Texecutioner, George W. Bush. In his five years as governor of Texas, Bush oversaw a total of 152 executions--incredibly, more than one out of every five state-sponsored killings that had taken place since the death penalty was reinstated in 1976. Bush's total lack of concern about any of the issues raised by death penalty opponents added fuel to the fire.</P>
<P>As in Illinois, the nightmare of innocent people being sent to their death was the most prominent question. But the other dirty secrets of the death penalty system began to emerge--the frighteningly bad quality of lawyers representing capital defendants, for example, and the fact that death rows across the country are made up disproportionately of minorities and almost exclusively of the poor.</P>
<P>Then there's the erratic way that decisions to pursue the death penalty get made. Rob Warden, executive director of Northwestern University's Center on Wrongful Convictions, points out that there are 102 state's attorneys making decisions about prosecutions in Illinois--one for each county--and the state's laws do little to control them.</P>
<P>"If [the death penalty system] has had an error rate that's so egregious on the fundamental question of guilt or innocence," he says, "we can only imagine how serious that error rate must be when it comes to aggravation and mitigation" and the other factors that decide whether someone convicted of murder gets a death sentence or a term in prison.</P>
<P>Once the centerpiece of the politicians' law-and-order agenda, the death penalty was now being questioned not only by long-time opponents, but by mainstream voices. As ABC's Ted Koppel put it in bluntly summarizing a four-part <I>Nightline</I> investigation: "The percentage of men and women sitting on death row who are Black or Hispanic and poor is so out of proportion to their numbers in the general population that we cannot continue to insist that the system is fair or that the justice we dispense is equal. We can choose to ignore that. But we can't deny it."</P>
<P>The conclusions of a special commission appointed by Ryan to investigate the Illinois death penalty system only underlined these issues. When it began meeting in 2000, an early straw vote of the 14 members on the question of whether the death penalty should be abolished turned up only four in favor. But after two years of study, the margin was 8-to-5 in favor of abolition, according to press reports.</P>
<P>Yet that didn't make it into the commission's published conclusions--because pro-death penalty members insisted that the panel could only propose "reforms." The final report, issued last April, recommended a total of 85 reforms necessary to ensure "fairness" in the death penalty system--though the commission admitted that even if each one was implemented, an innocent person could still end up sentenced to death.</P>
<P>The report opened up a debate among opponents of the death penalty about whether such an unjust system could ever be "reformed"--and if not, then maybe the commission's proposals should be opposed as window-dressing. But the Illinois legislature settled the question--by refusing to pass any change at all.</P>
<P>Ryan proposed three separate packages of legislation to take up aspects of the commission's study, but each one was shot down. The only legislation pertaining to the death penalty that did pass the statehouse was a post-September 11 proposal to <I>expand </I>capital punishment--and it became law over a veto by Ryan.</P>
<P>"They absolutely and systematically refused, in the case of the legislature, to institute any reforms, and in the case of the prosecutors, to do any housecleaning and make any admission at all of the problems," said Jennifer Bishop-Jenkins, a national board member of Murder Victims' Families for Reconciliation, who was active in the fight in Illinois.</P>
<P>"Not even just to say that we screwed up, but we'll do better now. I think that was the short-term thing that really pushed Governor Ryan over the edge. He knew he had no other choice but to act, because they did nothing."</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<p><font face="Times New Roman, Times, serif" size="4"><b>The battle over blanket clemency</b></font></p>
<font face="Times New Roman, Times, serif" size="3"><P>AFTER A speech at the University of Oregon law school last March, Ryan responded to a reporter's question by saying that he would consider a blanket commutation of every death sentence in the state.</P>
<P>That was exactly what a group of anti-death penalty lawyers centered around the State Appellate Defender's office wanted to hear. They had been discussing this very possibility for more than a year--and began putting their strategy of asking Ryan for blanket clemency into high gear.</P>
<P>Likewise, activist groups reacted to Ryan's statement with a campaign to support blanket commutations. One of the most important parts of their efforts, these groups say, was to give a voice to those most immediately affected by the death penalty--prisoners themselves, and their family members.</P>
<P>So town hall meetings in Chicago featured live call-ins from death row--and the testimony of relatives. "When something like this happens, as a family member, you don't know what to do, you don't know where to turn," says Gricelda Ceja, the mother of death row prisoner Raul Ceja. "And I'll tell you, people in the Campaign were such a help as far as providing support and being there and pointing you in the right direction. We appreciate it as family members--it's just helped us so much." </P>
<P>Activists in Illinois worked with a new sense of urgency because the moratorium on executions seemed like it might come to an end--and possibly sooner rather than later. With Ryan not running for re-election, both the Democratic and Republican candidates for the 2002 election were pro-death penalty.</P>
<P>The Republican, Jim Ryan, built his political career around capital punishment. He started out in politics as the prosecutor for the Chicago suburbs of DuPage County--where he oversaw the wrongful conviction of Rolando Cruz and Alejandro Hernandez, two of the best-known cases of innocent men sent to death row.</P>
<P>But in some ways, his Democratic opponent--and the eventual winner in November--Rod Blagojevich, was worse. For example, in pandering to the Fraternal Order of Police to win its endorsement, Blagojevich came out opposed to the videotaping interrogations, something that Jim Ryan had said he would support.</P>
<P>Even as death penalty opponents stepped up the pressure, the other side organized a counterattack. At hearings into clemency petitions conducted by the Illinois Prisoner Review Board, prosecutors organized a parade of the relatives of murder victims to demand that Ryan not commute any death sentences. The hearings became a media circus, with the injustices of the death penalty system drowned out by the horrible details of the murders, described by relatives reliving the suffering of their loved ones.</P>
<P>"That was a conscious decision by the prosecutors not to deal with the issues in these cases," said Frank Ralph, a Chicago lawyer who led the legal effort to win a special prosecutor into the Burge torture cases. "They had a chance to address these points and speak directly to the governor through the prisoner review board, and they chose not to."</P>
<P>Gary Gauger, a former Illinois death row prisoner who was exonerated and set free in 1996, says that the hearings were "incredibly typical of the prosecutors." "They were blaming George Ryan for these poor people having to relive the anguish of their loved ones being killed, and yet it wasn't George Ryan who called these hearings," Gauger said. "It was the prosecutors who assembled these people and had them get up there and relive the experience, strictly for the grief and shock factor. They built their careers by killing people, and this was basically a selfish ploy of their own to exploit the grief of the victims."</P>
<P>The ploy worked. A <I>St. Louis Post-Dispatch </I>poll of Illinois voters conducted before the hearings showed 50 percent opposed to blanket clemency and 46 percent in favor. One conducted a few weeks later showed the gap widening to 55 percent opposed and 40 percent in favor. Ryan himself began telling reporters that he had "pretty much ruled out" blanket commutations.</P>
<P>The weeks during and after the hearings were tough ones for death penalty opponents, but without their activity in the face of the prosecutors' attack, Ryan might never have felt the pressure to shift back. Members of the Campaign to End the Death Penalty, for example, organized a press conference outside the clemency hearings that brought together exonerated prisoners with death row family members.</P>
<P>The Center on Wrongful Convictions called a second innocence conference at Northwestern, bringing together three dozen people exonerated from death rows across the country. The following day--in an echo of the civil rights movement--the wrongfully convicted participated in a relay march, carrying a letter urging commutations from the state prison near Joliet to the door of Ryan's downtown Chicago office.</P>
<P>On New Year's Eve, Rev. Jesse Jackson joined family members of prisoners and Campaign activists on a visit to death row in Pontiac, where he added his voice to the call for clemency. A few days later, an even larger group of relatives met with Ryan to urge him to pardon or commute the death sentences of their loved ones. And for each of these, there were a dozen other events--press conferences, pickets, petitionings, public meetings.</P>
<P>Alice Kim of the Campaign says that these final weeks made a big difference. "Politicians, George Ryan included, are influenced by public pressure," she says. "When the prosecutors went on the offensive around the clemency hearings, that's when Ryan said he put blanket commutations on the backburner. But then he heard from our side."</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<p><font face="Times New Roman, Times, serif" size="4"><b>Winning hands-down</b></font></p>
<font face="Times New Roman, Times, serif" size="3"><P>WHEN RYAN scheduled speeches on the death penalty for his final days in office at the Northwestern and DePaul University law schools--both of them centers of the legal fight against the death penalty--it was clear that he wouldn't be siding with prosecutors. Even so, the scale of his actions sent shock waves around the country.</P>
<P>Ryan announced the pardons for Madison Hobley, Stanley Howard, Leroy Orange and Aaron Patterson, and the blanket clemency for every other prisoner facing the death penalty. But more than that, his speeches explaining his actions were a stunning indictment--not only of the death penalty, but the whole criminal justice system.</P>
<P>Ryan rose to prominence in Republican Party politics as a darling of conservatives. But you would never know it from his scathing critique of law enforcement. He singled out Burge and the Chicago police, tore into prosecutors who used the death penalty to further their political careers--and then hammered state legislators of both parties for refusing to lift a finger about any of it.</P>
<P>For Robin Hobley, Madison's sister, who spent long years pleading for her brother's freedom, it was hard to grasp what was happening. "I didn't believe it, even though it was written in the paper, and people were telling me congratulations," she said.</P>
<P>"I think there were a lot of factors that led to this and opened up the doors for the governor to be able to do this," Robin says. "For Madison, one thing was me out working with the Campaign to End the Death Penalty across the country. That helped tremendously in getting the message out and for people to hear it."</P>
<P>Jennifer Bishop-Jenkins echoes the importance of the years of organizing. "We have a really large, dedicated, very diverse and very committed group of activists," she says. "I really do think that the activists are a lot responsible for this, because we created a public climate."</P>
<P>Rob Warden of the Center on Wrongful Convictions agrees. "Chick Hoffman of the state appellate defenders' office said, 'We were an army of ants.' And we really were," Warden says. "This took work by literally hundreds of people. You can look at this and say that, without certain components, this never would have happened. If it hadn't been for the grassroots organizations, there is no doubt that we wouldn't be where we are today."</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<p><font face="Times New Roman, Times, serif" size="4"><b>The battle ahead</b></font></p>
<font face="Times New Roman, Times, serif" size="3"><P>AS SOON AS RYAN finished speaking, prosecutors and right-wing politicians were sputtering and fuming for the TV cameras. Dick Devine, the Cook County prosecutor, finally admitted that the death penalty system was "broken"--but only as of that afternoon, when Ryan emptied death row.</P>
<P>"George Ryan was the messenger," says Larry Marshall, the legal director of the Center for Wrongful Convictions. "And because they are so personally humiliated by the message, they're shooting the messenger. But the fact is that this was a slap in the face to the system, which is exactly what sometimes is necessary as a matter of a wakeup call."</P>
<P>As Bishop-Jenkins puts it, "The reason why the prosecutors are saying this--your Dick Devines and Joe Birketts--is because they ran out of arguments. They wouldn't clean house, they wouldn't admit wrongdoing, they wouldn't look at their own problems, and so they had to try to pull out at the end the only card that they could play politically, which was a very emotionally manipulative one, and one which re-victimizes those victims one more time."</P>
<P>Death penalty opponents aren't letting Devine and Co. go unopposed. On Martin Luther King Day, Rep. Bobby Rush (D-Ill.) hosted a press conference in Chicago to put pressure on the special prosecutor in the Burge torture cases--and turn up the heat on Devine. Anti-death penalty lawyers are preparing for legal challenges from prosecutors to Ryan's commutations.</P>
<P>Meanwhile, the three men freed from death row (Stanley Howard remains behind bars, serving time for another conviction) are determined to fight for those they left behind. "We were wondering when our turn was going to come," Madison Hobley told an audience of more than 100 at a Chicago neighborhood meeting to celebrate the victory in Illinois. "Their turn is going to come, too. They're coming home, as long as we continue to be together and fight for the cause."</P>
<P>Likewise, activists are turning to the fight to get rid of the death penalty, once and for all. State Rep. Art Turner and several other lawmakers have reintroduced legislation that would abolish the death penalty. At the national level, Sen. Russ Feingold (D-Wis.) and Rep. Jesse Jackson Jr. (D-Ill.) have said they will reintroduce measures to impose a national moratorium on executions.</P>
<P>Will it happen? The new Democratic president of the Illinois state Senate, Emil Jones of Chicago, says that, while he personally supports abolition, voting for Turner's proposal would be "political suicide."</P>
<P>But anti-death penalty activists have heard that line before. "We've got as far as we have because we made an impact on public opinion," says Marlene Martin of the Campaign. "So even though a majority of people support the death penalty, we still saw that 70-plus percent were in favor of the moratorium. That's something to build on, in making sure that people understand the real face of the death penalty--that it's brutal, dehumanizing, racist and wrong. If we can create that kind of climate, it won't be political suicide for politicians like Emil Jones. In fact, he'll think he has to do it. What happened in Illinois is an enormous step forward. This could be the beginning of the end of the death penalty in the United States."</P>
<P>Former death row prisoner Ronald Kitchen knows that there's still a fight ahead. If anyone has the right to be angry about the outcome in Illinois, it's Kitchen. Another member of the Death Row 10, he was hoping for a pardon from Ryan based on the pile of evidence of his innocence. But he remains unjustly imprisoned, facing a sentence of life without parole.</P>
<P>Nevertheless, Kitchen says, "We might be left behind, but we aren't forgotten. That's what it's all about. We have to continue to fight, and put it out there for people to see that this is not over with yet."</P>

<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
