<html>
<head>

<title>
"We want real justice for Bhopal"
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="4">Two survivors speak out on the 1984 industrial disaster</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>"We want real justice for Bhopal"</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">June 25, 2004 | Page 8</font></P>

<P><font face="Times New Roman, Times, serif" size="3">ON DECEMBER 2, 1984, a leak of lethal methyl isocyanate gas from a Union Carbide pesticide factory spread silently through the streets of Bhopal, India. Within days, some 8,000 people had died from direct exposure to the gas. Another half a million people suffered injuries, and at least 150,000 people--including children born to parents who were exposed to the poison gas--continue to suffer ill effects.</P>
<P>Bhopal is the worst industrial disaster in history, and the blame for it lies squarely at the door of Union Carbide. Safety measures designed to prevent a gas leak were either malfunctioning--or shut down to save on costs. The factory's warning safety siren was turned off--guaranteeing that there would be many more victims who were overcome without warning.</P>
<P>But Union Carbide has never been punished. It paid a pittance to the Indian government as a settlement--amounting to less than $550 for each survivor. And it abandoned the plant, leaving behind tons of toxic chemicals and contaminated groundwater. The Indian government has implemented various schemes such as economic rehabilitation centers that were supposed to provide training and economic support, but these jobs don't provide enough to raise a family on.</P>
<P>Survivors of the disaster, along with environmentalists and social justice groups around the world, have been fighting for the last 20 years to force Union Carbide--now owned by Dow Chemical--to take responsibility for the horror in Bhopal.</P>
<P>In April, two survivors, RASHIDA BEE and CHAMPA DEVI, were awarded the prestigious Goldman Prize--environmentalism's equivalent of the Nobel Prize. They donated their award of $125,000 to a trust fund to provide medical assistance to Bhopal children. While on a tour of the U.S., they talked to <I>Socialist Worker's </I>SNEHAL SHINGAVI.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<P><font face="Times New Roman, Times, serif" size="3"><B>WHAT HAPPENED in Bhopal in the days after the leak?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Champa:</b> </font><font face="Times New Roman, Times, serif" size="3">Things were really bad. We didn't know whether we were going to live or not. People actually began to crave death. And sometimes you would even think that the people who were dead were the ones that were actually better off. Things were so bad then that it hurt most people to take a breath or walk a step--most actually couldn't bear the pain. It felt like your lungs were on fire, or that they were about burst. </P>
<P>There were corpses everywhere--human and animal. You couldn't even see really, because it felt like someone was shining a light in your eyes or stabbing them with a needle. It took several days before people were able to open their eyes. </P>
<P>No one could even think about anyone else. When people died, you said "thank God" and kept walking. When children got free from their mothers, mothers left them behind and didn't even look back. No one could think about people who they had left behind or lost. Everyone was running. </P>
<P>And then people were lost and families were separated. You would go and look for people in the morgues, to see if their bodies were with the other corpses. People spent weeks sitting at home, telling themselves that their loved ones would come back, even when they couldn't find them. But you never found those people. You didn't even find their corpses. </P>
<P>That's what it was like for three days. People would offer charity. People would come from neighboring towns and villages and offer us food and help. But none of them wanted to touch the food that we made. The food that was in our homes had been contaminated. </P>
<P>And when we were actually able to look around our homes, we discovered that everything was covered with a strange, white powder. There were these giant trees outside with beautiful green leaves, but all of the leaves had now fallen off. The fish in the lake died. There were so many dead fish floating on the top that it looked like there was a blanket on the lake.</P>
<P>All the buffaloes that we owned--all of them in the neighborhood actually--died. Nor did any of the goats survive. All of the animals died. And when the dead animals began decomposing a few days later and released the gas that had been trapped in their bellies, more people died. The government didn't care. The doctors would ask the company for information about how to treat the illnesses. But the company wouldn't tell us. It still hasn't told us. </P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">Twenty years ago, we hadn't even heard of Union Carbide, we didn't know what it made, and we didn't suspect that it produced anything that could harm us or poison us. Suddenly, on the night of December 2, 1984, at midnight, a cloud of gas descended upon us like a tidal wave, and in that night, 8,000 people were killed.</P>
<P>At midnight, when everyone in Bhopal was sleeping, it suddenly felt like red chilies had been rubbed in our eyes, and when my son got up in a fit of coughing and opened the door, then suddenly our eyes began watering, and we began coughing violently. </P>
<P>He heard voices from the outside that screamed "Run! Run!" so he went out. And he saw that everyone was running away and that the police station we lived next to had been cleared out. All the jail cells were open. So he ran home and told us that everyone was saying that a warehouse used for drying chilies had caught fire, so everyone was leaving the area as quickly as they could and making their way toward the new city. </P>
<P>We decided that we had better leave as well. There were 37 people in our extended family. Everyone tried to keep track of everyone else, but it was impossible because our eyes were watering, and we couldn't see. We managed to walk away for some distance, but we couldn't walk any further, as we were short of breath, so we sat down with my father-in-law. And as we sat down, it felt like someone was stabbing our eyes with needles. </P>
<P>Whenever we could open our eyes--and it was hard to open our eyes--all we could see were corpses, everywhere. Bodies of dead children. Corpses just lying on the street. At 4 a.m., they announced that Union Carbide had contained the leak and that everyone should return home. That was the first time that we had heard that this happened because of a gas leak at Union Carbide. </P>
<P>But we couldn't breathe, and we couldn't see. And the more we ran, the more gas we were breathing. So, we sat there for a while because we couldn't figure out how we would get back to our houses. Then police cars arrived and began taking a few people at a time back to their houses. We were taken to one hospital, my father was taken to another hospital. And the rest of the family had also been taken to one hospital or another. We didn't know where anyone was. </P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Champa:</b> </font><font face="Times New Roman, Times, serif" size="3">When the explosion happened, we were sleeping. At midnight, there was a commotion outside. People were screaming, "Run! No one is safe!" So we decided to leave. When we left our home, my husband was leading the way, and he walked for a bit and then fell down. He hurt his stomach. His bladder ruptured. There was urine everywhere. After that, when we had gone a little farther, two of our daughters began vomiting and had dizzy spells. We had to revive them after they fainted. </P>
<P>There was a pipe nearby that was draining water, and we didn't know what kind of water it was--sewage water or what--but we took some cloth, dampened it in the water and wiped our faces. And then we couldn't walk any further. That's when the police came and told us to come with them. They took us straight to the hospital. </P>
<P>When we got the hospital, I can't even tell you how much it hurt. My eyes felt like they were on fire--like there was a bright line being shined into them, or I was staring into the sun and I couldn't blink. It was unbearable. I couldn't stop the tears. And when we were able to see, all we could see all around us were corpses--piles and piles of corpses. The only thing you wanted to do then was get away from there. You felt like if you stayed, you were certainly going to be absorbed into the growing piles of bodies. </P>
<P>When we left the hospital, it was around 6:30, and I was extremely dizzy and felt like I was going to faint. At 8:30, when we got back to our homes, all we could see everywhere were people lying on the ground--either unconscious or dead. People were carrying some of the bodies to the crematorium, loading them up on carts. At 11:00, we heard people screaming again that Union Carbide was still leaking gas. And then we couldn't stay. We didn't think that we were going to survive. </P>
<P>Everyone was hurting. We walked on until we came to a neighboring village. We found a house and went inside and sat there quietly. We shut all the windows. At 7:00, we left and went back home. The entire neighborhood was empty. But we had nowhere else to go. </P>
<P>Everyone was in bad shape. And we couldn't see. We would hear noises outside of people leaving. Young girls wandering in the street. So we sat there for a long time. I don't even remember how we found food or what kind of food it was. Ten days later, when I could see again, I washed out my eyes. I started cleaning the house. I had to throw everything out that had been contaminated. </P>
<P>And the children were really hurt. One of my sons began bleeding, and we couldn't figure out how to stop it. We took him to the hospital. He died on the fifteenth day. My youngest daughter was paralyzed--half her body. You can still see the effects of it on her face. </P>
<P>My oldest son has trouble with his lungs. He began coughing blood. He became tired of living--you know? He killed himself. My husband had injured his bladder. We took him to the doctor, but he refused to operate because the surgery was too dangerous. He ultimately developed cancer, too, in his bladder. </P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">On the third day, when we had recovered a little, we began searching for each other in our family--trying to figure out where everyone was. No one knew where they were--there were seven people still missing--so we went to the hospital to try and find their bodies among the corpses, because we thought we might find them there, but we couldn't. And so we could only imagine that their bodies had been thrown away somewhere in the communal graves that were being set up in the area. </P>
<P>Eventually, on the fifth day, we found out that they had been taken to another hospital in a neighboring district, and we went to get them. And then, on the 16th, when Bhopal was being evacuated , they told us that they were going to clean up Union Carbide's gas mess so we all had to leave. It turned out they were going to start production again to squeeze out the last bit of profit--produce some more of the pesticide. So we left to stay with our family to a nearby village.</P>

<B><P>WHAT HAVE the last 20 years been like?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Champa:</b> </font><font face="Times New Roman, Times, serif" size="3">Everyone is suffering--the young and the old, everyone. The women are facing the worst of it. They face the worst illnesses. Their children are born deformed. They get cancer. Girls who are 15 look like they are six. Women don't have their periods, and then they can't have children. And the problems have only been compounded after 20 years. You have children born with birth defects. Women have to watch as their children endure all kinds of operations. </P>
<P>And parents have to worry about their daughters not getting married. Potential grooms all wonder about how their family line will continue if they marry women who aren't having their periods or who give birth to deformed children. Potential in-laws only worry about what they will do if these girls get sick--why should they have to bear the cost of caring for them and feeding them? The illnesses are getting worse, too--TB, cancer. If you look at all these things together, you can see why this is a women's issue. </P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">On top of that, we were all desperate for medical care. No one knew how to treat the illnesses from the gas, and Union Carbide wasn't providing the information. They wouldn't tell us how to treat the illnesses and save people. And so we began demanding information about treatment. </P>
<P>And what Union Carbide did was to take the 5,000 tons or more of the chemicals that we left in the warehouse after the disaster, and it just dumped them into the ground around the factory. As a result, the ground water around the factory--and this is the primary source of water--is so poisonous that even today it makes the 20,000 inhabitants of the area sick. </P>
<P>Anemia has become prevalent. Their lungs feel like they are on fire. They have serious trouble breathing. They have digestive problems. They can't keep food down and can't sleep. They even found poison in breast milk--mercury and other poisons. And when infants drink poisoned breast milk, what chance do they really have in life? That poison goes straight to their brains and cause permanent injuries. When a child has a brain injury, what meaning can his life have? </P>
<P>The children do not grow well; they have growth retardation. A girl who is six years old looks like a toddler. One who is 12 looks like she is 6 years old. That's how severely affected the development of the children is in Bhopal. And their illnesses are the kinds that affect the children psychologically. They ask us all the time about how they will survive and how they will live with these illnesses. They hear that people develop cancer after ten years of exposure to the area and the water. And the children are asking what their lives can mean--what is the use of their lives. That's what it is like in Bhopal.</P>

<B><P>CAN YOU describe the economic conditions for people in Bhopal?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">In Bhopal, people who used to earn 50 rupees a day can't even manage to work enough to earn 25 rupees a day. And on top of that, they are afflicted with all kinds of diseases, and they spend their entire earnings on health care. They get some help from charities and the Sambhavna Clinic, but they aren't able to eat because there is not enough food. That's why we have been fighting for 20 years. We need economic support at the same time, because we certainly cannot depend on the government for economic support. </P>
<P>We've been trying to come up with creative solutions to these problems and earn an income. We've started a business, making handmade stationary--some women will make the paper, and others will design the stationary. And if that works, there is always a problem with marketing and figuring out how to sell the stuff. For instance, we have also started a business making paapads, and this is something that women can do and do well, but we are always struggling to sell the stuff. We are trying to find markets in Delhi, Calcutta, Bangalore--and make the paapad business successful. </P>
<P>But the victims' economic conditions are unbelievable in Bhopal. The 20,000 people who live in the area have difficulty breathing, and it's hard for them to work. And if you look at that, you can tell that there's a desperate need for economic aid. </P>
<P>The poor have never been able to afford education. And now, the government has raised tuition to go to public school, so there's not even an issue of education. Plus, when the kids get a little older, the parents need the children to help earn money for the family--to bring a little bit home and help with the expenses. It's not really even within the realm of possibilities. </P>

<B><P>WHY DO you think Dow Chemical refuses to give you justice?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">When we heard that Dow Chemical and Union Carbide had merged, they took on the responsibilities for the explosion, as they were the new owners. So we also began to demand that Dow assume responsibility for Bhopal--medical care, clean up, etc. </P>
<P>We took these demands on a march; we walked 300 miles to Mumbai, where they have a regional headquarters for Dow Chemical. And we spilled red paint all over the building as a symbol of the red blood of the people of Bhopal. Dow Chemical would have to take responsibility for this tragedy and give justice to the people of Bhopal. </P>
<P>When we met with the director of the headquarters of Dow Chemical, he told us that they wouldn't accept responsibility for Bhopal. We pointed out that there was a settlement in America--a case in which Dow Chemical acquired an asbestos factory that Union Carbide had owned, and in that instance, Dow Chemical was accepting Union Carbide's pending liabilities, because America is a powerful country, but this is a poor country, and that was why Dow Chemical wasn't willing to accept responsibility. </P>
<P>Why, we asked them, are you following a double standard? A human life is worth the same, whether they live in America or in the jungles of India. A human life should be worth the same. They told us the difference was that in America it was a question of an ongoing case, and that in India, the case had been settled, but we said this was a lie. We pointed out that there was a criminal case ongoing in India and that they had to take responsibility for the disaster. </P>
<P>So we started a campaign in India called "Jhadoo Maro Dow Ko" [Beat Dow Chemical with broomsticks]. If Dow refuses to take responsibility for the disaster in Bhopal, then we are going to sweep them off the face of the earth. You all might know what a "jhadoo" [broom] is, but you may not understand its significance. A jhadoo is something that you use to clean up the house. And when a woman gets upset, the first thing that she reaches for is her jhadoo. She reaches for her jhadoo when she is dealing with domestic violence or other kinds of oppression. So the women picked up their brooms to deal with Dow Chemical and their mess. </P>
<P>We were saying to them, "Either take responsibility for what happened in Bhopal, or we will sweep you up like so much rubbish. We won't let you do business anywhere." And this, you know, is the kind of "clean up" that can only be done with a jhadoo. </P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Champa:</b> </font><font face="Times New Roman, Times, serif" size="3">In 2000, we went to their headquarters with 5,000 jhadoos. We took contaminated water and contaminated soil with us, too, and we asked them if they would be willing to drink our water. </P>
<P>They called us inside and took our water and our soil and our brooms, and they said to us, "We feel for you." And we said, "What do you mean you feel for us?" And they said, "No, we feel your pain." And I said, " No, you don't feel my pain. It wasn't your family that died. It was my family that died. You don't feel any pain. Your company doesn't want to give us justice." </P>
<P>We don't think they will be able to put us off forever. You know, more and more people are becoming aware of what is going on. We are trying to wake people up. And once you have a population that is awake and willing to fight, nothing can stop you. </P>

<B><P>WHAT WOULD you say to Warren Anderson, the former chair of Union Carbide at the time of the Bhopal disaster, if you ever met him?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Champa:</b> </font><font face="Times New Roman, Times, serif" size="3">We don't want Warren Anderson put to death. We want to see him put in a dark cell somewhere, in prison. We want him to feel what we felt--when we were separated from our children, when our husbands died, when we couldn't see our families any more. That's what we want Warren Anderson to feel. </P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">We have four demands for Dow Chemical: </P>
<P>One, bring Warren Anderson and Union Carbide to India to face the ongoing criminal case in India. And we want the government of India to punish them such that every company will know that the same thing will happen to them should another Bhopal happen in India, or if they decide to cut-and-run. </P>
<P>Two, Dow Chemical [must] take responsibility for the gas-related illnesses and other illnesses that happened after the explosion--and responsibility, for instance, for the women who were young when the explosion happened who are now ill, their children have birth defects or they are unable to have any children at all. Dow Chemical should have to be responsible for the health of two generations of victims in Bhopal.</P>
<P>Three, the economic rehabilitation programs have ended, so Dow Chemical should be responsible for the job training of the people of Bhopal who are exposed and sick.</P>
<P>And four, Dow Chemical should clean up the contaminated soil and groundwater. </P>
<P>There are still 600,000 people suffering from gas-related illnesses. And the economic rehabilitation that we were promised in 1984 hasn't really happened. Only 83 of us are currently employed in these economic rehabilitation centers. The government has reneged on its promises. </P>
<P>That was the slogan we raised as we marched from Bhopal to Delhi. And even though the courts have ruled that we are to be made regular employees, we have yet to be made regular employees--we only make half of what the other workers make. And that's why we want the company to take full responsibility for the problems that we are facing. </P>

<B><P>HOW DID you become an activist?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">My husband is a tailor, but he couldn't work because he had a hard time breathing after what the gas had done to his lungs. He was coughing all the time and had chest pains, and so he couldn't work the machine. And my father was coughing up blood. There were all kinds of problems at home--all the people who earned money in our family were ill and couldn't work. And we had never even stepped foot outside our homes until then, and we had no idea what the world was like or how to earn money or anything. </P>
<P>When we went to work in the economic rehabilitation centers, this was the first time that we discovered that we weren't alone. We found out that every woman, each of our sisters, was facing the same problems. Every house either had someone who had died or someone who was ill. </P>
<P>And in each instance, it was the women who were trying to solve these problems. There were also difficulties that we faced at the economic rehabilitation centers, too. So this became the basis for us to form a labor union. There were a hundred women members--50 Muslims and 50 Hindus. And everyone resolved that they would work together in this struggle. </P>
<P>In this way, we organized all 40 centers--at all 40 centers, there were mostly women workers. There were all kinds of jobs--food preparation, leather work, sewing. In addition to our own labor issues, we began working to solve the problems that resulted from the explosion. And that was when we began campaigning to extradite Anderson--to bring him back to India and teach him a lesson after committing such a horrible crime and running away. </P>
<P>He should be brought back to Bhopal and punished so severely that other companies should be afraid of doing anything like this in India. Other companies should always be forced to think that the penalties that Anderson faces and the company faces could be penalties that they will face, too, if they make unsafe facilities or produce hazardous chemicals. That's what we wanted. And so we began demanding that the Indian government extradite Anderson and bring him to India to face justice.</P>

<B><P>CAN YOU describe your experiences with other environmental movements in India?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Champa:</b> </font><font face="Times New Roman, Times, serif" size="3">When a multinational comes to India, it deals with the government. The companies get rich, the politicians' wallets get fat, but the poor--the poor suffer. The poor get poorer. Whenever these factories are set up, they are always set up in poor neighborhoods. They aren't set up next to the homes of millionaires or politicians. And so when there are disasters or explosions, it's the poor that die. Not the rich. Not the politicians. </P>
<P>And that's why corporations and politicians will never be able to feel our pain. The poor feel the pain of the poor. The things that have happened to us in Bhopal are exactly like the things that have happened to people in Pondicherry and Patancheru. It's very important, you see, to fine these corporations. If these corporations were fined, other corporations would think twice about doing the same thing, and people's lives could be saved. </P>

<B><P>HAVE YOU had contact with the anti-globalization movement?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Champa:</b> </font><font face="Times New Roman, Times, serif" size="3">All of these movements have come into existence because they are trying to save people's lives. There is a natural solidarity between them. And if we can all get together and take our message to the government and get them to stop corporate globalization, we can easily save people's lives. It's incredibly important. </P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">We are all on the same platform now, and we have the same issues and the same concerns. Whether it is about caste issues or about corporations, all of us have to fight together. Politicians will do anything to save their skins and their seats in parliament. </P>
<P>We need a movement. And Bhopal happened because of globalization, and we don't want there to be other Bhopals. When we went to Patancheru [another city in India where corporate pollution is wrecking the environment], we all resolved to fight together, that we would all work together around the same issues. And we should get justice for them, too. Their fish are also dead. Their animals are also dead. </P>
<P>We decided that we would all fight together. And then the people from Patancheru came up to Bhopal and we all spoke with one voice: "No more Bhopals!" These organizations are growing. They are truly global organizations to oppose what our governments are doing all over the world. Look at what George Bush is doing to Iraq. We all have to fight that as well. We have to get together and defend Iraq. This shouldn't happen anywhere else in the world. No more innocent people should have to suffer or die. </P>
<P>What they are doing--these corporations and George Bush and others--is they are bringing all of us together. We are truly confident that we will all get together in the same movement, in the same organization, and fight together. It's so interesting because we feel these things, but it's really quite amazing to see our children also thinking the same things. </P>

<B><P>WHAT DO you call on people in the U.S. to do?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">Americans are so close to Dow Chemical. It's an American company. The managers are all Americans and live in America. Their shareholders are Americans. The opportunities that you have in America to challenge these people are opportunities that we do not have in India. </P>
<P>Everywhere there is a meeting of Dow Chemical and its shareholders, or everywhere Dow wants to open up a factory, you can go there and say, "No, first you have to take responsibility for the disaster in Bhopal, and then you can have your meeting." You have to make them talk about Bhopal first and how they abandoned Bhopal after ruining it. </P>
<P>You can confront Anderson and tell him that he has to go back to India--that he has to tell the world what he has done and what punishment he deserves for it. And if the American people get together, it won't be all that difficult to send Warren Anderson to India. </P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Champa:</b> </font><font face="Times New Roman, Times, serif" size="3">We have been raising our voices in India for a long time. In fact, we had been screaming for 18 years and nothing happened. But in the last two years, when people from America began screaming as well, it made an enormous difference. We have been able to involve so many more people in the struggle this way.</P>

<B><P>DO YOU also have demands of the Indian government, such as on the issue of health care?</B></P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Rashida:</b> </font><font face="Times New Roman, Times, serif" size="3">First of all, the company has to admit that it was wrong, and it has to tell us how to treat people who have been exposed to these gases. They still haven't told us. Our Indian government should force them to tell us what the cure is. They poisoned us and still won't tell us what the antidote is. </P>
<P>Secondly, the Indian government should take full responsibility for the health care and treatment of the victims. And if they can't afford it, then they should press the company to get it for us. Our Indian government should be fighting the company the same way we are. It should be saying, "You injured our people. You are responsible. You should treat them. You should provide jobs. You should clean the environment." </P>
<P>But to tell you the truth, we don't really expect the Indian government to be of any help to us. They have already cut their deals with the corporations. Our government has sold out to the corporations. The courts have, too. None of them are with us. </P>
<P>But still we tell them that if you hope to live your lives with any kind of self-respect, you have to give justice to Bhopal. If Bhopal gets justice, you may be able to live with yourselves. Or else the world will one day point at you and say, "This is India. A nation where 8,000 people were killed in a single day and the company responsible was allowed to flee. A nation that has been powerless so far to bring them to justice." </P>
<P>That's why the Indian government should care and help us get the justice we deserve. In my family, seven people died because of the gas. In every family, there are the same problems, the same illnesses, the chain of death continues today. There are 30 to 32 deaths a month because of gas-related illnesses. And neither will the company take responsibility, nor will the government take responsibility, nor are we getting justice in the courts. No one does anything to stop the contamination. </P>
<P>Despite all of these hurdles, people are continuing to struggle, and the biggest consequence of this struggle has been the changes that it produced in the women--the women and the children. </P>
<P>Ever since we began our campaign against Dow Chemical, our Jhadoo Maro campaign, we have been speaking all over the world to try to prevent other Bhopals from happening and to get justice for Bhopal. Because we don't think it's just a question of Bhopal, but a question of the future of the whole world. </P>
<P>So if Bhopal gets justice, then it will also mean that we can begin to do things to save the world. Because Bhopal is a lesson, and if we are unable to learn from this lesson, then there is no saving the world. If after seeing the consequences of Bhopal we learn nothing--if we set these companies loose on the world and do not affix any legal responsibility to them--then anything can happen. </P>
<P>If you find a Dow Chemical company anywhere near you, you should force them to answer the following questions about Bhopal: What have you done for Bhopal? What justice have you brought for Bhopal? If you are going to set up a factory here, then what kinds of chemicals are you using in that factory? </P>
<P>To get the answers to these questions--to get real justice for Bhopal--we will all have to fight together, from all parts of the world, as one movement. That is the only way we will be able to save the world and prevent more Bhopals from happening.</P>

<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
