<html>
<head>

<title>
Albert: First Reply To Maass
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="5"><b>First Reply To Maass' Opening Essay</b></font><br>

<P><font face="Times New Roman, Times, serif" size="2"><b>By Michael Albert</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | July 15, 2002</font></P>

<P><font face="Times New Roman, Times, serif" size="3">Maass opens his essay by defending Marxism against criticisms "that Karl Marx and Frederick Engels predicted that capitalism would collapse, and it hasn't; that the fall of the Berlin Wall exposed the failure of Marxism; that class struggle can't survive in a world of cable television, the Internet and SUVs" among others. But these aren't my criticisms and I don't want to explore them in a manner that might imply that they are mine.</P>
<P>Maass then quotes Daniel Singer indicating that "gravediggers of Marx--the new philosophers, the Fukuyamas--have plenty of ancestors and will have plenty of successors, and it's not worthwhile spending much time refuting their paid or unpaid funeral orations." True enough, which is part of why I don't wish to explore their types of critique. My type is quite different, from the left, not the right.</P>
<P>I also have to say that I don't want to debate the history of the Russian revolution. This isn't for want of having opinions about it--I have written a whole lot on it and disagree considerably with Maass--but is because a debate about past history doesn't seem to me to be the best or even a good entry point to a debate of the topic at hand, Marxism's relevance today. Yes, examining the history is part of how I came to my views, to be sure, but to debate the history of various revolutions requires agreeing on their facts, and we likely won't. So to go forward in debating Marxism's current relevance, it seems to me it will be more promising to identify what Marxism's main tenets are--since I think we can probably agree about that--and then to ask if they are useful or not today.</P>
<P>In contrast, arguing about whether the old Soviet Union's problems were a function of Stalin's horrible impact (one man somehow reversing a successful revolution) or arose from the inner logic of Bolshevik organization and aims and reflected precisely the implications of Bolshevism as it overcame from the top the aspirations of most participants in the struggle, would only lead to endlessly quoting accounts of the history and words of the participants, and differing about each. It would not likely lead us forward, I fear.</P>
<P>Maass says "Every time Marxism is buried, it seems to rise from the dead, whether a decade or a few years or even a few months later--to become recognized, by supporters and opponents alike, as an important influence on a new generation concerned with the issues of justice, equality and resistance." This has been true, and may be true again. But what does it tell us? Perhaps what Maass intimates--that Marxism is so true that it attracts adherents on that basis. Or, perhaps it tells us that Marxism so serves certain aspirations that it find adherents on that basis. If it's the latter (which is what Marx himself would suggest, I think), we would next be wise to ask what the aspirations are that it so resonates with.</P>
<P>Maass notes that Marxism has much that is insightful to tell us about capitalism. I agree. But this isn't enough to establish that we ought to use a toolbox of Marxist concepts as our sole guide or even necessarily as one guide to trying to replace capitalism with a better system.</P>
<P>Maass quotes some of the <I>Manifesto </I>indicating that parts have lasting accuracy. And again I agree. Many valuable insights exist in the <I>Manifesto </I>and in <I>Capital </I>and in many other works not only by Marx and Engels, but by other Marxists since them, of course. But this isn't enough to establish that we ought to use a toolbox of Marxist concepts as our our sole or even necessarily as one guide to trying to replace capitalism with a better system.</P>
<P>One of the <I>Manifesto </I>quotes that Maass highlights is: "The bourgeoisie has stripped of its halo every occupation hitherto honored and looked up to with reverent awe. It has converted the physician, the lawyer, the priest, the poet, the man of science into its paid wage laborers." And this, of course, is not a quote I would highlight because it is not, in my view, fully accurate. It implies that despite their relative control over their own work lives and over the work lives of countless others, and despite the status, power, and income advantages stemming from their position in the economy, these actors are just wage slaves, like those below. This, I think, is a major error of the Marxist conceptualization of capitalism. I instead call these actors who are located between labor and capital, the coordinator class, quite contrary to Marxist concepts.</P>
<P>My arguments with Marxism, as summarized in my opening statement, have nothing to do with its identification of profit as a driving force, with accumulation as a driving force, with class division and rule by capital as a driving force, or with many other quite valid insights. My arguments with Marxism have to do instead in part with its economism and, much more so, with its failures regarding comprehending economics itself, and particularly regarding class, and thus also in proposing economic aims.</P>
<P>Maass says "Karl Marx and Frederick Engels didn't have psychic powers. If their writings of more than a century and a half ago seem as if they were directly related to the problems of today, it's because they grasped essential dynamics of the emerging system of capitalism that remain central, despite the massive technological, economic, social and political changes of the last 150 years." And this is true. But to grasp some things, even profoundly well, does not establish that we ought to use a toolbox of Marxist concepts as our sole guide or even necessarily as one guide to trying to replace capitalism with a better system.</P>
<P>Of course private ownership of productive assets is horrific, production for profit is horrific, the accumulation process is horrific, market competition is horrific, each in ways very powerfully (though not always comprehensively) explicated by Marxism. So have Marx and Marxism taught us a great deal about these? Of course. But having acknowledged that, we still have to ask, are Marxism's concepts sufficient to the tasks that face us? Do they need augmentation? More, are Marxism's concepts, despite the various insights that they engender, also in other aspects biased or confused or obscure or incomplete or even wrong in ways that have offsetting negative implications so that they need correction? And if Marxism's concepts do need augmentation, and if they do need correction, is this just intellectual reform, so to speak -- a few refinements in an intellectual system that remains basically the same -- or are the changes more major than that, revolutionary to the extent of introducing a whole new logic and orientation sufficient to warrant seeing what we possess after making the changes as something other than Marxism? If we correct Marxism, has the goal changed, as but one example of a fundamental alteration?</P>
<P>That's worth debating, I think. And my views, as outlined in my opening essay are that the types of change needed are:</P>
<P>1. Relegation of economic insights to a proper prioritization, which is to say alongside and entwined with but not above cultural, kinship, and political insights .</P>
<P>2. Incorporation of concepts reflecting the impact of other spheres of life on the economy, as well as the reverse.</P>
<P>3. Enrichment of economic concepts to better account for the social, psychological, and power dynamics of economics itself.</P>
<P>4. Recognition of the way in which the social relations of work and the division of labor -- and not just property relations -- yield class divisions and class rule.</P>
<P>5. Comprehension of coordinator economic models and allegiance to a new set of economic goals in their place.</P>
<P>To try to generate debate about these matters I have two questions that may highlight differences or areas where Maass and I can in fact agree.</P>
<P>1. Do you and the ISO agree that economics is not the motor force of history but is, instead, a motor force of history alongside gender and kinship dynamics, race and cultural dynamics, and political dynamics, and that trying to address these other factors overwhelmingly only insofar as they impact class relations rather than also in light of their own intrinsic logic is just as narrow and misleading as trying to address economics overwhelmingly only insofar as it impacts gender or race or political relations but not in light of its own intrinsic logic would be?</P>
<P>2. Do you and the ISO agree that in capitalist economies between labor and capital there is another class -- call it the coordinator class, the professional managerial class, whatever -- which gains its status, income, and power, from a high degree of monopolization of the levers of daily economic decision making and empowering work conditions. tasks. and responsibilities, and which struggles with capitalists above and with workers below for its own advance?</P>
<P>3. Do Maass and the ISO agree that this coordinator class can become a new ruling class that replaces capitalists, and that that is precisely what occurs in the models that have heretofore been called socialism -- that is, in economies with public or state ownership, corporate divisions of labor, and markets or central planning for allocation -- and do you therefore also agree that to be truly liberatory for working people strategies for change must take into account the role of the coordinator class and orient both program and structure to prevent its rise to power and to instead eliminate it as a separate class by removing all the economic structures (and not just those related to ownership) that infuse some economic actors with domineering power and wealth compared to others?</P>
<P>My claim is that on agreeing to these points one would be propelled to next note that Marxism has contrary positions to these and is, in that sense and when considered as a whole framework, not an asset but a debit. On disagreeing about these points, of course...debate ensues.</P>
<P>Maass says, "No socialist or radical should be satisfied with proving the relevance of Marxism's insights into capitalism. Marxists want not only to explain what's wrong with society, but how to change it. The question of Marxism's relevance depends not only on its usefulness in explaining how the current system works, but on whether it remains useful as a guide to the struggle to change capitalist society."</P>
<P>I quite agree. But this means a few things, it seems to me, that Maass doesn't highlight. Marxism has to not only identify some very important truths about our current economy, but to identify all the truths that are centrally relevant to winning economic change. That is, even if we dispense with inflated formulations that see Marxism as explaining everything and guiding all kinds of practice, and we just say that it should explain the capitalist economy and help us to engage in economic-oriented struggle toward a superior alternative, we would still certainly have to agree that to do this well Marxism would have to properly identify the main classes in capitalism and explain their relations to one another and the types of interests and aims they have or could have, and, as well, the types of movement that would lead toward classlessness rather than simply toward a new class rule. Yet this is precisely where I think Marxism most dramatically fails. And I don't think it is due to changes since Marx's time, but rather that it is due to having been inadequate on this score from the outset.</P>
<P>Instead of two primary classes, as Marxism highlights, we need to understand three. Instead of two kinds of modern economy, capitalism and socialism, as Marxism highlights, we need to understand that there is one with capitalists as ruling class, one with coordinators as ruling class (which has heretofore gone under the name socialism and been advocated by Marxists), and one in which work and all economic life is truly liberated from rule from above, in other words, that there are three. I think the roots of confusion over these matters reside deep in Marxism's concepts, in the Labor Theory of Value, in its orientation to work, and so on...but regardless of its deep origins, the problem is evident and cripples Marxism's relevance.</P>
<P>Maass says some critics say that "Marxism has been tried-and failed, a judgment passed by masses of people in Russia and Eastern Europe who rebelled against `socialism' and tore down the Berlin Wall in the hopes of gaining the prosperity and freedoms offered by capitalism," and dismisses this formulation by saying the societies that were rejected did not warrant the label socialist.</P>
<P>The problem with this view is that what these societies created and enforced was Marxist, whether Maass calls it socialist or not. That is, Maass may want to reserve the word "socialism" for an economy in which workers and consumers truly manage their own lives without domination from above. But Marxism, though it certainly offers rhetoric that favors those worthy values (as do most advocates of capitalism and bourgeois democracy, for that matter), offers no model that implements the aspirations. Instead, every Marxist party that has ever achieved any kind of power has created a coordinator ruled economy (not to mention a political dictatorship). More, every Marxist party whether attaining power or not has employed language and used organizational structures consistent with those hierarchical aims, not with true worker rule. What would Marx tell us to do in this situation? Should we listen to the rhetoric that organized political groups put forth to describe themselves -- appealing all the while, of course, for support? Or should we look at the substance that they offer, the practice and the substantive descriptions of institutional aims? On this point. I think Marx would suggest the latter approach and that Marxists should follow his advice.</P>
<P>And so I have a third question for Maass.</P>
<P>(3) Do you and ISO agree that the organizational means used by a political movement seeking to replace capitalism should be consistent with the logic and aims that it claims to advocate for the future -- so that, for example, if such organizations favor classlessness they should eliminate in their own structures and methods the rule of a few, and, as well, all divisions of labor, methods of remuneration, and decision-making structures and procedures that perpetuate class division (and thereby, as well, create a context disempowering for workers)? If you do agree, does the ISO seek to follow this advisory?</P>
<P>Maass says "The real question is whether the broad outlines of Marx's ideas fit the world today." I agree that that is a central question. But to answer it we have to first agree on what those broad outlines are. What are the central tenets that any Marxist must agree on to be a Marxist? I am not taking my criticisms into detailed subparts of the broad range of views various Marxists hold one might reasonably say are long since jettisoned by others. My critique here and in my opening essay is of the Marxist base/superstructure idea that defining influences flow only from economy to polity, culture, and kinship but not vice versa. It is with the sole priority given by Marxists to property relations as a basis for class division and the ensuing mis-specification of the central classes of capitalism. It is with Marxism's misunderstanding of existing "socialist" models and with its lack of a truly liberating economic vision. It is with Marxism's allegiance to organizational forms that elevate coordinator rule rather than leading toward classlessness.</P>
<P>Maass says "From the beginning, Marx defined the working class not by the kind of work people did, but by their position in society-as `a class of laborers who live only so long as they find work, and who find work only so long as their labor increases capital.' In other words, the working class consists of people who have to sell their ability to work in order to survive."</P>
<P>I agree that this is the Marxist view. But I think it is harmful to our comprehension of society. Yes, we could say there are capitalists and in contrast there are those who sell their labor power for a wage. That's true enough. But the question arises, in this latter group does it make sense to refuse to draw an additional demarcating line that notes another fissure along which their arise opposed interests? Doctors, lawyers, managers, engineers, university professors, politicians, and various other highly empowered and rewarded actors in our society do, in fact, sell their ability to do work to capitalists for wages. However, I contend that this does not make them workers in the same sense as short order cooks, assemblers, brick layers, custodians, truck drivers, and others with much lower income and much less power over their lives are workers.</P>
<P>What's the difference?</P>
<P>There is no fixed perfect border line between any two classes, of course, but roughly speaking the former coordinator class members have a virtual monopoly on the conditions of daily decision making, have considerable control over their own circumstances at work, have considerable say over the conditions and/or tasks and circumstances of those below, and amass considerable status, power, and income in accord. The rationale for their advantages is attributed to their having great skill, knowledge, and intelligence, as seen via their education. The latter worker class members basically obey orders delivered by coordinators above, do not have much control over their own conditions or over anyone else's (except by rebelling), and have horribly low status, power, and income (though this will vary due to unionization and other factors affecting bargaining power). The rationale for workers' relative impoverishment and subordination is their lack of skills, knowledge, and intelligence, as seen by their lack of education.</P>
<P>In other words, contrary to the basic shared tenets of all Marxism, we don't have solely workers and owners as core classes, but instead among all those who work and who don't own means of production we have two groups: wage slaves below and coordinators above. Because there are three central classes, not two, anti-capitalists can have activist program and infrastructure that benefit coordinators above workers, or vice versa -- rather than it being the case that to be anti-capitalist automatically implies being pro-working class. This is the problem that I think afflicts Marxism.</P>
<P>Maass says, "In fact, one of the most important trends over the past few decades is the way that people in jobs once considered privileged and `above' the working class, such as nursing, teaching and clerical work, have been `proletarianized'-that is, forced into the kind of highly disciplined and sped-up environment typical of factory work."</P>
<P>But the thing is, these folks that Maass mentions are workers, even if sometimes better paid and with better conditions than some other workers. Maass doesn't mention managers, doctors, lawyers, and various other types of professionals, who are not workers but are members of the coordinator class. Their status and power can rise and fall too, to be sure, but it does so due to different dynamics than does the status and power of workers and is overwhelmingly opposed to the latter.</P>
<P>Here is a test to get a feeling for whether my claim may be valid. Ask any wage slave in my sense of the term if they think that they and some doctor or lawyer are in the same social category, if they think they have comparable status and power, much less income, and if they think they function via a similar logic. Ask them, for that matter, who they feel more anger and often more hatred toward, these "coordinators," in my terminology, or the capitalists further up the chain of command. I think working people are far more in tune with contemporary class dynamics, by and large, at least in these respects, than many Marxists. Indeed, on this particular score, the more Marxism one knows, very possibly the less in tune with class consciousness and actual class relations one may well be. Blinded by the light, so to speak.</P>
<P>Maass says "In a country like the U.S., something like 75 percent of the population is working class." Interestingly, I often give a rough estimate of 80%. But then I say only a few percent are capitalists. So what about the rest? I say they are in the coordinator class. Maass, it would seem to me, either thinks 25% of the population are capitalists, or he thinks something a good deal less is capitalist and has left open what the others are.</P>
<P>Why does it matter? It matters because one can talk about liberty and freedom and justice and equity and solidarity and every other favorable adjective that anyone can name but have in mind institutions that elevate capitalists as bourgeois intellectuals do, or have in mind institutions that elevate coordinators which is what I think is the case for Marxists, or have in mind institutions that actually do propel the values trumpeted, which ought to be the case for us. This is a huge difference, and, if true, certainly it is enough to warrant moving on to a new conceptual framework.</P>
<P>Maass says, "But it's important to emphasize the very broad range of people that fit the category of working class-those who have to sell their ability to work to survive, and therefore have no real control over what they do for a livelihood and how they do it, at least no control that their employers are bound to respect."</P>
<P>This is not a claim about the real world, in my view. It is, instead, a case of Marxist concepts interfering with perceiving the reality we face. CEOs and finance vice presidents and high level managers and professors at elite universities and high level engineers and doctors and lawyers and various others certainly do sell their ability to work in order to earn wages to survive. That is correct. But it is simply false that as a result they therefore have no real control over what they do, not only for a livelihood, but day to day. Do they struggle with owners above over the range of their prerogatives and benefits? Sure they do. But calling them workers obscures far more than it reveals about their position, their conditions, their struggles, and their potential aims, not least that they also struggle with workers below.</P>
<P>Maass says about the other criticism I consider important...economism..."The main argument is that Marxism, by placing so much emphasis on class and class struggle, ignores struggles against oppression--racial, sexual, national, etc. But the charge doesn't hold water to judge from the record--the amount that Marx and Marxists after him wrote specifically around questions of oppression, or more importantly, the commitment of Marxist organizations to take up the fight on these questions."</P>
<P>The actual criticism isn't that Marxists all ignore other than economic dynamics, though some do, but that they pay attention to them in ways that miss key intrinsic features and relations. We don't look, in fact, to Marx or to Marxist texts to get our most rich and instructive understanding of gender relations or race relations or political relations, or at least I don't. This only becomes damning if Marxists assert that their largely economic framework is a toolbox that sheds light everywhere with no need for priority insights from other frameworks. I hope Maass won't claim that.</P>
<P>On this score, Maass says Marxism tells us "different forms of oppression can't be [fully] understood in isolation from capitalism, because capitalism shapes them--just as it depends on them for its survival." I actually have no problem with that as long as those who say it realize, as well, that different forms of oppression (including exploitation and other economic oppressions) cannot be [fully] understood in isolation from patriarchy, racism, authoritarianism, because these latter systems shape all oppressions (including economic)--just as they are in turn shaped by them. I wonder if Maass agrees that feminists, multi-culturalists, and anarchists, for example, are entitled to say something about their viewpoints quite analogous to what he wants to claim about a comprehensive understanding of class and underlying economic relations (which, of course, regrettably I don't think Marxism gives us)?</P>
<P>And does Maass agree that while fighting for gender gains alone will be insufficient, or for race gains alone, or for political gains alone, so also fighting for economic gains alone will be insufficient, and, more, that fighting for any three of these in terms of implications for the fourth, taking the fourth as some kind of prior and singularly first rank focus, is also going to be insufficient? If so, on this we will quickly agree.</P>
<P>Maass says "Time and again, working people have taken mass action, with their struggles building until they shook whole countries. None of these movements has succeeded in...building a new society free of exploitation and oppression. But the struggles of the past confirm the potential for the future." Of course, but my view is that these movements have all, in fact, not only struggled, but often won -- and won precisely what their logic was aimed at winning even against the aspirations of most of those in the struggle (just as with bourgeois revolutions earlier), which was not a new society free of exploitation and oppression, but a new society without capital but with coordinators elevated to ruling economic status. While it might take us into too broad a range of issues, regarding politics populations suffering the victory of Marxist movements have suffered dictatorship, which was certainly not the rank and file's aim, of course, and regarding gender they have remained saddled with patriarchy that they also didn't actively seek, and regarding culture they got a homogenizing agenda they rebelled against but had to succumb to, and for the economy they got coordinatorism once their efforts were completely trampled beneath the Bolshevik agenda. All of this, it seems to me, was a natural outgrowth of the agenda of the commanding heights of their Marxist movements, a natural outgrowth of the focuses and absences characterizing Marxist concepts, not of their own aspirations.</P>
<P>Maass says, "The importance of this question--how to translate the framework of Marxism into real-life struggles from day to day--is probably the greatest challenge of today and the most important yardstick for judging the relevance of Marxism."</P>
<P>Yes, and it is one of the main reasons I believe we need to transcend Marxism. It seems to me that Leninism isn't an aberration, but is, instead, a natural fulfillment of Marxism's logic, just as Maass claims it to be and just as the fact that virtually every Marxist party has embraced it suggests. And it also seems to me that Leninism...in its organizational allegiances among other facets, is a doomed approach in modern societies. And I am not referring here to its economism -- which is a problem but is potentially overcomeable -- but to the fact that it elevates coordinator class members to both political and economic dominance in the movement itself and in the movement's goals. It makes coordinator elevation a priority. It celebrates it. And as such it doesn't really appeal very well to anti-authoritarian, anti-coordinator, working people, but, even if it did, momentarily, it would not lead to their elevation but only to a new subordination.</P>
<P>Maass says people have used Marxism and will do so again. It reveals much that is valid and important about our society. Certain inadequacies are the result of poor practitioners not the framework itself. All this is true enough. But it says nothing about left criticism of Marxism not only as economistic, but, more, as failing to provide a rich enough comprehension of economics to generate a desirable economic aim and settling, instead, for an aim that subordinates working people to coordinator class rule. Those are the central issues that I think call into question Marxism's value as even one among many core conceptual guides to contemporary practice, much less the sole guide. The issue for me isn't has Marxism got any value, but rather should Marxism be a conceptual framework we identify with and utilize at the core of our thinking about what we are against, what we want, and how we seek to get it. I don't think so.</P>

</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
