<html>
<head>

<title>
Maass: Which Marxism?
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="5"><b>Which Marxism?</b></font></p>
<p><font face="Times New Roman, Times, serif" size="2"><b>By Alan Maass</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | August 26, 2002</font></p>

<font face="Times New Roman, Times, serif" size="3"><P>Up until a decade ago, many discussions and debates on the left inevitably dealt with what was called the "Russia question"--what to say about the society that existed in the ex-USSR, as well as other countries that called themselves socialist. There were obvious reasons for this. Not only was the USSR locked in a Cold War with the U.S. that shaped politics worldwide, but many people and organizations defined themselves by their support for some form of "actually existing socialism." They expressed their goals and organized their activities based on a complete or partial identification with the system that existed in the USSR--or, alternatively, China or Cuba or Nicaragua, etc. At the same time, an increasingly prominent minority of socialists--my group, the International Socialist Organization, among them--rejected identification with what, in our opinion, masqueraded as Marxism and socialism in these countries. </P>
<P>Ultimately, the answer to the "Russia question" was about more than Russia. It was a barometer of how socialists explained their aims, analyzed society and participated in struggles for change.</P>
<P>The fall of the Berlin Wall and the collapse of the USSR changed this. Obviously, the immediate political issues raised by the Cold War disappeared. But also, it became harder to identify with "actually existing socialism." The only exception among significant numbers of people today is sympathy for Castro's Cuba. Most people who considered themselves supporters, however critically, of the USSR or China have since changed their minds--even about their past beliefs, in many cases. Thus, most people on the left today consider the "Russia question" to be a matter of historical debate, if they're familiar with the issue at all--certainly nothing with relevance to today's world.</P>
<P>But I think that the debate between Michael Albert and myself has shown that our answers to the "Russia question" are still very important. </P>
<P>Why? People who've read our exchange about Marxism's relevance might well wonder if we're writing about the same subject. I've made the case that the genuine Marxist tradition--in contrast to the distortions of Stalinism--is committed to democracy, freedom and mass participation in the struggle of the working class majority to win its own emancipation. Michael (I'm happy to follow him onto a first-name basis if he prefers) has argued that Marxism is fundamentally committed to the interests of what he calls a "coordinatorist" minority--and leads inevitably to a hierarchical society dominated by an elite.</P>
<P>When I've cited quotations and arguments from Marxism that I think back up my case and contradict his, Michael dismisses them as rhetoric--the "fine-sounding" words that Marxists have used to win popular support. The core concepts and principles of Marxism remain elitist, he says. Asked to talk about the Marxist vision of a future society, I cited, for example, Karl Marx's <I>The Civil War in France--</I>a work devoted, above all, to championing the forms of mass democracy developed in struggle by the participants of the 1871 Paris Commune as the crux of a solution to how the working-class majority would rule under socialism. But Michael won't accept that this has <I>any </I>bearing on our discussion. Seemingly, nothing that Marx wrote to the contrary can refute the assertion that Marxism's core concepts "privilege" a "coordinator elite." </P>
<P>Why is Michael so certain that the arguments I refer to are only "rhetorical entreaties" to mystify workers (and Marxists, too, according to his qualifications about the sincere intentions of many of them)? Why don't they have anything to do with the "core concepts"? Generally, when he goes beyond the bald assertion of Marxism's inevitable bias, his case comes down to this point (to choose one from a number of similar formulations): "[E]very Marxist party that has ever achieved any kind of power has created a coordinator-ruled economy (not to mention a political dictatorship)." In other words, the proof of the "coordinatorist bias" in Marxism is the practical result--as shown by the hierarchical societies that have described themselves as Marxist. Likewise, in the extracts from his books that he's provided links for at the bottom of his last rejoinder, his critique of Marxism's inherent elitism revolves almost entirely around the Russian Revolution.</P>
<P>Thus, the "Russia question." I believe that Michael's main criticisms of Marxism during this exchange depend on his acceptance that the ex-USSR was what it claimed to be--a society run by Marxists who were guided by the core concepts and principles of a tradition that runs back to Karl Marx. This is why we agree on so little. As I put it in a previous contribution, if the ex-USSR under the rule of Stalinism was a true reflection of Marxism's aims, then I would want nothing to do with Marxism. It's only because I think that there is a genuine Marxist tradition that I continue to make the case for its relevance.</P>
<P>Now I know that Michael will have objections to my characterization of his argument. For one thing, he does have other critiques of Marxism, revolving mainly around his belief that its overemphasis on economics leaves out other important considerations. This argument has come up to some extent during our exchange, and it takes up a portion of Michael's book referred to at the end of his last rejoinder. I tried to explain why I disagree with him in a different contribution ("Myths About Marxism"). But Michael has stated that he doesn't want to focus on this part of his case against Marxism--and more importantly, his more damning charge about Marxism's supposed elitism doesn't follow from this part of his critique. If Michael is right about Marxism's "economism" (and I don't think that he is), then Marxists would be merely less competent about understanding the world and how to change it--not guardians of an ideology that necessarily produces a hierarchical system dominated by an elite.</P>
<P>More to the point has been Michael's claim that Marx and Marxism deny both the existence of a "coordinator class" under capitalism and the possibility of a coordinator mode of production in a post-capitalist society. Here, seemingly, is the fatal flaw in Marxism at the heart of the "core concepts" which Michael rejects.</P>
<P>My argument is that Michael's criticisms about coordinators and coordinatorism don't hold together. They only really make sense as the extension of a critique of the hierarchical society of "actually existing socialism" in the ex-USSR. That is, I believe that Michael has taken a critique of Stalinism--in which I share many of his observations--and walked the cat backward. </P>
<P>Thus, again, the "Russia question."</P>
<P>I've devoted a lot of space in this exchange to making a Marxist case for <I>how </I>Russia became an exploitative and oppressive society ruled by an elite that used the rhetoric of Marxism to justify the exact opposite of Marxism's aims. I'll try not to repeat myself here. What I do want to explain in the bulk of this contribution is why I disagree with Michael's criticisms about Marxism's "coordinatorist" bias.</P>

<B><P>The coordinator class under capitalism</P>
</B><P>I want to comment separately on Michael's discussion of the coordinator class under capitalism and of the coordinatorist mode of production. But the most important question for me is how the two ends of this argument fit together. I can agree with some of Michael's characterizations about the managerial-professional middle class between capital and labor that he calls the coordinator class, and I can agree with some of his observations about the Stalinist system that he describes as a coordinatorist society. But the most fundamental problem with his argument is that "coordinator class" under capitalism and the "coordinatorist elite" in the ex-USSR, China, etc., are two different things--apples and oranges. In my opinion, the only thing that they share is their presence in Michael's attempt to damn Marxists by associating us with something that we're not--both in a future socialist society (as envisioned by genuine Marxism), but especially under capitalism.</P>
<P>I won't spend any more time answering the charge that Marxists "deny the existence of a third class between capital and labor," as Michael says again, for some reason, in his last rejoinder. We have both written now at great length about a distinct social layer that has conflicts with both capitalists above it and workers below--what Michael calls the "coordinator class" and what I have referred to as the "middle class." As far as I can tell, we mostly agree on <I>who </I>we're talking about--the most important component being managers and professionals who exercise authority over the labor of others and have a certain amount of autonomy at work. We should at least establish that the difference between us is about the nature of this class, especially how it acts and its potential to become a ruling class--not whether it exists. </P>
<P>Michael notes my hesitation to use the term "coordinator class," and he's right. I think that it's a loaded term that assumes other parts of his analysis. That's why I've stuck with "middle class"--though I recognize that it's not very precise. In previous discussions of this issue, other writers have used terms such as "the new middle class" and "the professional-managerial class." If it's helpful, feel free to mentally substitute them as far as my discussion is concerned. I'm not as concerned with the label as with the reality it refers to.</P>
<P>Michael's criticism of the case I make is that I see class distinctions only in terms of property relationships, and therefore only understand the middle class as having "some capitalistic attributes and some workeristic attributes, whatever combination and variation may be discussed." This misses class distinctions arising out of the "social relations of the division of labor...[T]he situation in workplaces [demarcates] a new class due to the distribution of empowering and disempowering tasks, such that some people monopolize the former and the rest endure the latter."</P>
<P>Actually, I do agree that one excellent way to identify middle class positions in a workplace would be to look at the distribution of empowering and disempowering tasks. You will find a large number of people who are supervised, and a smaller number who do the supervising. A large number of people who have no autonomy or say-so in how resources are used, and a smaller number who have a great deal of autonomy and exercise day-to-day operational control over resources. The distribution of "empowering work" can be a handy snapshot of class divisions.</P>
<P>But my question is: To what end? Why is there a "distribution of empowering and disempowering tasks"? Michael says that this system of authority arises out of the "division of labor" at work. But the division of labor doesn't develop autonomously. It's the product of capitalist property relations, continually shaped by them--a means of organization that ultimately serves the capitalist class and its drive to accumulate. Thus, the authority of the "coordinators" is real, but is <I>exercised within limits </I>imposed by the core priorities of the system. </P>
<P>To quote again from the passage in Marx that I referred to in a previous contribution, "An industrial army of workmen, under the command of a capitalist, requires, like a real army, officers (managers), and sergeants (foremen, overlookers), who, while the work is being done, command in the name of the capitalist." It's entirely in keeping with the development of a hierarchy that officers and sergeants seek to defend their positions--not only from challenges from below, but threats from above. But that doesn't change the fact that command is carried out "in the name of the capitalist." And when push comes to shove, the command of the officers is subordinate to the command of the generals.</P>
<P>I think that Michael's example of a Hollywood movie studio can illustrate my point. The studio owner has to employ people to run an operation that he can't supervise himself, and these people are on the lookout for ways to advance their own careers. Surprise, surprise--they play politics and make allegiances based on self-interest, rather than loyalty to the studio (frankly, this guy would have to be awfully na&iuml;ve to expect otherwise). But are we really to believe that the studio owner is powerless to control this bunch? I don't follow Hollywood news very closely, but I do know that studio executives have about as much job security as a professional basketball coach. They're always getting fired when the latest blockbuster doesn't materialize--after, of course, they've shaken up the ranks below them. These "high-level coordinators," as Michael calls then, may have a significant degree of autonomy in their jobs and may even resist some aspects of direction from above, but all of this takes place within the limits set by the requirements of capitalist accumulation. The bottom line is the bottom line.</P>
<P>It's also helpful to think about this example outside the specific context of the movie industry, which is more dependent on skilled labor and individual creativity than most businesses. The commodity that Hollywood sells can't be stamped out by a machine (though the studios have given it a shot...), so the people who make movies--as well as the supervisory parasites who align themselves with the creative talent--have that much more power. </P>
<P>But imagine the scenario Michael described at a company that makes dishwashing liquid. The company's owners can't supervise the operation, so they hire people to do this. These managers are just as ambitious on their own behalf. Without question, they're willing to kick the people below them. And they might very well resent the authority of those above--the owners who in all likelihood made it big on the basis of who they know, not what they know. Now you can imagine a certain amount of bureaucratic inertia common to corporations, as long as they're running in the black. But can you imagine any situation in which these managers would drag out the production of dishwashing liquid by exploiting "their relative monopoly on many daily decision-making levels and on information and relations critical to the project"? When you strip away the idiosyncrasies of the movie business, it becomes that much clearer that the power of managers is delegated from above as a function of the rule of capital--and remains ultimately subordinate and dependent.</P>
<P>With the cushion of profitability, those who "command in the name of the capitalist" will become more or less aggressive in protecting and advancing their own careers. But ultimately, the standard of profitability asserts itself, and the rule of capital predominates over other forms of authority and control.</P>
<P>So what about the AMA? This is Michael's one explicit example of "coordinators" <I>uniting </I>to defend their interests. The AMA defends "well-heeled doctors" by "keeping others away from their knowledge," Michael says. Fair enough. But what exactly is proved by this? I can see how the AMA serves as a defensive organization to preserve privilege by limiting the number of doctors--though I'd think many of the main victims would be other sections of the middle class, such as practitioners of non-Western medicine. </P>
<P>But how exactly is the AMA at odds with the capitalist class? The HMOization of health care may have shifted doctors as a group closer to a critique of the free market, but I think that the AMA is still pretty conservative on this question. As an organization, it might be able to impose certain requirements on health-care corporations. But this is at most an inconvenience--not much different from the accounting requirements demanded by the Securities and Exchange Commission. Actually, I could imagine the heads of the industry counting themselves blessed for having a strong organization of doctors to accomplish regulatory and quality control tasks that they would otherwise have to deal with. However more or less bothersome to the health-care bosses, from the point of view of the ruling class as a whole, organizations like the AMA are useful and even necessary for regulating different parts of the system.</P>
<P>In the end, I have to return to the question posed by Hal Draper that I paraphrased previously--here, I'll quote the full passage: "[T]he concept of the 'new middle class'...remains a wraith even for many who claim this concept alone makes Marx obsolete. It is one thing to recognize the existence of increasing numbers of new intermediate elements of various sorts, as Marx did; it is another thing to construct out of these elements an organic class that is meaningful enough to seriously affect social and political life. This requires a cohesiveness, a fund of common interests, an objective basis for solidarity and social unity, such as do not exist among the disparate elements of this ectoplasmic class-construct. C. Wright Mills called it an 'occupational salad,' but this may be too complimentary, since a good salad needs considerable togetherness; the 'new middle class' is more like a dish of herring and strawberries."</P>
<P>It's one thing to identify the factors that distinguish this middle class from those above and below, and another to claim that this class is capable of decisive and independent action (except in the limited circumstances that I referred to in a previous contribution, in which the two "hostile camps" above and below are paralyzed or weak). There is no collective consciousness or sense of solidarity--at least beyond the bounds of professional organizations like the AMA. Members of the middle class pursue their hopes for the future as individuals--hoping to climb the corporate ladder, not uniting with their peers. </P>
<P>Now, Michael rightly points out that, most of the time, workers don't identify collectively. But the nature of the working class under capitalism, brought together in workplaces and with little hope to advance as individuals, makes it necessary to organize together. The nature of the middle class, at least as I see it, doesn't lead in the same direction.</P>
<P>Members of the middle class, as Michael says, often do chafe under the rule of people who they see as "a painful impediment to the fullest manifestation of their capacities." Contempt for the blue-blooded, country club set born with a silver spoon in its collective mouth runs through popular culture--as does sympathy for the middle-class underdog (though not nearly so much for the real underdogs in society). I could probably turn on my TV right now and find a movie where some plucky character is facing down a boorish, pampered pretty boy from the right side of the tracks. But what happens when Michael J. Fox inevitably triumphs over old-money evil? He takes his rightful place among the elite, and the world in which the best and brightest are rewarded is saved again. </P>
<P>Ultimately, Michael (Albert, not Fox) believes that the coordinator class can "wage a class war against capital," enlisting the support of workers to overthrow the system, but then "imposing their rule in the process and...dominating in the new society." We'll leave aside for the moment whether this has ever happened. The question that I'd ask is: Why? Why go to the trouble of a revolution, when the instinct of members of the middle class--bred by their experience as managers who "command in the name of capital" and as a product of their whole world view--is to try to work their way up the ladder? </P>
<P>It's one thing to discuss the role of the middle class or coordinator class under capitalism. But when you start imagining this class taking action to establish itself as the rulers over a new society, Michael's case stops making sense, in my opinion. In fact, the only way it does make sense is to stop thinking of coordinators as doctors and lawyers and managers--that is, everyone that we've been talking about in the analysis of the coordinator class under capitalism--and understand them as a stalking horse for an argument against Marxism.</P>

<B><P>The coordinatorist society after capitalism</P>
</B><P>In my previous contribution, I said that I thought Michael and I have many points in common about the countries that called themselves "socialist"--the ex-USSR, the former regimes of Eastern Europe, China, Cuba and so on. What he calls a coordinatorist society--"It has public or state ownership of productive assets and corporate divisions of labor. It renumerates power and/or output. It utilizes central planning and/or markets for allocation. It has typically been called by its advocates market socialism or centrally planned socialism"--is, I think, an accurate description of the so-called "socialist" countries. </P>
<P>In Russia, according to my case, the rise of this exploitative and oppressive society was the product of the defeat of a working-class revolution and the reemergence, in circumstances of scarcity and civil war, of a minority ruling class centered in the state bureaucracy. And when it comes to the Third World revolutions in China, Cuba, etc., Michael and I agree on even more. We both believe that these revolutions were carried out by elements of the middle class in the name of Marxism and produced, from the beginning, a hierarchical society--usually, I would add, a great advance over the previous rule of colonial overseers or a corrupt oligarchy, but a hierarchy nonetheless.</P>
<P>"So we agree on what was there, we just don't agree on what to call it," Michael writes at one point. But his rejoinder shows that there are important ways that we disagree even about "what was there." Each time Michael becomes more explicit about the association of the so-called socialist societies with his analysis of the coordinator class, his argument breaks down. </P>
<P>For example, in referring to the negative attitudes of workers today to socialism, Michael writes, "[W] orkers reject, I think, their worst nightmare, that the managers and doctors and lawyers they hate in their daily lives and whose arrogance they continually suffer could become unrestrained rulers over them, and they see this in Marxism, not just dictatorship, and I think they are right." he writes. Does he really think that most people associate the ex-USSR with the rule of doctors and lawyers? Of course not. Most people rightly believe that the Red Army generals and KGB spies and Communist Party bureaucrats were in charge.</P>
<P>Michael's problem becomes more obvious when he describes the "ruling class in a market or centrally planned, state or public ownership economy. There are no capitalists. There is a sector--about 20 percent of the population--that monopolizes levers of control of the economy. They have way more income, more power, more status, than those below. They rule."</P>
<P>Where did the 20 percent figure come from? That's Michael's estimate of the size of the coordinator class under capitalism--maybe a bit high, but pretty close, in my opinion. But there's no way that 20 percent of the population belonged to the ruling class of the ex-USSR or China or any other "socialist" country. We're talking about people who exercise not just the authority of "the officers and sergeants," which is subordinate to the authority of the generals above. We're talking about people who shared, if not equally, than to a significant degree in operating the "levers of control of the economy" and the power and wealth it produced. No way is that one in five people in the ex-USSR. Or China. If China's population is 1.2 billion people, than about 240 million of them are fully fledged members of the ruling class, by Michael's calculation--nearly the population of the U.S. Does that sound right?</P>
<P>Michael is correct that an elite, using the rhetoric of Marxism to justify themselves, ruled over the so-called socialist countries. But that elite was never composed of "well-heeled doctors, lawyers, engineers, managers and professionals." On the contrary, the position of a doctor in the ex-USSR, for example, was worse than in the West--reduced to salaried employees of the state with far fewer privileges. Even managers in the system of state enterprises fared no better than their counterparts in the West. They enjoyed direct authority in supervising the labor of workers and relative privileges compared to the mass of people. But they were entirely subject to the demands of the five-year plan concocted by the bureaucratic ruling class above.</P>
<P>Once again, as I argued previously, what's striking about this description of the structure of society in the ex-USSR is how much it resembles Western-style capitalism. Once you strip away the rhetoric, you're left with the picture of a society dominated by a minority ruling class that controls the means of production--not through private ownership, but through the apparatus of the state. This ruling class, like its counterparts in Western-style capitalism, organizes production to meet the demands of competition--not the economic competition of individual capitals fighting to dominate the market, but the military competition of state capitals fighting for political survival. As under capitalism in the West, the primary goal is not the accumulation of private wealth (though this is certainly a goal!), but the accumulation of greater and greater means of production--in Stalinist Russia's case, machinery and factories that could be devoted to military production. "Accumulate, accumulate! That is Moses and the prophets!" Marx wrote in <I>Capital. </I>"Therefore, save, save, i.e., reconvert the greatest possible portion of surplus value, or surplus product, into capital!" Think about the drive to build up the Russian arms industry in the 1930s to deal with the threat from Germany--or the insane race to accumulate the means to destroy the planet during the Cold War with the U.S.--and you can see very clearly how the logic of capitalist production could apply under the rule of the "Marxist" bureaucracy in the ex-USSR.</P>
<P>This is why--or at least the first few reasons why--the ISO has made the case for identifying the ex-USSR and its imitators in China, Cuba, etc., as "state capitalist" societies. Michael objects that that this argument is "far less useful than realizing that it must be, instead, if not capitalism, and if not an economy in which workers self manage--then something else." He quotes me comparing different aspects of the system in the ex-USSR and the West, but dismisses my case, because I apparently didn't explain "the absence of that which for Marxists is usually the first thing mentioned about capitalism, that capitalists own the means of production." </P>
<P>In fact, I had raised just this question in the next sentence of the passage Michael quoted. To repeat my argument: "Nor is 'public or state ownership of productive assets' unknown in the West. Again, in a war economy, even the U.S. government has been known to take control, if not ownership, of whole sectors of industry. Nor did long-term public ownership of industry and services in Europe following the Second World War undermine capitalism. Otherwise, you'd have to imagine that Margaret Thatcher was a socialist and Marxist--since her government owned Britain's coal industry, British Rail, etc."</P>
<P>There isn't the space to do justice to the theory of state capitalism, developed mainly by the British Marxists Tony Cliff and Chris Harman. But I must insist on the importance of recognizing that capitalism doesn't depend on "private ownership of the means of production." Otherwise, there's no good way of explaining how countries like Britain--under both social democrats <I>and </I>free-market Tories like Thatcher--nationalized important sections of their economies. The explanation that makes the most sense is that British Steel was run according to the <I>logic </I>of capitalism--with competition underlying the drive to accumulate, and elected and unelected government officials acting in the same manner that private capitalists would. This same explanation, in broad terms, can apply to the ex-USSR.</P>
<P>If anyone is interested in reading more about the theory of state capitalism, I can recommend a couple of shorter articles available on the Web: <a href="http://www.isreview.org/issues/10/TheFallOfStalinism.shtml" target="_blank">"The Fall of Stalinism: Ten Years On"</a> by Anthony Arnove, in the <I>International Socialist Review;</I> <a href="http://www.marxists.de/statecap/harman/revlost.htm" target="_blank">"Russia: How the Revolution Was Lost"</a> by Chris Harman, in <I>International Socialism; </I>and <a href="http://www.marxists.de/statecap/binns/statecap.htm" target="_blank">"State Capitalism"</a> by Peter Binns, from a pamphlet in the "Education for Socialists" series.</P>
<P>I think that state capitalism provides the best explanation (and an original and innovative one, if I can respond to Michael's criticism that Marxists never recognize anything "new under the sun") for what kind of class society prevailed in the ex-USSR. We can disagree about the precise characterization. But the theory does, in my opinion, explain the structure of Russian society where Michael's account of a coordinatorist mode of production fails.</P>

<B><P>Apples and oranges</P>
</B><P>The coordinators of capitalism are just not the same as the coordinators of coordinatorism. This is, I think, the most basic contradiction of Michael's argument. Doctors and lawyers in today's world don't identify with Bolshevism, and Russia's Bolsheviks of 1917 weren't doctors and lawyers. The arguments that Michael puts forward only make sense as a criticism of Marxism--as an ideology that, despite its rhetoric and even the intentions of its proponents, inevitably produces a hierarchical society dominated by a new elite of coordinators. </P>
<P>I'm in a Catch 22 situation in challenging Michael's assertion here. "[I]f you can show me," he writes, "a serious proposal for an economic system that is supported by any Marxist party that has ever taken power, or has held it, or has even fought significantly for it, that disavows all those features, there would be something to discuss. But I don't think you can do that." </P>
<P>Actually, I can--and did in my previous contribution, quoting at great length from Marx, Frederick Engels, Lenin and Leon Trotsky. But this is dismissed as rhetoric. "Yes," Michael continues in the same breath, "you can show me Marxists calling for power to the workers and whatnot, as you have in your piece, just like I can show you capitalists saying serve the people. But I want to see proposals for institutions, other than those mentioned, by Marxist parties." </P>
<P>I can't win. Michael urges me to show him a "serious proposal" from Marxists for an economic system based on mass participation and democracy. When I cite Karl Marx on just this subject, I'm told that this is rhetoric that hides Marxism's elitist core. Why is this only rhetoric, and not reflective of the core of Marxism. "[Marxists] don't offer a vision that yields that result, or that is even consistent with it," Michael writes. Again with the vision thing!</P>
<P>If Michael is looking for the Marxist equivalent of Parecon--the elaborate discussion that he has helped to lead about what a future society would look like--then it's true that he won't find it put in those terms. Marx and Engels developed their brand of "scientific socialism" in conscious opposition to the prevailing utopianism of the socialists before them--their tendency to dream up the outline of a new society and present it as a finished product. At best, Marx and Engels thought, this was putting the cart before the horse, since the job of planning a new society will belong to <I>those who make one. </I>At worst, the utopias incorporated the prejudices of their creators--anti-Semitism and racism in some cases, disregard for the capabilities and potential of ordinary people to govern themselves in every case. Ironically, Marx and Engels reacted against the utopians for the very reason that Michael criticizes Marxism today--it was a recipe for a society controlled by an elite, however benevolent. </P>
<P>Instead, Marx and Engels mainly spoke about a future society in terms of which class would rule, not what its institutions would be like. The struggle to produce that society would determine its shape, they believed--because through the experience of struggle, a majority class that is oppressed under capitalism would gain the confidence and develop the sense of solidarity necessary to create a new society, based on freedom and democracy. </P>
<P>Sometimes, Michael writes as if he thinks that his discussions about Parecon and the shape of a future society are, in and of themselves, enough to guarantee that everything we want to see under socialism will prevail. In other words, you need a good plan. Institutional prescriptions worked out ahead of time by small numbers of people won't guarantee anything. The mass participation of ordinary people in the struggle to overthrow capitalism and build socialism--in whatever specific shape they decide on--is the guarantee.</P>
<P>But that said, it's simply not true that there is no anticipation in the Marxist tradition of what a new society would look like--no "serious economic vision." Marx's excitement at having gotten a glimpse of a society ruled by workers is palpable in <I>The Civil War in France--</I>which holds up the Paris Commune of 1871. Lenin's <I>State and Revolution </I>champions the soviets, or workers' councils, created spontaneously during the 1905 revolution in Russia, as the basis for a future workers' state. Is this not an "institutional prescription"?</P>
<P>Nope. "Even if we took all the positive quotes about workers freedom and control at face value," Michael writes, "and sometimes I think they are quite honest, in context, though coming from the likes of Lenin and Trotsky I think it is duplicitous garbage, to be honest--they would have no bearing whatever on my claim about serious economic visions. Such rhetoric does not constitute serious vision...Behind the rhetoric, instead, there is public ownership, markets, central planning, remuneration for output or power, and corporate divisions of labor." </P>
<P>This is Alice in Wonderland--passages from Marx mean just what Michael wants them to mean. Anything remotely positive in Marxism must be rhetorical fluff--or, if Lenin said it, "duplicitous garbage," since you can always heap abuse on Lenin. Behind the rhetoric (or the garbage, take your pick) is support for the institutions of a hierarchical, elite-dominated society. What? Can't find it? Can't find support for "markets" and "corporate divisions of labor" in <I>Capital?</I> Even when you put "every Marxist text about economics into a pile," as Michael suggests (inadvertently hinting that he's formed his opinions without having spent much time with them himself). Well, it doesn't matter. It must be there because...Michael's analysis says it is.</P>
<P>My argument, as I said at the beginning of this reply, is that Michael has taken a critique of Stalinism and extended it backwards to apply to the whole Marxist tradition, including Marx himself. But you simply won't find the evidence in Marx of support for a coordinatorist elite. In fact, you find the exact opposite--complete commitment to the principle of working class self-emancipation. </P>
<P>In order to square this circle, Michael resorts to his distinction between the rhetoric of Marxism and its elitist core--which he justifies by pointing out that capitalist ideology promotes false propaganda about equality and justice. But this isn't quite right. False propaganda is only one element of bourgeois ideology. You will find just as many other elements of the ruling ideas of capitalist society that explicitly justify a hierarchy. Like "meritocracy," the belief that the best and brightest rise to the top. The capitalist class can talk about equality at the same time as it celebrates a world where hierarchy is supposedly natural. So some elements of bourgeois ideology have a populist character, and some an elitist one. This is a reflection of the contradictions of the capitalist class itself--its attempt to pose as the ruler of society by natural right, coming up against the fact that the capitalists are a minority ruling class.</P>
<P>By contrast, you will not find any hint in genuine Marxism that hierarchy is natural and inevitable. There is no elitist "core" of Marxism at odds with its "rhetoric"--some set of principles with the power to overcome the intentions of everyone who has ever rallied to the banner of Marxism. </P>
<P>When I objected that the formulations along these lines were a little insulting, not only to Marxists like me, but to everyone who has ever looked to Marxism, Michael responded that his criticisms weren't meant personally--but that he does believe we Marxists are wrong. Quite right. The question shouldn't be whether I take personal offense. My point is to show what Michael's argument forces you to conclude about the capabilities of masses of people who we both would like to see "enter into the realm of rulership over their own destiny."</P>
<P>Because if Michael is right, and Marxism's "rhetorical entreaties" have, for the past 150 years, been a smokescreen for core principles that are fundamentally elitist, then an awful lot of people have been duped. And not only by the finer quality rhetoric of Karl Marx, but the mere "duplicitous garbage" of Lenin and Trotsky--which nevertheless represented, for millions of people in Russia and around the globe, the hope of a socialist future. </P>
<P>I'm open to a debate about what these leading Marxists have said and happy to point out--as I have at various points in this exchange--where I believe they were wrong. But in Michael's "original sin" version of Marxism, they can't possibly be <I>right </I>about their vision of a future socialist society ruled by the working-class majority. Whatever insights Marxists have had about capitalist society, as far as the future is concerned, there's only rhetoric or principles that embody the interests of a middle class elite. </P>
<P>I don't buy it. To me, there is neither an "elitist core" nor "fine-sounding rhetoric" in genuine Marxism--only a 150-year-old tradition that, though much developed over the years, can still be reduced to its commitment to a future society in which "the free development of each is the condition for the free development of all." </P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Alan Maass is the editor of <I>Socialist Worker,</I> a weekly newspaper published by the International Socialist Organization. He can be e-mailed at <a href="mailto:maass@socialistworker.org">maass@socialistworker.org</a>.</P>


</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
