<html>
<head>

<title>
Maass: Is Marxism Relevant Today?
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="5"><b>Is Marxism Relevant today?</b></font></P>
<p><font face="Times New Roman, Times, serif" size="2"><b>By Alan Maass</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | July 6, 2002</font></p>

<P><font face="Times New Roman, Times, serif" size="3">"Marx is definitely dead for humankind."</P>
<P>Quotations like this come up all the time when questions of radical political and social change are discussed. They can be found in the corporate media, especially the blowhard punditocracy. They can be found in textbooks and academic journals. And they can be found--actually, more often and with greater acrimony--in discussions on the left, among people who agree on many points. A variety of arguments are put forward as evidence--that Karl Marx and Frederick Engels predicted that capitalism would collapse, and it hasn't; that the fall of the Berlin Wall exposed the failure of Marxism; that class struggle can't survive in a world of cable television, the Internet and SUVs. What connects them is the desire to bury Marx and Marxism--historically interesting, maybe, but an irrelevancy in the modern world.</P>
<P>But there is one point worth making about the specific quotation cited above. It wasn't written in the last year or the last decade. It's nearly a century old--the words of Italian intellectual Benedetto Croce from an article in 1907. Croce was declaring that Marx and Marxism were irrelevant in the new century--the 20th century, that is. As Daniel Singer, the socialist journalist and writer who sadly died a year and a half ago, put it (citing Croce's words during a 1997 talk that was reprinted in <I>Monthly Review)</I>: "I have quoted it to remind you that gravediggers of Marx--the new philosophers, the Fukuyamas--have plenty of ancestors and will have plenty of successors, and it's not worthwhile spending much time refuting their paid or unpaid funeral orations."</P>
<P>Croce had the misfortune of passing judgement on Marxism a decade before the Russian Revolution of 1917--the great revolt against one of the world's cruelest dictators, the Tsar; the most thorough expansion of democracy and freedom known to the world to that point; and the first glimpses of what a society run by the majority of people might look like. The fact that this first experiment in socialism survived for only a brief few years before the bureaucratic counterrevolution of Stalinism doesn't change the fact that Marx and Marxism were very relevant indeed--viewed as a guide and a framework by masses of people who hoped to make a new society, with themselves as the collective masters. </P>
<P>Likewise, during the upheavals across the world following the First World War--from the revolution in Germany that toppled the Kaiser, to the short-lived establishment of workers' governments in Bavaria and Hungry, to even the U.S. and its "Great Red Year" of 1919, when one in five workers were on strike--many of those who could justly be called the most active in the struggle looked to Marxism as the best explanation of what they were fighting against and fighting for.</P>
<P>Though the years after the First World War marked the highest point of the influence of Marxism--or at least the genuine Marxist tradition, before the distortions caused by its association with Stalinism, in both Russia and other countries--its impression can be seen to some extent in all the great struggles since. Even, for example, the 1980-81 Solidarnosc revolt in Poland, which pitted the 10 million-strong Solidarity union against a dictatorial regime that ruled in the name of Marxism. Nevertheless, leading figures in the uprising and veterans of past struggles in Poland, such as Jacek Kuron and Karol Modzelewski, looked to an anti-Stalinist version of Marxism, with democracy and workers' self-activity at its core.</P>
<P>Every time Marxism is buried, it seems to rise from the dead, whether a decade or a few years or even a few months later--to become recognized, by supporters and opponents alike, as an important influence on a new generation concerned with the issues of justice, equality and resistance. If this is the case, then there must be something about Marxism that draws people to reexamine it time and again. If so, then the version of Marxism put forward by its critics in order to dismiss it--of dusty, old-fashioned ideas, obsessively focused on economic developments to the exclusion of all else--must be inaccurate. Marxism must be a living set of ideas that helps to better understand the world--and more importantly, how to change it.</P>

<P><B>Marxism and capitalism</B></P>
<P>Even after the fall of the Berlin Wall--when both defenders of the free market and many people on the left viewed the collapse of Stalinism as the signal of Marxism's long-foretold death--Marx's name keeps popping up. In 1997, in an article marking the 150th anniversary of the publication of the <I>Communist Manifesto, New Yorker </I>staff writer John Cassidy discovered "The Return of Karl Marx." "Many of the contradictions that he saw in Victorian capitalism and that were subsequently addressed by reformist governments have begun reappearing in new guises, like mutant viruses," Cassidy wrote. He reported a conversation with an investment banker: "To my surprise, he brought up Karl Marx. 'The longer I spend on Wall Street, the more convinced I am that Marx was right,' he said." </P>
<P>More recently, editorial writers at the Allentown, Pa., <I>Morning Call</I> dusted off their Marx in the wake of the Enron scandal: "For several years, we have been told that Marxism is now a defunct doctrine. However, the apparent collusion of our 'democratically elected' leaders in the deceitful (though quite profitable) methods of the firm called Enron should lead us to be less hasty in dismissing Marx as a total lunatic. At least one of the statements of Marx and Engels in the <I>Communist Manifesto </I>prompts renewed attention. 'The executive (the top level of government) of the modern state,' they wrote in 1848, 'is merely a committee for arranging the affairs of the (capitalist) bourgeoisie.'"</P>
<P>It's a telling statement about the continuing power of Marxism when supporters of the status quo feel the need to measure themselves and the society they champion against ideas that are supposed to be irrelevant. After all, it's not immediately clear why Marxism--a body of ideas whose essential core, though developed over the years, was expressed with only a few exceptions more than 150 years ago--<I>should </I>be relevant today. </P>
<P>When the <I>Communist Manifesto--</I>Marx and Engels' agitational pamphlet stating the principles of their version of scientific socialism--was written in 1847, capitalism as we recognize it today was confined to a few countries on the northwest edge of Europe. Only a small fraction of the world's population living in parts of Europe and North America were in the early stages of a different way of life, based on capitalist factory production. The number of industrial workers everywhere in the world at the time was smaller than the number of industrial workers in South Korea today. And the technology that we take for granted today--and which Marxists believe can, if democratically controlled, be the basis for constructing a new society of abundance, instead of poverty and competition--was unimaginable 150 years ago.</P>
<P>Now bear these facts in mind while reading a few random passages from the <I>Communist Manifesto:</I> </P>
<P>"The bourgeoisie has through its exploitation of the world market given a cosmopolitan character to production and consumption in every country...In place of the old wants, satisfied by the production of the country, we find new wants, requiring for their satisfaction the products of distant lands."</P>
<P>"The bourgeoisie has stripped of its halo every occupation hitherto honored and looked up to with reverent awe. It has converted the physician, the lawyer, the priest, the poet, the man of science into its paid wage laborers."</P>
<P>"In proportion as the repulsiveness of the work increases, the wage decreases. Nay more, in proportion as the use of machinery and division of labor increases, in the same proportion the burden of toil also increases, whether by prolongation of the working hours, by increase of the work exacted in a given time or by increased speed of the machinery, etc."</P>
<P>Reading these passages instantly brings to mind images of the world today--an internationally interconnected world dominated by corporate globalization; a world where the reign of profit reaches into and subordinates every area of society and every corner of culture; a world where the newest technological developments appear not as anything that will improve the lives of most people, but as a threat to our livelihoods and sometimes our very existence.</P>
<P>Karl Marx and Frederick Engels didn't have psychic powers. If their writings of more than a century and a half ago seem as if they were directly related to the problems of today, it's because they grasped essential dynamics of the emerging system of capitalism that remain central, despite the massive technological, economic, social and political changes of the last 150 years. </P>
<P>Marxism's relevance, as the <I>New Yorker's </I>Cassidy put it, lies in Marx's "riveting passages about globalization, inequality, political corruption, monopolization, technical progress, the decline of high culture, and the enervating nature of modern existence--issues that economists are now confronting anew, sometimes without realizing that they are walking in Marx's footsteps." But if these passages remain "riveting," it's because Marx and Engels were right when they wrote in a preface to a later edition of the <I>Manifesto: </I>"However much the state of things may have altered during the last 25 years, the general principles laid down in this <I>Manifesto </I>are on the whole, as correct today as ever. Here and there, some detail might be improved. The practical application of the principles will depend, as the <I>Manifesto </I>itself states, everywhere and at all times, on the historical conditions for the time being existing."</P>

<P><B>Marxism and the struggle for socialism</B></P>
<P>The recognition of the way that Marx's analysis of capitalism remains vital is part of explaining Marxism's relevance. But the discussion doesn't end there. After all, this is the part of Marxism that even the investment banker cited in Cassidy's article can accept--in isolation from the struggle to change society. No socialist or radical should be satisfied with proving the relevance of Marxism's insights into capitalism. Marxists want not only to explain what's wrong with society, but how to change it. The question of Marxism's relevance depends not only on its usefulness in explaining how the current system works, but on whether it remains useful as a guide to the struggle to change capitalist society.</P>
<P>Judged from this standpoint, two objections arise right away. The first is that Marxism has been tried--and failed, a judgement passed by masses of people in Russia and Eastern Europe who rebelled against "socialism" and tore down the Berlin Wall in the hopes of gaining the prosperity and freedoms offered by capitalism. But the question depends, above all, on whether these societies should be called socialist. In fact, the "rule of Marxism" in the USSR and its satellite regimes in Eastern Europe--not to mention other imitators that still exist, in China and Cuba--was diametrically opposed to basic principles of Marxism. If socialism is the "self-emancipation of the working class," as Marx put it, then how could any society in which workers exercised no power be called socialist? How does a society that tolerated and encouraged hundreds of forms of oppression--based on race, religion, gender, sexual orientation, nationality and ethnicity, to name a few--square with Marx's vision of "an association in which the free development of each is the condition for the free development of all." If Marx and the Marxists who followed him, including the Russian revolutionaries of 1917, insisted on the centrality of internationalism, why was Stalin's rise to power associated most of all with the development of a concept utterly foreign to the Marxist tradition: the theory of "socialism in one country"?</P>
<P>The answer must be that Stalinism used the rhetoric of Marxism to justify a very different reality--an exploitative system, characterized by the rule of a minority, using forms of authority not that very different to capitalism in the West. Such a masquerade isn't that strange in history. After all, we live in a country where half of political power lies in the hands of a party that named itself Democratic--though its commitment to Corporate America means that it regularly acts in the most undemocratic ways. </P>
<P>So was the Russian Revolution doomed to degenerate into Stalinism? The answer to this question is yes--<I>if </I>the revolution remained isolated in Russia, without the victory of socialism in other more advanced countries. Marxists have always believed that the basis for socialism is abundance--having enough to go around. Certainly, such a society could never survive by itself in an economically backward country where the working class was a minority. Because of the peculiarities of its development, the Russian working class led the revolt that toppled the Tsar and took power as the social force most determined to prevent the old order from being re-imposed. But it could never hold power and create socialism without the support of revolutions in other countries. In the event, the new workers state survived a civil war backed by the intervention of 14 imperialist countries, but at the cost of a ruined economy and a working class that was physically destroyed.</P>
<P>No Russian revolutionary had anticipated this. The desperate measures taken to try to hold power in the hopes that international situation would change laid the basis for a state bureaucracy that, under Stalin, began acting for itself. Ultimately, this counterrevolution was only accomplished by cutting off every living connection to the 1917 revolution--literally, with the murder of almost every veteran Bolshevik. </P>
<P>Much more could be said on this question. My point has been to show very briefly that the crimes of Stalinism shouldn't be used as an excuse to reject Marxism. On the contrary, the counterrevolution in Russia was a confirmation--a ghastly negative one--of Marx's most central propositions about how socialism could be achieved and on what basis.</P>
<P>On to the second objection: Marx predicted the inevitable downfall of capitalism, leading to the establishment of socialism. This hasn't happened, so Marx must have been wrong. There's a shorter answer to this objection: Not true. As common as this misperception is, it stands in sharp contradiction to a number of basic points in Marx's writings. Start with the <I>Communist Manifesto. </I>It doesn't begin with the proposition that history is the result of economic systems changing because of their own internal dynamics, but rather that history is the product of class struggle--of <I>people </I>toppling, transforming and creating economic systems and the political and social institutions associated with them.</P>
<P>This is the basic answer, though there are associated objections, which may explain why this sterile parody of Marxism still survives. For example, the fact that Marx and Engels telescoped many of the tendencies that they recognized in capitalism--that is, anticipated the emergence and development of social and economic factors at a much more rapid pace than actually took place--means that their writings have a sense of expectation about the coming revolution that didn't fit the reality of a capitalist system that was still in its initial stages. </P>
<P>Of course, some of this is merely enthusiasm for the struggle, and it shouldn't be apologized for. Throughout his life, Marx was a partisan first, rather than a dispassionate theorist--if such a thing exists. Nevertheless, it can be said that Marx was at times overoptimistic about how quickly history would move--"[flowing] in part from the underestimation of the subsequent possibilities inherent in capitalism, and in another part from the overestimation of the revolutionary maturity of the proletariat," as Leon Trotsky later put it. At the same time, we still talk about Marxism. The reason is that its basic principles have helped revolutionaries in every passing generation grapple with economic and social developments that Marx didn't anticipate. </P>

<P><B>The basis for a new society</B></P>
<P>The real question is whether the broad outlines of Marx's ideas fit the world today. The answer, I believe, is that they do, even more so than in Marx's own times. </P>
<P>First, what makes socialism possible? In the <I>Communist Manifesto, </I>Marx and Engels recognized that capitalism was a tremendous advance over the societies that came before it--a dynamic system that held the promise of more advances for humanity than "all preceding generations together." These advances didn't come without a terrible cost. "Capital [first emerged] dripping from head to toe, from every pore, with blood and dirt," Marx wrote, referring to the centrality of slavery in the U.S. to the development of capitalism. But along with this barbarism, capitalism produced technological and intellectual advances that would have been unimaginable under previous systems--and which created the possibility for the first time in human history of eliminating scarcity.</P>
<P>But as in all previous forms of society, a system that was once revolutionary has become the opposite. The potential to make new advances in the way that people use resources and produce things to meet their needs--to be more specific, the potential to end hunger, house the homeless, eliminate poverty, give all the sick access to the best health care--has come into conflict with capitalism's social structure, dominated by a ruling class that puts its own wealth and power first. </P>
<P>The expression of this contradiction can be seen in countless ways. HIV/AIDS, for example, was once a death sentence. Today, new drugs exist that have extended the lives of sufferers. So why aren't they available to every single person infected with HIV, without exception? Because they are owned by pharmaceutical companies whose mission isn't to produce and distribute drugs where they're needed, but to make a profit. To put the matter in Marxist terms, the social relations of capitalism--the system of private property--are a fetter on the further development of the productive forces of society in improving the quality of all people's lives.</P>
<P>Or consider the condition of the U.S. economy today. Corporate profitability remains low as a result of what Wall Street call "excess capacity." There are enough auto factories in the world to produce cars to meet the current demand internationally--<I>and </I>sell another car to every U.S. buyer. The capacity utilization in fiber optics--following the 1990s boom that was going to wire the world--is, incredibly, in single digits. </P>
<P>These are signs of what Marx called, 150 years ago, a crisis of overproduction. The unplanned and anarchic free market produces more than capitalists can sell--at an acceptable profit rate. This last point is key, because the concept of overproduction makes no sense in terms of the vast need around the world for the most basic products. It only makes sense in terms of profit--there are too many products to be sold at an acceptable rate of return. As Marx wrote, "So long as the most urgent needs of a large part of society are not satisfied, or <I>only </I>the most immediate needs are satisfied, there can of course be absolutely no talk of an <I>overproduction of products</I>--in the sense that the amount of products is excessive in relation to the need for them. On the contrary, it must be said that on the basis of capitalist production, there is constant <I>underproduction </I>in this sense. The limits to production are set by the profit of the capitalist and in no way by the needs of the producers." </P>
<P>This reality inevitably produces tensions in society, which can and do burst out into open conflicts. Such struggles almost always start over isolated and seemingly narrow issues, with modest goals and usually modest numbers. But for Marxists, they represent different expressions of a deeper conflict--between those whose actions represent at least a questioning and ultimately a challenge to the status quo, and those who defend the current order because they stand to gain from it.</P>

<P><B>The gravedigger</B></P>
<P>Capitalism not only creates the conditions that make a socialist society possible. Just as importantly, Marx believed that it brought together the social force--the working class--capable of toppling the system and creating a new society based on democracy and majority rule. </P>
<P>Does this 150-year-old focus on the working class as the "gravedigger" of capitalism fit the world today? One of the most constant criticisms of Marxism is that the working class has been shrinking in importance and in numbers as capitalism has aged. What people who say this actually mean is that, in advanced countries, the blue-collar industrial working class has been decreasing as a proportion of the workforce as a whole. On the other hand, the size of the industrial working class internationally is bigger than ever, and even in advanced countries like the U.S., it remains an important part of the economy. More importantly, though, the idea that Marxists only care about blue-collar workers is a stereotype--one that goes along with a picture of the proletariat as all-male, working only in factories, engaged in manual labor, etc. </P>
<P>From the beginning, Marx defined the working class not by the kind of work people did, but by their position in society--as "a class of laborers who live only so long as they find work, and who find work only so long as their labor increases capital." In other words, the working class consists of people who have to sell their ability to work in order to survive. Obviously, this applies not only to blue-collar factory workers, but to people who work in offices or the service sector. In fact, one of the most important trends over the past few decades is the way that people in jobs once considered privileged and "above" the working class, such as nursing, teaching and clerical work, have been "proletarianized"--that is, forced into the kind of highly disciplined and sped-up environment typical of factory work.</P>
<P>So when Marxists talk about the working class, we don't mean a minority of people--those that fit into the narrow blue-collar category. We mean the vast majority of people in society. In a country like the U.S., something like 75 percent of the population is working class. And this applies around the world, even in countries that a couple decades ago didn't seem to fit the picture at all. Nearly every country in the world today has a big working class. And what's more, the struggles of recent decades have shown the emergence of the working class in the less developed world as a social force. It's impossible, for example, to talk about the revolution that toppled the dictator Suharto in Indonesia without recognizing the role of the new working-class movement--something that wouldn't have made sense a decade before. Likewise, in South Africa, the struggle against apartheid was transformed in the mid-1980s by the rise of the Black workers' movement, which provided the economic and social power to shake the regime in a way that previous strategies could not.</P>
<P>Now obviously, if three-quarters of the U.S. population are working class, not all of these people think of themselves as that--much less realize that Marxists look to them as "gravediggers" of capitalism. Whether, when, how and on what terms people come to recognize this class position and what it means politically is another matter. But it's important to emphasize the very broad range of people that fit the category of working class--those who have to sell their ability to work to survive, and therefore have no real control over what they do for a livelihood and how they do it, at least no control that their employers are bound to respect. </P>
<P>Others on the left accuse Marxists of putting class before other social identities--that is, "privileging" our favored social grouping, as it were, above others. But this is to reduce all these "identities" to interchangeable categories with nothing different about them. What makes the working class unique from the Marxist point of view is that, first, it is the vast majority in society, and second, it has economic power as the producer of the wealth that drives capitalism forward. Therefore, it has a unique potential to make fundamental change, if organized and conscious of what it can accomplish.</P>
<P>To say all this doesn't mean that Marxists care only about class issues and class conflicts. This is another criticism commonly expressed on the left. Unfortunately, distorted versions of Marxism have given aid and comfort to this belief. Stalinism, for example, turned "official Marxism" into a dull and wooden economic determinism--and the rulers of the ex-USSR were quick to repress political struggles that didn't fit their interests, such as the demand for national liberation in the USSR's republics or the struggle for gay and lesbian liberation. </P>
<P>But there is a tradition of Marxism, going back to Marx himself, which is anything but reductionist. Marx's collaborator Frederick Engels made this point in a letter that is worth quoting at length: "According to the materialist conception of history, the ultimately determining element in history is the production and reproduction of real life. More than that neither Marx nor I have ever asserted. Hence, if somebody twists this into saying that the economic element is the only determining one, he transforms that proposition into a meaningless, abstract, senseless phrase. The economic situation is the basis, but the various elements of the superstructure--political forms of the class struggle and its results, to wit: constitutions established by victorious classes after a successful battle, etc., juridical forms, and even the reflexes of these actual struggles in the brains of the participants, political, juristic, philosophical theories, religious views and their further development into systems of dogmas--also exercise their influence upon the course of the historical struggles and in many cases preponderate in determining their form."</P>
<P>Let's be explicit about the crux of the case made against Marxism on these grounds. The main argument is that Marxism, by placing so much emphasis on class and class struggle, ignores struggles against oppression--racial, sexual, national, etc. But the charge doesn't hold water to judge from the record--the amount that Marx and Marxists after him wrote specifically around questions of oppression, or more importantly, the commitment of Marxist organizations to take up the fight on these questions. </P>
<P>Apart from a moral desire to see the oppressed win justice, there are two important ways that these struggles are centrally important to the class struggle. First, struggles around one issue can spark a fight on others. Thus, the civil rights movement in the U.S. South set the stage not only for the Black Power movement in the north, but the anti-Vietnam War movement, the women's liberation movement, the gay and lesbian liberation movement and the 1970s rank-and-file rebellion in the unions. Second, oppression divides the working class, pitting different groups of workers against one another. "Labor in a white skin cannot emancipate itself where it is branded in a black skin," Marx wrote about slavery in the U.S., and the point applies similarly to other forms of oppression. The logic of this position demands that anyone committed to working class self-emancipation be the first to champion struggles of the oppressed, because working-class unity isn't real unless it is on the basis of the demands of the oppressed.</P>
<P>It might be more accurate for Marxism's critics to say that they disagree with the <I>conclusions </I>of Marxism on questions of oppression. Marxists say two things that are controversial here. First, different forms of oppression can't be understood in isolation from capitalism, because capitalism shapes them--just as it depends on them for its survival. Second, the most thorough struggles against oppression can't be organized on the basis of separate struggles of the oppressed. Such a struggle assumes unity among the oppressed across class lines, which is a recipe for conflict. And it also means rejecting the potential for mobilizing the working class majority in society--which, it should be obvious, is made up of countless workers who suffer oppression--that ultimately has a collective interest to fight for the liberation of all.</P>
<P>Once again, how people come to recognize this interest is another matter. It often seems that the different criticisms of Marxism stem from a pessimism about the possibilities for change--whether working people will fight back, whether they will champion each other's demands, whether they can organize an alternative society that really is just and democratic. Certainly, there can be long periods of time when most working people seem satisfied with--or at least passive about--their situation. Capitalism has plenty of ways to maintain this state of affairs. It controls institutions, like the schools and the media, for communicating its worldview. And second, there's the dog-eat-dog logic to a world in which working people are forced to compete with each other to get by--the main source, while compounded by scapegoating, of divisions among workers.</P>
<P>But the chaotic and unplanned nature of capitalism itself upsets this situation--causing conflicts that fester beneath the surface for a long time and then suddenly break out into the open. And when struggles do take place, even modest ones, old ideas absorbed from school, the media and so on get challenged--opening up the possibility that concepts like solidarity and self-activity can take their place. Struggle transforms people and gives them confidence in their own power. As Marx put it, "Revolution is necessary not only because the ruling class cannot be overthrown in any other way but also because the class overthrowing it can only in a revolution succeed in ridding itself of all the muck of ages and become fit to found society anew."</P>
<P>These are not theoretical points. They represent the experience of the working class movement internationally. Time and again, working people have taken mass action, with their struggles building until they shook whole countries. None of these movements has succeeded in destroying capitalism permanently and building a new society free of exploitation and oppression. But the struggles of the past confirm the potential for the future.</P>

<P><B>Marx and Marxism</B></P>
<P>Marxism isn't the same as what Karl Marx thought, wrote and did up until his death in 1883. Obviously, there have been important developments and contributions to what Marxism represents. Much of this development can be seen along the lines of what Marx and Engels expected and welcomed--"[t]he practical application of the principles...[based on] the historical conditions for the time being existing," as they wrote in the 1872 preface to the <I>Manifesto. </I>In other cases, areas of Marx's writings needed to be rethought in the light of actual developments. But these contributions, and there are many that could be cited, show the strength of Marxism--its ability to grapple with new social developments based on an understanding rooted in the core assumptions developed by a 150-year-old tradition.</P>
<P>The most important contribution to Marxism after Marx, is the question of revolutionary organization. Marx himself gave a few signposts about how he thought socialists should go about organizing. In the <I>Communist Manifesto, </I>he and Engels wrote, "The Communists fight for the attainment of the immediate aims, for the enforcement of the momentary interests of the working class; but in the movement of the present, they also represent and take care of the future of that movement." In other words, socialists have to be involved in every economic and political struggle possible. But at the same time, they point out the connections between different struggles--and try to convince more and more people of the need to get rid of the capitalist system and replace it with a socialist society. </P>
<P>The times that Marx lived through, however, didn't give him the opportunity for applying these guidelines very often. It became the task of future generations to work out the question of organization. The most important conclusions came from the Russian revolutionary Lenin--who is probably more reviled than Marx in the Marxist tradition. Too often on the left, the word "Leninist" is hurled around as a term of abuse, without any effort to understand and answer the substantial political questions about organization that he posed.</P>
<P>The importance of this question--how to translate the framework of Marxism into real-life struggles from day to day--is probably the greatest challenge of today and the most important yardstick for judging the relevance of Marxism. I doubt that there is much disagreement on the importance of Karl Marx's analysis of the nature and workings of capitalism. He was shortsighted on some questions. On many others, his arguments have been vindicated. But for Marx and for the genuine tradition of revolutionary Marxism, the analysis is only as important as the real-world efforts to apply it and make it relevant to the struggle to change society. </P>
<P>Whether Marxism is relevant depends not only on whether the set of ideas helps us explain the world today, but whether it helps us to understand and organize the struggle to change it. As Marx put it: "The philosophers have only <I>interpreted </I>the world in different ways; the point, however, is to change it."</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Alan Maass is the editor of <I>Socialist Worker,</I> a weekly newspaper published by the International Socialist Organization. He can be e-mailed at <a href="mailto:maass@socialistworker.org">maass@socialistworker.org</a>.</P>


</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
