<html>
<head>

<title>
Maass: Myths About Marxism
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="5"><b>Myths About Marxism</b></font></p>

<p><font face="Times New Roman, Times, serif" size="2"><b>By Alan Maass</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | August 5, 2002</font></p>

<P><font face="Times New Roman, Times, serif" size="3">This reply will focus on Michael Albert's criticism that Marxism is "economistic." The argument is formulated in a number of ways over the course of his initial essay and his reply to mine, but the crux is that the Marxist tradition "tends to exaggerate the centrality of economics and gives insufficient attention to gender, race, polity and the environment." At best, Marxism "[addresses] these other factors overwhelmingly only insofar as they impact class relations, rather than also in light of their own intrinsic logic." </P>
<P>Albert has said that he doesn't want to focus on this question in our debate, and he has had much more to say about Marxism's understanding of social class and its supposed bias toward a "coordinatorist" elite. I focused my first reply to him ("Marxism vs. Coordinatorism") on these questions and intend to take them up again. But Albert has also referred to Marxism's "economism" numerous times, and I think this is an important point that needs to be answered.</P>

<B><P>The myth of Marxism's "economism"</B></P>
<P>Albert's charge that Marxism is economistic can rely on what has become accepted as fact on the left. The general agreement is that Karl Marx and the Marxists who followed him were economic "reductionists"--that is, they reduce social questions, from whatever realm of life, to a matter of economics and tend to ignore or downplay issues that aren't immediately related to the class struggle. </P>
<P>As in many other ways--as I've argued throughout this exchange--anyone who wants to argue the case for Marx and Marxism has an albatross to throw off: the association of Marxism with Stalinism, which appropriated Marxism's vocabulary to justify exploitative and oppressive societies in the ex-USSR, China, etc. I took up a lot of space in previous contributions explaining why Stalinism is a gross distortion of Marxism. I won't repeat the points here, but it's important to recognize how the predominance of Stalinism for several generations shaped the debate on the left.</P>
<P>For example, long after the movement for gay and lesbian liberation took off at the end of the 1960s, the position of "official Marxism," embodied in the Communist Party, was that gay sexuality was a bourgeois deviation. The Maoist alternative was that gays and lesbians were examples of petty bourgeois decadence. A minority of socialists rejected this bigotry, looking back to a genuine Marxism that's committed to the fight against all oppression--and which was responsible, for example, for the overturning of all laws against homosexuality following the Russian Revolution of 1917. But because of the predominance of Stalinism, especially in the U.S., the gay and lesbian liberation movement developed with a tendency to dismiss Marxism as having nothing to say about how to understand and fight sexual oppression.</P>
<P>But this isn't the only reason for the widespread acceptance, three decades later, of the idea that Marxism is "economistic." After all, the 1960s and 1970s also produced a rebirth of authentic Marxism among people who challenged the domination of Stalinism and tried to put the principles of self-activity, liberation and democracy back at the core of the socialist tradition. This tradition of Marxism was vindicated by the fall of the Berlin Wall and the collapse of the ex-USSR a decade ago--while most aspects of Stalinism have been marginalized. Thus, in reality, you will find very few people today who consider themselves Marxists and believe anything approaching the concepts that Albert and others attribute to us--that, for example, the "defining influences [on society] flow only from economy to polity, culture and kinship and not vice versa" or that "conceptualizations of the other mentioned realms [don't]offer equally central insights." </P>
<P>These distortions of Marxism are alive today most of all among advocates of <I>other </I>frameworks for understanding oppression--who keep erecting a Marxist straw man to tear down in making their own case. But the widespread acceptance of the straw man instead of the real thing means that anyone who wants to make the Marxist case has to spend a lot of time stating what we know to be obvious--that Marxists devote a great deal of energy to fighting oppression. As I said elsewhere, I don't know any Marxist who would recognize themselves in the generalization that Marxism "gives insufficient attention to gender, race, polity and the environment." Certainly I can't recognize the newspaper that I work on, <I>Socialist Worker, </I>which would be a hell of a lot shorter if we were truly as inattentive as we're accused of being. Or the organization I belong to, the International Socialist Organization, which is involved constantly in struggles around just these questions.</P>
<P>Albert seems to accept this point--kind of. In his reply, he says: "The actual criticism isn't that Marxists ignore all other than economic dynamics&#133;" He can't, however, stop himself from adding: "though some do." </P>
<P>The discussion really should be about what Albert says next--"that [Marxists] pay attention to [gender, race, politics, etc.] in ways that miss key intrinsic features and relations." This is a real objection. I think it's a wrong one, based on a misunderstanding of the approach that genuine Marxists take to understanding different relationships in society--but I'll make that case in a moment.</P>
<P>The debate about <I>how </I>Marxists pay attention, though, can't take place if there's any misconceptions about whether we <I>do </I>pay attention. For example, in his opening essay, Albert writes: "Marxism tends to presume that if economic relations are desirable, other social relations will fall into place." Now if this were true, Marxism would be complacent about the struggle against oppression. I could guess where Albert's formula comes from. Marxists do make the point that a socialist society ruled by the working majority will eliminate the material basis for bigoted ideas. For example, in a society of abundance, based on cooperation instead of competition, Black and white workers won't be pitted against one another for scarce jobs, not to mention housing, education and other aspects of life. One of the most important sources of the perpetuation of racist ideas among white workers will be eliminated. Eventually, in a mature socialist society, racist ideas will make as much sense as the belief that the earth is flat and supported on the backs of elephants.</P>
<P>But to say this <I>isn't </I>to say that ideal social relations "will fall into place"--merely as a result of a change in how the economy is organized. On the contrary, unity and solidarity can't be assumed--they have to be fought for. </P>
<P>The first question to ask is why anyone would expect to achieve "desirable economic relations" without challenging all the forms of oppression that prop up the undesirable ones that exist now. Winning genuine liberation for the oppressed is bound up with the struggle to win the liberation of the whole working class, because the two things--oppression and exploitation--are bound together under capitalism. The system is driven by exploitation--the extraction of profits from the labor of workers--but it depends in various ways on different systems of special oppression that affect different parts of the working class. There won't be freedom from one without achieving freedom from the other.</P>
<P>At several points, Albert argues that Marxism is interested in struggles against oppression only in terms of their implications for economic struggles. Now, first of all, these implications are enormously important. It has been a given for Marxists back to Marx's day that the workers' movement can't succeed in the long term or even the short if one part of it is kept down. The guiding principle here can be summed up in a statement Marx made about slavery in the U.S. South, "Labor in a white skin cannot emancipate itself where it is branded in a black skin." </P>
<P>But Marxists do support struggles against oppression in their own right. Fundamentally, there's the moral desire to see justice done. But there's another factor--the famous slogan of the labor movement is that "an injury to one is an injury to all," but it's also true that "a victory for one is a victory for all." A victory in the struggle against racism, for example, ultimately strengthens the struggle against other forms of oppression <I>and </I>the struggle against economic exploitation. One concrete example would be the way that the civil rights movement set the stage for the other 1960s and '70s social movements, including an upheaval in the labor movement. </P>
<P>Actually, I've always considered the importance of non-economic struggles to be a central understanding of Marxism. So I was a little startled by Albert's off-handed reference to Lenin and his "economism." Anyone who's read Lenin's writings will know that he spent an awful lot of time railing against&#133;economism--by which he meant a tendency among Russian socialists to narrowly focus on workplace issues and neglect political questions. </P>
<P>In contrast, Lenin insisted that Marxism had to respond to all political issues. To take one example, he argued that Russian socialists--living in the belly of the Tsarist beast, so to speak--had to take every opportunity to challenge great Russian chauvinism and champion revolts against the Tsar's "prison house of nations." Not to do so would strengthen the hold of chauvinism among workers in the oppressor nation--and confirm to workers in the oppressed nations that they had no allies in Russia itself. Lenin's insistence on the unconditional support for the right of nations to self-determination was a recognition that working-class unity could only be achieved on the basis of equality--and that means championing the demands of the oppressed. </P>
<P>As Lenin famously put it: "Working-class consciousness cannot be genuine political consciousness unless the workers are trained to respond to <I>all </I>cases of tyranny, oppression, violence and abuse, no matter <I>what class </I>is affected&#133;Socialists should conduct propaganda that exposes the horrors and abuses of the system, so that the most backward workers will understand, <I>or will feel, </I>that the students and religious sects, the peasants and the authors are being abused and outraged by those same dark forces that are oppressing and crushing him at every step of his life. Feeling that, he himself will be filled with an irresistible desire to react, and he will know how to hoot the censors one day, on another day to demonstrate outside the house of a governor who has brutally suppressed a peasant uprising, on still another day to teach a lesson to the gendarmes in surplices who are doing the work of the holy inquisition."</P>
<P>Call it what you want--but economism that ain't.</P>

<B><P>Insights and conceptualizations</B></P>
<P>Albert has a pair of loaded dice at this debate. He argues in numerous formulations that Marxism needs to incorporate "concepts reflecting the impact" of factors such as "gender and kinship dynamics, race and cultural dynamics and political dynamics." On the one hand, this implies that Marxism has little valuable to say about these dynamics. On the other, it promotes "concepts" on the basis of their subject matter, not their content. Comes up sevens every time.</P>
<P>More always sounds better than Less. It seems perfectly obvious that Marxists should supplement their understanding of the world with "conceptualizations" that focus on non-economic realms. No one can object to a proposition at that level of abstraction. </P>
<P>But which "conceptualizations"? Are they compatible with core concepts of Marxism, or do they contradict them? Are the conceptualizations of gender dynamics compatible with the conceptualizations of kinship, race, cultural and political dynamics? Are all conceptualizations of gender dynamics compatible with each other? If not, then More can become Less--less useful for understanding society because of the contradictions.</P>
<P>That's why Albert's questions have to be answered concretely: Which insights and which conceptualizations? So, for example, Marxists of course incorporate feminist insights that help us to understand aspects of women's oppression. But there are other "feminist insights" that, on analysis, don't contribute to our understanding--so we reject them. </P>
<P>Here's one example that comes to mind: Naomi Wolf's book <I>The Beauty Myth </I>makes a useful analysis of sexual commodification and how media images contribute to women's oppression. Her call, elaborated in her follow-up book <I>Fire With Fire, </I>for replacing "victim feminism" with "power feminism" isn't useful at all. Unless, that is, you accept the argument that "enough money buys a woman out of a lot of sex oppression" as the basis for a program for liberation--and can stomach the celebration of American women soldiers during the Gulf War for "wielding real firepower [that] shook loose the blinkers that keep women from imagining themselves as beings who can elicit not just love and desire, but respect and even fear."</P>
<P>If Albert thinks that Marxists should gain insights from "power feminism," then he has to explain how to square a set of ideas that explicitly justifies an individualistic approach to change, accessible only to a minority of upper-class women, with the project of winning liberation for all. If he doesn't think so, then he should amend his formulations--to acknowledge that there are different insights into "gender, race, polity and the environment," which need to be judged on their own terms.</P>
<P>The same can be said about "conceptualizations," a term that Albert uses several times, which I take to mean a more general framework for understanding some aspect of the system. It is a caricature to suggest that Marxists believe that any and all aspects of life can be understood by studying economic relations--an argument I'll come back to later. </P>
<P>I should also say that I have no problem with the argument that non-economic issues have to be understood on their own terms. Thus, Marxists argue that the issues of race and racism as we understand them today developed with the rise of capitalism, and the two have been intertwined since. But of course racism and the antiracist movement have their own tempo and rhythm of development, related to economic developments, but not reducible to them. </P>
<P>Maybe this is enough to set to rest the charge that Marxists reduce every question to economics or class. There's no way that you can look at the real Marxist tradition--both in terms of its analysis and its historical commitment to struggles--and accept that it has no "conceptualization" of other realms of life than economics. </P>
<P>But I think that Albert's real objection is we don't agree with specific kinds of "conceptualizations." He only refers to which kinds once: "patriarchy, racism, authoritarianism."</P>
<P>Now there are plenty of disagreements on the left about these terms, which doesn't help the clarity of this discussion. For example, patriarchy means many things to many people--I know Marxists aren't alone in that assessment. And I have no idea what Albert is talking about when he refers to an "authoritarian" system of oppression. In what sense does "authority" operate as a social system independent of capitalist exploitation and forms of oppression based on race, gender, sexual identity, etc.? I know that anarchists have had a longstanding gripe about the authority exercised by, say, a marshal at a demonstration. We can argue this point if he wants. But it's one thing to talk about authority in movements for change and quite another to claim that such a system functions throughout society. </P>
<P>For the purposes of discussion, I'll make the assumption that the conceptualizations Albert alludes to share an important characteristic that has come to define what is known as identity politics. The characteristic is an understanding of economic exploitation and different systems of oppression as quite distinct, with certain connections to one another, but not decisive ones. Rather than the Marxist picture of a capitalist society in which exploitation and oppression are bound together--each with a life of its own, but connected as parts of the same system--the conceptualizations of identity politics stress the separateness of these different realms. The picture is of a society crisscrossed with conflicting and overlapping antagonisms, with none that are more decisive or less decisive than others and no necessary connection between them.</P>
<P>The first point to make is that identity politics conceptualizations of non-economic issues are no less likely to draw distinctions among themselves. Thus, it's disingenuous to lump together conceptualizations of "gender, race, polity and the environment," as counterposed to Marxism's conceptualization of economics. The celebration of "difference" has been the main thrust of theories of identity politics, with the governing assumption being that different forms of oppression can't be understood in connection to other forms or to society at large, but only on their own terms. </P>
<P>The extremely frustrating practical conclusion has been the splintering of forces seeking social change and the active attempt to differentiate struggles--something that the experience of organizations like ACT UP and Queer Nation shows very clearly, as many activists and writers have pointed out. As the feminist writer Barbara Smith put it: "Queer activists focus on 'queer' issues, and racism, sexual oppression and economic exploitation do not qualify, despite the fact that the majority of 'queers' are people of color, female or working class&#133;Building unified, ongoing coalitions that challenge the system and ultimately prepare a way for revolutionary change simply isn't what 'queer' activists have in mind."</P>
<P>Marxists reject identity politics conceptualizations because we reject the core assumption that exploitation and different forms of oppression have to be understood and dealth with separately. That doesn't mean we believe oppression is a myth, or that oppression should only be understood as a simple reflection of economics, or that these different realms don't need to be understood on their own terms. It does mean we believe that by understanding the connections between exploitation and oppression and, crucially, the ways that they shape each other, Marxism can provide a richer analysis--and more importantly, pose an alternative that doesn't splinter movements seeking change, but has the potential to build unity among them.</P>

<B><P>Marxism and oppression</B></P>
<P>The contrast between Marxism and post-Marxism seems most stark when it comes to their different conclusions. For Marxists, the overthrow of capitalism has to involve a united class struggle against not only exploitation, but all forms of oppression. The various brands of identity politics share a basic pessimism about this potential for unity.</P>
<P>What is the Marxist case for being optimistic? Obviously, this question can't be answered exhaustively here. But one way to start would be to focus on who benefits from oppression under the existing system--and who therefore has an interest in ending it. </P>
<P>Take women's oppression. It's certainly obvious how ruling-class men benefit from women's oppression--not simply at the level of individual relationships, but in terms of the system as a whole. They reap the profits of paying women workers less for the same work as men. Also, the system bears no responsibility for the cost of raising the next generation of workers--what a process that Marxists refer to generally as "reproduction." The burdens that women mainly bear inside the nuclear family remain a private responsibility. Beyond scant government measures that may or may not exist as a social safety net, there is no recognized social responsibility under capitalism to provide care for children and to maintain families. Because the system isn't responsible, the wealth of ruling-class men is that much greater.</P>
<P>But by this measure, ruling-class women clearly benefit from women's oppression. They share in the greater wealth that the ruling class enjoys because of the systematic discrimination against women in the workplace and the privatized nature of reproduction. What's more, ruling class women have the resources to hire workers to perform much of the labor that falls on them inside the nuclear family. Oppression does affect all women, but far from equally. In important ways, ruling-class women benefit from the oppression of working-class women--and they have the financial resources to overcome many of the burdens that fall on them as a result of privatized reproduction.</P>
<P>What about working-class men? Again, in most, though not all, individual nuclear families, working-class men gain an advantage from the unequal burden of privatized reproduction that falls on women. But this advantage is overwhelmed by the disadvantage of having the responsibility for reproduction located in the nuclear family. That is, husbands would benefit, too, from a system of socialized child care and so on. </P>
<P>Moreover, in crucial ways, working class men plainly <I>aren't </I>responsible for women's oppression. Husbands don't pass laws restricting the reproductive rights of their wives. Likewise, men aren't paid more because women are paid less. In fact, the opposite is the case--employers have long taken advantage of women's low wages to try to push down the wages of all workers. </P>
<P>This is the gist of the Marxist case against the belief that all men benefit from the oppression of all women. On the contrary, working-class men have an interest in fighting to end the oppression of working-class women. </P>
<P>To say this is <I>not </I>to say that working-class men automatically perceive and act on this interest. Overcoming the false ideas about women's "naturally" subordinate position in society--which exist in the heads of men <I>and </I>women--depends on the course of struggles that challenge existing prejudices. When struggles do take place--economic or political, even modest ones--old ideas absorbed from school, the media and life under capitalism in general get challenged, opening up the possibility that concepts like solidarity and self-activity can take their place. But none of this is automatic. In fact, it depends ultimately, I would argue, on the intervention of revolutionary organizations making the case for the importance of championing all demands against oppression.</P>
<P>This argument can be applied, with certain obvious qualifications, to other forms of oppression--racism, anti-gay bigotry and so on. And on this score, Marxism has a tradition and a record to be proud of--in its commitment not only to the fight against exploitation, but for the liberation of all.</P>

<B><P>Base and superstructure</B></P>
<P>Albert's belief that Marxism is "economistic" flows from a wrong understanding of Marxism's core concepts. He's especially critical, for example, of an old pair of culprits--base and superstructure. According to him, Marxism identifies an economic base of society, which produces a social superstructure&#133;end of story. "My critique here and in my opening essay," Albert says, "is of the Marxist base/superstructure idea that defining influences flow only from economy to polity, culture and kinship, but not vice versa."</P>
<P>Again, there is a basis for believing this about Marxism--if you accept the distortions of Stalinism. The theorists who justified the existence of a hierarchical society in the ex-USSR were very concerned to write the concept of workers' control over society out of Marxism. So they concocted a formula out of scraps of Marx's writings under which a certain level of industrial development would simply equal socialism, regardless of the actual experience of the vast majority of the population.</P>
<P>This is a parody of Marxism that directly contradicts passages from Marx, including those where the base/superstructure distinction arises. But to explain why, I have to briefly sketch out the basic ideas of Marx's historical materialism.</P>
<P>Marx's use of the terms base and superstructure was a shorthand reference to different elements of society and how they develop through history. As a materialist, Marx believed that the most basic factor in history is the way that human beings interact with nature and cooperate with each other to produce the things that they need--"the simple fact, hitherto concealed by an overgrowth of ideology, that mankind must first of all eat, drink, have shelter and clothing, before it can pursue politics, science, art, religion, etc.," as Frederick Engels said in a memorial speech for Marx. </P>
<P>Putting it more formally, Marx argued that the existing "forces of production," meaning the tools and technology for producing what people need and the knowledge and skills to use them, have corresponding "relations of production," meaning the form of organization resulting from human beings cooperating with each other in the process of production. "The sum total of these relations of production constitutes the economic structure of society, the real basis on which arises a legal and political superstructure, and to which correspond definite forms of social consciousness," Marx wrote.</P>
<P>So the way that human beings materially provide for themselves shapes the way that they cooperate with each other, and this in turn gives rise to distinctive forms of political organization, as well as the ruling ideas of a given society. </P>
<P>When you look at this in terms of the broad strokes of human history, it seems obvious. After all, how could the complex forms of political organization created under capitalism exist in the world of hunter-gatherer bands tens of thousands of years ago, where the numbers of people associated with a given band was limited to a few dozen by the material inability to provide for any larger numbers? Likewise, the idea of competition which so dominates the ideology of capitalism would make no sense in such a world--which is why, for example, European settlers in North America reported that Native Americans found the new social structures being imposed on them utterly alien because they didn't allow them to cooperate. </P>
<P>The same distinctions can be made about different forms of class society. Thus, the feudal world, in which the main methods for producing what people need to survive revolved around small-scale agricultural production, led to the political rule of kings, lords, dukes, etc., and predominance of duty, honor and chivalry as some of the basic components of the ruling ideology. A world dominated by urban industrial production creates forms of political rule organized around a limited democracy, and the predominance of competition and individualism in the ruling ideology.</P>
<P>If that were all there were to Marx's views, then he would be guilty of what Albert claims he is. But Marx didn't believe that the forces of production developed evenly and unhindered, leading automatically to transformations throughout society. In fact, his entire account of history is built around the idea that the potential for developments in the way that people produce is stifled by the existing organization of society, both at the economic base and in the political, legal and ideological superstructure. Far from ignoring the impact of the superstructure on the base of society, Marx believed that the various parts of the superstructure became arenas of massive political and ideological struggle, whose outcomes could determine what happens in the base.</P>
<P>Engels was especially explicit about this in criticizing mechanistic readings of Marxism that began to develop after Marx's death. "According to the materialist conception of history," he wrote in one letter, "the ultimately determining element in history is the production and reproduction of real life. More than that neither Marx nor I have ever asserted. Hence, if somebody twists this into saying that the economic element is the only determining one, he transforms that proposition into a meaningless, abstract, senseless phrase. The economic situation is the basis, but the various elements of the superstructure--political forms of the class struggle and its results, to wit: constitutions established by victorious classes after a successful battle, etc., juridical forms, and even the reflexes of these actual struggles in the brains of the participants, political, juristic, philosophical theories, religious views and their further development into systems of dogmas--also exercise their influence upon the course of the historical struggles and in many cases preponderate in determining their form." </P>
<P>I actually quoted this passage in my initial essay, and I'm not exactly sure why Albert ignored it in repeating his criticism of "the Marxist base/superstructure idea that defining influences flow only from the economy."</P>
<P>So genuine Marxism has never believed that the superstructure is a passive reflection of the economic base. Political forms, legal dogmas expressing the rule of different kinds of property relations, ideological creations--all of these can have a reciprocal influence, affecting the character of production and how it takes place in a given society. As Engels put it at another point: "Political, juridical, philosophical, religious, literary, artistic, etc., development is based on economic development. But these all react on one another and also upon the economic basis. It is not that the economic situation is cause, solely active, while everything else is only passive effect. There is rather interaction on the basis of economic necessity, which ultimately always asserts itself."</P>
<P>This should correct the misunderstanding that "the Marxist base/superstructure idea [sees] defining influences flow only from economy to polity, culture and kinship, but not vice versa." But a difference does remain. In Albert's initial essay, he writes, "Marxism would need to recognize both directions of causality, not exclusively or even primarily only causality from economics to the rest of society." Marxism does recognize "both directions of causality." But it also insists that economics "ultimately always asserts itself," as Engels wrote--that the material question of how people produce to meet their needs is the <I>primary </I>factor in shaping other realms of life.</P>
<P>The point of saying that economics is more active in shaping other realms of life than vice versa is to give a picture of how society has developed and changed throughout history. Ultimately, no one who thinks that "everything influences everything" equally can offer a convincing explanation for the enormous variety in the forms of human societies, what connects those different forms and how they've been transformed throughout history.</P>
<P>Consider the question of racism. As we understand it today, racism hasn't existed for longer than five or so centuries--that is, no serious historical account has uncovered a similar form of systematic racial oppression before the dawn of capitalism. So, for example, slavery existed in a number of different civilizations--most notably, the Roman Empire--but it wasn't based on race, as modern slavery was. There are, of course, examples of xenophobia, but nothing that approaches the systematic character of racism under capitalism, with its propagation of a vast and utterly false ideology justifying the inferiority certain human beings because of skin color. </P>
<P>So how is this to be explained? Did some dormant instinct suddenly kick in 500 years ago? Is there some another explanation for the sudden appearance of a new form of oppression? Or does it make more sense to recognize that the early development of capitalism, with its drive to exploit far-flung markets and insatiable demand for a highly disciplined pool of cheap labor, gave rise to a system of racial oppression to meet its needs? </P>
<P>Again, it must be stressed that to identify economics as the primary factor that led to the development of racism doesn't mean that racism as a system of oppression hasn't taken on a life of its own and in turn shaped the development of capitalism--sometimes in absolutely decisive ways, such as apartheid South Africa. But one <I>did </I>come first. Thus, in the broad outlines of history, one factor has to be seen as more decisive in shaping the other.</P>

<B><P>The proof in the pudding</B></P>
<P>"All mysteries which lead theory to mysticism find their rational solution in human practice and in the comprehension of this practice," Karl Marx once wrote. In other words, the proof is in the pudding. </P>
<P>Much of this debate has taken place at a high level of abstraction. And while it may or may not be an interesting intellectual exercise, the discussion should return to the initial question: Is Marxism relevant today--as a tradition that can help those fighting struggles now? If I've been insistent about being concrete in assessing political ideas and theories, it's because I think that they need to be applied to the real world--and used in today's struggles for change.</P>
<P>If the Marxist case holds any water, then we should be able to see some practical evidence for the approach that I've tried to describe. If it's true that workers have an interest in championing struggles against oppression--and that the actual course of struggles themselves help people to challenge old conceptions and become conscious of this interest--then history should show some proof. </P>
<P>I think that it does. Naturally, the recent evidence is anecdotal--especially from the period of the last 20 years, when the level of struggle has been highly uneven at best. Nevertheless, when I hear the case made that all men are part of a patriarchal power structure that props up unequal gender relations, I think of the Mother Jones brigade of miners' wives during the Pittston miners strike of 1989-90. Here was a struggle, taking place in a very traditional community, where women--mainly because of economic necessity, rather than an ideological commitment--took the initiative in a campaign of mass civil disobedience. And the public role of women in the struggle couldn't help but lead to questioning about women's role inside families. These kind of shifts in gender relationships as a result of struggle have taken place time and again--with the unfolding uprising in Argentina against the free market another example that comes to mind.</P>
<P>There many other examples I could cite. Of course, the burden of centuries can't be overthrown in a single demonstration or a single strike, and not every struggle transforms everyone participating in it and even most people. But the point of such examples is to say that there is an overall <I>direction.</I> The needs of the struggle itself open the way for backward ideas to be challenged and the basis for unity built. But the only guarantee that the potential for unity is realized depends on the efforts of the most advanced and committed activists making the case.</P>
<P>For Marxists, the greatest test of all is the 1917 Russian Revolution. Albert makes it very clear that he disagrees with my assessment of that revolution and especially the Marxist revolutionaries, the Bolsheviks, who led it. He's right that this debate isn't likely to change either of our minds. But I have to take exception when he says that we "likely won't" agree on the facts. There <I>are </I>facts about the Russian Revolution that aren't subject to interpretation.</P>
<P>Here are some facts that are relevant to this discussion about Marxism and oppression. In the months following the October Revolution, the new government of workers' councils approved the right women to vote and run for public office--at a time when no other society had yet granted full suffrage. Women were granted equal pay for equal work. Abortion was made free and legal. Divorce was granted on request. All laws criminalizing homosexuality were repealed. In the land of the pogroms, Jews were elected to lead the workers' councils in Russia's two biggest cities and the Soviet Republic itself. </P>
<P>All of this took place within months of the establishment of workers' power--before the civil war, economic crisis and imperialist intervention strangled the Russian Revolution, as the leading members of the Bolsheviks acknowledged at the time. </P>
<P>But the defeat of the Russian Revolution doesn't alter its accomplishments. This was a revolution that everyone admits was inspired by a commitment to Marxism, and it produced in its very first weeks some of the most advanced measures aimed at ending oppression that the world has ever known. That, I think, is one of the most important arguments for why Marxism is very relevant today--as a tradition committed not only to ending economic inequalities, but to banishing all bigotry and discrimination and building a society of justice and freedom.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Alan Maass is the editor of <I>Socialist Worker,</I> a weekly newspaper published by the International Socialist Organization. He can be e-mailed at <a href="mailto:maass@socialistworker.org">maass@socialistworker.org</a>.</P>


</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
