<html>
<head>

<title>
Albert: Conclusion
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="5"><b>Conclusion</b></font><br>

<P><font face="Times New Roman, Times, serif" size="2"><b>By Michael Albert</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | September 16, 2002</font></P>

<P><font face="Times New Roman, Times, serif" size="3">Our topic in this debate has been the relevance of Marxism for seeking social change today. My view has been that while Marxism of course contains many powerful and important insights, adhering to Marxism as a guiding ideology that we label ourselves by ultimately does more harm than good. </P>
<P>When Richard Wright said his goodbyes to Communism he wrote:</P>
<DIR><P>"An hour's listening disclosed the fanatical intolerance of minds sealed against new ideas, new facts, new feelings, new attitudes, new hints at ways to live. They denounced books they had never read, people they had never known, ideas they could never understand, and doctrines whose names they could not pronounce. Communism, instead of making them leap forward with fire in their hearts to become masters of ideas and life, had frozen them at an even lower level of ignorance than had been theirs before they met Communism."</P></DIR>
</DIR><P>Talking about Marxism most broadly, there is a sense in which Wright's comment encapsulates my views as well &#151; not of every Marxist, of course, and certainly not of Alan Maass, my debate partner with whom I share a great many agreements and who is the antithesis a "mind sealed against new ideas," but of Marxism as it plays out on average for organized movements and parties, and particularly Leninist ones. But in this debate I focused on only two central issues where I think criticism may lead most constructively forward. </P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>First, Marxism's concepts tend to over emphasize the defining influences arising from economics, and to under emphasize the defining influences arising from gender/kinship, community/culture, and polity. This doesn't mean that all (or even any) Marxists will ignore everything but economics, nor even that all (or even any) Marxists won't care greatly about other matters. It means, instead, that when Marxists address the sex life of teenagers, marriage, the nuclear family, religion, racial identity, religion, cultural commitments, sexual preferences, political organization, war and peace, and ecology, they will overwhelmingly tend to highlight implications for class struggle and to deemphasize concerns rooted in the specific features of race, gender, power, and nature. The criticism predicts, that is, that Marxist movements may respect innovations coming from other viewpoints when movements force them too, but that Marxists will not generate many original and useful insights themselves regarding analysis and aims for polity, culture, and kinship. It predicts, as well, that Marxism's concepts will not sufficiently offset tendencies imposed by society, by circumstances of struggle, or by tactical choices that generate authoritarian, racist, or sexist trends -- even against the best moral and social inclinations of most Marxists. And it therefore also predicts that we will see some pretty horrible results regarding race, gender, culture, ecology, and political organization from Marxist movements in struggle and especially from Marxist movements in power, as we most certainly have. In other words, my claims about Marxism's "economism" do not predict silly monomania about economics or even a universal and inviolable pattern of over adherence to economics and under adherence to everything else, but, instead, they predict a harmful pattern of imbalance that arises and persists on average. </P>
<P>Second, Marxism's concepts fail to highlight a (coordinator) class between labor and capital defined primarily by its relation in the division of labor and not by matters of ownership or political bureaucracy. Marxism inadequately understands the post capitalist modes of production it positively calls "socialist" or critically calls "state capitalist," and fails to see that they elevate neither capitalists nor workers to ruling economic status, but what I call the coordinator class of planners, managers, and other empowered actors in the economy. Likewise, Marxism typically favors markets or central planning for allocation, public or state ownership for control of assets, remuneration for output or power (and sometimes, for need) to determine distribution of income, plus corporate divisions of labor to define workplace organization. And regardless of hopes or intents, these commitments all propel coordinator outcomes. Notice, this doesn't say that most (or arguably even any) individual Marxists are self-consciously trying to advance the interests of managers and other empowered actors over and above workers. It says, instead, that the concepts within Marxism do little to prevent this elevation of the coordinator class and even propel it in various ways, so that we can expect to see coordinator economic dominance emerging from successful Marxist movements regardless of the sentiments of the movement's rank and file and slogans of its leadership &#151; as we have in fact seen, historically, every time.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>What is an antidote for the two highlighted problems? Regarding economism, in our debate I suggested that the problem is a conceptual framework that starts from economics and only then enters into other realms derivatively and with the primary intention of seeing economic implications. I proposed that we ought to instead begin with concepts that simultaneously highlight economics, polity, kinship, and culture. We ought to use concepts that first prioritize understanding each of these sphere's own logic and dynamics, and that second prioritize seeing how each sphere influences and even limits and defines the others. In these two steps our new conceptual framework should posit no a priori hierarchy of importance to these spheres of life, but should instead see how they work out in practice. I have urged that this approach will more likely yield thorough insights about racism, ethnocentrism, sexism, homophobia, and authoritarianism (as well as economics), than will starting with economics only as our foundation. </P>
<P>In other words, I have argued a multi-focus approach will better push activists toward useful insights about all these spheres of social life and better ward off pressures to be narrow or even reactionary regarding any of them. The argument is structurally like one that says that starting from kinship and gender, or from polity, or from culture, and trying to understand society primarily based on that focus and in terms of affects on it, is unlikely to be as insightful regarding economics as is starting (as well) from economics -- an argument that I think all Marxists accept. And I have noted as well a possible correction of this type economism even within the broad rubric of Marxism. A person could say, for example, "I am Marxist but I am also feminist, multi-culturalist, anarchist, and green, and I recognize that dynamics arising from spheres of life other than the economy are critically important and can even define economic possibilities, just as the reverse can occur. Yes, of course I still think class struggle is critical to social change, but I realize it is not alone critical. Gender, race, religious, ethnic, sexual, and anti-authoritarian struggles are also critical. I realize that just as we need to understand non-class phenomena in their relation to class struggle, we also have to understand economic phenomena in their relation to gender, race, and political conflicts." </P>
<P>But, if this new Marxist renounces ideas of economic base and extra-economic superstructure, rejects historical materialism as typically understood to impact history overwhelmingly only from modes of production, and transcends seeing class struggle as the alone dominant conceptual framework for identifying strategic issues -- will still calling him or herself a "Marxist" continue to mean what it meant in the past? Will the label "Marxist" connote what the multi-focus activist intends his or her self description to connote? I don't think so, but I can imagine overcoming this communicative problem. </P>
<P>In contrast, the class-definition difficulty of Marxism seems less tractable to me. The basic problem is straightforward. Capitalists are capitalist by virtue of private ownership of the means of production. No longer having capitalists above workers requires, therefore that private ownership must be replaced. So far, so good. But there is, however, another class above workers, located between labor and capital, that I call coordinators. Coordinators are made coordinator by virtue of market or centrally planned allocation and hierarchical divisions of labor that allot to them a virtual monopoly on empowering tasks and on the levers and requisites of daily decision making. No longer having coordinators above workers requires, therefore, that those features too must be replaced. The problem is, Marxists don't generally reject markets, central planning, and especially hierarchical divisions of labor, much less try to replace them. </P>
<P>Yes, Marxists sometimes talk about a class between labor and capital &#151; but they do so primarily in political terms, asserting that its roots derive from Stalinism. They rarely see a third class between labor and capital deriving from the division of labor and from modes of allocation (not ownership or politics). And they do not see, therefore, that markets, central planning, and hierarchical divisions of labor are a source of class division and of a ruling class other than capitalists above labor, even if private ownership is eliminated and the state remains or becomes democratic. </P>
<P>Marxists do not, in this regard, in my experience, offer a clear institutional statement of truly classless institutional aims regarding economic decision-making, divisions of labor, workplace organization, remuneration, and allocation. Yes, Marxists often offer descriptions of the justice, equity, and dignity that "socialism" should usher in. And these descriptions are most often eloquent and worthy statements that any advocate of justice can support. But, if we look at texts by Marxists to see descriptions of institutions that will propel these proposed values, we find either vague rhetoric that lacks institutional substance, or, when there is real institutional description, we find advocacy of institutions that are properly labeled market coordinatorist and or centrally planned coordinatorist. And when we look at Marxist practice, we find these same coordinatorist structures universally implemented, and likewise within Marxist movements, even those out of power.</P>
<P>But could a Marxist transcend this problem too, and yet continue to see him or herself as a Marxist? </P>
<P>I don't know &#151; but, if one does, I think signs that it has occurred would be obvious. For example, such new Marxists would disavow what has been called socialism in countries around the world, not by calling it capitalism or calling it deformed socialism, but by recognizing it as a third mode of production that enshrines a different class above workers. More, such new Marxists would offer a new economic vision contrary to coordinatorism, and this new vision would very explicitly dispense with markets, central planning, and divisions of labor since these provide more empowering work to some people and less empowering work to others, as well as dispense with modes of remuneration that reward property, power, or output. </P>
<P>Additionally, to transcend rhetoric and get beyond mere rejection to providing aims that can orient strategy, such new Marxists would not arrogantly present a full blueprint for the future, of course--but they would propose major defining institutions to seek in place of all rejected options. (The ones I have offered are councils, remuneration for effort, balanced job complexes, self management decision norms, and participatory planning.) And finally, they would also advocate internal movement organization, methods, and programs that would embody, propel, and actually arrive at these positive aims, rather than approaches that would obstruct their attainment.</P>
<P>Not just vision, then, but also strategy is at stake. It is one thing--and correct--to say that we can only reach a better future by acting from where we are in the present. Our efforts must arise from the grounds we occupy. That's a truism, of course, not just a Marxist advisory. For getting from capitalism to a better economy as well as for getting from New York to Bangkok, say, you have to start from where you initially are. You can't make a trip unless you leave from your initial position taking into account, of course, your options as they are defined in the present. To do otherwise is dissociated from realty or, in the political case, "utopian." But, having said this, it is also true that you won't get from New York to Bangkok by bicycle, nor in a plane with insufficient fuel, nor via a hot air balloon, nor by going to the bus station, nor by going in the wrong direction by plane, and so on. Strategy has to be rooted in the starting context, for sure, but it also has to aim for the sought destination. If not, strategy is very likely to lead somewhere other than where one hopes to wind up. In context of our debate, my related point has been that strategies for social change need to self-consciously seek to overcome coordinator class rule. If they instead embody organizational choices and methods that lean on and elevate coordinator class consciousness and attitudes to central authority&#133;such as employing centralist forms of party, advocating markets, central planning, corporate divisions of labor, and so on...they will not only not eliminate coordinator class rule, they will entrench it--and Marxism's flaws lead to this result even regardless of the desire of many Marxists to end up someplace much nicer than coordinatorism. For Marxists to talk about workers liberating themselves is wonderful. However, Marxists proposing that workers should do this by methods which will subordinate workers to a domineering (coordinator) class in the seeking of a new economy and that will make that other (coordinator) class the ruling class of the new economy once it is attained, undoes the virtues of their rhetoric, however heartfelt it may be</P>
<P>But what about the relation of Marxists who seek to correct the error of ignoring coordinatorism to the heritage that they previously celebrated? </P>
<P>Well, I doubt such new Marxists would call themselves Leninist or Trotskyist, but even if they did, they would certainly disavow huge swaths of associated thoughts and actions. Thus, instead of always quoting Lenin and Trotsky positively, for example, they would forthrightly reject Lenin saying: </P>
<DIR><P>"It is absolutely essential that all authority in the factories should be concentrated in the hands of management." </P>
</DIR><P>And saying: </P>
<DIR><P>"Any direct intervention by the trade unions in the management of enterprises must be regarded as positively harmful and impermissible." </P>
</DIR><P>And saying: </P>
<DIR><P>"Large scale machine industry which is the central productive source and foundation of socialism calls for absolute and strict unity of will... How can strict unity of will be ensured? By thousands subordinating their will to the will of one." </P>
</DIR><P>And saying: </P>
<DIR><P>"A producer's congress! What precisely does that mean? It is difficult to find words to describe this folly. I keep asking myself can they be joking? Can one really take these people seriously? While production is always necessary, democracy is not. Democracy of production engenders a series of radically false ideas." </P>
</DIR><P>And so on.</P>
<P>And they would reject Trotsky saying (about left communists):</P>
<DIR><P>"They turn democratic principles into a fetish. They put the right of the workers to elect their own representatives above the Party, thus challenging the Party's right to affirm its own dictatorship, even when this dictatorship comes into conflict with the evanescent mood of the worker's democracy. We must bear in mind the historical mission of our Party. The Party is forced to maintain its dictatorship, without stopping for these vacillations, nor even the momentary falterings of the working class. This realization is the mortar which cements our unity. The dictatorship of the proletariat does not always have to conform to formal principles of democracy." </P>
</DIR><P>And saying:</P>
<DIR><P>"It is a general rule that man will try to get out of work. Man is a lazy animal." </P>
</DIR><P>And saying (with pride): </P>
<DIR><P>"I consider that if the Civil War had not plundered our economic organs of all that was strongest, most independent, most endowed with initiative, we should undoubtedly have entered the path of one - man management much sooner and much less painfully." </P>
</DIR><P>And so on.</P>
<P>More positively, if the topic came up, such new Marxists would indicate how they would have done things differently than the Bolsheviks and than every Marxist party since the Bolsheviks. For example, regarding the Bolsheviks, they might point out that the shop committee movement in Russia was moving in 1917-18 towards a National Congress to take over grassroots planning&nbsp;and coordination of the economy and note that unlike the Bolsheviks they would have seen such local agents as the best locus of planning rather than preferring the state. They might also note that Power to the Shop Committees was what the anarcho-syndicalists argued at the First All-Russian Trade Union Congress in January 1918, and indicate that they would have supported the anarchists in that, instead of opposing them, as the Bolsheviks did.&nbsp;</P>
<P>These new Marxists, noting that the Bolsheviks voted at that Trade Union Congress along with the Mensheviks and SRs to dissolve the shop committees into the trade unions and advocated "union management" of the economy, might say they would have at least stuck with that compromise instead of devolving by 1921 into advocating replacing union management with the still worse top-down "one-man management."&nbsp;</P>
<P>Instead of a hierarchical army these new Marxists might indicate that they would have favored using a militia based on the mass organizations, like the Revolutionary Army of the Ukraine. They might note that arguing, as supporters of Bolshevism do, that this would have been ineffective against the whites would be unreasonable given that it was the revolutionary army of the Ukraine that saved the Bolsheviks during the winter of 1919, when they attacked the white army besieging Moscow from the rear, destroying it.</P>
<P>And instead of invading the Ukraine with the Red Army to crush the People's Congress of the eastern Ukraine in 1921, as the Bolsheviks did, these new Marxists might indicate that they would have supported the Congress and helped it expand into the western Ukraine.</P>
<P>These new Marxists would note that instead of invading Kronstadt in 1921&nbsp;and crushing the Soviet there, they would have agreed to the Kronstadter's demands for new elections to the Soviets, even if this meant that the Bolsheviks would have to go into opposition. </P>
<P>More, these new Marxists would note more generally that hierarchical structures in political institutions risk ushering in coordinator rule (as well as creating an environment uncongenial, in the modern era, to widespread worker involvement) and also political authoritarianism, and if they wanted to argue that in some difficult contexts such structures had to be employed, they would urge seeing them as a temporarily imposed expedient, and would make that clear, and in all other respects would try to pave the way for non-hierarchical relations, now and in the future. </P>
<P>And, finally, attuned to the broader comprehension of class definition and working class liberation, these new Marxists would not say that everyone who sees vision and strategy differently than them but calls themselves a Marxist, is a Stalinist. They would instead recognize that Marxism is a very incomplete framework and leads most people who adopt it to unworthy positions, even against their personal inclinations. </P>
<P>And I have to say, about this last point, nearing the end of this concluding statement, throughout this debate I have been portrayed at various points, often implicitly, sometimes explicitly, as dismissing and insulting Marxists. I reject that. To see why, suppose we were to envision a humongous stadium filled with all the people in all past and current history who called (or who now call) themselves Marxists. (This is not your average size ball park, of course, as it contains millions of people.) </P>
<P>I have argued that this huge set of people overwhelmingly, though not universally, have shared a viewpoint that has negative attributes and implications, even against the people's finest aspirations and values. I don't see how saying this about a conceptual framework's likely implications for the people who adopt it is particularly degrading to those people or dismissive of them. </P>
<P>Yes, I say that the problems with Marxism's concepts lead in their large-scale implications toward coordinatorism, not to mention toward political authoritarianism, and often even toward defending these vile results despite having other stated aspirations. But this doesn't say that vile motives or personality or values produced the bad outcomes. It says, instead, that flawed concepts, visions, and strategies were the culprit, and that in the process of vast Marxist struggles, those participants willing to put up with or to celebrate coordinatorist and authoritarian methods and outcomes will eventually rise to top positions &#151; as has in fact happened in history. </P>
<P>In contrast, to these claims about the concepts widely held by the large set of self-proclaimed Marxists that we are envisioning in our hypothetical immense stadium, ironically, those Marxists who come closest to agreeing with me on many of these issues tend to dismiss all but a tiny fraction of the stadium's seat holders--the fraction that they don't dismiss is usually their organization and some leaders from a hundred years ago, and Marx, etc., I guess, in the analogy, roughly those occupying a few selected box seats on the third base line, and maybe some little group out in the bleachers somewhere, too --as being Stalinist. </P>
<P>So am I missing something here? I characterize nearly everyone in the stadium as being victimized by the implications of a set of concepts generally despite their best intentions and hopes. People in the stadium tend to characterize almost everyone else in it as Stalinist or otherwise defective. Who is being dismissive? Who is denigrating people?&nbsp; </P>
<P>The irony in this discussion, in other words, is that while I am taking a position highly critical of adopting Marxism as a guiding conceptual framework, particularly to the exclusion of other concepts, nonetheless I suspect that I am far less dismissive and derogatory toward the full set of people who have called themselves Marxists throughout the world than those in that set are about each other, tending to pejoratively damn as Stalinist (or Trotskyist, or whatever) Cuba and its supporters, huge swaths of the past participants in movements in China, Russia, Eastern Europe, and so on, and parties all over the world who support, in addition to other views or acts, some views that the (Marxist) critic of them rejects.</P>
<P>Put differently, why is my critiquing a set of concepts and institutions as a whole insulting, but for one Marxist to very pejoratively call every Marxist outside his or her circle of friends Stalinist or Trotskyist or (running dog lackey) or whatever other dismissive label he or she deems appropriate, acceptable? And which approach is sectarian? </P>
<P>At any rate, all that aside, suppose a Marxist organization does come along and follows more or less the positive trajectory in their thinking and commitments regarding class definitions and allegiances, economic aims, strategic commitments, and views of the heritage, as described above. Would that group continue to name itself after Trotsky, Lenin, or even just Marx? </P>
<P>I doubt that it would. I think it would find, like I found when I tried to call myself an unorthodox Marxist after having traveled essentially the trajectory noted but wanting to keep the linguistic link to the council communists like Rocker and Pannekoek, to Gramsci, to Rosa Luxembourg, and to Che&#133;that despite my desires, the accumulated weight of past and current beliefs of those who were the loudest and most visible claimants to the mantel "Marxist" far outweighed my rejection of their views, which rejection I had to endlessly repeat just to avoid being utterly misunderstood, and that calling them "Stalinists" or even just "orthodox" to dismiss them as irrelevant to my choice of the label (unorthodox) Marxist was mere hand waving and special pleading, and not understood by anyone outside a small circle of friends. Thus I came to my choice to leave behind the label "Marxist," and (for the most part) to avoid all the endless bickering and outright fighting over it, and to instead continue to expand my deviating views in new directions. </P>
<P>I do hope this debate has been helpful to some people. I have learned just how thin is the membrane that separates myself and some Marxists -- yet, at the same time, just how sturdy it is. Whoever is right, and whoever is wrong, and however much, hopefully in short order new paths through that membrane will be trod, correcting the views on both sides.</P>

</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
