<html>
<head>

<title>
Albert: Albert Rejoins
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="5"><b>Albert Rejoins</b></font><br>

<P><font face="Times New Roman, Times, serif" size="2"><b>By Michael Albert</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | July 21, 2002</font></P>

<P><font face="Times New Roman, Times, serif" size="3">Alan,</P>
<P>I hope you won't mind that I am going to write this like a letter, and directly to you, conversationally. I think will be a bit less formal and more congenial than referring to Maass, throughout, as if we aren't conversing back and forth.</P>
<P>Also, before getting into your points, you and I disagree so much about the texts you quote and about the historical events you have referenced that to clash on that just won't yield progress, I fear, though it may give us both carpel tunnel syndrome. You asked me for quotes contrary to those that you offered, so to respect your request at the end of this piece I include a few such quotes in an essay format addressing the Russian revolution, etc. But I include the pieces I link to there only with great hesitation because I don't want to debate my quotes, or your quotes, or the history of the Russian revolution. Years back, I spent a lot of time on such debates -- including writing whole books on it -- so it isn't that I can't come back with ample words on the topics. It is that I think doing so won't move us forward. So I'd rather just address the ideas we hold and try to see where we can agree, or can agree to disagree. </P>

<P><B>The Question of Focus</B></P>
<P>Also, still scene setting, I think we can let "Marxism's alleged insufficient attention to gender, race, polity and the environment" slide in this debate because my guess is most readers have their own already very well formed views, on the one hand -- and because between us it is not the largest divide. I have written a lot on the matter, and on problems with the labor theory of value, Marxist dialectics, and so on, in other volumes. It is just too much to try to address all of it here, alongside the economic class issues, I suspect. But before dropping the matter entirely I want to agree with what you said, and thus hopefully clarify our difference. You are right that the issue isn't that I think we should give lots of attention to race, gender, authority, ecology, and so on and that in contrast Marxists think we should give them no attention or even just less attention. The issue is that we think attention should be given differently. </P>
<P>Marxists -- most Marxists -- feel that race, gender, and actually everything about society, is important and can be very very important -- but it attains its importance for people who are trying to create a better world precisely in context of class struggle. The lenses Marxists use to understand society are not confined to but are certainly rooted in attention to class relations. Marxists try to see how economic relations are affecting classes and thus affecting potential change. Marxists then try to see how other phenomena, race, gender, etc. are impacting the class struggle and try to address the dynamics in ways that will propel working class gains, which, in turn, they believe, will auger gains of all kinds. If this isn't your Marxism, let me know, please. But I do think it is representative.</P>
<P>I see things quite differently, however. It seems to me that it is correct that economics is a profoundly important aspect of society and that the (class) divisions and struggles economics produces among people are hugely instrumental in affecting the quality of our lives. But I think this same thing can be said for cultural relations, for sexual and gender relations, and for political relations. So I think that rather than understanding the latter three and the divisions and struggles they engender largely or even primarily as they impact class, we need to instead understand each of them (and economics as well) insofar as they all impact one another. </P>
<P>Put differently, Marxism says that the mode of production of a society emanates, if you will, a force field that affects all of society, often very dramatically. I agree. To me, in fact, it seems obvious. But then I also agree with the feminist who says that the organization and relations of socialization and nurturance --currently patriarchal -- emanate a force field that affects all of society, often very dramatically. And I agree with the multi-culturalist who says the same thing about cultural and community relations and with the anarchist who says it about political and power relations. If all these viewpoints are right about identifying a locus of influence (and each is simultaneously wrong whenever it denies the comparable importance of the other loci of influence) so that there are four origins of profound influence in society rather than only one -- then a base superstructure approach, in any guise at all, is horribly wrong. </P>
<P>I, have to add that I don't think this is a devastating critique of Marxism. Many Marxists, I agree with you, Alan, are inclined to accept this view already. All could adopt the more complex formulation, keeping the core of Marxism's insights about modes of production and class and so on but realizing that influences from race, gender, sexuality, and authority relations can mold the economy just as the reverse can occur, and that groups defined by those other core features can be central actors in historical struggle and change, just as classes can. That's why I am not placing this critique, however important I think it is, at the top of this debate. If this were Marxism's only problem it wouldn't cause me to reject Marxism, but to try to root out bad old ideas and incorporate good new ones.</P>
<P>So when you say "We do have differences about the relationship and the dynamics of `economics` and `gender, race, polity and the environment,' etc." and that "the debate is about <I>how </I>we give attention, not <I>if </I>we do," I am happy to agree. Historically, in my view, giving attention to matters of race, gender, authority, and ecology primarily via examining their impact on and implications for class struggle often leads to dismissing their importance in their own right and compromising attention to their own dynamics, but other times, you are also right, it leads to emphasizing them. Just as, for the radical feminist, giving attention to other facets of society in terms of their impact on gender relations sometimes leads to too little or a biased and narrow attention to class, or race, and so on, and to compromising them in practice. It is really quite reciprocal, I think. And both are wrong in the same way on this score.</P>
<P>The mistake of "monism" -- even a very flexible and enlightened monism -- is to tend, under pressure, to elevate one realm to predominance and lose track of the priority of others, and to compromise the others, as well. The point is, to prioritize economics and class as the primary focus of attention raised above all others in importance not only misperceives a more complex reality, it relegates other focuses, equally important, to too subordinate a position. The solution isn't to reduce attention to economics, but to elevate attention to other spheres and to their mutual defining influences without presupposing any to be prior or dominant.</P>

<P><B>Marxism and Class</B></P>
<P>You say, Albert believes that the most damning charge against Marxism is that it "gets the economy wrong." He believes that "Marxist class theory literally denies the existence of what [he calls] the coordinator (professional-managerial or technocratic) class"; that "this coordinator class can actually become the ruling class of a new economy"; and even that "Marxism's economic goals amount to advocating a coordinator mode of production." </P>
<P>And you are correct. In a nutshell, that is my view. And interestingly, in a similarly nutshell kind of summary, it seems to me that in your piece you were at great pains to call what there is other than capitalists and workers the middle class, and to describe it as some kind of conflicting group that is part worker, part capitalist, but is certainly not a class unto itself defined by its own different conditions. And you also seemed to be quite keen to deny that it can become a ruling class, and to deny that Marxist economic vision is, whenever it is offered in a serious institutional model, a coordinator vision. In other words, you fulfilled precisely the claims above, it seems to me. </P>
<P>You ask, "How can Marxism advocate a program of class rule for a class that it doesn't acknowledge the existence of?" I am surprised a Marxist would ask that question. That's precisely what elite classes do. Capitalists don't celebrate "class rule by capitalists" but serving the populace, and for the most part their ideologies obscure their own existence. Marx himself taught us that elites and particularly ruling classes do precisely this. A revolution aiming to enthrone a minority class in power won't celebrate the distinction between that class and those below, of course. It will instead focus on "all good peoples" and on winning them more justice and equity. Marx taught, rightly, that we shouldn't blindly accept that rhetoric -- we should look to see what the program is, what the goal is, what the techniques are, and then we should judge based on all that, not based on self description. In these respects it turns out, ironically, that I may be a bit more "Marxist" than you. I think class really matters, that class interests matter, that institutions that produce class hierarchy matter, and that these together can totally swamp nice rhetoric or even very very sincere pro-working class desires and intentions. </P>
<P>I should think you would agree that if the coordinators could conceivably economically rule, and if they were to employ an ideology that sought their rule, then surely that ideology would trumpet the rights of all people and very much obscure anything that would shed light on how the sought gains would subordinate most of those fighting for change to the rule of the coordinators.</P>
<P>When bourgeois elements railed against thrones they didn't do it in the name of their own future great wealth and power, but in the name of freedom, justice, and so on, for everyone. Their ideology was sharp in railing at the enemy, but very vague as to differences between themselves and "their troops." This is always true when an elite contends for power, in any realm. In fact, I have no doubt many believe their own rhetoric, for example that many at the top of U.S. society today believe their's. And understanding this phenomenon is one of abiding accomplishments of Marxism, I think -- that is, to see that it doesn't change the reality a bit. Their class position, the defining relations of their lives, and the attitudes, values, and modes of operation these relations gave elites, lead not to justice for all, but to enrichment for the few. It is so for capitalists and it is the same (in different ways) for a coordinator class dominated movement seeking a new and better society. It may be that the people in leadership, even, in considerable degree or even overwhelmingly are quite sincere...they rally workers below by railing against existing injustices perpetrated by an elite that is to be replaced...they feel pain for the suffering and solidarity in struggle, the "masses" want dignity and justice and expect it, but it all leads to a new class in place of the old one, still above workers because that's what's immanent in the ideology and its institutional aims.</P>
<P>You ask "And how would the professionals, managers and technocrats in U.S. society react to the idea that Marxism is the best expression of their economic aims." Well, insofar as they put forth virtually the same rationales for their decision making hierarchies as Marxists put forth for party structures, I think they would identify. Asked whether they would prefer a society in which those boring and ignorant owners were no longer over their heads, but instead they could rationally rule with their wise and insightful wisdom, of couse on behalf of everyone's well being, I think they would again identify. </P>
<P>I might rejoin, however, how would workers in the U.S. react to the idea that Marxism is the best expression of their economic aims? And I think this question has much more weight than yours because it isn't just the image of Stalinism that workers reject, or other gross distortions. That is, workers reject, I think, their worst nightmare, that the managers and doctors and lawyers they hate in their daily lives and whose arrogance they continually suffer could become unrestrained rulers over them, and they see this in Marxism, not just dictatorship, and I think they are right. Coordinators, to the extent that they reject Marxism, in contrast see just dictatorship, I suspect, and that's not so wise, since I agree with you that it is eliminable from the picture. </P>
<P>You make a lot of the fact that I said Marxists ignore the coordinator class, but, in fact, you reply, Marxists have paid great attention to those existing between labor and capital. I'll stick to my position. I say that class exists due to ownership, yes, but also due to social relations of the division of labor. Some have positions that empower, others have positions that deaden. This differential can lead to class division. To pay attention to those who exist between labor and capital by saying they have some capitalistic attributes and some workeristic attributes, whatever&nbsp; combination and variation may be discussed, is precisely still seeing everything in terms of these two categories and not introducing a third. </P>
<P>And why should we introduce a third class label? Because the situation of those who monopolize empowering work and the levers of daily economic decision making power isn't just confused. This group between labor and capital isn't just the bottom of capitalists above merging into the top of workers below. It has its own position, its own definition, and as a result its own views and interests. Calling it the petty bourgeoisie is again just working in terms of the old ownership viewpoint...and paying attention to the wrong sector of people...they own a little but not a lot of capital. The point is to see that something other than ownership differences can be the source of class division and even class rule.</P>
<P>When you say that Marx insightfully noted that capitalists had to elevate a sector to a considerable degree of power, I say, yes, Marx himself understood a whole lot of things, and if this is one, that's good. But the richer understanding isn't embedded in the system that is called Marxism. If people who read a useful take on such matters from Marx or whoever else come to realize that it is possible for the situation in workplaces to demarcate a new class due to the distribution of empowering and disempowering tasks such that some people monopolize the former and the rest endure the latter, that'll be excellent. But this type insight is not a part of Marxism itself. </P>
<P>You say I exaggerate when I say Marxists literally denied the existence of " a social layer between labor and capital" -- but did I really say that? I think I said they deny the existence of a third class between labor and capital (and, yes, I should have qualified by noting I wasn't talking about the petty bourgeoisie but in context I think that was quite evident). And Marxists do deny the existence of such a class, I believe.</P>
<P>You say, "Marxists after Marx have spent plenty of time and ink adding to the understanding of this middle class, and I have a small stack of books next to me as I write this to prove it." I don't doubt it. What is revealing to me is that the mountainous attention never transcends the bounds of allegiance to only property as originator of class difference. Thus, it doesn't arrive at the idea of a coordinator class, much less recognize the existence of a coordinator mode of production.</P>
<P>You say "The challenge has always been to figure out who fits into the middle class and who doesn't." Actually, no, I would say the challenge is to discern what makes this group, though fuzzy at the edges like all social groups, different? What impacts its view of itself and others? What is its situation as compared to that of capital above and labor below? My answer is that its singular situation doesn't have to do with property ownership, but with its qualitative position in the production process. </P>
<P>You say, "I'm going to give Albert the benefit of the doubt. He doesn't define his coordinator class except with four words in parenthesis--professional-managerial or technocratic.'" Actually, that wasn't a definition but just other names that others have used, synonyms, more or less. The definition I gave was in the following paragraphs. I think it was clear enough. I said the coordinator class was defined by having a relative monopoly on empowering work. It controls its own situation to a great extent. It controls or defines the situation of workers below to a considerable extent. It works to enlarge and defends its comforts and power against capital above and workers below, even as it sometimes also just does the bidding of those above, of course. Who am I talking about? Well heeled doctors, lawyers, engineers, managers, and professionals of diverse other kinds. People who see capitalists, by and large, as an annoying obstacle to the fullest elaboration of their personal genius. And people who see workers, by and large, as more or less dumb folk to be taken care of and, of course, kept below. I think it is about 20% of our population, but I am certainly not sure about that.</P>
<P>Alan, you make a lot of the fact that one can only fully understand a "middle class" by knowing its relations to those above and those below. True. One can also only fully understand the working class by understanding its relations to other classes, above, and likewise for understanding the capitalist class. But this doesn't tell us that any of these is merely a part of the others. You make a lot of the fact that this middle group is stronger and richer at one end, and weaker and poorer at the other end. True. So what? It is true also of capitalists and of workers. All classes have a broad reach and much variation, naturally. What causes us to say that high income skilled workers and low income horrendously exploited workers are all part of one working class is that they have something that we think is quite important in common, despite many other differences. What causes us to say that the richest of the rich and the far less wealthy but still coupon clipping owners are all capitalists, is, again, that they have something that we think is important in common, despite many other differences. It is the same for what I call the coordinator class. What is in common from the top to the bottom of this class too is what they share, in this case their relative monopoly on empowering work and the fact that their being richer or poorer and more or less powerful owes overwhelmingly to the extent of their holdings on that axis. What the AMA does for doctors, keeping others away from their knowledge, is different than what the Teamsters do (or should do more of) for workers, enhancing their bargaining power through threats to withhold labor. The coordinator class, in the middle, views itself and those above and below differently than the other classes view themselves and those above and below. It has different broad tastes, dispositions, and interests, as well as income and power -- all the things that characterize class. This is true in capitalism, and of course if capitalists are removed but the social relations of economic life still demarcate coordinator order-givers over worker order takers, it is true in coordinator-ruled post-capitalism too.</P>
<P>Alan, you quote, "As Marx put it, referring to the nature of the classic petty bourgeoisie, `The independent peasant or handicraftsman is cut up into two persons. As owner of the means of production, he is capitalist; as laborer, he is his own wage-laborer.'" But to me this is a problem, at least if it is extended as you are doing to all those between labor and capital. In that case, it is not an insightful step toward a solution. It is seeing things in terms of property ownership and two main classes, only. If someone seems different -- a lawyer, engineer, psychiatrist -- it must be that its because he or she is a mixture. There is nothing else under the sun than workers and owners. The problem is, there is, in fact, something else under the sun. </P>
<P>You say, "This contradictory nature distinguishes the middle class from the `two great hostile camps'" -- that is, that it shares some conditions with each rather than being in one or the other. But in contrast I see this group as having its own defining relations due to its relative monopoly of empowering work -- and the relative status, power, income, and world view owing to and contributing to that condition. </P>
<P>You say "Albert's `coordinators' don't, under anything but exceptional circumstances, act as an <I>independent </I>class, either economically or politically." I think this is false. I think they often act in their own interests and even organize together to do so, the AMA being but one example. Workers also are often fragmented, often not fighting for change, and so on. This doesn't cause us to say that they aren't a class, nor should it with this other group. It is the potential, owing to their position, sometimes actualized in smaller ways and sometimes in much larger ways, that is the issue.</P>
<P>I spent some time once chatting with a potential donor -- it didn't work out -- who owned a movie studio, among other things. I asked him why movies took so damn long to create, from time of conception to their actual appearance. He told me a very interesting story. He said that in operating his firm he had no choice but to employ a bunch of people -- vice presidents, etc. -- because he simply could not oversee everything. Though he hired them to enhance his profit, these folks, he said, felt very little allegiance to him or his firm. They wanted to advance their careers, whether in his firm or elsewhere. They sought, he said, to gain loyal relations to key people regarding the unfolding movie -- stars, the director, whatever. Then they would stretch out the process, endlessly exploiting the power card they held -- their relative monopoly on many daily decision making levers and on information and relations critical to the project -- to advance their own careers. He bemoaned it, urging that he often had much more trouble with this group of folks, vis-a-vis earning profit, than with his workers--though at the same time he simply couldn't do without them. Obviously this is just one story, but it is quite instructive, I think. There is more to capitalism than owners seeking profits and workers trying to get the best wage they can for the least time at work, though surely those phenomena are very important.</P>
<P>You say, "In other words, the middle class does `contend with capitalists and workers within capitalism,' as Albert puts it--but almost never both at the same time, or independently of one or the other sides." Actually, those high level coordinators in the movie industry were waging class war in both directions, up and down, I would argue. But you are right that if they really go all out against capital above, in that endeavor they would have no choice but to win allegiance from workers below. Which brings us back to the earlier point about their saying they are fighting for justice, dignity, equity, and so on...but really for their own advance.</P>
<P>You say that what you call the middle class and what I call the coordinator class can't become a ruling class because it is too disparate. You might as well say that about workers -- they have never risen from beneath elites, and they embody a wide range of differences. On the other hand, I claim that in various countries -- notably the Soviet Union, etc. -- the coordinator class has, in fact, become the ruling economic class.</P>
<P>You and I disagree about how this class--whatever name we give it--thinks of itself and sees others. I think to explore the issue one needs only consult oneself or any worker, on the one hand, and on the other hand any high level doctor or lawyer. I think the differences in outlook are really quite transparent and easily traced to the different class position.</P>
<P>You ask, "What is the basis for political and social unity between a supervisor on the assembly line, the assistant comptroller for the same company, a creative director at the advertising agency hired by that company, and a legal associate at the company's law firm?"</P>
<P>That they all get their status, power, income, and identity from monopolizing empowering skills and knowledge and levers of control and influence. That they all tell themselves that they have their advantages, not because they take it and withhold it from others, but because they are smarter than others. That they see capitalists as a painful impediment to the fullest manifestation of their capacities -- though also, of course, also frequently have to serve capital (like workers, by the way). That they see workers as inferior, subordinate, maybe worth saving but not worthy of serious influence. And that, if they rise to the insight, they can run the economy without capitalists above them and with workers still below them. </P>
<P>You ask, "Under what circumstances would they all unite against both workers below and capitalists above?" That would be suicidal, of course, as a stated program. Rather, what they would do if they wanted to usher in a new economy, is wage a class war against capital, rightly identifying its many horrors and in so doing appeal to all those who suffer its indignities and impoverishment, but, in the course of struggle, monopolizing control over institutions, retaining their own elite culture and values as defining, and imposing their rule in the process, and then dominating in the new society, just as has occurred. </P>
<P>You say, "In the real world, can anyone imagine `coordinators' uniting to overthrow capital and establish their own independent mode of production?" Yes,&nbsp; I can. Not in the trivial way that you may be rejecting -- standing behind banners saying capitalists suck and workers do too, of course. But in a social process that throws off the capitalists as the enemy to be overcome but employs the working class as allies -- really, as troops, then selling them out at the pass, so to speak. This, to my mind, is Bolshevism.</P>
<P>You say that your presentation rejects my key points, but I didn't see where you made a case that coordinators were not capable of becoming a ruling class in a market or centrally planned, state or public ownership economy. There are no capitalists. There is a sector -- about 20% of the population -- that monopolizes levers of control of the economy. They have way more income, more power, more status, than those below. They rule. If we reject these economies, and you say you do, then presumably we agree that these rulers aren't workers. I say they are the coordinator class. I say the problem is that the new structures don't actually liberate work, but continue to subordinate it. Who you think these dominants folks are, I don't know.</P>
<P>You say, "Does Albert really believe that the economic aims of accountants, lawyers and mid-level corporate executives were best expressed by Karl Marx?" In a way, yes, I do. That is to say, I think an economy that elaborates their interests as ruling interests is very much the logic and agenda of Marxist and particularly Leninist ideology. </P>
<P>You say, "His argument, as I understand it, is that the societies which have called themselves socialist and been ruled over by people who claim to be Marxist--countries like the former USSR, China, Cuba, North Korea, etc.--should be understood as `coordinatorist.'"</P>
<P>Yes, that's my view.</P>
<P>In this new economy, as you quote me, there is "public or state ownership of productive assets and corporate divisions of labor. It remunerates power and/or output. It utilizes central planning and/or markets for allocation. It is typically called by its advocates market socialism or centrally planned socialism...It has been adopted by every Marxist party that has ever redefined a society's economic relations."</P>
<P>And now you say, "This is by and large an accurate description of the countries listed above, past and present. But the question is whether they were socialist--and whether the `Marxist parties' that redefined their economic relations had anything to do with Marxism." </P>
<P>So we agree on what was there, we just don't agree on what to call it. Well, if you can show me a serious proposal for an economic system that is supported by any Marxist party that has ever taken power, or has held it, or has even fought significantly for it, that disavows all those features, there would be something to discuss. But I don't think you can do that. Yes, you can show me Marxists calling for power to the workers and whatnot,&nbsp; as you have in your piece, just like I can show you capitalists saying serve the people. But I want to see proposals for institutions other than those mentioned, by Marxist parties. </P>
<P>You say, "In the USSR and the other bastions of `Marxism,' the experience of workers wasn't one of control and freedom, but of exploitation, oppression and alienation from all levers of social and political control," and, as a result, you reject those economies. Good. We agree on that. But I think that calling every victory by a party full of people who call themselves Marxists and who can recite its concepts and theories inside out, not Marxist, isn't really particularly helpful. </P>
<P>You go on, "In fact, what stands out most about these so-called `socialist' societies is how much they resemble capitalism." And here is where our growing agreement above falls apart again. It is like seeing the folks between labor and capital as part worker part owner rather than as a class unto themselves. Analogously, now you are saying the old Soviet economy can only be either capitalism or socialism, those being the only possible options. If it isn't socialism, lo and behold, however warped or amended, it must be capitalism, however disguised. This is what concepts do. They organize our thoughts and provide categories we use. Sometimes they push us past the obvious to important revelations. Sometimes, as in this case, they hiding the obvious in mistaken formulations. </P>
<P>To say that the old Soviet economy was capitalist despite that there was no private ownership of the means of production, is, to me, far less useful than realizing that it must be, instead, if not capitalism, and if not an economy in which workers self manage -- then something else. The absence of owners and the elevation of central planners, local managers, and others throughout society who share the basis of their power including lawyers, engineers, etc. -- to ruling status, is what characterized these economies as different.</P>
<P>You say "Take Albert's description of the 1coordinatorist' economy. A corporate division of labor, remuneration of power and/or output and the use of markets for allocation are mainstays of Western-style capitalism. Central planning is common enough on a piecemeal basis, especially in circumstances like the war economies overseen by the U.S. government and its rivals in other countries during the Second World War, and to a lesser extent in the military-industrial complex to this day." This is true. And so the old Soviet economy had some features in common with capitalism. But all of a sudden the absence of that which for Marxists is usually the first thing mentioned about capitalism, that capitalists own the means of production, isn't even an issue. That capitalist didn't exist in the Soviet system and that there was no compulsion to seek profit, for that matter, doesn't seem to rule out it was an economy elevating capitalists and prioritizing profit. To me this is mental gymnastics. I wonder why the obvious step, which is to give this economy a new name and not try to shoehorn it into old categories, is rejected.</P>
<P>If we call the Soviet Union state capitalist, as you suggest, one conclusion is that we don't have to worry about the possibility that maintaining a division of labor that has some people ruling over others -- say in a Leninist Party -- is part and parcel of ushering in a new economy that isn't in the interests of workers. We can just do it because there is no such thing as an economy not in the interests of workers other than capitalism, and we are certainly anti-capitalist. Perhaps that is part of the reason. In truth, of course, one can be anti-capitalist in ways that don't elevate workers. </P>
<P>At this point you provide your view of some of the history of various revolutions. I just don't see the point in repeating here a contrary view that I have offered in many places and at far greater length, though some of my views will appear in the appended essay included to provide the quotes you requested. </P>
<P>You note that I said that coordinatorism "is celebrated as the goal of struggle in every Marxist text that offers a serious economic vision." And you say "That is utterly false--for Marx and for every genuine Marxist who followed him. The `goal of struggle' in every text that takes up this question is a society characterized by mass working-class participation, democracy and freedom."</P>
<P>Well, I think what I claimed is true, because of the words "serious economic vision" which perhaps weren't entirely clear in their meaning. I didn't say Marxists never trumpet working class participation and control. Nor that they never seriously desire it, as individuals. I said they don't offer a vision that yields that result, or that is even consistent with it. I said that instead, every serious Marxist formulation of what an economy ought to be in the shape of institutional prescriptions, including of course, what they have done -- is coordinatorist. </P>
<P>Now I have to admit, I did exaggerate, in one sense. There are some Marxists, they have been called council communists, who tried to describe a truly socialist -- in the positive sense -- vision. I feel they just didn't get very far, though others might feel that is too dismissive. But they are the exception that proves the rule, in my view. They ought to be extolled as the best Marxism has had to offer. Instead, they are literally ignored, to my knowledge, by large Marxist parties the world round. </P>
<P>Quoting the best of Marx at me is fine. I have learned from his work, too, of course. You will find positive quotes from him in the appended material, as a matter of fact. But the best of Marx isn't Marxism, which is no doubt why even while alive Marx said he doubted he would call himself a Marxist. Marxism isn't everything every Marxist has ever written -- there is a great amount I admire and learn from written by Marxists, of course. Marxism -- in the sense of do we want to adhere to it or to transcend it -- is a batch of core concepts and approaches, and those are what I am questioning. </P>
<P>As to a serious economic vision -- put every Marxist text written about economics in a pile. I am willing to bet that to the extent that they provide a serious vision -- an institutional explanation of allocation, incentives, distribution of income, production decision making, and so on -- they will advocate, overwhelmingly, and perhaps even universally, the institutions I mentioned above and which you said you reject as unworthy. I don't understand why you wouldn't find that a point of great concern. </P>
<P>Even if we took all the positive quotes about workers freedom and control at face value -- and sometimes I think they are quite honest, in context, though coming from the likes of Lenin and Trotsky I think it is duplicitous garbage, to be honest -- they would have no bearing whatever on my claim about serious economic visions. Such rhetoric does not constitute serious vision. It is rhetorical flourishes not unlike when Bush or Clinton waxes eloquent about democracy, in my view, unless there is real and worthy institutional substance behind the rhetoric -- and there isn't. Behind the rhetoric, instead, there is public ownership, markets, central planning, remuneration for output or power, and corporate divisions of labor. </P>
<P>You say, "These passages seem to me to reflect Marxism's commitment to a society run by the mass of working people, rather than an elite--a thread that I think runs continuously through the genuine Marxist tradition." I am quite happy to accept this is true of you and I am very much aware that it is true of countless cadre over the years. I also, believe, however, that the sentiment doesn't stand a chance in hell against coordinatorist biases and institutions whose logic is contrary to the desire -- an insight, by the way, that is very much in tune with the best of Marx's teachings.</P>
<P>You say "Albert's only apparent recognition that Marxists--from Marx's time to this day--have said quite the opposite are veiled references to our "rhetorical entreaties" that apparently hide the real agenda. Now this is pretty insulting--not only to Marxists like me, who would appear to be `coordinators' in training, but to all the people who have looked to Marxism over the years." I can see how it can feel insulting, though I certainly don't mean it to be. The thing is, it isn't insulting to say that people are making a mistake. Which is what most are doing. And I think it isn't even insulting to say that when people are of a certain class and approach or they become enmeshed in structures that elevate them in the same manner as being in that class, that that dynamic and its logic will overtake their intentions especially if it is propelled as well by new institutions around them. I think this is a fact of life -- which Marx thought too, by the way. We shouldn't see ourselves and our wills and values as more powerful than the institutional contexts that we construct and which, in turn, thereafter, impact us. </P>
<P>Put another way, the problem isn't bad people. Yes, Stalin was no nice guy. But the problem was the institutions which select and elevate a thug like Stalin. The problem with Marxism Leninism isn't that everybody in those parties wants to trample workers on the road to ruling them. The problem is that those parties, and their core concepts, however well meaning many or even for most adherents may be, lead to that outcome. That's what I said before, and I say it here again. None of us, no one, is immune to the pressures of our circumstances, and on average concepts and organizational choices and strategies that have a built-in logic elevating coordinators are overwhelmingly likely to do just that: elevate coordinators. </P>
<P>Become a cop, even with the best motives the odds are you aren't going to serve the people, all the people, and some who take this route will become grotesque. Become a lawyer, even with the best motives the odds are that you aren't going to be a paragon of justice but an elitist coordinatorist person. Become a Leninist, with the very best of motives -- the very very best -- and the odds are you aren't going to make a revolution in our modern world, I think (for want of diverse focus and especially, ironically, true working class appeal), but if you do, the odds are your achievement will, even against your hopes, elevate coordinators to economic rule, not workers. If that's insulting, I can't help it. I don't think it should be. It isn't a comment about people. It is a comment about concepts, methods, institutional allegiances, etc. </P>
<P>You say "it is no surprise when Albert associates Marxism and Stalinism without qualification." Actually, I never did that. But I do think it is highly likely in a modern capitalist society for a Marxist to become Leninist, indeed, almost built into the conception's concepts and methods. </P>
<P>You say, "The point comes down to this. If Albert is right that the so-called `socialist' societies of the ex-USSR, etc. are a true reflection of the economic aims of Marxism, then I would agree with him. Marxism would need to be not `transcended,' but repudiated."</P>
<P>Well I think that may be enough. That is to say...if we always talk in terms of just plain statements of ideas, and if you reject all that you say, then I should like many ideas you enunciate and the same in reverse. We ought to try it, I think.</P>
<P>You say "If Albert thinks a debate with me and the ISO about the relevance of Marxism is useful, then he should address himself to <I>our </I>Marxism--not the fake Marxism of bureaucrats and dictators that we have always rejected and opposed." I think I am speaking to the core views of Marxism, period. I think our disagreements indicate that. You wouldn't let an advocate of capitalism say don't talk to me about depressions, about starvation, about wars and colonization -- that's just bad capitalism, I am for good capitalism. I won't agree to talk about Marxism and simply ignore what virtually all Marxists say they are for when they present institutional vision, what they have done and do when they are in power, and what their conceptual apparatus obscures -- consistently with both the former problems.</P>
<P>I am telling you that I think certain concepts and views, even in the hands of wonderful people, even as those people sincerely proclaim their contrary desires, lead to the results we both reject. We can disagree about that, but there is not much point telling me I have to read the ISO's particular essays to hold the view as if of all the Marxists anywhere, somehow you guys have settled on the real Marxism, and the rest are delusional or something. Does the ISO utilize democratic centralism? If not, okay, I will take a closer look. But if so, that would be a big indicator for me...consistent, in my view, with coordinator dominance. But it could be that in addition the ISO has beliefs in many domains I would like and support, I don't know.</P>

<P><B>Parecon</B></P>
<P>I am happy to hear that you support the idea of council self management. The fact that I think Lenin and Trotsky obliterated attempts at it and you think they mourned the loss that was instead imposed by outside pressures is a huge difference, of course. But that we can say we agree about council self management, and therefore perhaps that we also agree that as far as an economic revolution the key vehicles ought to be directly democratic, self managing, workplace and community councils that are subordinate to no other actors or structures than themselves, and in which all the workers and consumers have a full and clear conception of the institutions they are striving toward, is very good.</P>
<P>To say remuneration for effort and sacrifice is somehow free marketish is wrong. Markets remunerate bargaining power in practice, and in idealized theory -- in the free market dream -- they remunerate output. These are hugely different than remunerating effort and sacrifice. If we have onerous work and fulfilling pleasant empowering work -- which in a parecon we would divide up in a balanced way -- the former would be remunerated more than the latter according to a parecon, but the reverse would occur according to markets. The remuneration scheme couldn't be more contrary.</P>
<P>You say, "In a society of true abundance, where the resources and means of production are democratically controlled, I'm not sure that the concept of `sacrifice' will hold any real meaning." If you prefer a different word, that's fine with me. But if I work longer then I give up or sacrifice more of my leisure. If I work harder I also sacrifice more compared to you. And if I work at more onerous tasks, I do as well. I doubt that you disagree. I hope not. </P>
<P>You say "Certainly, there will be no reason why anyone should ever go without, and a mature socialist society will have developed the technological means to abolish as much of the work that no one wants to do as possible (garbage collection is the classic example). The guiding principle of a socialist society will be solidarity, so I would imagine the members of that society would see it as their <I>responsibility </I>to every other to do their share--without the need to be remunerated on the basis of `sacrifice.' Remuneration should be on the basis of need, not the quantity or quality of work."</P>
<P>To say solidarity is a guiding value -- and it is of participatory economics -- should mean not that we assume people are solidaritous but rather that the economy's institutions literally produce solidarity in us. Instead of creating a situation wherein to get ahead one must ignore or trample the lives of others, that is, the economy should instead create a condition wherein I get ahead by paying attention to everyone's well being, and vice versa. Parecon does that, though it would take us a bit far a field to fully describe how. </P>
<P>I hope you won't take this wrong but I think talking about eliminating onerous work and everyone automatically working on behalf of everyone else and rewarding need are the sincere views of someone committed to good values who, however, hasn't thought deeply about an economic vision. And I think that's a problem. Your forebears in your heritage, the rank and file workers of Russia, had those ideas in mind, pretty much in the same form, and they got Soviet coordinatorism instead. What they didn't have in mind was actual institutional aims that they could fight for and implement. Institutional aims were in the minds of folks at the top, only, and those aims weren't participatory or self-managing. An ideology that serves coordinator aims, plus vague aspirations about economics that won't guide practice a whit in a real revolution, and what do you get? Coordinators in the saddle, I believe. </P>
<P>You talk about working people needing to be in command of their own revolution. I quite agree. But that entails that they have institutions of direct self-management throughout the process and that they know what they are after and will accept nothing less. Vision must be their property, not the property of a party operating on their behalf.</P>
<P>I am very happy to hear that you think " balanced job complexes sound like an excellent idea." If so, however, does that mean that your newspaper and party utilize them? Shouldn't they -- both to experiment with structures that can become part of a new economy and to provide evidence of their commitment to the new goals, as well as to enjoy the benefits? What do you think?</P>
<P>And it is nice to hear that you feel participatory planning is central to your aims, and that you have "no major objections to Parecon--at least the extremely brief outline that Albert has presented." Maybe we can get make some progress with this commonality, or potential commonality. Maybe the ISO should consider parecon to see if it fulfills your vision of true socialism, to see if it provides institutions that you feel would really deliver on the values and aspirations you hold dear. I should love to hear that you all felt that way.</P>
<P>You say, "I have two questions: What does Albert make of the fact that a Marxist can embrace the substance of the principles he puts forward as another formulation of those at the core of the Marxist tradition? And how do we get there?" I smile. What would you expect? </P>
<P>Do I think that parecon is contrary ultimately to many of Leninism's and even of Marxism's inclinations? Yes. But that doesn't mean I think every person who calls themselves Marxist will be blind to a good thing if it comes along. I'll be surprised, but happy about it, if a Marxist party decides to advocate participatory economics. If you look deeper into it and you really like it, and if we can talk about the implications for how we get to it and get some synergy there too, that would be very nice. </P>
<P>I have gone on endlessly, I fear. You ask about strategy. I recently published a book on "how we get there" -- which I very much think is critical, of course. It is called Moving Forward, and published by A K Press. If we go another round, and you ask more, I will reply about that. </P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>For my "Quotes" and such, as you requested, please <a href="http://www.zmag.org/excerpt.htm" target="_blank">click here</a>. The link will take you to excerpts from the introduction to the book <a href="http://www.parecon.org/lookingforward/toc.htm" target="_blank"><I>Looking Forward</a> (1990)</I>. The excerpt is about coordinatorism, including its modern roots in Bolshevism, and it has ample quotes. The book, also online, is about Participatory Economics.</P>
<P>For those really into the topics and my further views, far more material about Marxism and Leninism and about other ideologies as well can be found in the first book that I ever wrote, <I><a href="http://www.zmag.org/WITBU/witbuTOC.html" target="_blank">What Is To Be Undone</a> (1974)</I>, which is also online on ZNet. It is full of quotes -- quotes galore. The fifth chapter, for example, is about the Russian Revolution: <I><a href="http://www.zmag.org/WITBU/witbu05.html" target="_blank">A Critique of Bolshevik Practice</a></I>.</P>

</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
