<html>
<head>

<title>
Albert: Albert Replies 2
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="5"><b>Albert Replies 2</b></font><br>

<P><font face="Times New Roman, Times, serif" size="2"><b>By Michael Albert</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | August 6, 2002</font></P>

<P><font face="Times New Roman, Times, serif" size="3">Maass has written a rejoinder focusing on focus&#150;that is, focusing on whether Marxism takes into account other realms than the economy effectively. This is a topic I didn't want to pursue and which I barely raised at all in the piece he is reacting to, but...</P>
<P>Maass notes that I say the Marxist tradition "tends to exaggerate the centrality of economics and gives insufficient attention to gender, race, polity and the environment." At best, Marxism "[addresses] these other factors overwhelmingly only insofar as they impact class relations, rather than also in light of their own intrinsic logic." I hope he will relate to this as I said it...and not to the view I didn't offer which is that Marxism ignores all but the economy, or says all but the economy is unimportant, or even doesn't say other realms are highly important. Some Marxists are guilty of all of this, but not most, anymore, certainly. The issue is how realms are addressed.</P>
<P>My concerns -- which I think could be accommodated by Marxism but for the most part aren't -- are different. Thus, I think that Marxism says the economy emanates a field of influence that contours and molds all sides of life, which is correct,. But I think that Marxism doesn't admit that family and kinship relations do that too, as does the culture, as does the polity and political relations generally, which is incorrect. </P>
<P>So I am not saying that Marxists ignore other dimensions than economics, I am saying they however much attention they give them, they understand other dimensions by and large in terms of their relations to economics, and hardly ever vice versa. </P>
<P>So let's pinpoint our differences. In your view, Alan...</P>
<P>(a) Does Marxism say the economy emanates a field of influence that contours and molds all sides of life? </P>
<P>And (b) does it say, as well, that so do kinship, cultural, and political relations emanate such defining fields of force?</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>If a radical feminist were to say -- and many have -- that society and history are best understood as results of the clash and jangle of kinship and gender dynamics as mediated not only through families and socialization, of course, but also via the economy and polity and culture, I think most Marxists would say, hold on, wait just a minute. That is self-defeatingly narrow. It is wrong to think that a conceptual toolbox that starts from gender and kinship and that sees other domains largely in terms of relations to kinship will properly and fully illuminate those other domains. In our societies there are tremendous pressures to direct people away from understanding class and economy. If our framework doesn't overtly elevate and highlight class and economy in their own right and give clear and focused priority attention to them, then they will fall by the wayside, being understood, in this instance, only to the degree that feminist values and insights happen to require.</P>
<P>And I think Marxists would be accurate in arguing thusly. The thing is, the feminist would then also be accurate in turning the tables and saying it is wrong to think that starting from economics and understanding other domains largely in terms of a conceptual toolbox that starts from class and production you will illuminate those other domains properly and fully. In our societies there are tremendous pressures that direct people away from understanding kinship and gender. If our framework doesn't elevate and highlight kinship and gender and give clear and focused priority attention to them, then they will fall by the wayside, being understood, in this instance, only to the degree that class-focused values and insights happen to require. </P>
<P>Is each viewpoint being a little unfair to some practitioners of the other camp? Yes. But, on balance, regarding what comes through the clash and jangle, I think each viewpoint is right in their critique of the other.</P>
<P>The feminist who is subject to the critique of being gender-reductionist could certainly be a silly feminist denying the importance of economics at all. But the real point is that even a much better feminist who has very wide ranging concerns will still be subject to the criticism if she addresses economics using primarily concepts and views developed not from thinking firstly directly about production and consumption, but instead firstly via her understanding of gender. When she says that gender impacts economic structures and relations, she will be right. But when she fails to address just as closely that economics impacts gender and socialization, she will be wrong. I suspect Maass might well agree with my reactions here.</P>
<P>But the situation is quite reciprocal, I think. The critique I have of Marxism on this score, one shared by many others, is that Marxism doesn't emphasize that there are multiple sources of powerful influence on history and society, each able to impact the logic and operations of the others. Marxism could admit this...but it rarely does, in my experience. </P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass starts by saying "Albert's charge that Marxism is economistic can rely on what has become accepted as fact on the left. The general agreement is that Karl Marx and the Marxists who followed him were economic `reductionists'--that is, they reduce social questions, from whatever realm of life, to a matter of economics and tend to ignore or downplay issues that aren't immediately related to the class struggle."</P>
<P>Yes, someone's concerns could rest on those views, but mine don't. Maybe the difference wasn't clear, but, again, I am not saying Marxism ignores or even necessarily downplays (in the sense of saying they are literally unimportant) race or gender, among others. Rather, Marxists tend to understand these in light of class struggle and economics, insofar as they are impacted by the economy and class, and insofar as they impede or can help to propel class struggle. These non-economic domains are rarely seen by Marxists as having their own logics which impose on social possibilities and history as much as economics does. </P>
<P>Maass refers to a long period of truly reactionary Marxist stances re other than economic issues. The question to ask about this is how could a set of powerful concepts and values vis-a-vis history and society lead to such a condition, or even just permit it, even in what Maass wants to call horrible deviations? </P>
<P>Yes, under pressure from movements of women and cultural communities and gays and lesbians Marxists have by and large jettisoned the horrible prior reactionary stances, or at least some have. But that isn't the standard by which I want to judge an intellectual framework. I want a set of ideas, concepts, and values which propels people -- even against their socialization and biases -- to powerful insights about not only economics but also gender, race, sexuality, and ecology, among other focuses. I have said repeatedly that Marxists could adopt all that...I just don't think many have, historically.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass, you say "you will find very few people today who consider themselves Marxists and believe anything approaching the concepts that Albert and others attribute to us--that, for example, the `defining influences [on society] flow only from economy to polity, culture and kinship and not vice versa' or that `conceptualizations of the other mentioned realms [don't] offer equally central insights.'"</P>
<P>Okay, great. Then why waste time on this issue? If you agree with me that the lines of defining influence run both ways and that it is wrong to treat economics as more dominant or prior to or above or in some way more fundamental than race or gender or polity -- then fine. We are done on that front. </P>
<P>Maass says, "These distortions of Marxism are alive today most of all among advocates of <I>other </I>frameworks for understanding oppression--who keep erecting a Marxist straw man to tear down in making their own case."</P>
<P>Whoops, I guess we aren't quite ready to move on. Okay, please point me to four books on Marxism that are well respected and that indicate that not only economics but also kinship, culture, and polity are the sources of defining influences on society and history, so much so that no one of these realms should be prioritized above the rest. Hell, just direct me to one book by a noted Marxist that does that.</P>
<P>Do you doubt, in contrast, that if I go to my bookshelves with only a little digging I can find not just four but, say a dozen highly respected anti-Stalinist and truly humane Marxists from whose books I can quote on the priority of economics and in whose books I can look until the cows come home for serious treatment of other domains giving them remotely the priority and importance that is given to economics?</P>
<P>But let me repeat once more...I am not saying, unless I have been very unclear, that Marxists don't pay attention to race, gender, polity, etc. I am saying they (still) by and large pay attention to these in ways that underplay the intrinsic features of each and their defining impact on society relative to the importance of the intrinsic features of economics and class's defining impact. I don't think you are addressing this. Marxists address non economic relations largely insofar as they impact and are impacted by class struggle. But why not do that, yes, but also look at economics insofar as it impacts and is impacted by feminist struggle? And so on.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>A Marxist looks at families and, if astute, will rightly see that their social relations of kinship and socialization and sexuality are significantly impacted by their class position. Thus, economics impacts kinship and, as well, gender. I agree.</P>
<P>The thing is, a feminist looks at workplaces, and, if astute, will rightly see that their production relations are significantly impacted by patriarchal pressures, up to and including disruption of the most economically logical division of labor to incorporate defining features literally imposed, against economic logic, by gender expectations. Thus, kinship impacts economics, and, as well, class. I agree with this too.</P>
<P>More, agreeing with both the Marxist looking at families and the feminist looking at factories, I think that what we need is a conceptual framework that propels us to see not one or the other of these types of dynamic, but both of them -- and others too, such as the interfaces with culture and polity, and so on. </P>
<P>Now if you agree with all that, then fine, we are done on this issue.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass says, "Albert seems to accept this point--kind of. In his reply, he says: `The actual criticism isn't that Marxists ignore all other than economic dynamics&#133;' He can't, however, stop himself from adding: `though some do.'" </P>
<P>What's the problem with saying that. Some do, in fact, unless you literally want to say that everyone who has called themselves a Marxist and who has pretty much ignored other than economics was, by virtue of that fact, not a Marxist.</P>
<P>Maass says, "the discussion really should be about what Albert says next--`that [Marxists] pay attention to [gender, race, politics, etc.] in ways that miss key intrinsic features and relations.'"</P>
<P>Yes, it should be, I agree. </P>
<P>Maass notes, "for example, in his opening essay, Albert writes: `Marxism tends to presume that if economic relations are desirable, other social relations will fall into place.' Now if this were true, Marxism would be complacent about the struggle against oppression."</P>
<P>Actually, that isn't what follows. Rather, what follows is that Marxists would pay very close attention to other struggles whenever doing so seemed to them essential in order to win the economic class struggle, but the way they would pay attention might not be best suited to winning the race, gender, or anti-authoritarian struggles as well as the class struggle. </P>
<P>Maass says he "could guess where Albert's formula comes from," but the formula he has in mind to guess about, isn't mine. </P>
<P>Maass says..."Winning genuine liberation for the oppressed is bound up with the struggle to win the liberation of the whole working class, because the two things--oppression and exploitation--are bound together under capitalism. The system is driven by exploitation--the extraction of profits from the labor of workers--but it depends in various ways on different systems of special oppression that affect different parts of the working class."</P>
<P>This is actually an example of what I am criticizing, as I read it. Yes, the kinship, cultural, political, and economic systems in society intertwine with one another, even define one another, and are mutually enforcing. And yes, the economic system is driven by economic factors -- but the kinship system and political system and cultural system are driven in turn by their own logics -- also impacted by economics and vice versa. </P>
<P>Maass quotes as evidence of Marxist breadth of viewpoint..."Lenin insisted that Marxism had to respond to all political issues. To take one example, he argued that Russian socialists--living in the belly of the Tsarist beast, so to speak--had to take every opportunity to challenge great Russian chauvinism and champion revolts against the Tsar's `prison house of nations.' Not to do so would strengthen the hold of chauvinism among workers in the oppressor nation--and confirm to workers in the oppressed nations that they had no allies in Russia itself. Lenin's insistence on the unconditional support for the right of nations to self-determination was a recognition that working-class unity could only be achieved on the basis of equality--and that means championing the demands of the oppressed."</P>
<P>So what happens if one thinks working class unity can only be gained by paying less attention to some issue or other -- abortion, affirmative action, gay rights, or whatever? That is, even when looking for evidence of Marxists addressing other domains in their own right, much less addressing them insofar as they impact economics rather than vice versa, Maass offers quotes like the above and this next one which to me demonstrate very nearly the reverse of what he claims for them. "As Lenin famously put it: `Working-class consciousness cannot be genuine political consciousness unless the workers are trained to respond to <I>all </I>cases of tyranny, oppression, violence and abuse, no matter <I>what class </I>is affected&#133;Socialists should conduct propaganda that exposes the horrors and abuses of the system, so that the most backward workers will understand, <I>or will feel, </I>that the students and religious sects, the peasants and the authors are being abused and outraged by those same dark forces that are oppressing and crushing him at every step of his life. Feeling that, he himself will be filled with an irresistible desire to react, and he will know how to hoot the censors one day, on another day to demonstrate outside the house of a governor who has brutally suppressed a peasant uprising, on still another day to teach a lesson to the gendarmes in surplices who are doing the work of the holy inquisition.'"</P>
<P>Maass says, "Call it what you want--but economism that ain't."</P>
<P>Actually, if we are talking about economism in the more subtle sense I have been posing it as a problem, yes, that is what the above is, or in any event, the above -- chosen as a paradigm case -- doesn't provide something markedly better. </P>
<P>If or when Marxism incorporates a multifold attention to spheres of social life as all being influential, then Marxists will be a source for insights about the sexuality of teenagers, the dynamics of marriage and the nuclear family, the dynamics of culture, and religion, and the rest of the diverse realms of human engagement, each not just as they reflect economic pressures, or as they are comprehensible in terms of economic concepts, or as they are important to address in order to further class struggle, but in their own right.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass says, "Albert has a pair of loaded dice at this debate. He argues in numerous formulations that Marxism needs to incorporate `concepts reflecting the impact' of factors such as `gender and kinship dynamics, race and cultural dynamics and political dynamics.' On the one hand, this implies that Marxism has little valuable to say about these dynamics. On the other, it promotes `concepts' on the basis of their subject matter, not their content. Comes up sevens every time."</P>
<P>I don't know precisely what this means, but obviously I am not suggesting we incorporate just any old concepts, but rather valuable and useful ones. That's why I don't like Marxism's class concepts...for example...because they leave out too much that is important even while, of course, class concepts are needed.</P>
<P>We live in a multi-faceted world and we have all been subject to conditions that generate mental biases of diverse kinds having to do with class, race, gender, and power, among other things. I believe the political framework we utilize should work strongly against those biases to cause us to prioritize attention to each of these realms in their own right, even against our training and upbringing and sometimes our group interests, in no sense subordinating any one of the focuses to the others.</P>
<P>I think Maass will agree that one could have a framework that picks out one realm as more important, even as it also pays attention to the others, though in considerable part via its concern for the first. I suspect he would say that's what nationalists do, and feminists, highlighting kinship and culture/community, respectively. And I think he would say they have an approach, a set of concepts, a view of how to look at society and history, which tends to give too little priority and attention to the intrinsic influential dynamics of economics. And I think Maass would be right in saying this, if he did. And I would say it. But this is also what I am saying about Marxism. </P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass says, "More always sounds better than Less. It seems perfectly obvious that Marxists should supplement their understanding of the world with `conceptualizations' that focus on non-economic realms. No one can object to a proposition at that level of abstraction."</P>
<P>Right, which is why I make it a bit more exacting -- and were this a book, I would make it far more exacting. It is not just that Marxists should add some good stuff to their insights -- it is that they should recognize that kinship dynamics and gender relations, cultural dynamics and community relations, and political dynamics and power relations all also exist in their own right, like economics and class relations, and with their own logics and systems of institutions, and that just as economics emanates defininginfluences throughout society which impact those other realms, so do those other realms emanate defining influences that impact one another and economics. If we can agree on all that...then we can conclude this part of our debate. Actually, if we can't agree on it, we should probably stop this part anyhow, agreeing to disagree.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass says, "If Albert thinks that Marxists should gain insights from "power feminism," then he has to explain how to square a set of ideas that explicitly justifies an individualistic approach to change, accessible only to a minority of upper-class women, with the project of winning liberation for all."</P>
<P>I have to ask you Alan -- why did you write that? What could possibly have caused you to (a) go get some ridiculous views, and then (b) act like there was some reason to wonder if I advocated those views?</P>
<P>Maass says, "It is a caricature to suggest that Marxists believe that any and all aspects of life can be understood by studying economic relations."</P>
<P>Yes, it would be a caricature, which is why I have never said that. </P>
<P>Maass says, "I should also say that I have no problem with the argument that non-economic issues have to be understood on their own terms." </P>
<P>Good. </P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass says, "I have no idea what Albert is talking about when he refers to an "authoritarian" system of oppression. In what sense does `authority' operate as a social system independent of capitalist exploitation and forms of oppression based on race, gender, sexual identity, etc.? I know that anarchists have had a longstanding gripe about the authority exercised by, say, a marshal at a demonstration. We can argue this point if he wants. But it's one thing to talk about authority in movements for change and quite another to claim that such a system functions throughout society."</P>
<P>Not only does an authoritarian political system not operate independent of capitalism, but, vice versa, with the same force, which is the part Marxists just don't seem to get. In any event, unless we are going to dissect everything about society...we have to agree to disagree about some things and leave others unexplored. But, Alan, here maybe we can get some quick agreement. you would say Stalinism is a horrendous violation of what you hold dear. Okay, good. I would say that too. Now was Stalinism an economic system? I think not. I think it was mostly a political system -- an authoritarian political system which emanated authoritarian implications throughout all of society. I would imagine you would agree with that, and so right there we have the possibility of the existence of a powerful and overridingly important political system established. I also think there is a system of political hierarchy in our current society, different, but powerful and influential. </P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass says, "For the purposes of discussion, I'll make the assumption that the conceptualizations Albert alludes to share an important characteristic that has come to define what is known as identity politics."</P>
<P>Why did you do this? Saying it is "for the purposes of discussion" -- well of course it is for the purpose of discussion, you are discussing it. But the problem is, it has nothing to do with me. I am a strong critic of identity politics and I would actually be surprised if you didn't know that. And at any rate, I surely didn't say anything remotely like what identity politics claims. So why do you spend a long time rebutting identity politics, as if you are thereby rebutting my views, I wonder?</P>
<P>I have written at length about historical materialism and the rest that you bring up in your foray into Marxist theory. We agree about some of it, but not too much. I don't think there is much point in reproducing that long content here. A whole book, admittedly written a long time ago, is even online, for those interested. It is linked from the top page of ZNet -- and titled, What Is To Be Undone.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>After you provide your summary of Marxist views you note: "But a difference does remain. In Albert's initial essay, he writes, `Marxism would need to recognize both directions of causality, not exclusively or even primarily only causality from economics to the rest of society.' Marxism does recognize `both directions of causality.' But it also insists that economics `ultimately always asserts itself,' as Engels wrote--that the material question of how people produce to meet their needs is the <I>primary </I>factor in shaping other realms of life."</P>
<P>Fine, let's let that stand as our disagreement. When you say "The point of saying that economics is more active in shaping other realms of life than vice versa is to give a picture of how society has developed and changed throughout history," I say, yes, and it is not as good a picture as we need because it underplays the impact that other domains have had and can and will have, in the future. </P>
<P>Maass, you quote Marx saying, "All mysteries which lead theory to mysticism find their rational solution in human practice and in the comprehension of this practice. In other words, the proof is in the pudding." Indeed. And so I look at the history of Marxist Leninists in power, and in struggle -- the human practice -- and what I see is much worse than anything I have even argued. </P>
<P>You say the real issue is, "Is Marxism relevant today--as a tradition that can help those fighting struggles now? If I've been insistent about being concrete in assessing political ideas and theories, it's because I think that they need to be applied to the real world--and used in today's struggles for change."</P>
<P>I quite agree. But the question isn't just is Marxism useful -- the question is rather, is Marxism the best framework we can adopt -- the most useful one. </P>
<P>Your essay here was trying to make a case that Marxism is exceptionally useful for its capacity to propel adherents to pay insightful attention to the rich dynamics of race, gender, and power relations -- in addition to and not just in relation to class relations. I don't buy it, so we disagree.</P>
<P>For me a framework which emphasizes the entwined importance of economics, polity, kinship, and culture -- and which starts from the premise of their mutual defining influences on one another, and their mutual capacity to impact historically important constituencies' consciousness and agendas, has more hope for propelling insights into all these domains than a framework which prioritizes any one of these realms above the rest. I actually think a Marxist could agree with that, including saying that Marxism brings part of that whole framework to the table...though for reasons having to do with my other criticisms, I would question the latter part of the claim.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Maass says, "For Marxists, the greatest test of all is the 1917 Russian Revolution. Albert makes it very clear that he disagrees with my assessment of that revolution and especially the Marxist revolutionaries, the Bolsheviks, who led it. He's right that this debate isn't likely to change either of our minds. But I have to take exception when he says that we `likely won't' agree on the facts. There <I>are </I>facts about the Russian Revolution that aren't subject to interpretation."</P>
<P>Yes, there are such facts, but we are unlikely to agree what they are or their meaning. You are right that in the early days of the Russian revolution there were many profoundly valuable innovations, for example. But I think they were crushed, not solely by civil war, but also by the Bolshevik agenda. I think again we need to agree to disagree. My own views are available for anyone interested in many places, including that book online mentioned earlier and, for example, the book titled Socialism Today and Tomorrow, which looks at Race, gender, power, and class in the Russian, Chinese, and Cuban revolutions.</P>

</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
