<html>
<head>

<title>
Maass: Marxism vs. Coordinatorism
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="5"><b>Marxism vs. Coordinatorism</b></font><br>
<font face="Times New Roman, Times, serif" size="3"><i><b>A reply to Michael Albert's opening essay</b></i></i></font></p>
<p><font face="Times New Roman, Times, serif" size="2"><b>By Alan Maass</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | July 19, 2002</font></p>

<P><font face="Times New Roman, Times, serif" size="3">I'll oblige Michael Albert and focus on the points that he says he wants to discuss in this debate--the nature of what he calls the "coordinator class," and his claim that Marxism advocates a "coordinator mode of production."</P>
<P>Not that I want to ignore the other "problems" (among a certain number of "virtues") that Albert raised about Marxism in his initial essay. Actually, he spends the first third of the article on other half-developed criticisms--the supposedly soul-deadening obscurity of dialectics; Marxism's alleged insufficient attention to gender, race, polity and the environment; the inadequacies of the labor theory of value and Marxist crisis theory. </P>
<P>These are all issues worth discussing, and I disagree with Albert's brief assertions on them every bit as much as his conclusions about "coordinatorism." But I'll forego them here, on the expectation that the discussions will come up at other points in this exchange. </P>
<P>One complaint, though, before moving on--in the hopes of helping to frame this debate. I fully expect Albert to disagree with my conclusions about Marxism, and I think that a discussion of our differences can help clarify important political issues. I do think, however, that I ought to be able to recognize the Marxism that Albert makes a case against. In a number of places, though, he's settled for repeating distortions and misrepresentations, instead of the real thing. Like, for example, his one-sentence dismissal of "orthodox Marxist crisis theory, in all its variants" because it "often [sees] intrinsic collapse where no such prospect exists." </P>
<P>Albert can make whatever assertions he likes, but what we need here are examples--quotations, historical references, etc. Thus, for example, who are these "real existing people" whose use of Marxism "gives insufficient attention to gender, race, polity and the environment"? Personally, I don't know any Marxist who would recognize themselves in these generalizations. Looking back on my own experience, I can't imagine how I would describe the political discussions and the activism that I've taken part in for the past 20 years without talking about the central importance of "gender, race, polity and the environment." We do have differences about the relationship and the dynamics of "economics" and "gender, race, polity and the environment," etc. We should have that discussion out. But Albert shouldn't claim that Marxists and Marxist organizations "give insufficient attention" to these issues. The debate is about <I>how </I>we give attention, not <I>if </I>we do. But I'll look forward to making this case at greater length elsewhere in this exchange.</P>

<B><P>The coordinator class?</P>
</B><P>Albert believes that the most damning charge against Marxism is that it "gets the economy wrong." He believes that "Marxist class theory literally denies the existence of what I call the coordinator (professional-managerial or technocratic) class"; that "this coordinator class can actually become the ruling class of a new economy"; and even that "Marxism's economic goals amount to advocating a coordinator mode of production." </P>
<P>Putting the beginning and end of the argument together like this highlights the problems: How can Marxism advocate a program of class rule for a class that it doesn't acknowledge the existence of? And how would the professionals, managers and technocrats in U.S. society react to the idea that Marxism is the best expression of their economic aims. I'm not sure--maybe Albert can explain. But I can't figure out how to deal with these questions together, so I'll take up the two ends of the argument separately.</P>
<P>Albert is right that Karl Marx and other contributors to the Marxist tradition identify two main classes in capitalist society--"two great hostile camps...directly facing each other: bourgeoisie and proletariat," as Marx and Engels put it in the <I>Communist Manifesto. </I>But that doesn't mean he ignored the existence of social classes other than the capitalist class and the working class, including the layers that exist between the two in capitalist society. He wrote extensively about the "petty bourgeoisie"--people who make their living primarily by their own labor, rather than through the economic exploitation of others, using self-owned means of production (tools) or other property (their own store or office). The classic examples are self-employed tradespeople or shopkeepers--a social layer that was more extensive in capitalism's infancy--though the term can be extended without too many conditions to cover small employers or professionals.</P>
<P>Also--and more to the point of Albert's arguments about "coordinators"--Marx anticipated a development in capitalism that wouldn't take place on a significant scale until the end of the 19th century: the rise of what he called the "overseers of labor and stewards of capital." In one of his economic notebooks, for example, Marx refers to the tendency, as the system develops, for capitalist owners to "hand over the work of direct and constant supervision of the individual workmen, and groups of workmen, to a special kind of wage-laborer. An industrial army of workmen, under the command of a capitalist, requires, like a real army, officers (managers), and sergeants (foremen, overlookers), who, while the work is being done, command in the name of the capitalist. The work of supervision becomes their established and exclusive function." </P>
<P>So it's simply not true that Marx "literally denied the existence" of social layers between capital and labor. Likewise, Marxists after Marx have spent plenty of time and ink adding to the understanding of this middle class, and I have a small stack of books next to me as I write this to prove it.</P>
<P>The challenge has always been to figure out who fits into the middle class and who doesn't. And here, I'm going to give Albert the benefit of the doubt. He doesn't define his "coordinator class" except with four words in parenthesis--"professional-managerial or technocratic." Various writers have used such terms to throw together such vastly different occupations as top corporate executives, as long as they aren't stockholders, and technical employees whose paycheck is calculated as an annual salary rather than an hourly wage. </P>
<P>I'm going to guess that I know what Albert means and assume that his coordinator class doesn't include white-collar employees like computer programmers, lab technicians, etc. These are people who should be considered part of the working class, though the case can be made that they exercise relative control over their work and that their work indirectly coordinates other people's labor. And I'll assume that Albert doesn't include among the coordinators people who may not technically own the means of production, but whose power in society comes from their share in the ruling class's collective control over them--that is, top corporate executives, top bureaucratic administrators and leading politicians. This bunch has to be considered part of the capitalist class, or we're left with the absurd idea that a Walton toddler who shares in the family stake in Wal-Mart is a capitalist, but Bush administration officials who coordinate and implement the national policy of the American ruling class aren't.</P>
<P>Albert should say so if he doesn't agree with these qualifications--and explain what he does mean.</P>
<P>But for right now, I'll guess that Albert is referring to the people who fall somewhere along a spectrum in between. Among them are people closely associated with the process of producing goods and services, who supervise and control the labor of others. They may have operational control over how resources are used from day to day, but have less if any say about their strategic allocation. Also situated along the spectrum are employees less central to production who have high degrees of autonomy about how they do their work and gain considerable privileges from their role in the process.</P>
<P>It's important to see how this spectrum blurs at one end into the ranks of the managerial capitalists and at the other into the white-collar working class. This highlights the point that Marxists make--not that the middle class doesn't exist, but that it can only be understood by its relationship to the capitalist class above it and the working class below it. As Marx put it, referring to the nature of the classic petty bourgeoisie, "The independent peasant or handicraftsman is cut up into two persons. As owner of the means of production, he is capitalist; as laborer, he is his own wage-laborer." </P>
<P>This contradictory nature distinguishes the middle class from the "two great hostile camps." Albert's "coordinators" don't, under anything but exceptional circumstances, act as an <I>independent </I>class, either economically or politically. Under capitalism, their existence is bound up with their relationships to the capitalists above and workers below--and is circumscribed by economic functions they perform that belong to either capital or lbaor. Most of the time--in periods of relative social stability, including mild crises--they identify with the capitalist class in its conflicts with labor. But in times of profound crises, when the middle class is pushed in the direction of ruin, they can revolt against the rule of capital, usually following the lead of a working-class rebellion. </P>
<P>In other words, the middle class does "contend with capitalists and workers within capitalism," as Albert puts it--but almost never both at the same time, or independently of one or the other sides.</P>
<P>I can think of a couple historical exceptions in which the middle class has played a decisive political role. What these situations have in common is that one or both of the two main classes were either paralyzed or exceptionally weak. One example that comes to mind is the rise of fascism in Germany in the 1920s and '30s. This was possible because of the defeat of German workers' revolt after the end of the First World War. But the country's profound economic and social crisis left the ruling class unable to re-impose its unquestioned authority. This vacuum opened the way for the Nazis, as the political voice of the petty bourgeoisie, to come to power, winning support with anti-capitalist rhetoric, anti-Semitic scapegoating and the promise of restoring order. But no one would seriously claim that fascism's anti-capitalism was anything but rhetoric--and that the Nazis didn't defend the rule of capital. </P>
<P>A very different case would be some of the national revolutions in the less developed world, starting in the 1950s. In these cases, the old order was so corrupt and doddering and the small native bourgeoisie so compromised by its ties to both the oligarchies and imperialism that elements of the middle class intelligentsia played the leading role in carrying through revolutions of national liberation. The political complexion of these revolutions varied widely. But the project ultimately amounted to carrying out national economic development on the model of state capitalism--in effect, carrying out the rule of capitalism, under another name and in a (sometimes) kinder, gentler form.</P>
<P>So these are historical exceptions in which the middle class has played a decisive role. But its independence from capital and labor was limited, and under no circumstances, I would argue, did it preside over the creation of a new mode of production, distinct from capitalism. </P>
<P>Much more could be said here, but let's return to the relevance of Albert's picture in the contemporary world around us, since that's where he expects Marxism to prove its relevance. It's one thing to identify intermediate social elements between labor and capital, which have conflicts with both. It's another to explain the basis on which this class can take independent action, much less come to rule over society in anything but very limited circumstances. As the American Marxist Hal Draper put it, "This requires a cohesiveness, a fund of common interests, an objective basis for solidarity and social unity, such as do not exist among the disparate elements of this ectoplasmic class-construct."</P>
<P>The middle class is a significant minority of the population, seemingly all the more so because its lifestyle is celebrated by the media echo chamber. But under most circumstances, members of this social layer don't identify with each other. Their hopes for the future aren't collective, but individual--based on the dream of climbing the ladder to join those above them. This leads to the despicable mentality of yuppiedom, summed up for me by the bumper sticker "Prosperity is my birthright."</P>
<P>If Albert disagrees, then he should be specific. What is the basis for political and social unity between a supervisor on the assembly line, the assistant comptroller for the same company, a creative director at the advertising agency hired by that company, and a legal associate at the company's law firm? Under what circumstances would they all unite against both workers below and capitalists above? In the real world, can anyone imagine "coordinators" uniting to overthrow capital and establish their own independent mode of production? And to move to another of Albert's points, can anyone conceive of yuppies coming to view Marxism as the best expression of their economic aims?</P>
<P>But this leads me to the other end of Albert's argument.</P>

<B><P>Marxism and the coordinators?</P>
</B><P>I've argued that I think Albert is wrong to say Marxism "literally denies the existence" of the middle class and wrong in his understanding of the nature of this social layer and its capability of taking independent class action, much less establishing a new mode of production. But in terms of the preceding attempt to understand this middle class in capitalist society, Albert's association of "coordinatorism" with Marxism comes out of left field. Does Albert really believe that the economic aims of accountants, lawyers and mid-level corporate executives were best expressed by Karl Marx? </P>
<P>This end of Albert's case can't be understood unless it's considered separately. His argument, as I understand it, is that the societies which have called themselves socialist and been ruled over by people who claim to be Marxist--countries like the former USSR, China, Cuba, North Korea, etc.--should be understood as "coordinatorist."</P>
<P>Here is his description of "this new economy": "It has public or state ownership of productive assets and corporate divisions of labor. It remunerates power and/or output. It utilizes central planning and/or markets for allocation. It is typically called by its advocates market socialism or centrally planned socialism...It has been adopted by every Marxist party that has ever redefined a society's economic relations."</P>
<P>This is by and large an accurate description of the countries listed above, past and present. But the question is whether they were socialist--and whether the "Marxist parties" that redefined their economic relations had anything to do with Marxism. </P>
<P>My organization, the International Socialist Organization, is part of a tradition that has always rejected the idea that these top-down regimes represent Marxism. Our case is simple--that the starting principle of Marxism was summed up in a sentence written by Marx for the rules of the First International: "The emancipation of the working classes must be conquered by the working classes themselves." It doesn't matter what the rulers of the ex-USSR and the other so-called "socialist" countries called themselves--any more than it matters for our understanding of democracy that Bill Clinton calls himself a Democrat. The question is whether workers control society. In the USSR and the other bastions of "Marxism," the experience of workers wasn't one of control and freedom, but of exploitation, oppression and alienation from all levers of social and political control.</P>
<P>In fact, what stands out most about these so-called "socialist" societies is how much they resemble capitalism. Take Albert's description of the "coordinatorist" economy. A corporate division of labor, remuneration of power and/or output and the use of markets for allocation are mainstays of Western-style capitalism. Central planning is common enough on a piecemeal basis, especially in circumstances like the war economies overseen by the U.S. government and its rivals in other countries during the Second World War, and to a lesser extent in the military-industrial complex to this day. Nor is "public or state ownership of productive assets" unknown in the West. Again, in a war economy, even the U.S. government has been known to take control, if not ownership, of whole sectors of industry. Nor did long-term public ownership of industry and services in Europe following the Second World War undermine capitalism. Otherwise, you'd have to imagine that Margaret Thatcher was a socialist and Marxist--since her government owned Britain's coal industry, British Rail, etc. There's much more to it, but this is the beginning of an explanation of why I think that the best term to describe the so-called socialist countries is "state capitalist," not coordinatorist.</P>
<P>So how did this happen--that the rulers of undemocratic, oppressive and exploitative societies could masquerade as something they weren't? Again, there is a long tradition of Marxists who have attempted to come to terms with this question, both in general and in light of the historical facts of each case. I can't possibly do justice to the full argument, but I think that it's necessary to sketch out some of the main points of a Marxist analysis of Stalinism, because Albert doesn't show any sign that he recognizes it exists.</P>
<P>In only one case--Russia--did any of these countries actually have a working-class revolution. But while the October revolution of 1917 won power for the workers' councils, or soviets, establishing the basic institution of a socialist society, the task of creating socialism could never be completed if an economically backward Russia remained isolated in a sea of capitalism, without socialist revolutions in other countries to come to its aid. All of Russia's Bolsheviks, the majority party in the workers' councils, accepted this, Lenin most of all. "We are far from having completed even the transitional period from capitalism to socialism," Lenin wrote in January 1918. "We have never cherished the hope that we could finish it without the aid of the international proletariat. We have never had any illusions on that score...The final victory of socialism in a single country is, of course, impossible." </P>
<P>Lenin was proved right. Without victorious revolutions in more advanced countries, the revolution was doomed. But the form that its defeat took was unexpected. The Bolshevik-led workers' state survived the civil war against it, but the basis for a society controlled by workers was wiped out by the ravages of the war, the ruin of Russian industry and the actual disintegration of the Russian working class. In these desperate conditions, the Bolsehvik Party came increasingly to step into the breach, substituting its own rule for that of the decimated institutions of workers' power created out of 1917--and within the party, the growing apparatus, led by Stalin, edged the membership from control. Though not unopposed, Stalin and his fellow bureaucrats ultimately took charge as a new ruling class, reversing the victories of 1917, but preserving the rhetoric of socialism and Marxism--by distorting it out of all recognition. The resulting society reestablished class rule, though in a different form--with a state bureaucratic ruling class making all the main decisions and using the utmost repression to preserve its power.</P>
<P>In the other so-called "socialist" countries, beginning with the Chinese Revolution of 1949, the economic model of the USSR's "socialism" was adopted, along with the fake Marxist rhetoric--but without the inconvenience of a working-class revolution. In China, the working class played no role in Mao's long march--in fact, his army explicitly ordered workers to stay on the job as they conquered successive cities. The same was true of the Cuban Revolution--led by Castro's guerillas, who spent more than a year in power before they declared their devotion to socialism and Marxism. Cuba's revolution was a blow struck for national liberation and against U.S. imperialism, and socialists have always supported it for this reason. But that doesn't make Castro and his regime a model for socialism.</P>
<P>Cuba was one of a number of less developed countries that saw revolutions in the years following the Second World War, against either direct colonial rule or a corrupt old order propped up by imperialism. Many of the victors turned to the model of state capitalism in the USSR, which seemed to provide an alternative to domination by the West in the form of a program for independent national economic development. Not all of these countries adopted the rhetoric of Marxism, though. Castro and the Cuban revolutionaries eventually did; Egypt's Gamal Abdel-Nasser identified himself as a nationalist; Kwame Nkrumah and the African socialists promoted some elements of the vocabulary and not others. Opponents of imperialism supported their struggles, regardless of the rhetoric, against the economic and political domination of the imperialist powers. And the revolutions in at least some of these less developed countries produced real advances for working people. But these societies' claim to be Marxist was based on their association with and imitation of the USSR's fake Marxism.</P>
<P>In this respect, Albert's brief sketch of "coordinatorism" does capture some of the reality of the Third World revolutions. They were in at least some cases carried out by sections of the middle class, in the name of "the people." The new society was run by an elite that, to varying degrees, relied on centralized planning, bureaucratic control and public ownership to organize the economy. Workers gained no real measure of control, at the workplace or in any aspect of their lives. </P>
<P>But Albert's picture fails because he accepts the self-identification of these societies--some of them, anyway--as socialist and Marxist. This can only be done by ignoring Marx's own vision of a future society. In quoting Albert's description of the "coordinatorist" economy at the beginning of this section, I left out one sentence: "It is celebrated as the goal of struggle in every Marxist text that offers a serious economic vision." That is utterly false--for Marx and for every genuine Marxist who followed him. The "goal of struggle" in every text that takes up this question is a society characterized by mass working-class participation, democracy and freedom.</P>
<P>The first place to look in Marx's own work for this vision is a pamphlet called <I>The Civil War in France, </I>a collection of speeches made on the heels of the Paris Commune of 1871, an uprising from below that briefly established a government controlled by the working class. What is especially noteworthy about the circumstances is that it shows Marx didn't pluck his ideas about a future society out of thin air or dream them up during his researches in the British Museum. He saw what Parisian workers produced in action and adopted these accomplishments.</P>
<P>As for Albert's charge that "every Marxist text" advocates the rule of a "coordinatorist" minority, Marx's main focus in <I>The Civil War in France </I>is to show how the Commune came up with ways to maintain mass democracy, by controlling its representatives. Far from celebrating the representatives, Marx celebrates the fact that they were immediately recallable and paid no more than an average workers' wage, so that they couldn't rise above the social level of those they represented. "[The Commune's] true secret was this," Marx wrote. "It was essentially a working class government, the product of the struggle of the producing against the appropriating class, the political form at last discovered under which to work out the economical emancipation of labor." </P>
<P>The crucial importance of workers emancipating themselves and controlling society in their own interests runs through everything that Marx wrote--and through the Marxist tradition that followed him. Here is the case put by different Marxists:</P>
<P>Frederick Engels: "It goes without saying that society cannot itself be free unless each individual is free. The old mode of production must therefore be revolutionized from top to bottom. Its place must be taken by an organization of production in which, on the one hand, no individual can put on to other persons his share of the productive labor...and in which, on the other hand, productive labor, instead of being a means to the subjection of men, will become a means to their emancipation, by giving each individual the opportunity to develop and exercise all his faculties."</P>
<P>Lenin: "It is just the revolutionary periods which are distinguished by wider, richer, more deliberate, more methodical, more systematic, more courageous and more vivid making of history than periods of philistine, Cadet, reformist progress...[The liberals] shout about the disappearance of intellect and reason when, instead of the picking of draft laws to pieces by petty bureaucrats and liberal <I>penny-a-liner </I>journalists, there begins a period of direct political activity of the 'common people,' who simply set to work without more ado to smash all the instruments for oppressing the people, seize power and take what was regarded as belong to all kinds of robbers of the people--in short, when the intellect and reason of millions of downtrodden people awaken not only to read books, but for action, vital human action, to make history."</P>
<P>Leon Trotsky: "The most indubitable feature of a revolution is the direct interference of the masses in historic events. In ordinary times, the state--be it monarchical or democratic--elevates itself above the nation, and history is made by specialists in that line of business--kings, ministers, bureaucrats, parliamentarians, journalists. But at those crucial moments when the old order becomes no longer endurable to the masses, they break over the barriers excluding them from the political arena, sweep aside their traditional representatives, and create by their own interference the initial groundwork for a new regime...The history of a revolution is for us first of all a history of the forcible entrance of the masses into the realm of rulership over their own destiny."</P>
<P>These passages seem to me to reflect Marxism's commitment to a society run by the mass of working people, rather than an elite--a thread that I think runs continuously through the genuine Marxist tradition. I'm under no illusion that there aren't other passages which might be quoted, and that these passages might seem to contradict the ones I've chosen. Fine--let Albert at least quote Marx and the others, and we'll discuss their meaning and context. But he shouldn't be satisfied with naked assertions that "the goal of struggle in every Marxist text that offers a serious economic vision" is an elite, top-down society--and that "coordinatorism does have roots in various Marxist and particularly Leninist concepts and commitments." Let's see the evidence.</P>
<P>Albert's only apparent recognition that Marxists--from Marx's time to this day--have said quite the opposite are veiled references to our "rhetorical entreaties" that apparently hide the real agenda. Now this is pretty insulting--not only to Marxists like me, who would appear to be "coordinators" in training, but to all the people who have looked to Marxism over the years. </P>
<P>Marx developed his vision of "scientific socialism" in direct opposition to other brands of socialism of the time that anticipated a fully imagined new society imposed from above. In contrast, Marx insisted that the victory of socialism depended not on the visions of an enlightened elite or negotiations with the upper classes, but the struggles of the working class to emancipate itself. No one made this point better than the great American socialist Eugene Debs: "Too long have the workers of the world waited for some Moses to lead them out of bondage. He has not come; he never will come. I would not lead you out if I could; for if you could be led out, you could be led back again. I would have you make up your minds that there is nothing you cannot do for yourselves."</P>
<P>For most of the 20th century, a majority of the socialist movement accepted Stalinism--or at least one of its imitators in China, Cuba, etc.--as Marxism, with all the distortions and false interpretations of the Marxist tradition that went with it. This has warped the meaning of Marxism for millions of people. So it is no surprise when Albert associates Marxism and Stalinism without qualification. But a minority in the socialist movement--sometimes a very small minority--always challenged the identification of Stalin's Russia or Mao's China with genuine socialism. And it was this minority that was vindicated by the fall of the Berlin Wall and the collapse of the ex-USSR a decade ago--when masses of working people rose up against the "Marxists." </P>
<P>The point comes down to this. If Albert is right that the so-called "socialist" societies of the ex-USSR, etc. are a true reflection of the economic aims of Marxism, then I would agree with him. Marxism would need to be not "transcended," but repudiated. </P>
<P>But I don't agree that these countries were "actual Marxist economies"--or actual Marxist anythings. The tradition that my organization is a part of has always rejected that contention, and our case for what constitutes genuine Marxism is equally longstanding. We've spent quite a number of years cleaning out the stables. If Albert thinks a debate with me and the ISO about the relevance of Marxism is useful, then he should address himself to <I>our </I>Marxism--not the fake Marxism of bureaucrats and dictators that we have always rejected and opposed. </P>

<B><P>What kind of society?</P>
</B><P>At the end of his opening essay, Albert rightly offers a positive alternative, rather than only criticisms of Marxism--what he calls "participatory economics." After referring us to the Parecon Web site, he briefly mentions the four main principles of this vision of a new economy--defining each one negatively by counterposing it to "Marxism." After the long case that I've made for rejecting Albert's distorted view of Marxism, it will be no surprise that I think his counterpositions are just as wrong.</P>
<P>But strip away these, and I think that his principles are reasonably close to what I would expect in a future, fully developed socialist society: </P>
<P>1) <B>Council self-management</B>--if I'm correct in understanding this phrase to mean workplace councils and other decision-making bodies, organized by neighborhood or some other criteria--is at the core of the Marxist tradition's vision of workers' power. In his pamphlet <I>State and Revolution, </I>for example, Lenin argued for the centrality of workers' councils, based on the experience of the 1905 Russian Revolution, when workers established the first soviets to organize their struggle. Every great upheaval since has thrown up a similar form--the shoras of the 1979 Iranian revolution, for example, or the cordones in Chile in the early 1970s, to name a couple examples. </P>
<P>2) If anything, I would say that <B>remuneration for effort and sacrifice </B>is a concession to the ideology of the free market. In a society of true abundance, where the resources and means of production are democratically controlled, I'm not sure that the concept of "sacrifice" will hold any real meaning. Certainly, there will be no reason why anyone should ever go without, and a mature socialist society will have developed the technological means to abolish as much of the work that no one wants to do as possible (garbage collection is the classic example). The guiding principle of a socialist society will be solidarity, so I would imagine the members of that society would see it as their <I>responsibility </I>to every other to do their share--without the need to be remunerated on the basis of "sacrifice." Remuneration should be on the basis of need, not the quantity or quality of work.</P>
<P>3) Likewise, <B>balanced job complexes </B>sound like an excellent idea. It was Karl Marx, after all, who said--in an affront to vegetarians everywhere--that communism would make it possible "to do one thing today and another tomorrow, to hunt in the morning, fish in the afternoon, rear cattle in the evening, criticize after dinner, just as I have a mind, without ever becoming hunter, fisherman, shepherd or critic." I would only suggest that "balanced job complexes" should be seen as a positive good in themselves, rather than something necessary to prevent the rise of "coordinators." After all, it will never be possible for everyone to do every task that needs accomplishing in society. The key to preventing the rise of privileged "coordinators" is democratic control over production.</P>
<P>4) Finally, <B>participatory planning </B>is likewise central to the Marxist alternative--as opposed to the top-down centralized planning carried out by the Stalinist regimes.</P>
<P>So I have no major objections to Parecon--at least the extremely brief outline that Albert has presented. I have two questions: What does Albert make of the fact that a Marxist can embrace the substance of the principles he puts forward as another formulation of those at the core of the Marxist tradition? And how do we get there?</P>
<P>The second is the far more important one. Parecon is an economic vision, but what is to be done to achieve it? Maybe Albert doesn't believe that we should focus on this question--thus, his offhand criticism of "Marxism's general taboo against 'utopian' speculation." I confess that I'm not sure exactly what he means, given that two sentences later, he chides Marxists for <I>being </I>utopian in their assertion of the principle: "From each according to their ability, to each according to their need." </P>
<P>My argument is that Marxism provides both a vision of the future, but more importantly, an understanding of how to achieve it. You won't read much about the shape of the future socialist society in Marx's writings. He typically stated his aim in terms of who would rule--the rule of the working class majority. This is important for two reasons. First, the job of planning a new society will belong to those who make it, using whatever proposals and alternatives they see fit. And second, a society organized around the principles of solidarity and cooperation is only possible once working people have changed themselves. </P>
<P>As Marx argued, "Revolution is necessary not only because the ruling class cannot be overthrown in any other way but also because the class overthrowing it can only in a revolution succeed in ridding itself of all the muck of ages and become fit to found society anew." In other words, the struggle to achieve a new world--in which the mass of ordinary people become conscious of their own power, learn what they share in common, overcome the division within their ranks and become confident in their own abilities to reorganize society--is ever more important than the vision of that new world itself. </P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Alan Maass is the editor of <I>Socialist Worker,</I> a weekly newspaper published by the International Socialist Organization. He can be e-mailed at <a href="mailto:maass@socialistworker.org">maass@socialistworker.org</a>.</P>


</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
