<html>
<head>

<title>
Maass: A World Worth Fighting For
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="5"><b>A World Worth Fighting For</b></font></p>
<p><font face="Times New Roman, Times, serif" size="2"><b>By Alan Maass</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | September 16, 2002</font></p>

<font face="Times New Roman, Times, serif" size="3"><P>It's not hard to convince most people that there's something wrong with society. That much stares us in the face from the newspaper--the horrifying drive toward war and violence; the corruption of an economic system organized around corporate greed; two-faced political leaders in the pockets of corporations.</P>
<P>The difficulty is agreeing on what precisely is wrong--and even more so, what to do about it. Can society be changed? What kind of change? Who would do the changing? By what means? </P>
<P>Actually, for people who consider themselves on the left--including, I'd wager, most people reading this debate, since you'll have tracked it down on ZNet or <I>Socialist Worker </I>Online--we probably have similar answers. Between Michael Albert and myself, for example, I think there's a lot of agreement. We share both criticisms about capitalism and a commitment to struggles against poverty, oppression and injustice. And we have a fairly similar idea of what a future society might look like.</P>
<P>Nevertheless, this debate on Marxism's relevance has found us far apart. Naturally, Michael focused on the areas where he disagrees, and I disagreed with his critique. Still, I think the discussion has been valuable, because it can help clarify the issues involved for others to judge for themselves. And it's to Michael's credit that he took up this exchange--especially with the scarcity of any serious discussion of ideas and strategies, Marxist or otherwise, on the left.</P>
<P>What's become clearest to me over the course of the discussion is how much the differences between us depend on our understanding of Marxism. We both seem to start from a commitment to similar ideals, such as democracy and liberation. I think that Marxism, both as a tool for analyzing society and in the vision of working-class struggle and transformation that it offers, is a distillation of these commitments. Michael thinks that Marxism, though its rhetoric may sound good, ultimately upholds the interests of a "coordinatorist" elite.</P>
<P>I've argued at length in previous contributions why I disagree. But for these concluding statements, Michael and I decided to focus on a positive statement of our positions. So I want to return to how Marxists answer the question of "what to do about it"--above all, Marxism's commitment to liberation and workers' power, won by the act of the working-class majority itself. </P>

<B><P>The principle of self-emancipation</P>
</B><P>Debates about Marxism and socialism have often come down to a question of the meaning of the terms--even back in Karl Marx's day. In fact, Marxism came into being as a distinct brand of socialism in part as a response to what Marx and his partner Frederick Engels believed were the inadequacies of other theories of socialism. </P>
<P>Specifically, Marx and Engels were critical of the utopianism of the socialists who came before them. Saint-Simon, Charles Fourier and Robert Owen could critique the problems of industrial capitalism as it developed in the 19th century, but their response was mainly to counterpose an ideal world to what existed around them. There was no connection between the aim of their imagined utopia and their understanding of how to achieve it. This inevitably meant an elitist attitude. As Owen--the best of the bunch in many ways--put it: "This great change...must and will be accomplished by the rich and powerful. There are no other parties to do it." Owen's goal was "[governing or treating] all society as the most advanced physicians govern and treat their patients in the best arranged lunatic hospitals."</P>
<P>Marx reacted sharply against the paternalism--the conceit of "socialists" who claimed to have "the solution to all riddles lying on their desks, and the stupid outside world had only to open its mouth wide for the roasted pigeons of absolute knowledge to fly into it." But he and Engels also began to outline a different way of thinking about socialism, focused not on "dogmatically anticipating" the new world, but rather on "finding the new world" in what existed in the old. Engels later summarized the point this way: "Since the historical appearance of the capitalist mode of production, the appropriation by society of all the means of production has often been dreamed of...as the ideal of the future. But it could become possible, could become a historical necessity, only when the actual conditions for this realization were there. Like every other social advance, it becomes practicable, not by men understanding that the existence of classes is in contradiction to justice, equality, etc., not by the mere willingness to abolish these classes, but by virtue of certain new economic conditions."</P>
<P>Specifically, two "new economic conditions" were key for Marx and Engels. One was the development of human productive power to the point that a society of abundance is possible. Socialism can't exist in conditions of scarcity, because unless there's enough to go around, there's certain to be a scramble over who gets what. Capitalism, according to Marx and Engels, raised human knowledge and technology to the point where the potential exists to eliminate poverty, hunger, homelessness and so on.</P>
<P>But abolishing poverty means getting rid of the system that causes it, and that requires a social force capable of overthrowing it. This is why the second "new economic development" of central concern to Marx and Engels was the creation of the working class--the first majority class of toilers in history with the social power to overturn the status quo and the collective interest in establishing a new society not divided between rulers and ruled. </P>
<P>Marx and Engels focused on how the working class--unlike other toiling classes, such as the peasantry--is forced by the conditions of work to cooperate, laying the basis for cooperation in resistance as well. Moreover, because capitalism brings workers together in large numbers, it's easier for workers to discuss and make collective decisions about what needs to be done. And the cooperative arrangements of work lay the basis for how workers can take control, ultimately over the whole of society.</P>
<P>Thus, rather than imagining a better world disconnected from the question of how to get there, the whole stress of Marxism is on how the process of "getting there" determines the shape of the better world. At the heart of the question is how the working-class majority can prepare itself for the future. As Marx put it, "Revolution is necessary not only because the ruling class cannot be overthrown in any other way but also because the class overthrowing it can only in a revolution succeed in ridding itself of all the muck of ages and become fit to found society anew." </P>
<P>So in spite of Marx and Engels' famous impatience for the day of the revolution to arrive, they insisted that no shortcuts devised by a minority--however well-meaning--could be an effective substitute for the masses of workers learning their own power and developing the organization to use it. </P>
<P>This basic principle--that "the emancipation of the working class must be the act of the working class itself"--runs back to the founding of Marxism. Not that there haven't been disagreements among people who called themselves Marxists. Even in Marx's lifetime, a new deterministic interpretation of "Marxism" had begun to develop--in which the transition from capitalism to socialism was seen as inevitable. More recent, of course, has been the association of Marxism with the Stalinist regimes of the ex-USSR and its imitators.</P>
<P>I've discussed that question in particular at great length, and could go on doing so. But in fact, the whole matter can be reduced to a simple question: Do workers control society? The American socialist Eugene Debs summarized the point, echoing Marx's words: "In the struggle of the working class to free itself from wage slavery, it cannot be repeated too often that everything depends on the working class itself. The simple question is: Can the workers fit themselves, by education, organization, cooperation and self-imposed discipline, to take control of the productive forces and manage industry in the interest of the people and for the benefit of society? That is all there is to it."</P>

<B><P>What is to be done?</P>
</B><P>Debs stated the first principle of Marxism very concisely. But of course, that's not <I>all </I>there is to it. Marx's emphasis on the need for workers to become "fit to found society anew" begins to get at an important contradiction--not in Marx's ideas, but a contradiction in real life. On the one hand, the action of human beings is the driving force of history. "History does nothing," Marx wrote, "it possesses no immense wealth, it wages no battles. It is man, real living man, that does all that." On the other hand, the circumstances in which people act are constrained by the existing structure of society. Marx summed up the conflict in a famous passage from the <I>Eighteenth Brumaire of Louis Bonaparte: </I>"Men make their own history, but they do not make it just as they please; they do not make it under circumstances chosen by themselves, but under circumstances directly encountered, given and transmitted from the past."</P>
<P>If the working class majority in society has the power and the interest in overthrowing capitalism and creating a new society, how does it come to this conclusion collectively? Obviously, for Marx, the process of struggle itself is crucial. But struggles don't develop evenly and inevitably. There are always some groups of workers who, on the basis of greater experience or more extensive discussions, are more advanced. Nor is the process static. People's consciousness changes under the impact of events--victories and defeats in struggle, the overall political climate, etc.--going both forward and backward. And at the level of individuals, there are countless subjective factors--some directly related to the weight of capitalist society on them and some not--that set people apart, making it inevitable that some feel more confident to lead than others. </P>
<P>To ignore these factors on the basis of the quite correct view that all people's consciousness develops through struggle means being resigned to passivity until a perfectly united movement develops.</P>
<P>This, in very brief terms, is the heart of the organization question for Marxists--how to apply the principles and analyses of Marxism to the needs of the real world. The most important conclusions on this subject were drawn by the Russian revolutionary Lenin, who was the first Marxist to generalize an understanding of the need for a vanguard party of socialists to discuss and decide how to bridge this gap between analysis and action. Such a party, Lenin believed, would bring together the activists in the workers' movement--not primarily intellectuals, as has been claimed by Lenin's critics, but working-class militants--most committed to the struggle and with the clearest idea of what needs to be done to advance the movement.</P>
<P>Now this isn't the time to open up a debate about Leninism. That would take another couple exchanges to flush out. There are all sorts of misconceptions about Lenin's arguments--dating back to disagreements about Lenin's own actions during the Russian Revolution, but also related to the crimes of Stalinism that were justified in the name of Leninism. I can't deal with these questions here--though I'll recommend an article for readers who would like to see a defense of Leninism against the kind of critique that Michael Albert made in books referred to in this exchange. The article is <a href="http://www.isreview.org/issues/24/hallas.shtml" target="_blank">"Toward a Revolutionary Socialist Party"</a> by the British Marxist Duncan Hallas, reprinted in the <I>International Socialist Review. </I></P>
<P>My reason for raising this is that I think the most important challenge for Marxists today isn't confronting some profound theoretical question, but making Marxism relevant from day to day, in often quite modest struggles. In fact, this "organization question" isn't exclusive to Marxists. Consider this passage from a recent book on strategies for the left: "With social change, the winning logic shouldn't be for those who develop unequally and are 'faster' to leave the slower pack behind and cross a finish line first. The only way to win the 'social change race' is for the whole pack to cross all together and as fast as this whole can be induced to go. The fastest and otherwise best activists need to stay with the pack, working to increase its speed as a whole, even if it means holding themselves back a bit at times."</P>
<P>The author of these words is Michael Albert. Though he might run screaming from the room to hear it, I think that this passage raises the exact question that genuine Leninism is addressed to: How should a vanguard relate revolutionary ideas to wider numbers of people, showing by the example of their ideas and organization that they have an alternative that can both win smaller or larger changes in the way that the existing society operates--and also build the confidence and experience of people for the larger struggle of transforming society altogether? </P>
<P>Again, this is an important discussion that couldn't be exhausted here, even if we had the time. But the very first thing to say is that there can't be an individual answer. You can be the finest Marxist thinker, with a perfect understanding of the dynamics of capitalist society. But unless you're involved in a Marxist organization--one committed to organizing the most advanced activists in a group based on both democracy in debate and discussion, and then a centralized commitment to carrying out the decision of the majority--it's impossible to put the best analysis to practical use in the struggle for a better world. </P>

<B><P>The future socialist society</P>
</B><P>One of Michael's chief criticisms of Marxism during this debate has been that it doesn't offer a concrete institutional vision of a future society. And it is true that Marx and Engels never drew a blueprint for socialism. But throughout the genuine Marxist tradition--from Marx to the present day--there is a commitment to a society in which the working-class majority rules on the basis of democracy and mass participation. To understand <I>how, </I>Marxists have looked not to their imaginations, but to the answers developed by workers in the course of struggle.</P>
<P>The most important turning point in Marx's ideas on this question came in 1871, after the Paris Commune gave Marx an example of what a society run by the working-class majority could look like. As he said in the <I>Civil War in France, </I>"It was a thoroughly expansive political form, while all previous forms of government had been emphatically repressive. Its true secret was this. It was essentially a working class government, the product of the struggle of the producing against the appropriating class, the political form at last discovered under which to work out the economic emancipation of labor."</P>
<P>When the Russian revolutionary Lenin focused on the question of what form a workers' state would take, his pamphlet <I>State and Revolution </I>drew on two examples: the Paris Commune, but even more so, the experience of the soviets (the Russian word for councils), which developed spontaneously out of the 1905 revolution in Russia, and again in 1917.</P>
<P>The soviets first appeared as workplace committees organized for a wave of battles over economic issues. But the need to respond to wider political questions--most obviously, the use of massive repression by the Tsar--led the councils to make links locally and then regionally. As Lenin described it, "Soviets of Workers Deputies are organs of direct mass struggle. They originated as organs of the strike struggle. By force of circumstance, they very quickly became the organs of general revolutionary struggle against the government. The course of events and the transition from a strike to an uprising irresistibly transformed them into organs of an uprising." </P>
<P>Here was the form, Lenin and the other revolutionary socialists of Russia recognized, through which workers could exercise power democratically. There was a direct connection between the economic power of workers and a new political system based on representation from the factory floor. The level of grassroots participation was obvious from the ratio of delegates to those they represented: one delegate for every 500 workers. And like the Paris Commune, delegates were immediately recallable and paid no more than an average workers' wage.</P>
<P>John Reed, the American socialist and author of <I>Ten Days That Shook the World</I>, captured the spirit of the soviets: "As all real socialists know, and as we who have seen the Russian Revolution can testify, there is today in Moscow and throughout all the cities and towns of the Russian land a highly complex political structure, which is upheld by the vast majority of the people and which is functioning as well as any newborn popular government ever functioned...The Soviet state is based upon to the Soviets--or Councils--of Workers' and Peasants' Deputies...No political body more sensitive and responsive to the popular will was ever invented. And this was necessary, for in time of revolution, the popular will changes with great rapidity."</P>
<P>Compare Reed's description of the way that the soviets served as forums for intense debate and decision-making with what the soviets became under the Stalinist bureaucracy--lifeless rubber stamps for the rule of tyrants. Nothing more starkly shows the difference between the Russian Revolution's promise of a different world, based on mass democracy and participation, and the grim reality following the isolation and defeat of the revolution a few short years later.</P>
<P>But what survived the counterrevolution in Russia was the model of workers' rule itself. The council system formed spontaneously by Russian workers has arisen again and again in the biggest working-class upheavals--the Spanish revolution of 1936-37, the Hungarian revolt against Stalinist repression in 1956, the cordones of Chile in 1973, the workers' commissions in Portugal in 1974-75, the shoras during the Iranian revolution of 1979.</P>
<P>Once again, much more could be said about this question. Two articles available on the Internet are helpful in this discussion--a <I>Socialist Worker </I>story by Amy Muldoon called <a href="http://www.socialistworker.org/2002-2/421/421_08_WorkersCouncils.shtml" target="_blank">"How will workers run society?"</a> and Ahmed Shawki's <a href="http://www.isreview.org/issues/03/russian_revolution.shtml" target="_blank">"Eighty Years Since the Russian Revolution"</a> in the <I>International Socialist Review</I>.</P>
<P>But I'd like to end with this point about the spirit of workers' power. Much can be said about the accomplishments of the Russian Revolution, however short-lived--from ending Russia's participation in the carnage of the First World War, to the first experiments in workers' control of production, to the active effort to emancipate women. But what is at least as impressive is the way in which the revolution brought to life masses of people condemned to, at best, a life of long and anonymous labor. In the accounts of the revolution, you sense the expanding horizons of people taught all their life to be obedient and docile, who suddenly find themselves in a new world where what they think matters.</P>
<P>Krupskaya, a veteran member of the Bolsheviks and Lenin's wife, captured this in her memoirs: "The streets in those days presented a curious spectacle: everywhere, people stood about in knots, arguing heatedly and discussing the latest events...These street meetings were so interesting, that it once took me three hours to walk from Shirokaya Street to the Krzesinska Mansion. The house in which we lived overlooked a courtyard, and even here, if you opened the window at night, you could hear a heated dispute. A solider would be sitting there, and he always had an audience--usually some of the cooks, or housemaids from next door, or some of the young people. An hour after midnight, you could catch snatches of talk--"Bolsehviks, Mensheviks..." At three in the morning, "Miliukov, Bolsehviks..." At five--still the same street-corner meeting talk, politics, etc. Petrograd's white nights are always associated in my mind with those all-night political disputes."</P>
<P>That's the description of a world where ordinary human beings have come alive in a way they won't under capitalism. And that is a world worth fighting for. Today, in a society plagued by war and poverty, in a society where an alternative is desperately needed, Marxism offers a vision of what the world could be that is every bit as relevant today as it ever was.</P>

<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>Alan Maass is the editor of <I>Socialist Worker,</I> a weekly newspaper published by the International Socialist Organization. He can be e-mailed at <a href="mailto:maass@socialistworker.org">maass@socialistworker.org</a>.</P>


</font>
<p><font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a> | <a href="../MarxDebate.shtml">Return to the debate main page</a></font></p>
<p>&nbsp;</p>


<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
