<?php

/**
 * @file
 * Update functions for the SW module.
 */

/**
 * Removes image links to betteroffred.org and internationalsocialist.org.
 */
function sw_update_8000() {
  foreach (['%betteroffred%', '%internationalsocialist.org%'] as $keyword) {
    \Drupal::database()
      ->query("DELETE FROM {media__field_image_url} WHERE field_image_url_uri LIKE :keyword", [":keyword" => $keyword]);
  }
}
