<html>
<head>

<title>
"Uno tiene que tomar acci&oacute;n desde la base"
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="5"><b>"Uno tiene que tomar acci&oacute;n desde la base"</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">8 de febrero de 2002 | P&aacute;gina 3</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>JAMES PETRAS ha trabajado por los &uacute;ltimos dos a&ntilde;os con el movimiento de desempleados en Argentina y con el movimiento rural de trabajadores sin tierra en Brasil por m&aacute;s de una d&eacute;cada. El es el autor de numerosos libros sobre Am&eacute;rica Latina. El habl&oacute; a principios de enero con ALAN MAASS, el redactor de <I>Socialist Worker,</I> acerca del levantamiento.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3"><B><P>&#191;DE DONDE sali&oacute; la chispa para el levantamiento de diciembre?</P>
</B><P>LA FUERZA motriz de estas movilizaciones masivas tiene sus ra&iacute;ces en las actividades sostenidas y de gran escala del movimiento de los desempleados.</P>
<P>El movimiento de trabajadores desempleados ha estado ganando fuerza durante los &uacute;ltimos cinco a&ntilde;os. Pero en el &uacute;ltimo a&ntilde;o, se ha extendido a trav&eacute;s del pa&iacute;s y ha jugado un papel mayor en asegurar programas de subsistencia del gobierno y programas de obras p&uacute;blicas para por lo menos un sector de los desempleados.</P>
<P>Sus t&aacute;cticas consisten en paralizar la circulaci&oacute;n de bienes y el transporte. As&iacute; que los llamados piqueteros bloquean las carreteras m&aacute;s importantes para hacer sus demandas.</P>
<P>En el movimiento de los desempleados existe una preponderancia de mujeres, especialmente mujeres a la cabeza de su hogar, que ha crecido con el desempleo.</P>
<P>En algunas &aacute;reas, el desempleo es probablemente de 50 a 60 por ciento. Muchos de los piqueteros son trabajadores de f&aacute;brica con experiencia sindical. Muchos otros son j&oacute;venes que nunca han tenido un trabajo.</P>
<P>Ellos se organizan y bloquean las carreteras. El tr&aacute;fico se embotella, los camiones no pueden moverse, las f&aacute;bricas no pueden obtener sus suministros. Estos son los equivalentes funcionales de cuando los trabajadores de una f&aacute;brica ponen un alto al uso de sus herramientas. En este caso, en vez de la producci&oacute;n ser directamente parada, ellos paran las entradas de materia prima y la salida de productos procesados.</P>
<P>Entonces el gobierno puede mandar a la polic&iacute;a, en cuyo caso hay una confrontaci&oacute;n total. Hay gente que ha muerto, cinco o seis recientemente en el norte de Argentina.</P>
<P>Pero el temor del gobierno es que si las confrontaciones contin&uacute;an, las muchedumbres de los inmensos arrabales pueden sumarse al conflicto, y podr&iacute;an convertirlo en una mini guerra civil. Pero el gobierno generalmente--despu&eacute;s de amenazas y movilizaciones de la polic&iacute;a--negocia un acuerdo.</P>
<P>Estos acuerdos son discutidos por los participantes mismos. Ellos no delegan a ning&uacute;n l&iacute;der para ir al centro de la ciudad. Ellos hacen que el gobierno venga a las carreteras, y la gente all&iacute; discute lo que ellos deben exigir y lo que ellos deben aceptar.</P>
<P>Su experiencia con el liderazgo delegado es que &eacute;stos van el centro, se sientan en una habitaci&oacute;n grande con el gobierno o con la burocracia del sindicato, y usualmente son comprados. Los l&iacute;deres reciben alg&uacute;n soborno, a&uacute;n los l&iacute;deres militantes. O son atrapados en alg&uacute;n acuerdo tripartita, y la base es traicionada. Su actividad se trata de representaci&oacute;n directa, negociaci&oacute;n directa, acci&oacute;n directa.</P>
<P>Estas demostraciones han sido enormemente exitosas dentro de las &aacute;reas limitadas en que ellos operan. Pero recientemente, tan temprano c&oacute;mo septiembre del a&ntilde;o pasado, hubo dos reuniones nacionales que trataron de coordinar los comit&eacute;s de las diferentes ciudades y regiones y suburbios de Buenos Aries, y ellos crearon una clase de comit&eacute; coordinador.</P>
<P>Pero lo que ellos le ense&ntilde;aron a toda la poblaci&oacute;n es que uno no puede depender de los pol&iacute;ticos. Uno mismo tiene que tomar acci&oacute;n y desde debajo.</P>
<B><P>&#191;C&Oacute;MO FUE que las luchas de los piqueteros prepararon el camino para las demostraciones de diciembre?</P>
</B><P>PIENSO QUE ese esp&iacute;ritu comenz&oacute; a manifestarse, a&uacute;n en el centro de Buenos Aires, poco antes de este &uacute;ltimo levantamiento. Hubo varios casos donde quejas surgieron, y los comerciantes y otros decidieron cerrar las calles del centro de la ciudad.</P>
<P>Hab&iacute;a un debate inmenso dentro del movimiento, porque el supuesto liderato progresista del sindicato pens&oacute; que podr&iacute;a ganar el apoyo de la clase media bloqueando las calles principales pero permitiendo funcionar a las calles alternativas. Esto fue opuesto por los movimientos de desempleados m&aacute;s militantes, que dijeron que o se cierran todas las calles, o ninguna.</P>
<P>Este esp&iacute;ritu captur&oacute; la imaginaci&oacute;n no s&oacute;lo de trabajadores empleados y, por supuesto, de los j&oacute;venes, pero tambi&eacute;n de la empobrecida clase media baja, e incluso sectores m&aacute;s opulentos de la peque&ntilde;a burgues&iacute;a, c&oacute;mo comerciantes, peque&ntilde;os empresarios y otros que ten&iacute;an cuentas en los bancos.</P>
<P>Cu&aacute;ndo el gobierno confisc&oacute; finalmente los ahorros--billones de d&oacute;lares en ahorros--de la clase media, estas capas tambi&eacute;n se tiraron a las demostraciones en las calles. Esta es una clase media empobrecida y radicalizada.</P>
<P>Es un error pensar en &eacute;sta c&oacute;mo simplemente la clase media. Estas son gentes que perdieron todos sus ahorros. No tienen dinero pagar sus compras en el supermercado, o sus alquileres, o ir de vacaciones, o lo que sea. As&iacute; que a partir del ejemplo de los trabajadores desempleados, llegaron a juntarse varios sectores de la poblaci&oacute;n.</P>
<P>Hay una gran masa de desempleados que est&aacute; envuelta en alg&uacute;n tipo de econom&iacute;a informal. Hay trabajadores que no hab&iacute;an recibidos sus sueldos porque las cuentas de sus patrones hab&iacute;an sido congeladas. Y hay una gran masa de empleados p&uacute;blicos y peque&ntilde;os comerciantes y otros que forman un frente muy amplio contra los banqueros.</P>
<P>Los banqueros han podido sacar su dinero. Usando la compra de acciones argentinas en la bolsa de valores de Nueva York, ellos no han tenido ning&uacute;n problema en sacar su dinero fuera del pa&iacute;s.</P>
<P>Entonces esto es un fen&oacute;meno de clase, en que los trabajadores desempleados formaron un polo de atracci&oacute;n, atrayendo a los trabajadores, a la peque&ntilde;a burgues&iacute;a y otros sectores de la clase media a la pol&iacute;tica de la lucha extraparlamentaria--a la pol&iacute;tica de rechazar a los grandes partidos burgueses.</P>
<P>Esto, yo pienso, es la din&aacute;mica. Ahora, si esta clase media ser&aacute; un aliado estrat&eacute;gico--si ellos logran un arreglo que les permita sacar su dinero de los bancos--es algo que est&aacute; por verse.</P>
<P>Pero creo que el factor m&aacute;s importante en esto es que la acci&oacute;n de masas, m&aacute;s que todas las huelgas rituales de la burocracia sindical, llev&oacute; al desalojo de los l&iacute;deres principales del neoliberalismo y de los portavoces principales de los bancos de los EE.UU. y del imperialismo estadounidense en el gobierno en aquel momento.</P>
<P>Cada vez, estos fueron reemplazados por caras nuevas, todos dentro del marco del neoliberalismo. No hay forma de que la deuda sea pagada sin precipitar un levantamiento masivo--en cuyo caso, yo pienso, el sistema parlamentario burgu&eacute;s colapsar&aacute;, y quiz&aacute;s habr&aacute; una guerra civil, con el ej&eacute;rcito entrando en acci&oacute;n.</P>
<P>Nada en la prensa burguesa captura el grado de tensi&oacute;n y polarizaci&oacute;n que existe hoy en Argentina. En Argentina, los activistas y revolucionarios lo describen c&oacute;mo una situaci&oacute;n pre-revolucionaria. Y ciertamente el grado de hostilidad hacia todos los partidos burgueses y el grado de militancia de grandes masas de personas describir&iacute;a la situaci&oacute;n c&oacute;mo pre-revolucionaria.</P>
<P>No hay en este momento un partido revolucionario organizado con ra&iacute;ces y apoyo. Hay miles de activistas y militantes locales que se envuelven en estas actividades, y hay una amplia radicalizaci&oacute;n de conciencia entre cientos de miles, sino millones, de argentinos hoy--inaudito en tiempos recientes en Am&eacute;rica Latina.</P>
<P>Pero los peque&ntilde;os partidos de izquierda--todos los Trotskistas y los partidos marxistas--gastaron la mayor parte de sus recursos recientemente para elegir oficiales a un parlamento impotente. Y en ning&uacute;n lugar estos partidos--o la centro-izquierda, por supuesto--han ejercitado cualquier clase del liderazgo. Han estado fuera de vista. Ellos publican sus manifiestos; ellos venden sus peri&oacute;dicos. En ninguna de estas crecientes confrontaciones de masas--que alcanza las proporciones de cientos de miles en ciudades diferentes--ha habido alguna vanguardia organizada.</P>
<P>Hay militantes del movimiento de los desempleados, que tienen alguna experiencia de lucha callejera y preparaci&oacute;n. Program&aacute;ticamente, ellos est&aacute;n claros sobre sus demandas inmediatas--que son proyectos masivos de empleo, sueldos decentes, beneficios de desempleo, y por supuesto, el rechazo al pago de la deuda. Y algunos sectores claman por la renacionalizaci&oacute;n de los sectores estrat&eacute;gicos de la econom&iacute;a.</P>
<B><P>&#191;C&Oacute;MO VA ser el nuevo gobierno de Duhalde?</P>
</B><P>EL ACTUAL gobierno del Presidente Duhalde es claramente una provocaci&oacute;n. El es un hombre de la derecha, y &eacute;l organiz&oacute;, en el pasado, un aparato pol&iacute;tico de matones.</P>
<P>A pesar de lo que la prensa dice, &eacute;l es capaz de movilizar a luchadores callejeros derechistas--grupos cuasifascistas que pueden atraer a lumpenes y a algunos desempleados desorientados a retar por la hegemon&iacute;a de las calles y quitarle un poco de presi&oacute;n a la polic&iacute;a. Ya ha habido una confrontaci&oacute;n mayor, con la polic&iacute;a, por supuesto, tomando el lado de los matones peronistas de Duhalde.</P>
<P>Pero esto es, yo pienso, un ensayo. No va a haber un per&iacute;odo de luna de miel para Duhalde. Ahora, mientras hablamos, est&aacute;n ocurriendo demostraciones masivas en Argentina, y hay preparaciones para una muestra grande de fuerza cuando &eacute;l anuncie su programa econ&oacute;mico esta tarde.</P>
<P>M&aacute;s que ning&uacute;n otro acontecimiento [internacional] reciente, nosotros hablamos de un pa&iacute;s que tiene una larga tradici&oacute;n sindical, de acci&oacute;n colectiva. Las huelgas generales son m&aacute;s comunes en Argentina que en cualquier otro pa&iacute;s del mundo.</P>
<P>Este es el pa&iacute;s que hoy tiene la concentraci&oacute;n m&aacute;s grande de trabajadores industriales desempleados del mundo. Y tercero, este es el pa&iacute;s con el n&uacute;mero m&aacute;s grande de trabajadores desempleados organizados y comprometidos con la acci&oacute;n directa.</P>
<P>Pienso, que lo que es necesario o que hace falta en este contexto es un liderato pol&iacute;tico reconocido que pueda llevar este proceso din&aacute;mico hacia adelante a la creaci&oacute;n de un gobierno de trabajadores. Creo que la corriente lucha pondr&aacute; de relieve esta cuesti&oacute;n muy agudamente.</P>
<P>Debemos tener presente que el liderato en Washington no descansar&aacute; hasta que entierre este movimiento. Y pienso lo que quiz&aacute;s veamos es la preservaci&oacute;n de la fachada pol&iacute;tica civil y el regreso del ej&eacute;rcito c&oacute;mo un factor determinante en la pol&iacute;tica.</P>
<P>Y eso es c&oacute;mo tirar madera al fuego. C&oacute;mo vimos con la dictadura de 1976, esto requiri&oacute; 30,000 muertos y desaparecidos para enterrar al movimiento. Esta vez, hay muchos, muchos m&aacute;s activistas y militantes que los que hab&iacute;a en el apogeo de las movilizaciones de los 1960s y 1970s.</P>
<B><P>HABLASTE ACERCA de lo conservador de los l&iacute;deres obreros y de las huelgas generales "rituales". &#191;Pero no han jugado las uniones un papel en la resistencia?</P>
</B><P>UNO NO puede meramente hablar de una huelga general en Argentina. Hay huelgas generales, y hay huelgas generales. Y todos saben esto en Argentina. Uno puede hablar con un conductor de taxi, que, cuando uno le pregunta, "&#191;Qu&eacute; piensas de esta huelga general?", dir&aacute; que los bur&oacute;cratas la usan para disipar la presi&oacute;n.</P>
<P>Estas son eventos de un d&iacute;a sin movilizaciones activas u ocupaciones de f&aacute;bricas. Los patrones lo saben, y el gobierno lo sabe--que si ellos se sientan y cruzan los brazos por un d&iacute;a, todo volver&aacute; a la normalidad.</P>
<P>As&iacute; que tienen pocas consecuencias. Hay poca movilizaci&oacute;n y poco que lleve a activar a la clase y a crear conciencia de clase. Son decididas desde arriba, y son apagadas desde arriba.</P>
<P>Hay tres confederaciones sindicales en Argentina. El sindicato oficial es la CGT, que se ha aliado con cada gobierno desde que cay&oacute; la dictadura--e incluso lleg&oacute; a tener arreglos con la dictadura.</P>
<P>Est&aacute; la CGT-Moyano--la CGT disidente dirigida por Hugo Moyano, que ha sido cr&iacute;tico de la CGT oficial por estar tan cercanamente vinculada al gobierno. Pero en cambio, esta federaci&oacute;n es manejada por otro conjunto de bur&oacute;cratas que utilizan su oposici&oacute;n al status quo para presionar al gobierno a hacerle concesiones a sus miembros mientras se mantienen al margen de alg&uacute;n desaf&iacute;o estructural.</P>
<P>La tercera uni&oacute;n de importancia es la progresista CTA, que surgi&oacute; c&oacute;mo un rechazo a la CGT y que tiene muchos de los trabajadores del sector p&uacute;blico--trabajadores que no han recibido ning&uacute;n alivio tras el cierre y los recortes de servicios y los despidos de cientos de miles.</P>
<P>La burocracia del sindicato de Moyano ha estado m&aacute;s dispuesta a comprometerse con las huelgas generales y a movilizarse en torno a asuntos espec&iacute;ficos. Ellos usan much&iacute;sima ret&oacute;rica populista, pero negocian luego sobre asuntos m&aacute;s estrechos de car&aacute;cter seccional, constantemente negociando a espaldas de los trabajadores.</P>
<P>Esto es por lo que muchos sectores de la clase de trabajadora desconf&iacute;an de ellos, vi&eacute;ndolos esencialmente c&oacute;mo una oposici&oacute;n oportunista que es capaz de traer gente a las calles, pero que es tambi&eacute;n bastante capaz de sacarla de las calles.</P>
<P>La CTA ha sido el m&aacute;s activo y radical de los sindicatos, dirigida por la ATE, la uni&oacute;n de empleados p&uacute;blicos. Ellos han estado envueltos con los piqueteros y los desempleados.</P>
<P>Ellos han se&ntilde;alado asuntos estructurales muy importantes. Sin embargo, en ning&uacute;n momento han cuestionado el sistema capitalista. Adem&aacute;s, ellos tienden a enfrascarse en acciones militantes, y entonces retroceden y negocian. Ellos han estado conscientes de su posici&oacute;n c&oacute;mo empleados del estado--y por lo tanto est&aacute;n comprometidos a negociar con el estado pero m&aacute;s all&aacute; de palabras no se comprometen con el resto de la clase trabajadora.</P>
<P>Ellos dicen que debemos unificar a los desempleados con los empleados p&uacute;blicos. Pero la experiencia de los trabajadores desempleados con el liderato nacional de la CTA--y, particularmente, el de la ATE--ha sido que los desempleados se convierten en auxiliares. Y cuando las negociaciones verdaderas suceden, es sobre reducciones en empleo en el sector p&uacute;blico. Eso es por lo que los desempleados decidieron irse y organizarse por s&iacute; mismos.</P>
<P>Entonces, hay sectores poderosos de las uniones de empleados p&uacute;blicos, m&aacute;s sectores de la uni&oacute;n de maestros, que se han envuelto en la lucha de masas y en confrontaciones--y han sufrido algunas heridas y muertes a&uacute;n en las grandes movilizaciones.</P>
<P>Pienso que uno tiene que distinguir entre el liderato nacional--particularmente de la CTA y en menor grado del grupo de Moyano--y la gente com&uacute;n. Esto es especialmente cierto en las provincias, donde uno encontrar&aacute; sindicalistas muy militantes y muy radicales, inclusive l&iacute;deres locales, as&iacute; c&oacute;mo tambi&eacute;n de la base.</P>
<P>Por ejemplo, en C&oacute;rdoba, en Salta, y en Neuqu&eacute;n, donde la industria del petr&oacute;leo est&aacute; localizada, uno tiene un n&uacute;mero grande de activistas sindicales, algunos que han sido influenciados por los piqueteros, que se han unido a las luchas.</P>
<B><P>&#191;CU&Aacute;L ES la forma que toman los v&iacute;nculos entre los movimientos de desempleados y los miembros de base de las uniones?</P>
</B><P>TE PUEDO dar un ejemplo. Los trabajadores de un hospital en Neuqu&eacute;n protestaron por semanas, tratando de deshacerse de un director abusivo. Finalmente, el director llam&oacute; a la polic&iacute;a para que terminara el bloqueo que los huelguistas ten&iacute;an de la entrada al hospital.</P>
<P>La voz rod&oacute; hasta que lleg&oacute; a los desempleados. Ellos se montaron en sus autom&oacute;viles y autobuses--o cualquier transporte disponible--y llegaron all&iacute;, tantos c&oacute;mo 300. En menos de una hora, el director fue destituido, y los trabajadores del hospital eligieron a un director nuevo.</P>
<P>Esto es un ejemplo de la clase de solidaridad entre los trabajadores de la salud y los piqueteros que ocurre frecuentemente en el interior del pa&iacute;s. Yo pienso que esto es un desarrollo muy prometedor. Pero tiene que ser visto en el contexto.</P>
<P>Las declaraciones que vienen de los lideratos generales no son representativas de lo que ellos hacen--y ciertamente no corresponden a las clases de alianzas que se est&aacute;n levantando a nivel de base. Esto es lo significativo.</P>
<P>No quiero decir que no haya l&iacute;deres individuales en alg&uacute;n sector particular de la industria que haya demostrado militancia. Pero la militancia de hoy tiene que ser entendida en un sentido muy concreto. &#191;D&oacute;nde estaban a los l&iacute;deres de la ATE y la CTA durante las protestas del 20 de diciembre?</P>
<P>Los militantes me dicen que estos estaban debajo de su cama. Ellos brillaban por su ausencia en esos d&iacute;as magn&iacute;ficos que derribaron al gobierno de de la R&uacute;a. Ellos no ense&ntilde;an la cara, c&oacute;mo dicen en Argentina. Y eso es muy importante, porque la acci&oacute;n dice mucho m&aacute;s que los discursos y los programas.</P>
<B><P>&#191;EN DONDE figuran los trabajadores industriales en este panorama del movimiento obrero?</P>
</B><P>EL GRUESO de los trabajadores industriales est&aacute; hoy desempleado. Ellos sol&iacute;an ser el 40 por ciento de la fuerza laboral. Hoy en d&iacute;a son menos del 20 por ciento.</P>
<P>Tenemos que pensar de los desempleados no c&oacute;mo alg&uacute;n tipo de vendedores ambulantes urbanos pobres. Estamos hablando de Argentina. Hablamos de gente que trabajaba en plantas de autos, que eran trabajadores del acero, que trabajaban en la metalurgia y la mec&aacute;nica. Cu&aacute;ndo habl&eacute; en una reuni&oacute;n en Argentina en mayo pasado, conoc&iacute; a much&iacute;simos trabajadores que ten&iacute;an experiencia en los sindicatos.</P>
<P>Y lo que es a&uacute;n m&aacute;s interesante son las esposas de los que fueron trabajadores industriales. Una de las cosas que he notado es la militancia y los niveles altos de participaci&oacute;n de las esposas de los trabajadores industriales--esposas que han tomado a&uacute;n m&aacute;s responsabilidades familiares porque sus esposos han llegado a desorientarse, en parte a causa de estar desempleados por tanto tiempo.</P>
<P>Las mujeres son quienes los empujan a unirse a la l&iacute;nea de piquete--a llegarse all&iacute; y estar activos para conseguir un trabajo. Porque si uno no est&aacute; en el bloqueo de la carretera, uno no va a estar all&iacute; para conseguir un trabajo cuando la asamblea re&uacute;na.</P>
<P>Para entender al movimiento sindical, pensemos que [John] Sweeney [presidente de la confederaci&oacute;n sindical de los EE.UU., la AFL-CIO] y el sector com&uacute;n y corriente de la AFL-CIO estar&iacute;an en la CGT. La centro-izquierda de la AFL-CIO estar&iacute;a probablemente con Moyano, el disidente. Muy pocos sindicalistas estar&iacute;an en la CTA. Y por supuesto, la secci&oacute;n militante de la CTA ser&iacute;a totalmente for&aacute;nea al sindicalismo estadounidense--o inclusive a la mayor parte del sindicalismo europeo contempor&aacute;neo.</P>
<P>Tenemos que poner esto en perspectiva. La acci&oacute;n de masas y las confrontaciones de masas que comenzaron el 20 hicieron m&aacute;s para cambiar la agenda pol&iacute;tica y la fisionom&iacute;a del gobierno que todas las huelgas generales y las protestas simb&oacute;licas de los sindicatos en los &uacute;ltimos cinco o diez a&ntilde;os. Las huelgas generales son importantes cuando tienen un contenido social--cuando los trabajadores ocupan las f&aacute;bricas y salen y confrontan al gobierno.</P>
<P>Esto es lo que yo pienso que estos movimientos de los desempleados tienen. Hoy estos son gente desesperada. Estos no son trabajadores empleados que luchan contra cierta reducci&oacute;n. Ellos han perdido todos sus ahorros. Ellos llevan sin trabajo mucho tiempo. Muchos de ellos no han visto carne por meses. Esto es toda una masa desesperada de gente que abarca varias clases--pero en donde las demandas de clase son articuladas.</P>
<B><P>&#191;CU&Aacute;LES SON las perspectivas para el desarrollo de una organizaci&oacute;n o un partido que pueda adelantar las grandes cuestiones pol&iacute;ticas?</P>
</B><P>EL PRINCIPIO organizativo de la lucha ha sido el hambre. Eso es lo que instig&oacute; el saqueo de los supermercados en diciembre, y la organizaci&oacute;n de los bloqueos de carreteras antes de eso. Hab&iacute;a lo quiz&aacute;s podr&iacute;amos llamar demandas de sobrevivencia pidiendo trabajos--a&uacute;n trabajos de baja paga c&oacute;mo los de obras p&uacute;blicas que pagan unos $200 al mes--y alimentos.</P>
<P>A partir de esa lucha y organizaci&oacute;n, algunos de los trabajadores m&aacute;s avanzados en el movimiento--con experiencia sindical y alguna experiencia pol&iacute;tica--comenzaron a traer otros asuntos, asuntos estructurales c&oacute;mo el repudio de la deuda, inversiones p&uacute;blicas de gran escala y la renacionalizaci&oacute;n de las industrias estrat&eacute;gicas.</P>
<P>Hay marxistas y socialistas que han estado envueltos en algunas de estas organizaciones. Pero ellos est&aacute;n all&iacute; c&oacute;mo militantes dentro de estos movimientos. Ellos no son, ciertamente, la fuerza dominante. Y ellos ciertamente no tienen la influencia en estos movimientos para dar liderato y direcci&oacute;n--por lo menos por el momento.</P>
<P>Pienso que lo que tenemos son tres niveles. Uno es la base, que sufre una privaci&oacute;n horrenda. Este es un pa&iacute;s que es uno de los productores de carne y grano m&aacute;s grandes del mundo, y los trabajadores pasan hambre. Ellos no tienen carne de res, no tienen las pastas, no pueden alimentar a sus hijos--y ellos ven los trenes transportando las decenas de miles de toneladas de carne hacia Buenos Aires para ser embarcadas a Europa.</P>
<P>Esto es una provocaci&oacute;n. Aqu&iacute; est&aacute; una de las &aacute;reas m&aacute;s f&eacute;rtiles del mundo con un desempleo en gran escala y con hambre--inaudito en la historia de Argentina.</P>
<P>Eso es un nivel. El segundo nivel es el liderato emergente, que tiene una concepci&oacute;n de los cambios estructurales que nosotros podr&iacute;amos llamar anti-capitalista y populista. Y entonces tenemos un tercer nivel, en que los asuntos del socialismo y de una revoluci&oacute;n entran en juego.</P>
<P>Mientras el gobierno contin&uacute;a evitando medidas que alivien los problemas, cada vez m&aacute;s el poder dentro de estas movilizaciones se mueve hacia la izquierda. Hace un mes, el asunto de la repudiaci&oacute;n de la deuda extranjera era un asunto izquierdista. Hoy, es com&uacute;n y corriente. El asunto de grandes proyectos de obras p&uacute;blicas era un asunto izquierdista. Hoy, tambi&eacute;n se ha hecho com&uacute;n y corriente.</P>
<P>La renacionalizaci&oacute;n de industrias estrat&eacute;gicas b&aacute;sicas ten&iacute;a un grupo muy peque&ntilde;o de partidarios. Hoy, est&aacute; ganando decenas de miles de adeptos. La intervenci&oacute;n en los bancos era un asunto de una minor&iacute;a. Hoy, ha llegado a ser un asunto principal.</P>
<P>As&iacute; que todo el debate pol&iacute;tico se ha movido hacia la izquierda, seg&uacute;n la izquierda comienza a ganar hegemon&iacute;a ideol&oacute;gica. Pero son las ideas, no una izquierda organizada.</P>

<?php include "../../legacy-includes/BottomNavLinksObrero.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdObrero.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
