<html>
<head>

<title>
Victoria en el piquete
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<font face="Times New Roman, Times, serif" size="4">Obreros inmigrantes en Chicago logran...</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>Victoria en el piquete</b></font><p>
<font face="Arial, Helvetica, sans-serif" size="2">17 de agosto de 2007</font><p>

<font face="Times New Roman, Times, serif" size="3">LEE SUSTAR y ORLANDO SEP&Uacute;LVEDA reportan sobre la victoriosa huelga de trabajadores inmigrantes en Chicago que pararon labores despu&eacute;s de ser amenazados con despido por su estatus migratorio --y sus implicaciones para el movimiento por los derechos laborales y del inmigrante.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">LA NOTABLE victoria de los obreros inmigrantes en huelga, sin sindicato, contra la f&aacute;brica de jab&oacute;n Cygnus Corp., al sur de Chicago, termin&oacute; tan inesperadamente como comenz&oacute; hace dos semanas, el 10 de agosto, con docenas de trabajadores llenando la oficina de una agencia de empleo temporal y votando para aceptar la oferta de la agencia de reenviarlos a la planta sin represalias, y con las amenaza de cesaci&oacute;n en su contra cancelada.<p>
Estos trabajadores inmigrantes mexicanos prevalecieron sobre la gerencia de Cygnus, apoyada por su casa matriz, Marietta Corp., fabricante de jabones y detergentes con marcas de tienda para minoristas tales como Wal-Mart, Target y Walgreens, y por Ares Management, una firma accionista privada que controla Marietta y que est&aacute; valorada en $16 mil millones.<p>
La huelga en Cygnus fue contra toda Am&eacute;rica Incorporada, una lucha con muchas inciertas probabilidades.<p>
Sin embargo, no hubo vacilaci&oacute;n cuando los trabajadores decidieron parar contra los planes de la gerencia de despedir a cualquiera cuyo estatus migratorio no pudiera ser verificado antes del 10 de agosto.<p>
Cygnus utiliz&oacute; las cartas No-Match --una notificaci&oacute;n del gobierno indicando que los n&uacute;meros de Seguro Social en archivo no concuerdan con &eacute;sos dados por los empleados --para amenazar los trabajos de sus pocos trabajadores permanentes.<p>

<table width="270" align="right"><tr><td>
<table width="258" cellpadding="12" cellspacing="0" align="right" border="2" hspace="8" bordercolor="006699" bgcolor="#FFCC66"><tr><td>
<font face="Arial, Helvetica, sans-serif" size="4" color="#990000"><b>What else to read</b></font><p>
<font face="Arial, Helvetica, sans-serif" size="2">Los obreros de Cygnus a&uacute;n necesitan tu ayuda financiera despu&eacute;s de sobrevivir su paro sin beneficios de huelga. Haz tu cheque o money order a Chicago Worker's Collaborative (con "Cygnus Workers" en la l&iacute;nea de memo), y env&iacute;alo a: Comit&eacute; Solidario con los Trabajadores Cygnus, c/o Chicago Workers Collaborative, P.O. Box 08048, Chicago, IL., 60608. Llama al 773-653-3664 para m&aacute;s informaci&oacute;n.
</td></tr></table>
&nbsp;<p>
</td></tr></table>

<font face="Times New Roman, Times, serif" size="3">Por su parte, los trabajadores temporales fueron dichos que la compa&ntilde;&iacute;a cambiar&iacute;a a otra agencia, y que ah&iacute; ellos tendr&iacute;an que re-verificar su estatus. Amenazas similares ciernen sobre los trabajadores inmigrantes a trav&eacute;s de EEUU, con el gobierno poniendo en ejecuci&oacute;n nuevas reglas para las cartas No-Match, bajo las cuales &eacute;stas se podr&aacute;n usar como argumentos para la cesaci&oacute;n del empleo, o peor.<p>
Patrones a trav&eacute;s del pa&iacute;s ya han comenzado a usar las cartas No-Match como pretexto para despedir a sus trabajadores. La gerencia de Cygnus indudablemente sinti&oacute; que podr&iacute;a hacer lo mismo, habiendo por largo tiempo tenido a sus obrero trabajando por el salario m&iacute;nimo, o un poco m&aacute;s, y sin beneficios.<p>
En cambio, Cygnus fue golpeada por una huelga casi total, con animados piqueteros, y con cada vez mayor apoyo solidario, incluyendo la promesa de un sindicato para organizarlos. Una operaci&oacute;n rompe huelga se desinfl&oacute;, con m&aacute;s y m&aacute;s camiones saliendo de la planta sin carga. Los pocos a&uacute;n trabajando dentro de la planta informaban a los huelguistas sobre la fuerte ca&iacute;da de la producci&oacute;n.<p>
As&iacute;, casi dos semanas despu&eacute;s de provocar la huelga, la gerencia invitaba a los empleados permanentes a una reuni&oacute;n, en la que despu&eacute;s de cuatro horas de negociaciones, hizo una oferta: &iquest;Volver&iacute;an ellos trabajar con la misma paga, pero con todas las amenazas de terminaci&oacute;n retiradas?<p>
Los trabajadores no dijeron s&iacute;. Despu&eacute;s de todo, no estaban en las negociaciones por ellos mismos, sino como representantes elegidos por todos los huelguistas. Dijeron al jefe de Cygnus, John White, que volver&iacute;an hablar con &eacute;l una vez que reportaran al resto de los trabajadores.<p>
Manuel, un empleado permanente, propuso una reuni&oacute;n en un parque p&uacute;blico cercano para discutir el acuerdo. All&iacute;, Edith, tambi&eacute;n permanente y el l&iacute;der de la huelga, dijo as&iacute;: "No hay permanente o temporal --somos todos trabajadores."<p>
Mart&iacute;n Unzueta, organizador de Chicago Workers Collaborative y consejero de los trabajadores, propuso ir a la ma&ntilde;ana siguiente, 7:30 AM, a la agencia temporal, Total Staffing, para exigir el mismo acuerdo que los empleados permanentes hab&iacute;an conseguido de Cygnus. Los trabajadores volver&iacute;an a la obra todos, o ninguno.<p>
La agencia temporal Total Staffing de hecho ya hab&iacute;a preparado una carta ofreciendo a cada individuo la oportunidad de volver a trabajar a Cygnus. Pero para los jornaleros --los que era 110 de los 118 trabajadores en la planta, muchos de los cu&aacute;les hab&iacute;an estado en el trabajo por a&ntilde;os --el acuerdo no estaba a&uacute;n cocinado. Ten&iacute;a que ser votado primero.<p>
Haciendo una un&aacute;nime muestra de manos en la oficina del sur de Chicago, todo lo que la ansiosa gerencia de Total Staffing pudo hacer fue ordenar reporteros y activistas solidarios a salir. Sin embargo, el encargado no se atrevi&oacute; a pedir que los empleados permanentes salieran. Se quedaron ah&iacute; para discutir la oferta, votaron, y luego intercambiaron congratulaciones.<p>
Una huelguista, Julia, explic&oacute; c&oacute;mo la unidad entre los trabajadores de Cygnus y la solidaridad de otros crearon esta victoria. "Nos fuimos a la huelga, podr&iacute;as decir, con nuestros ojos cerrados, pero ahora sabemos que hay gente en que podemos contar. Y que los dem&aacute;s no piensen que no se puede, por que s&iacute; se puede".<p>
Como un trabajador temporal que ha trabajado en la planta por 11 meses, Ignacio, lo puso, "una de las lecciones es que la unidad nos hace fuertes. Aunque &eacute;ramos simples empleados, hicimos que una gran compa&ntilde;&iacute;a temblara y se moviera. Esta victoria es para nosotros los trabajadores, pero tambi&eacute;n para toda la clase obrera y para todos los grupos comunitarios que nos dieron su apoyo".<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">DE HECHO, la ayuda de la comunidad hacia los trabajadores de Cygnus primero tom&oacute; forma hace m&aacute;s que un a&ntilde;o, cuando ellos hicieron contacto con j&oacute;venes activistas pro-inmigrante de la Coalici&oacute;n de Sur Este de Chicago por los derechos de los inmigrantes (SECCIR).<p>
Una activista de SECCIR, Olga Bautista, hab&iacute;a trabajado en el departamento de contabilidad de Cygnus en 2004. Dos a&ntilde;os m&aacute;s tarde, ella pasaba volantes en el estacionamiento de la planta para convocar la masiva marcha del 10 de marzo de 2006, que produjo una ola de similares movilizaciones a trav&eacute;s del pa&iacute;s.<p>
Uno de los empleados permanentes, Edith, tom&oacute; un volante y pidi&oacute; sugerencias de que hacer respecto de la carta No-Match que la compa&ntilde;&iacute;a hab&iacute;a recibido algunos meses antes. Bautista la puso en contacto con Mart&iacute;n Unzueta de Chicago Workers Collaborative, que se centra en los derechos de los trabajadores inmigrantes.<p>
Unzueta entr&oacute; en contacto con la compa&ntilde;&iacute;a y les inform&oacute; que las cartas No-Match no indican estatus migratorio, y que no requieren acci&oacute;n alguna por parte del empleador. La gerencia dej&oacute; de hablar del tema.<p>
Mientras tanto, los trabajadores de Cygnus comenzaron a organizarse. Muchos asistieron a la protesta del 10 de marzo y casi todos salieron a la protesta del Primero de Mayo, luego que Edith negociara con la gerencia permiso para que los trabajadores fueran a marchar, a cambio de un d&iacute;a de trabajo en s&aacute;bado, para compensar por la producci&oacute;n perdida. "Tuvimos incluso un autobus para que los tomara de la planta y llevara a la marcha", Bautista record&oacute;.<p>
En los meses pr&oacute;ximos, los trabajadores discut&iacute;an m&aacute;s y m&aacute;s los problemas de la planta, no s&oacute;lo los bajos salarios, pero tambi&eacute;n las inseguras condiciones de trabajo. Seg&uacute;n un trabajador, la gerencia solamente les da guantes, pero no les da m&aacute;scaras o botas de trabajo a los que mezclan los productos qu&iacute;micos para los detergentes y jabones.<p>
Fuera de la planta, los tanques de almacenaje sin etiquetas contienen muchos productos qu&iacute;micos t&oacute;xicos, que a menudo se derramar de las tinas creando humos nocivos y pisos resbaladizos. Seg&uacute;n un reportaje en el <i>Chicago Sun-Times</i>, seis trabajadores fueron llevados a hospitales el pasado 18 de diciembre despu&eacute;s de que un material corrosivo se derramara sobre su piel.<p>
Accidentes m&aacute;s peque&ntilde;os son rutinarios, un trabajador dijo a los reporteros en el piquete y mostr&oacute; las quemaduras qu&iacute;micas en sus antebrazos, pecho y est&oacute;mago, donde el &aacute;cido hab&iacute;a quemado a trav&eacute;s de su ropa de calle. "Tienen las m&aacute;scaras, pero no nos las dan", dijo &eacute;l. Otro trabajador se quej&oacute; de s&oacute;lo hay una persona en la planta, de la gerencia, autorizada a llamar a la ambulancia en caso de emergencias.<p>
Otro bullente agravio es el racismo y la discriminaci&oacute;n. Los trabajadores en la planta se quejan de que la gerencia trata al mexicano abusivamente y que han tenido que aguantar abierto abuso racista. A una mujer la degradaron de su posici&oacute;n de supervisora porque no pod&iacute;a hablar ingl&eacute;s; su paga fue recortada.<p>
As&iacute;, este a&ntilde;o, mientras la protesta del Primero de Mayo se acercaba, el ambiente en Cygnus era diferente. Los trabajadores estaban m&aacute;s confiados, y comenzaron a pedir un aumento de sueldo. La gerencia tom&oacute; una l&iacute;nea m&aacute;s dura, negando a cualquier negociaci&oacute;n para que los trabajadores atendieran la marcha.<p>
Algunas semanas m&aacute;s adelante, la nueva jefa de recursos humanos, Mary Ann Vasquez, dijo a los empleados permanentes que ten&iacute;an que aclarar sus Seguros Sociales. Al mismo tiempo, inform&oacute; a los trabajadores temporales que tendr&iacute;an que cambiar de Total Staffing a una agencia de empleo diferente, Staffmark, y verificar con ellos su estatus migratorio.<p>
Cualquiera que no pudiera cumplir con eso para el 10 de agosto quedar&iacute;a sin trabajo. La respuesta de los trabajadores: una huelga indefinida.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">LA PLANTA de Cygnus es el m&aacute;s inveros&iacute;mil lugar para convertirse en el punto focal de solidaridad laboral. Nunca sindicalizada, la planta est&aacute; situada literalmente en el l&iacute;mite sur de la ciudad de Chicago, entre dos l&iacute;neas de ferro cargo altamente circuladas y que atoran regularmente el tr&aacute;fico local.<p>
Los camiones cargados, en su camino a los terraplenes pr&oacute;ximos, son a menudo forzados a esperar que los trenes pasen por 20 &oacute; 30 minutos. Cuando pueden finalmente rodar, los conductores, fuera de su horario, ponen el acelerador a fondo, levantando grandes nubes del polvo, mientras pasan sin echar un vistazo por enfrente de la planta.<p>
Pero el 30 de julio todo parec&iacute;a diferente. Camioneros sorprendidos miraban a una l&iacute;nea de piquete improvisada, con pancartas caseras y gritos. Muchos saludaron y hicieron sonar sus bocinas para demostrar su apoyo.<p>
Cada d&iacute;a, el piquete estaba mejor organizado --un horario fue hecho, alimento y bebidas donados fueron distribuidos, un altavoz fue usado para amplificar los gritos. Un n&uacute;mero de organizaciones, tambi&eacute;n caminaron la l&iacute;nea --incluyendo Chicago Workers Collaborative, SECCIR, el Centro Comunitario Juan Diego, la Organizaci&oacute;n Socialista Internacional, tanto como individuos activistas del movimiento pro-inmigrante.<p>
El due&ntilde;o de la casa vecina a la planta, s&iacute; mismo un inmigrante mexicano y el trabajador fabril, permiti&oacute; a los trabajadores tomar descansos del ardiente piquete sent&aacute;ndose en el sombreado umbral de su casa, almacenar sus materiales y utilizar su ba&ntilde;o.<p>
Los huelguistas pronto produjeron un volante donde explicaba a los conductores que llegaban a Cygnus de la huelga, pidi&eacute;ndoles no cruzar el piquete.<p>
Un camionero no sindicalizado, afro-americano, se sinti&oacute; obligado a hacer su entrega. Pero m&aacute;s tarde, vino a caminar en el piquete y prometi&oacute; su ayuda, identificando el movimiento por los derechos del inmigrante con las luchas por los derechos civiles. Su presencia tuvo un visible impacto en los huelguistas, especialmente luego de que la gerencia de Cygnus hab&iacute;a jugado la carta racial empleando a afro-americanos como rompehuelgas.<p>
En m&aacute;s de alg&uacute;n caso, sin embargo, los conductores Teamster miraron la l&iacute;nea de piquete, tomaron un volante, y siguieron conduciendo sin entregar su cargo, con las aclamaciones de huelguistas y de sus partidarios.<p>
Y el 1&ordm; de agosto, el cuarto d&iacute;a de huelga cuatro representantes de la Asociaci&oacute;n Internacional de los Maquinistas (IAM), distrito 8, aparecieron en el piquete. La uni&oacute;n hab&iacute;a sido llamada a la huelga por Ram&oacute;n Becerra, un funcionario de la Federaci&oacute;n de Chicago del Trabajo, que tambi&eacute;n dirige el cap&iacute;tulo de Chicago del Concejo Laboral para el Adelanto Latino Americano.<p>
Becerra hab&iacute;a escuchado de la huelga por medio Jorge M&uacute;jica, periodista y organizador laboral y una figura principal en el Movimiento del 10 de Marzo de Chicago. Mujica, as&iacute; como Unzueta, se hab&iacute;a convertido en consejero de los huelguistas y se hab&iacute;a movido r&aacute;pidamente para alistar la ayuda del sindicato.<p>
La dificultad fue que el distrito 8 no ten&iacute;a ning&uacute;n hispanoparlante entre su personal. Pero con M&uacute;jica como int&eacute;rprete, el representante de la uni&oacute;n Karl Sarpolis dej&oacute; claro que &eacute;sta apoyar&iacute;a a los trabajadores. "Sabemos c&oacute;mo estas compa&ntilde;&iacute;as discriminan contra las minor&iacute;as," dijo, dej&aacute;ndoles de una petici&oacute;n para unirse al sindicato. Cuando volvi&oacute; dos d&iacute;as m&aacute;s tarde, 90 trabajadores hab&iacute;an firmado la petici&oacute;n.<p>
En una junta en el piquete, los trabajadores eligieron un comit&eacute; provisional, en caso de que la uni&oacute;n consiguiera negociar con la gerencia, y decidi&oacute; celebrar una reuni&oacute;n con el sindicato para el s&aacute;bado 4 de agosto siguiente, en el Centro Juan Diego, al sureste de la ciudad.<p>
Unos 60 obreros llegaron a reunirse con los representantes del distrito 8 de IAM que dirige Carl Gallman, junto con Sarpolis y Armando Arreola, un representante del Local 701, un int&eacute;rprete ingl&eacute;s-espa&ntilde;ol de IAM que fue enviada por su presidente local, Bill Davis, para proporcionar ayuda adicional.<p>
Gallman, veterano de los d&iacute;as de gloria de IAM en los a&ntilde;os 70, reconoci&oacute; qu&eacute; estaba frente a &eacute;l: un cuarto lleno de huelguistas resueltos, militantes. El sindicato estaba dispuesto a organizar la planta--trabajadores temporales y permanentes por igual, dijo. "Vamos a ayudarles, ya sea que se unan al sindicato o no", declar&oacute;.<p>
Los representantes laborales y los huelguistas hab&iacute;an llegado independientemente a la misma conclusi&oacute;n: primero hab&iacute;a que negociar el regreso de los trabajos a cada uno, dejar los salarios y las condiciones para m&aacute;s tarde. Despu&eacute;s de que Gallman y los otros funcionarios de IAM se fueran, M&uacute;jica presidi&oacute; la reuni&oacute;n donde los trabajadores discutieron c&oacute;mo mejorar las l&iacute;neas de piquete y organizar la solidaridad.<p>
Aun cuando estos trabajadores de salario m&iacute;nimo hab&iacute;an estado una semana sin paga, y por supuesto no ten&iacute;an ning&uacute;n beneficio de huelga, nadie se quej&oacute;. La muy enfocada discusi&oacute;n fue sobre todo acerca de c&oacute;mo llevar la lucha adelante. Luego, los activistas solidarios empezaron a decir en alto lo que hab&iacute;an comenzado a pensar en privado: Esta huelga de hecho puede ser ganada.<p>
La victoria result&oacute; tener nada que ver con la ayuda del movimiento laboral. El lunes siguiente, Gallman del IAM llam&oacute; a Cygnus para hablar con la gerencia y para demandar el derecho de representar a los trabajadores. Mientras que esto ciertamente agreg&oacute; a la presi&oacute;n sobre la gerencia, su mensaje no fue devuelto, y el asunto no sigui&oacute; m&aacute;s lejos.<p>
El debate presidencial Dem&oacute;crata en Chicago, auspiciado por la AFL-CIO, ofreci&oacute; una nueva ocasi&oacute;n de alistar el apoyo del movimiento laboral. El Secretario-Tesorero de AFL-CIO, Rich Trumka, tom&oacute; una copia de la carta de recaudaci&oacute;n de fondos, expres&oacute; simpat&iacute;a, y dijo que el departamento de organizaci&oacute;n de la federaci&oacute;n dar&iacute;a seguimiento. Linda Chavez-Thompson, vice presidente ejecutivo de la federaci&oacute;n, dijo algo similar. Los l&iacute;deres laborales locales de Chicago tambi&eacute;n mostraron inter&eacute;s.<p>
Al final, sin embargo, los obreros ganaron sin mucha ayuda material de las uniones, donde a menudo la maquinaria organizacional est&aacute; oxidada y en el mejor de los casos, toma tiempo para engrasarla.<p>
Una notable excepci&oacute;n fue la Uni&oacute;n de Trabajadores Comerciales y de Alimentos (UFCW), Local 881, que prometi&oacute; $500. En retrospecci&oacute;n, los miembros del Comit&eacute; Solidario se dieron cuanta que debieran haber tomado una colecta directamente entre los 17.000 miembros de sindicatos que atendieron al debate.<p>
Pero mientras el movimiento laboral era lento en moverse, la organizaci&oacute;n de los trabajadores se desarroll&oacute; diariamente.<p>
Dos d&iacute;as despu&eacute;s de reunirse con IAM, varios huelguistas se unieron a los trabajadores de Dunkin Donuts despedidos despu&eacute;s de recibir cartas No-Match; esa tarde, treinta m&aacute;s vinieron a charlas con al abogado laboral Chris Williams, que proporciona consejo legal al Chicago Workers Collaborative.<p>
El 8 de agosto, la moral de los trabajadores subi&oacute; cuando el <i>Chicago Tribune</i> hizo de su lucha la historia principal en la portada, sum&aacute;ndose a la extensa cobertura de los medios hispanos. Una delegaci&oacute;n del centro comunitario Juan Diego se las arregl&oacute; para entrar a la planta a demandar una negociaci&oacute;n con los trabajadores, teniendo &eacute;xito donde un intento previo hab&iacute;a fallado.<p>
El mismo d&iacute;a, varios obreros se unieron a docenas de partidarios en un evento de recaudaci&oacute;n de fondos organizado por el Comit&eacute; Solidario con los Trabajadores de Cygnus, que se hab&iacute;a formado cuatro d&iacute;as atr&aacute;s. M&aacute;s de $1.300 fueron recaudados, incluyendo la donaci&oacute;n de UFCW --dinero que fue r&aacute;pidamente hecho bolsas con comestibles para familias de los apremiados huelguistas.<p>
Igual de notable fue el car&aacute;cter del evento mismo, que uni&oacute; a activistas pro-inmigrantes y laborales en una tarde llena de m&uacute;sica, mezclada con emotivos discursos por parte de los huelguistas y sus partidarios. Los artistas incluyeron Chuy Negrete, un muy bien conocido cantante local, el grupo de danza Azteca Nahuil, e Iv&aacute;n Res&eacute;ndiz, joven guitarrista cl&aacute;sico. El evento corri&oacute; hasta muy tarde con los asistentes cantando canciones populares de la revoluci&oacute;n mexicana, del movimiento laboral, y del repertorio popular mexicano.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">ESA MISMA noche, los negociadores elegidos por los trabajadores se sentaron por varias horas con un representante de la casa matriz de Cygnus, Marietta Corp.<p>
Edith, uno de los l&iacute;deres de la huelga, dijo que &eacute;l se present&oacute; como &aacute;rbitro neutral preparado para terminar el conflicto. Pero Edith y el resto de los trabajadores no lo creyeron y dijeron que negociar&iacute;an solamente en presencia de su abogado, Chris Williams.<p>
En una reuni&oacute;n en el piquete al d&iacute;a siguiente, los trabajadores reiteraron sus demandas: Cada uno volver&iacute;a a su trabajo, o nadie. Ning&uacute;n acuerdo se tomar&iacute;a en las sesiones de negociaci&oacute;n. Los trabajadores votar&iacute;an juntos si aceptaban, o no, cualquier oferta de la gerencia.<p>
"Esa es la tradici&oacute;n mexicana," explic&oacute; a Jorge M&uacute;jica. "Un comit&eacute; de negociaci&oacute;n no es un comit&eacute; de firma. Cuando hay una huelga, los trabajadores se declaran en asamblea permanente", votando aceptar o no la oferta de la gerencia.<p>
Incluso si ninguno de los principales activistas de la huelga tuviera experiencia sindical en EEUU o M&eacute;xico, los trabajadores actuaban en esa tradici&oacute;n. "Cada uno tiene un t&iacute;o, hermano, un primo que ha hecho esto," dijo Mujica.<p>
Mientras las cuatro horas de negociaciones sobrevinieron, lleg&oacute; a estar claro que la gerencia estaba lista arrojar la toalla. Los muelles de cargamento estaban vac&iacute;os, los camiones sal&iacute;an sin carga, y un enorme derramamiento de jab&oacute;n se desparram&oacute; por el estacionamiento, un accidente que costar&iacute;a por lo menos un par de horas de producci&oacute;n, seg&uacute;n los trabajadores.<p>
La operaci&oacute;n rompe huelga hab&iacute;a descendido en farsa, con un enjambre de estudiantes secundarios alrededor de un supervisor de Cygnus que intentaba clasificar asignaciones durante el cambio de turno en la tarde. Contenedores cargaron de jab&oacute;n de plato hab&iacute;an sido dejados apenas adentro de planta, bien lejos del muelle de cargamento.<p>
Los guardias de seguridad, quienes en los d&iacute;as anteriores hab&iacute;an amenazado con arrestar a partidarios de los huelguistas, caminaban cabizbajos, ni siquiera haciendo caso de dos reporteros que merodeaban por el estacionamiento de empleados.<p>
La gerencia capitul&oacute;, y Total Staffing cay&oacute; en l&iacute;nea. El &uacute;nico tema sin resolver al tiempo de prensa era la situaci&oacute;n de un supervisor que hab&iacute;a salido con los trabajadores a la huelga.<p>
Sin embargo, los trabajadores ganaron una victoria con implicaciones de gran envergadura para el movimiento por los derechos del inmigrante y laboral. "El movimiento laboral tiene mucho que aprender de estos trabajadores, porque no podr&aacute; ser fuerte si sigue dejando a los obreros inmigrantes a un lado", dijo Mart&iacute;n Unzueta, que estos &uacute;ltimos a&ntilde;os ha conocido a docenas de trabajadores que desean estar organizados, pero que no puede encontrar un sindicato que asuma la tarea. "Los trabajadores inmigrante est&aacute;n listos para ser organizados", agreg&oacute;.<p>
Como Unzueta, Jorge M&uacute;jica piensa que la victoria en Cygnus puede inspirar m&aacute;s avances. "La gente record&oacute; c&oacute;mo luchar", dijo. "Estamos acostumbrados a tener demostraciones callejeras en M&eacute;xico todo el tiempo. Pero cuando la gente llega aqu&iacute;, vive vidas ocultadas y muy silenciosas.<p>
"Pero este entero proceso, desde Marzo 10 del a&ntilde;o pasado al Primero de Mayo este a&ntilde;o, se trata de demostrar que la lucha es posible. No fue hasta el Primero de Mayo este a&ntilde;o que los trabajadores pidieron el aumento de sueldo. Esto no habr&iacute;a ocurrido sin las marchas. Si no hubieran participado los trabajadores una o dos veces, no habr&iacute;an ido a la huelga".<p>
Edith, el l&iacute;der de la huelga que organiz&oacute; a los trabajadores para participar en esas marchas, dijo que la lucha por salarios y mejores condiciones continuar&iacute;a. "Estoy feliz porque mientras que comenzamos con miedo, ahora nos damos cuenta que podemos hacer un mont&oacute;n de cosas si permanecemos unidos", ella dijo. "Si [la situaci&oacute;n de los trabajadores temporales] no se hubiera sido resuelta, habr&iacute;amos continuado la huelga, pero con la ayuda de todos, porque no tenemos sindicato."<p>
"Los trabajadores tienen que aprender que no deben estar asustados, porque aqu&iacute; les ense&ntilde;amos que la unidad es la forma de avanzar."<p>
<i>Shaun Harkin contribuy&oacute; a este reporte</i>.<p>

<?php include "../../legacy-includes/BottomNavLinksObrero.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdObrero.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
