<html>
<head>

<title>
Venezuela derrota a los golpistas
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Arial, Helvetica, sans-serif" size="2"><b>REPORTAJE DIRECTO DESDE VENEZUELA</b></font><br>
<font face="Times New Roman, Times, serif" size="4">Ch&aacute;vez triunfa sobre la oposici&oacute;n apoyada por EE.UU.</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>Venezuela derrota a los golpistas</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">24 de septiembre de 2004 | p&aacute;gina 3</font></p>


<font face="Times New Roman, Times, serif" size="3"><P>LA VICTORIA abrumadora de Hugo Ch&aacute;vez en el voto revocatorio presidencial que se celebr&oacute; el 15 de agosto, que cont&oacute; con una participaci&oacute;n masiva de votantes, ha frustrado una vez m&aacute;s a la oposici&oacute;n venezolana y a sus mentores en Washington. Pero la derecha seguir&aacute; tratando de socavar a Ch&aacute;vez y a su gobierno. En este reportaje especial, LEE SUSTAR escribe para <I>Obrero Socialista</I> desde Caracas sobre el refer&eacute;ndum venezolano -- y su impacto a largo plazo.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3"><P>LOS POBRES de Venezuela reaccionaron con j&uacute;bilo al anuncio de la victoria de Hugo Ch&aacute;vez en el refer&eacute;ndum. Miles de personas del barrio colindante de Catia se concentraron alrededor de Miraflores, el palacio presidencial, de la misma forma en que lo hicieron en abril del 2002 para protestar contra y derrotar el golpe de estado respaldado por el EE.UU.</P>
<P>Esta vez, el ambiente era todo de celebraci&oacute;n, con los manifestantes bailando en las calles al son de orquestas de salsa populares. Los j&oacute;venes se ape&ntilde;uscaban en la parte trasera  de las camionetas. Uno de los muchos Chevrolets de los setentas que se ven en la ciudad--mantenidos en buena condici&oacute;n por necesidad y con el ingenio de los pobres de Caracas--apenas se mov&iacute;a cargando a 20 personas api&ntilde;adas adentro y parados en la capota.</P>
<P>El gent&iacute;o todav&iacute;a segu&iacute;a creciendo en las calles cuando Ch&aacute;vez se dirigi&oacute; a la multitud desde el balc&oacute;n del palacio, poco despu&eacute;s de las cuatro de la madrugada del 16 de agosto. Quiz&aacute;s la aclamaci&oacute;n mayor ocurri&oacute; cuando &eacute;l declar&oacute;: "Esto es un golpe al centro de la Casa Blanca".</P>
<P>Pocas horas despu&eacute;s, los Chavistas organizaron caravanas de carros, tocando sus bocinas al ritmo de la consigna popular: "Uh, ah, &#161;Ch&aacute;vez no se va!" Esto es una victoria para el pueblo", dijo Maria Luisa Delgado, una maestra jubilada, cuando ella y un amigo se preparaban para unirse a la celebraci&oacute;n en medio del territorio de la oposici&oacute;n--el suburbio de clase media alta de San Antonio de los Altos. "Tenemos democracia verdadera en Venezuela, participativa y pro-activa".</P>
<P>Previsiblemente, la mal llamada Coordinadora Democr&aacute;tica--la coalici&oacute;n de la oposici&oacute;n que recibe fondos del National Endowment for Democracy, instrumento del gobierno estadounidense--declar&oacute; que hubo fraude en el funcionamiento del sistema electr&oacute;nico que tabul&oacute; la votaci&oacute;n. Pero estas declaraciones fueron deslegitimadas cuando los observadores internacionales--incluso el ex-presidente estadounidense Jimmy Carter--aceptaron los resultados anunciados por la Comisi&oacute;n Electoral Nacional, que indicaban que el "No" a la revocaci&oacute;n gan&oacute; con 58 por ciento del voto, contra el 42 por ciento a favor del "S&iacute;".</P>
<P>Hasta el propio el Departamento de Estado de EE.UU. decidi&oacute; tragarse los resultados. Con 94 por ciento de los votos tabulados, Ch&aacute;vez logr&oacute; casi 5 millones de votos--m&aacute;s de 1 mill&oacute;n de votos por encima de su total en los comicios del 2000. La oposici&oacute;n logr&oacute; 3.6 millones de votos por el "S&iacute;" en una votaci&oacute;n que cont&oacute; con la participaci&oacute;n de un 80 por ciento de los electores elegibles, seg&uacute;n estimados iniciales. La gran participaci&oacute;n electoral en los barrios hizo claro que Ch&aacute;vez todav&iacute;a cuenta con el apoyo del 80 por ciento de la poblaci&oacute;n que vive bajo la l&iacute;nea de pobreza.</P>
<P>En un pa&iacute;s, que seg&uacute;n un informes recientes, tiene una desigualdad social m&aacute;s profunda que la de Brasil o la de Sud&aacute;frica, los ricos siempre han odiado a Ch&aacute;vez porque ha levantado las esperanzas de los pobres. Hoy, lo odian aun m&aacute;s por cumplir con sus promesas con una serie de programas contra la pobreza costeados con los crecientes ingresos obtenidos de la exportaci&oacute;n de petr&oacute;leo.</P>
<P>Mientras tanto, EE.UU. considera que el nacionalismo de Ch&aacute;vez es una ruptura peligrosa con las pol&iacute;ticas del neoliberalismo del llamado consenso de Washington. En una &eacute;poca de rebeliones populares en contra de condiciones econ&oacute;micas y sociales insoportables que han derrocado a gobiernos a lo largo de Sur Am&eacute;rica, Ch&aacute;vez intenta situarse como un l&iacute;der regional.</P>
<P>Tambi&eacute;n, sus denuncias habituales contra imperialismo estadounidense siempre han enfurecido a los oficiales norteamericanos--cosa que hoy en d&iacute;a  adquiere mayor importancia debido a la crisis de la ocupaci&oacute;n de EE.UU. en Irak. Todas de &eacute;stas son razones suficientes para que Washington quiera desestabilizar a Ch&aacute;vez.</P>
<P>Como Venezuela es el mayor exportador de petr&oacute;leo de EE.UU., la situaci&oacute;n ha sido aun m&aacute;s bochornosa para Washington. No s&oacute;lo es que Ch&aacute;vez le pincha el ojo regularmente al T&iacute;o Sam, sino que lo hace con sus bolsillos llenos de d&oacute;lares americanos. Por eso es que EE.UU. apoy&oacute; el golpe de estado contra Ch&aacute;vez en abril del 2002--descrito eufem&iacute;sticamente como una "alteraci&oacute;n temporera del orden constitucional" en el sitio de la red del Departamento del Estado de EE.UU.--e inmediatamente le otorg&oacute; reconocimiento oficial al gobierno golpista.</P>
<P>Pero la oposici&oacute;n mostr&oacute; sus garras dictatoriales inmediatamente--lo que provoc&oacute; una rebeli&oacute;n popular que derrib&oacute; al nuevo r&eacute;gimen en s&oacute;lo dos d&iacute;as y forz&oacute; a los militares a permitir que Ch&aacute;vez regresara al poder triunfantemente. Ahora, si un reportaje en el peri&oacute;dico espa&ntilde;ol <I>El Mundo</I> es correcto, la CIA hab&iacute;a llegado a la conclusi&oacute;n de que la victoria de Ch&aacute;vez en el referendo era inevitable--y que los esp&iacute;as de Washington se reunieron con sus contrapartes latinoamericanos en Chile para discutir los supuestos planes de Ch&aacute;vez de extender su "revoluci&oacute;n bolivariana" a sus pa&iacute;ses vecinos.</P>
<P>Esto, por supuesto, son tonter&iacute;as--pero provee un pretexto para tentativas futuras de aislar y desestabilizar a Venezuela. No obstante, esto ser&aacute; m&aacute;s dif&iacute;cil ahora. La victoria de Ch&aacute;vez es la s&eacute;ptima en una serie de &eacute;xitos electorales de su movimiento--incluso su primera elecci&oacute;n en 1998 despu&eacute;s del colapso de los partidos pol&iacute;ticos venezolanos tradicionales; la elecci&oacute;n de una asamblea constituyente encargada de redactar una constituci&oacute;n nueva el a&ntilde;o siguiente; y la reelecci&oacute;n de Ch&aacute;vez con un mandato de seis a&ntilde;os en 2000.</P>
<P>Ahora Ch&aacute;vez obtuvo la mayor&iacute;a m&aacute;s grande de su carrera. Pero esto no va a traerle estabilidad pol&iacute;tica al pa&iacute;s. No solo es que la oposici&oacute;n y sus mentores de EE.UU. seguir&aacute;n su hostigamiento, pero las contradicciones entre las pol&iacute;ticas de Ch&aacute;vez y su base social se van a hacer m&aacute;s evidentes. </P>
<P>En una rueda de prensa antes del voto, Ch&aacute;vez se comprometi&oacute; a reunirse con los l&iacute;deres de la oposici&oacute;n inmediatamente despu&eacute;s del refer&eacute;ndum--el ejemplo m&aacute;s reciente de una serie de intentos de llegar a un acuerdo con la oposici&oacute;n. Dado el tama&ntilde;o de su victoria, es posible que pueda encontrar a alguien dispuesto a esto entre los grandes empresarios o figuras opositoras--pero solo para ganar tiempo hasta que puedan desafiarlo otra vez.</P>

<P><font face="Times New Roman, Times, serif" size="4"><b>Trasfondo del ascenso del Chavismo</b></font></P>

<font face="Times New Roman, Times, serif" size="3"><P>LAS RELACIONES entre Ch&aacute;vez y la oposici&oacute;n y los grandes empresarios llaman la atenci&oacute;n al papel contradictorio de un hombre que se describe &eacute;l mismo como un revolucionario, pero que dirige un estado capitalista dominado por una burocracia hostil. Gran parte de la administraci&oacute;n civil permanece en manos de miembros de los dos partidos gobernantes tradicionales de Venezuela--el centroizquierdista Acci&oacute;n Democr&aacute;tica (AD), y el conservador Partido Social Cristiano (COPEI).</P>
<P>Estos dos partidos gobernaron a Venezuela por d&eacute;cadas seg&uacute;n un pacto para compartir el poder negociado en 1958, despu&eacute;s la ca&iacute;da de la dictadura militar. AD y COPEI convirtieron en mandato constitucional la condici&oacute;n de que  solo candidatos que corrieran listas nacionales pod&iacute;an competir en las elecciones. Tambi&eacute;n centralizaron el poder en el gobierno federal--por ejemplo, designando a los gobernadores estatales--pudiendo as&iacute; impedir que otros partidos rivales, tal como el Partido Comunista, pudieran desplegar un desaf&iacute;o en serio.</P>
<P>Los cuadros de estos partidos habitualmente se robaban los comicios al intimidar a los votantes en las urnas, descalificar votos y manipular las listas de inscripci&oacute;n de votantes. Las maquinarias pol&iacute;ticas omnipresentes eran sufragadas por los ingresos de la compa&ntilde;&iacute;a petrolera, PDVSA, que fue nacionalizada junto con otras empresas en 1976, bajo el gobierno del presidente Carlos Andr&eacute;s P&eacute;rez del partido AD.</P>
<P>Este tipo de capitalismo de estado reforzaba el poder pol&iacute;tico de los dos partidos gobernantes--y produc&iacute;a una econom&iacute;a y un estado impregnados por la corrupci&oacute;n. Durante la crisis financiera de los 1980, los oficiales del gobierno ayudaron a sus amigotes a asegurar acceso a d&oacute;lares estadounidenses, permitiendo una fuga de capital de $11 mil millones fuera del pa&iacute;s mientras que los sueldos reales de los venezolanos se precipitaron en un 20 por ciento.</P>
<P>Esto era s&iacute;ntoma de una crisis econ&oacute;mica de estancamiento que era m&aacute;s amplia y que reflejaba la presi&oacute;n de la competencia del mercado mundial contra las empresas dirigidas por el estado. Mientras tanto, PDVSA, supuestamente manejada por el estado, se convert&iacute;a en una potencia aut&oacute;noma, invirtiendo dinero en operaciones fuera del pa&iacute;s para disminuir sus impuestos.</P>
<P>Fue en este contexto que P&eacute;rez fue elegido a la presidencia otra vez en 1988. Entonces, lanz&oacute; un plan de austeridad neoliberal agresivo, recortando los gastos del gobierno y permitiendo aumentos inmensos en los precios de los bienes esenciales, como hab&iacute;a especificado un acuerdo con el Fondo Monetario Internacional (FMI).</P>
<P>Esto provoc&oacute; una protesta insurreccional y espont&aacute;nea el 27 de febrero de 1989, en la cual tanto como 1,500 fueron muertos por la polic&iacute;a y las fuerzas armadas, de acuerdo a los activistas. La represi&oacute;n caus&oacute; una crisis dentro del ej&eacute;rcito entre las filas de los oficiales de rango intermedio y entre los soldados, incluyendo a Ch&aacute;vez.</P>
<P>En 1992, Ch&aacute;vez comand&oacute; un golpe militar contra P&eacute;rez, pero se rindi&oacute; y fue encarcelado. Ch&aacute;vez no era visto como un aspirante a dictador militar, sino como un h&eacute;roe popular -- y fue perdonado el siguiente a&ntilde;o. &Eacute;l comenz&oacute; a articular la c&oacute;lera y las aspiraciones de los trabajadores y las de los pobres, que hab&iacute;an sufrido bajo las pol&iacute;ticas neoliberales extremas del gobierno.</P>
<P>El porcentaje de trabajadores en el sector informal--los que trabajan como jornaleros, vendedores en la calle u en otros trabajos similares--aument&oacute; de 34.5 por ciento a 53 por ciento de la fuerza laboral para el 1999. Los sueldos verdaderos en la industria venezolana--que incluye a las plantas de ensamblaje de la industria automotriz de General Motors y Ford--decayeron un 40 por ciento desde 1980 hasta finales de los 1990.</P>
<P>Esto formaba parte de una transferencia m&aacute;s profunda de la riqueza de los pobres hacia los ricos. Entre 1981 y 1997, el 40 por ciento m&aacute;s pobre de la poblaci&oacute;n experiment&oacute; una ca&iacute;da de su porci&oacute;n del ingreso nacional de 19.1 por ciento a 14.7 por ciento, mientras que el 10 por ciento m&aacute;s rico se apoder&oacute; de un tercio del ingreso nacional. Entre 1984 y 1994, la pobreza casi se duplic&oacute;, alcanzando el 66 por ciento de toda la poblaci&oacute;n.</P>
<P>Durante el mismo per&iacute;odo, los recortes presupuestarios destruyeron lo que hab&iacute;a sido uno de los estados de bienestar m&aacute;s desarrollados entre los pa&iacute;ses pobres. Los gastos en la vivienda y para el desarrollo urbano se recortaron 70 por ciento a principios de los 1990, los gastos m&eacute;dicos se recortaron 37 por ciento, y los del desarrollo social un 56 por ciento.</P>
<P>Todo esto significaba que Ch&aacute;vez encontr&oacute; una audiencia lista para sus ideas de una "revoluci&oacute;n Bolivariana" nacionalista--que tom&oacute; el nombre de Sim&oacute;n Bol&iacute;var, el l&iacute;der de la lucha anticolonial contra Espa&ntilde;a de a principios del siglo XIX. Aunque las pol&iacute;ticas "bolivarianas" eran vagamente definidas, un punto estaba claro: que los pobres hab&iacute;an sufrido ya demasiado, y que su hora hab&iacute;a llegado.</P>

<P><font face="Times New Roman, Times, serif" size="4"><b>&#191;La revoluci&oacute;n desde arriba?</b></font></P>

<font face="Times New Roman, Times, serif" size="3"><P>LOS PARTIDARIOS de Ch&aacute;vez describen los cambios pol&iacute;ticos en Venezuela como "el proceso", una forma corta de referirse al "proceso revolucionario bolivariano". "El proceso"--lo que Ch&aacute;vez ha descrito como un tercer camino entre el capitalismo y el comunismo "fracasado"--comenz&oacute; vacilantemente cuando &eacute;l tom&oacute; su cargo en 1999.</P>
<P>El Plan Bol&iacute;var 2000 puso al ej&eacute;rcito a cargo de la administraci&oacute;n de varios programas contra la pobreza, como los de reparaci&oacute;n de viviendas, escuelas y edificios p&uacute;blicos; y los de distribuci&oacute;n de servicios m&eacute;dicos y de alimentos. M&aacute;s abarcadora fue la reforma agraria.</P>
<P>En un pa&iacute;s donde el 3 por ciento de la poblaci&oacute;n posee 70 por ciento de las tierras agr&iacute;colas, el gobierno de Ch&aacute;vez distribuy&oacute; tierras del estado a 130,000 familias en 2003. La toma de las tierras de propietarios privados se ha autorizado, pero no se ha implementado. La reforma urbana de la propiedad de terrenos les otorg&oacute; t&iacute;tulos a las familias de barrios pobres donde las organizaciones comunitarias se hab&iacute;an organizado para pedirlos.</P>
<P>Sin embargo, la recesi&oacute;n econ&oacute;mica de fines de los 1990, el colapso en el precio del petr&oacute;leo, y la fuga del capital de Venezuela limit&oacute; los fondos disponibles para las reformas. Con la econom&iacute;a en contracci&oacute;n, la oposici&oacute;n pudo movilizar una marcha masiva en contra de Ch&aacute;vez el 11 de abril de 2002--lo que le sirvi&oacute; como plataforma para el lanzamiento del golpe militar fallido.</P>
<P>El pr&oacute;ximo golpe fue la huelga de la industria petrolera organizada por la federaci&oacute;n laboral venezolana tradicional, la CTV -- hist&oacute;ricamente "dependiente financieramente de los gobiernos sucesivos de AD y controlado pol&iacute;ticamente por el partido AD", de acuerdo a un libro reciente sobre el pa&iacute;s, escrito por Julia Buxton, especialista en asuntos venezolanos. Los trabajadores de la industria petrolera y el ej&eacute;rcito pudieron romper lo que realmente era una huelga patronal, pero la econom&iacute;a qued&oacute; devastada, encogi&eacute;ndose 8.9 por ciento en 2002 y otro 9.4 por ciento el a&ntilde;o pasado.</P>
<P>La revista conservadora <I>The Economist</I> pronostic&oacute; engre&iacute;damente la ca&iacute;da eventual de Ch&aacute;vez. Pero el agudo aumento en el precio del petr&oacute;leo--gracias en parte a la guerra y ocupaci&oacute;n de EE.UU. en Irak-- lo ha cambiado todo. La econom&iacute;a venezolana va rumbo a crecer tanto como un 12 por ciento este a&ntilde;o.</P>
<P>Esto le ha permitido a Ch&aacute;vez poder lanzar nuevos proyectos de reforma, conocidos como las "misiones", que brincan por encima de la ineficiente burocracia y refuerzan su base pol&iacute;tica. Los programas incluyen subsidios de alimentos para los pobres, asistencia m&eacute;dica en el campo y en los arrabales urbanos, ofrecida por m&eacute;dicos cubanos, y mejor acceso a la educaci&oacute;n superior.</P>
<P>Las misiones fueron centrales en la movilizaci&oacute;n de numerosas delegaciones de los barrios al gigantesco mitin a favor del gobierno en Caracas el 8 de agosto--seg&uacute;n algunos estimados, con la participaci&oacute;n de un mill&oacute;n de personas. "La victoria de Ch&aacute;vez significa que Venezuela est&aacute; comenzando a utilizar sus riquezas para el bienestar de su pueblo", dijo Mar&iacute;a Carmen, de 70 a&ntilde;os.</P>
<P>Argelio, un joven de la misi&oacute;n contra la pobreza de Barrio Adentro, dijo que "las zonas populares" de Caracas como la suya eran claves para el cambio pol&iacute;tico venezolano. "El barrio de Del Valle es importante para la revoluci&oacute;n venezolana, para nuestra libertad, para el patriotismo y para el pueblo de Venezuela".</P>
<P>Los programas contra la pobreza y las reformas, sumados a las denuncias frecuentes de Ch&aacute;vez contra el imperialismo norteamericano y el neoliberalismo, representan una ruptura con el consenso de Washington de las privatizaciones, la desregulaci&oacute;n y la flexibilizaci&oacute;n del trabajo impuestos a trav&eacute;s de Am&eacute;rica Latina. El c&iacute;rculo de asesores de Ch&aacute;vez incluye l&iacute;deres de ATTAC, un grupo globof&oacute;bico franc&eacute;s y otros intelectuales izquierdistas bien conocidos internacionalmente.</P>
<P>Pero, &#191; constituye esto una "revoluci&oacute;n"? En algunos aspectos, Ch&aacute;vez es como un retorno a los l&iacute;deres latinoamericanos nacionalistas y populistas del pasado, como L&aacute;zaro C&aacute;rdenas en el M&eacute;xico de los treintas o Juan Per&oacute;n en la Argentina de los cuarentas. No obstante, mientras que estos gobiernos nacionalizaron las industrias m&aacute;s importantes para el desarrollo de sus pa&iacute;ses, Ch&aacute;vez no ha tratado de expropiar a la industria privada.</P>
<P>En su lugar, est&aacute; tratando a usar su control de PDVSA para disciplinar a los empresarios venezolanos y para ser m&aacute;s agresivo en las negociaciones de los acuerdos de comercio--por ejemplo, oponi&eacute;ndose al &Aacute;rea de Libre Comercio de las Am&eacute;ricas (ALCA). En este sentido, Ch&aacute;vez persigue una pol&iacute;tica de "inserci&oacute;n soberana" en el mercado mundial, como la llama el presidente brasile&ntilde;o, Luiz In&aacute;cio "Lula" da Silva.</P>
<P>&Eacute;sta es una pol&iacute;tica de reimponer la iniciativa nacional en contra del imperialismo norteamericano y sus instituciones, como el FMI, el Banco Mundial y la Organizaci&oacute;n Mundial del Comercio (OMC). Mientras que Lula ha capitulado ante estas presiones, Ch&aacute;vez se ha resistido, usando los ingresos de la venta de petr&oacute;leo para trazar un rumbo distinto.</P>
<P>No obstante, Ch&aacute;vez ha seguido pag&aacute;ndole sus deudas a los usureros del FMI y ha tratado de reconciliarse con secciones de la clase capitalista venezolana. La mayor&iacute;a de los obreros, incluyendo los que est&aacute;n organizados en la central izquierdista, la Uni&oacute;n Nacional de Trabajadores de Venezuela, apoya a Ch&aacute;vez en contra de la oposici&oacute;n patronal. Muchos de los afiliados de la UNT se retiraron de la CTV tras la huelga patronal en la industria petrolera.</P>
<P>Sin embargo, los salarios reales que no han aumentado y la destrucci&oacute;n de trabajos por despidos y por la exportaci&oacute;n de trabajos al exterior no han sido asuntos que el gobierno de Ch&aacute;vez haya abordado expl&iacute;citamente. Una huelga a principios  de este a&ntilde;o por trabajadores de un sindicato independiente contra la compa&ntilde;&iacute;a de acero de Venezuela--una compa&ntilde;&iacute;a en que la mitad pertenece al estado y la otra mitad a un consorcio de multinacionales--puso sobre el tapete estos asuntos.</P>
<P>Por su parte, la CTV acus&oacute; a la UNT--que recibe tratamiento preferencial de Ch&aacute;vez--de ser virtualmente un brazo del estado. La UNT ha recibido recursos del gobierno, pero a veces se ha encontrado en contra de la pol&iacute;tica del gobierno.</P>
<P>Los capitalistas venezolanos que manejan las compa&ntilde;&iacute;as privatizadas tienen sus propios v&iacute;nculos con el mercado mundial y no quieren ceder la iniciativa a Ch&aacute;vez o al estado. Ellos y sus mentores en Washington--que incluyen tanto a Republicanos como a Dem&oacute;cratas--continuar&aacute;n socavando el gobierno de Venezuela.</P>

<P><font face="Times New Roman, Times, serif" size="4"><b>&#191;Ahora qu&eacute; en Venezuela?</b></font></P>

<font face="Times New Roman, Times, serif" size="3"><P>LOS RESULTADOS del refer&eacute;ndum en Venezuela son una victoria para todos los que nos oponemos al imperialismo estadounidense y al neoliberalismo--en Venezuela y en todo el mundo. Pero la polarizaci&oacute;n de la sociedad venezolana que se reflej&oacute; en el voto no va a resolverse por los resultados de la elecci&oacute;n.</P>
<P>La intervenci&oacute;n de Washington continuar&aacute;. Los grandes empresarios venezolanos y los ricos puede que quieran un golpe militar como el de Chile en 1973. Pero las fuerzas armadas a&uacute;n son leales a Ch&aacute;vez, as&iacute; que ellos tendr&aacute;n que construir una oposici&oacute;n electoral y esperar hasta un momento m&aacute;s oportuno.</P>
<P>Pero la frase a menudo citada de los partidarios de Ch&aacute;vez, sobre que "el ej&eacute;rcito venezolano est&aacute; del lado del pueblo" no garantiza nada contra un futuro golpe de estado. Los ej&eacute;rcitos son instituciones inherentemente r&iacute;gidas, conservadoras y jer&aacute;rquicas, en que la cadena de comando tiene que ser obedecida sin protestas si es que va a ser eficaz--y los oficiales de alto rango est&aacute;n socialmente entremezclados con los ricos y los poderosos.</P>
<P>El ej&eacute;rcito, sobre todo, est&aacute; en el centro de un estado que refleja y refuerza las relaciones de las clases sociales en la sociedad. La revoluci&oacute;n bolivariana de Ch&aacute;vez ha tratado de reconfigurar y circunvalar ese estado--pero no lo ha desmantelado. Eso significa que el proceso de cambio social ser&aacute; continuamente obstaculizado y socavado, si no es bloqueado por completo.</P>
<P>Desde que la huelga patronal de la industria petrolera fue derrotada, los activistas de izquierda en las organizaciones populares y en el movimiento se ha quejado de que "el proceso" se ha burocratizado y desradicalizado. En una entrevista luego de que los resultados del refer&eacute;ndum fueron anunciados, Roland Denis, ex-ministro de planificaci&oacute;n local en el gobierno de Ch&aacute;vez y activista de las organizaciones populares, dijo que la lucha se intensificar&aacute; despu&eacute;s de que terminen las celebraciones.</P>
<P>"Esto es un proceso que es inmensamente mayoritario, sostenido fundamentalmente, por supuesto, por las clases populares, y [los resultados de la elecci&oacute;n] demuestran sus fuerzas", dijo Denis, quien fue forzado a renunciar a su puesto por ser demasiado izquierdista, seg&uacute;n algunos reportes. "Es evidente, sin embargo, que los revolucionarios no pueden depender de un plan electoral para construir una sociedad nueva".</P>
<P>Agreg&oacute; que hay una "gran contradicci&oacute;n entre la pol&iacute;tica del proceso y su programa" --disputas entre los dirigentes que quieren reducir la marcha de los cambios, y los que quieren romper con todas limitaciones y "profundizar" el proceso. Esto refleja el hecho de que Ch&aacute;vez ha podido hasta el momento balancearse entre clases antag&oacute;nicas -- los capitalistas y los ricos por un lado, y los trabajadores y los pobres por el otro.</P>
<P>Como ha sido el caso en elecciones previas en Venezuela, el refer&eacute;ndum canaliz&oacute; ese conflicto de clases hacia las urnas. Ahora, la victoria de Ch&aacute;vez, junto con el crecimiento econ&oacute;mico y las misiones anti-pobreza, incrementar&aacute;n las demandas populares por un cambio m&aacute;s profundo.</P>
<P>Esto podr&iacute;a impulsar a los trabajadores y a los pobres a una lucha por sus propios intereses--una reforma agraria m&aacute;s r&aacute;pida y abarcadora, la reconstrucci&oacute;n del sistema tradicional de servicios m&eacute;dicos, salarios m&aacute;s altos, y m&aacute;s trabajos. Tales luchas ser&aacute;n enfrentadas con una resistencia feroz por parte de los empresarios y los ricos--y forzar&aacute;n al gobierno de Ch&aacute;vez a escoger uno de los bandos.</P>
<P>En medio de esas batallas, el debate sobre la naturaleza y la direcci&oacute;n del proceso revolucionario en Venezuela se desarrollar&aacute;--y tendr&aacute; un impacto enorme a trav&eacute;s de Am&eacute;rica Latina y del mundo.</P>

<P><I>Traducci&oacute;n de Lance Selfa y H&eacute;ctor Reyes</I></P>

<?php include "../../legacy-includes/BottomNavLinksObrero.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdObrero.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
