<html>
<head>

<title>
El caso en contra del "Cualquiera Menos Bush"
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="5"><b>El caso en contra del "Cualquiera Menos Bush"</b></font></P>

<P><font face="Arial, Helvetica, sans-serif" size="2">24 de septiembre de 2004</font></P>

<font face="Times New Roman, Times, serif" size="3">Las encuestas revelan que m&aacute;s de la mitad de la poblaci&oacute;n estadounidense est&aacute; en contra de la guerra en Irak, y que n&uacute;meros aun mayores quieren el servicio m&eacute;dico universal y una mejor educaci&oacute;n para sus hijos. Millones tambi&eacute;n dicen que considerar&iacute;an votar por una candidatura presidencial genuinamente anti-guerra y pro-obrera en noviembre--el desaf&iacute;o independiente montado por Ralph Nader y Peter Camejo al sistema pol&iacute;tico bipartidista.<p>
El potencial existe para constru&iacute;r una verdadera alternativa de izquierda. Sin embargo gran parte de este potencial ser&aacute; desperdiciado, por lo menos hasta despu&eacute;s de la elecci&oacute;n. Desafortunadamente, mucha gente que aportar&iacute;a su voz, sus ideas y su habilidad organizativa para moldear a partir del sentimiento difuso que existe en contra de Bush una fuerza pol&iacute;tica de izquierda, en vez est&aacute;n usando su talento para canalizar apoyo para John Kerry. <p>
Para la mayor&iacute;a de estos progresistas--como para milliones de otras personas--la &uacute;nica virtud de Kerry es que no es Bush. Y para muchos en la izquierda resulta dif&iacute;cil reconciliar esta cuesti&oacute;n: deshacerse de Bush, pero votar <i>por </i>el Dem&oacute;crata que es pro-guerra, pro-ocupaci&oacute;n, pro-TLC, que apoya la ley USA PATRIOT, y que se opone al derecho al matrimonio de gays y lesbianas.<p>
LANCE SELFA, de <i>Obrero Socialista</i>, responde a los argumentos de los progresistas que urgen un voto por "Cualquiera Menos Bush" (ABB, por sus siglas en ingl&eacute;s).<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3"><b>Muchos progresistas implican que hay una inmensa diferencia entre los dos candidatos. &iquest;Es esto cierto?</b><p>

La actual acusaci&oacute;n liberal en contra de los que apoyamos a Nader es que creemos que no hay ninguna diferencia entre los dos partidos principales de Estados Unidos--los Dem&oacute;cratas y los Republicanos. En realidad, nadie en la izquierda estadounidense--ciertamente no en este peri&oacute;dico--ha argumentado esto.<p>
De hecho, el sistema pol&iacute;tico estadounidense funciona precisamente porque existen algunas m&iacute;nimas diferencias entre los dos partidos. Simplemente no ser&iacute;a cre&iacute;ble--ni ser&iacute;a una f&oacute;rmula para el &eacute;xito electoral--si los dos partidos se postularan con programas id&eacute;nticos.<p>
Sin embargo, siendo los partidos capitalistas gobernantes de los Estados Unidos, los Dem&oacute;cratas y los Republicanos son instrumentos de la clase capitalista. Llevan a cabo las pol&iacute;ticas de la clase capitalista. Solo se diferencian en los detalles.<p>
Mientras los Republicanos abiertamente ostentan su favoritismo hacia los ricos, los Dem&oacute;cratas son, como ha dicho el experto Republicano Kevin Phillips, "el segundo partido m&aacute;s entusiastamente capitalista del mundo". Mientras que los "aguilas" neo-conservadores alrededor de Bush exclaman a gritos la necesidad de un nuevo imperialismo estadounidense, Kerry y los Dem&oacute;cratas hablan de la necesidad de un "internacionalismo forzudo".<p>
En las questiones claves de hoy--de lo que se supone se tratan las elecciones--hay poca diferencia entre Kerry y Bush. El experto conservador George Will ha dicho que Bush y Kerry tienen posiciones tan parecidas respecto a Irak que no cabe una hoja de papel en la distancia entre estas. Los dos est&aacute;n dedicados a mantener y hacer prevalecer la ocupaci&oacute;n estadounidense de Irak. Kerry vot&oacute; a favor de las leyes de Bush como la ley trituradora de derechos llamada USA PATRIOT y la ley "No Child Left Behind" que ha deteriorado severamente a la educaci&oacute;n publica. El apoy&oacute; las guerras en Afganist&aacute;n e Irak. Y fue de los primeros en proponer--cuando Bill Clinton era presidente--el "cambio de r&eacute;gimen" en Irak.<p>
Respecto a la pol&iacute;tica dom&eacute;stica, Kerry ha apoyado firme e inquebrantablemente los tratados de "libre comercio" como el TLC y el ALCA. Como Bush, tambi&eacute;n se opone al derecho de los homosexuales a casarse.<p>
En todas estas cuestiones--que son fundamentales--hay muy poca diferencia, y esta reside principalmente en la ret&oacute;rica, entre Bush y Kerry. El problema con los progresistas que apoyan a Kerry es que toman las diferencias que s&iacute; existen entre los candidatos y las elevan al nivel de ser razon suficiente como para votar por el Dem&oacute;crata.<p>
Este es el m&eacute;todo cl&aacute;sico del "mal menor" en operaci&oacute;n. Pero al enfocarse en las diferencias esp&eacute;cificas se pierde de vista el acuerdo general entre los dos partidos.<p>
De esta manera la convenci&oacute;n Dem&oacute;crata en Boston destac&oacute; a Ron Reagan acusando a Bush de oponerse a la investigaci&oacute;n m&eacute;dica con c&eacute;lulas matrices (provenientes de embriones desechados) por las conecciones de este con los fan&aacute;ticos anti-aborto. Por supuesto, no hay nada de malo con la investigaci&oacute;n con c&eacute;lulas matrices, y cualquier gobierno razonable deber&iacute;a apoyarla. Pero esta cuesti&oacute;n es secundaria en esta elecci&oacute;n.<p>
Sin embargo, esta fue la &uacute;nica critica a Bush "aprobada" por los funcionarios de Kerry en la convenci&oacute;n--mientras que no permitieron que ning&uacute;n delegado portara ning&uacute;n cartel que tuviera la palabra "Paz". Eso hubiera debilitado el mensaje en una convenci&oacute;n dedicada a demostrar que Kerry ser&iacute;a m&aacute;s duro que Bush en Irak y en la "guerra conta el terrorismo". De acuerdo a la l&oacute;gica del "mal menor" deber&iacute;amos ignorar todo esto y votar por Kerry porque tiene una mejor posici&oacute;n que Bush respecto a la investigaci&oacute;n con c&eacute;lulas matrices.<p>
Los editores del semanario <i>The Nation </i>escribieron en su "Carta Abierta a Ralph Nader" en febrero que, "La posiblidad de que [esta campa&ntilde;a] se transforme en una carrera entre Bush y Bush Lite (liviano) as casi zero". Pero despues del belicismo de la convenci&oacute;n Dem&oacute;crata, quien se puede creer esto?<p>

<b>Kerry no ser&aacute; perfecto, &iquest;pero no tendr&iacute;an mejores posibilidades de &eacute;xito las luchas de base con Kerry en la Casa Blanca en vez de Bush? &iquest; No son los Dem&oacute;cratas m&aacute;s suceptibles a nuestra presi&oacute;n que los Republicanos?</b><p>

Varias figuras reconocidas en la izquierda con mucha experiencia en los movimientos--como el fundador de Alternative Radio, David Barsamian, y la l&iacute;der de United for Peace and Justice, Leslie Cagan--sostienen este argumento. Ellos motivan el voto por Kerry porque, seg&uacute;n su argumento, es m&aacute;s probable que una administraci&oacute;n Dem&oacute;crata responda a sectores pol&iacute;ticos como los sindicatos, los grupos pro derechos de las mujeres, o el movimiento contra la guerra.<p>
Este argumento no es nuevo ni se limita a esta elecci&oacute;n. Resurge cada a&ntilde;o electoral. Desafortunadamente, es otro argumento para el cual la evidencia es escaza--y que escacea m&aacute;s con cada nueva elecci&oacute;n.<p>
De echo, la ortodoxia dominante del partido Dem&oacute;crata de hoy--alimentada por los titiriteros del <i>Democratic Leadership Council</i> en el seno del partido--es que los candidatos Dem&oacute;cratas deben probar que <i>no </i>complacer&aacute;n a sus partidarios electorales m&aacute;s fieles, y que har&aacute;n todo lo posible para ayudar a los grandes empresarios financieros del partido. En los estados claves, los grandes "campos de batalla" como Michigan, los esfuerzos sindicales para promover que la gente vote frecuentemente logran movilizar lo que equivale a la mitad de los votos obtenidos por los Dem&oacute;cratas. Sin embargo, la administraci&oacute;n de Clinton "premi&oacute;" a los trabajadores con el TLC y con los programas que forzaban a los recipientes de ayuda gubernamental a trabajor por estos beneficios (el llamado "welfare-to-work") que socavaron los empleos de los trabajadores sindicalizados.<p>
&iquest;Y qu&eacute; de los temas como el aborto?, donde las diferencias entre los dos partidos son realmente identificables. Por lo menos los Dem&oacute;cratas est&aacute;n comprometidos a mantener el aborto como una opci&oacute;n legalmente disponible para las mujeres, mientras que los Republicanos est&aacute;n dedicados a prohibirlo. Esto es verdad, pero apoyar a los Dem&oacute;cratas simplemente porque no son tan malos como los Republicanos demuestra que tan d&eacute;biles son las esperanzas de los liberales y los progresistas.<p>
Cuando Bill Clinton se postul&oacute; para presidente prometi&oacute; aprobar una ley de "Libre Opci&oacute;n" que garantizar&iacute;a el derecho de las mujeres a elegir el tener un aborto. Cuando este asumi&oacute; el pod&eacute;r, abandon&oacute; la ley. Mientras que s&iacute; vet&oacute; los efuerzos de la derecha de prohib&iacute;r el procedimiento de aborto durante el embarazo avanzado, el malnombrado "aborto de parto parcial", desafortunadamente tambi&eacute;n aprob&oacute; leyes que le negaban a las empleadas federales la covertura en sus planes m&eacute;dicos de abortos, y tambi&eacute;n a las residentes de Washington D.C., y adem&aacute;s mantuvo la prohibici&oacute;n de la cobertura de abortos por el programa Medicaid.<p>
Pero los grupos pro derechos de la mujer nunca le hicieron pagar un precio pol&iacute;tico a Clinton por estas traiciones. Mientras tanto, un ataque coordinado contra el derecho al aborto concentr&oacute; sus fuerzas a nivel de los estados, y las l&iacute;deres de organizaciones feministas se rehusaron a mobilizar un contra ataque--bas&aacute;ndose parcialmente en la premisa de que el derecho al aborto estaba seguro con un Dem&oacute;crata en la Casa Blanca.<p>

<b>Era una cosa votar por Ralph Nader en 2000 cuando era el candidato del Partido Verde. Pero este a&ntilde;o es un independiente. Su campa&ntilde;a no est&aacute; haciendo nada para constru&iacute;r al Partido Verde o a la izquierda en general.</b><p>

Este argumento es discutido principalmente por los que apoyaron la nominaci&oacute;n de David Cobb y Pat LaMarche como candidatos del Partido Verde para presidente y vice presidente. Como escribi&oacute; el autor de izquierda Stephen Shalom en la revista <i>New Politics</i>, "Los argumentos a favor de apoyar a David Cobb . . . parecen ser m&aacute;s convincentes que los argumentos a favor de Nader. Cobb es verdaderamente parte del Partido Verde, que es una verdadera organizaci&oacute;n, avanzando por un proceso democr&aacute;tico--no muy eficientemente, es verdad, pero democr&aacute;tico sin embargo.<p>
"Examine el sitio en la red del Partido Verde, www.gp.org, y vea los enlaces con sitios como los de United for Peace and Justice, Znet, Democracy Now y Fair Trade Coffee. Este es nuestro partido". Este argumento cargar&iacute;a algo de peso si el prop&oacute;sito de la candidatura de Cobb fuera enfrentarse agresivamente a Bush y Kerry en las cuestiones como la guerra, la ocupaci&oacute;n, la ley USA PATRIOT, el derecho al aborto, los servicios m&eacute;dicos o cualquiera de muchos asuntos en los que el Partido Verde est&aacute; a la izquierda de los Dem&oacute;cratas.<p>
Pero la campa&ntilde;a de Cobb claramente ha declarado que persiguir&aacute; una estrategia de "estados seguros" en que no har&aacute; campa&ntilde;a en los estados donde un voto numeroso para los Verdes podr&iacute;a inclinar la elecci&oacute;n a favor de Bush. Esto se ilustr&oacute; lo m&aacute;s absurdamente cuando LaMarche, una residente de Maine, dijo en una entrevista que votar&iacute;a en contra de si misma si la elecci&oacute;n pareciera cerrada en Maine. Al acceptar esto, la lista Verde declara su propia irrelevancia en el debate nacional.<p>
No podemos reconstru&iacute;r a la izquierda si no queremos que nuestras ideas tengan relevancia en el mundo real. De hecho, Shalom escribi&oacute; que el votar por Cobb es una manera de reconstruir a la izquierda sin darle ayuda inmerecida a Bush--en otras palabras, sin presentar un desaf&iacute;o que pudiera llegar a lastimar a Kerry y a los Dem&oacute;cratas en donde importa.<p>
A contrario, la campa&ntilde;a de Nader-Camejo--a pesar de los numerosos ataques viciosos por personas de la izquierda y de una campa&ntilde;a legal por los Dem&oacute;cratas para mantenerla fuera de la papeleta electoral alrededor del pa&iacute;s--intenta ofrecer una alternativa de izquierda a la gente que quiere votar en contra de la guerra y la ocupaci&oacute;n, en contra de la ley USA PATRIOT, y a favor del derecho al matrimonio de los homosexuales y de un plan de salud nacional.<p>
As&iacute; dijo el organizador de la campa&ntilde;a Nader-Camejo, Todd Chretien: "Como comprendieron Paine, Douglass, Parks, Lewis, Malcom, Mario, Gurley-Flynn y muchos otros, cualquier movimiento que tiene como meta el ganar, necesita aprender a pararse y defenderse presisamente cuando se encuentra en los momentos m&aacute;s oscuros. Solo de esta manera las millones de personas que detestan el sistema que los oprime pueden encontrar la confianza en si mismos para unirse y transformar a nuestro movimiento de una cuesti&oacute;n de protestas por una minor&iacute;a a un torrente de poder".<p>

<b>Esta elecci&oacute;n es un refer&eacute;ndum sobre la guerra en Irak. Imagina la reacci&oacute;n del pueblo de Irak si los estadounidenses re-eligen al hombre que invadi&oacute; a su pa&iacute;s y que mat&oacute; a tanta gente. Tenemos que asegurarnos de que Bush no consiga un mandato para su guerra contra el mundo.</b><p>

La fundadora del grupo Global Exchange, Medea Benjamin, lo puso de esta manera: "El mundo est&aacute; mirando y esperando sin ni siquiera parpadear, a ver si el pueblo estadounidense rechazar&aacute; la pol&iacute;tica de Bush. La &uacute;ltima vez que estuve en Irak, Ghazwan Al-Mukhtar, un ingeniero iraqu&iacute;, me dijo que, 'Saddam Hussein era un bastardo, pero esto no era una democracia, y nosotros no lo eligimos. Entonces sus malas acciones no eran hechas a nombre nuestro. &iquest;Puedes dec&iacute;r lo mismo de George Bush?'"<p>
"Nos debemos a nosotros mismos y al resto del mundo el asegurarnos de que Bush no pueda hablar m&aacute;s a nombre nuestro". Este ser&iacute;a un argumento convincente si las elecciones nacionales estubieran organizadas para despedir al presidente. Desafortunadamente, como la propia Benjamin sabe, la &uacute;nica manera de lograr esto es eligiendo a John Kerry.<p>
En "Una Carta Abierta a los Progresistas", Benjamin, Peter Coyote, Daniel Ellsberg y otras figuras importantes sostuvieron el argumento que "el &uacute;nico candidato que puede ganar en vez de Bush en Noviembre es John Kerry"--y motivaron el voto por Kerry en los estados en disputa. Si Kerry es elegido con un programa que pretende continuar la ocupaci&oacute;n de Irak, aumentando el numero de tropas ah&iacute;, e "internacionalizando" la ocupaci&oacute;n y otras cosas peores, &iquest;podr&iacute;amos decir que un voto por Kerry es un voto en contra de la pol&iacute;tica de Bush?<p>
Kerry se ha postulado abiertamente como el candidato que puede hacer que la ocupaci&oacute;n <i>funcione</i>--que no viene como ninguna buena noticia para los iraqu&iacute;es. Si el resultado termina siendo lo mismo para los iraqu&iacute;es--y para los soldados estadounidenses y sus familias--&iquest;por qu&eacute; ser&iacute;a mejor tener a Kerry hablando a nombre nuestro en vez de Bush?<p>
Al pueblo iraqu&iacute;--o a los campesinos colombianos, o de cualquier otro pueblo--que sentir&aacute; el peso de los ataques imperialistas estadounidenses, le da igual si es una administraci&oacute;n Dem&oacute;crata o una Republicana la que da las ordenes de bombardear a su pa&iacute;s o de armar a los paramilitares en contra suya.<p>

<b>Al Gore no hubiera invadido a Irak, y es menos probable que Kerry se vaya a la guerra en el futuro. Esto es suficiente motivo para votar por &eacute;l.</b><p>

"Si Gore hubiera sido el presidente, hubiera invadido a Afganist&aacute;n, pero dudo que hubiera invadido a Irak", el socialista y activista anti-guerra Tariq Al&iacute; le dijo a Doug Henwood el 6 de agosto en una entrevista de radio. "Esto es principalmente una agenda neo-conservadora, dominada por la necesidad de controlar el petr&oacute;leo y apaciguar a los israel&iacute;es. Esta guerra en Irak es algo que esta administraci&oacute;n ha perseguido absolutamente. La derrota de esta administraci&oacute;n ser&iacute;a una derrota para el partido pro guerra".<p>
El problema con el argumento de Tariq Al&iacute; es que no hay forma de comprobar esto. No sabemos si Gore hubiera invadido a Irak, y no sabemos lo que nos espera en el futuro; entonces no podemos predecir si Kerry llevar&aacute; a los Estados Unidos a m&aacute;s guerras.<p>
Lo que s&iacute; sabemos es que los Dem&oacute;cratas tienen una larga historia de presentarse como m&aacute;s moderados que los Republicanos, pero llevando siempre a cabo las mismas pol&iacute;ticas guerreristas. As&iacute; fue que en la elecci&oacute;n presidencial de 1964 Lyndon Johnson (LBJ) se postul&oacute; como el candidato de la paz en contra del "belicista" Barry Goldwater, y gan&oacute; una victoria arrolladora. Pero fue el mismo LBJ quien arreci&oacute; la guerra en Vietnam.<p>
El candidato a vicepresidente de Al Gore, Joe Lieberman, era uno de los principales agitadores pro-Israel en el gobierno estadounidense, y apoy&oacute; el Proyecto por un Nuevo Siglo Americano, panacea de los neo-conservadores. Durante la campa&ntilde;a a favor de la invasi&oacute;n de Irak el a&ntilde;o pasado, Lieberman a menudo apareci&oacute; en televisi&oacute;n criticando a Bush, &iexcl;por no movilizarse lo suficientemente r&aacute;pido! <p>
Sabemos que Kerry y Edwards votaron <i>a favor</i> de las guerras de Bush en Afganist&aacute;n e Irak. Sabemos que los dos justificaron el "cambio de r&eacute;gimen" en Irak mucho antes que Bush se adue&ntilde;ara del proyecto. Y el 10 de agosto, Kerry declar&oacute; frente a los medios que, sabiendo lo que ahora sabe sobre las mentiras de Bush y las ficticias "armas de destrucci&oacute;n masiva", hubiera votado comoquiera &iexcl;a favor de la guerra y apoyado la invasi&oacute;n! <p>
El programa Dem&oacute;crata, escrito principalmente por los funcionarios de Kerry, crit&iacute;ca a la administraci&oacute;n de Bush porque "no asign&oacute; recursos suficientes para llevar a cabo la misi&oacute;n" en Irak. Afirma que "con John Kerry como el comandante en jefe de las fuerzas armadas, no esperaremos nunca por una luz verde del extranjero cuando nuestra seguridad se encuentre en juego". En otras palabras, Kerry no va a renunciar su derecho a mandar tropas estadounidenses alrededor del mundo "unilateralmente".<p>
A pesar de que es cierto que los programas de los partidos no valen el papel en que est&aacute;n escritos, es dif&iacute;cil ignorar el mensaje que mandan los Dem&oacute;cratas con el desfile de ex-generales en su convenci&oacute;n--y la paliza pol&iacute;tica que le dieron a los delegados anti-guerra para que aceptaran un programa agresivamente pro-guerra. De echo, Kerry est&aacute; adoptando los puntos clave del programa neo-conservador--sin el lastre pol&iacute;tico de los neo-conservadores.<p>
Los anti-imperialistas como Tariq Al&iacute; y Noam Chomsky saben esto muy bien, y se opondr&aacute;n a las aventuras imperialistas que un presidente Kerry pudiera dirigir tanto como se oponen a las de Bush. Pero entonces, &iquest;no es esto buena raz&oacute;n para que no le perdonen nada hoy?<p>

<b>Me gustar&iacute;a votar por Nader, pero este a&ntilde;o no tenemos el lujo de votad de acuerdo a nuestros principios. Lo que est&aacute; en juego para los trabajadores y los oprimidos es demasiado.</b><p>

"La elecci&oacute;n presidenci&aacute;l de 2004 no es un debate entre votar por tus miedos o por tu consciencia", dice una declaraci&oacute;n de Greens for Impact--una organizaci&oacute;n de Verdes que incluye radicales conocidos como el autor de izquierda Normon Solomon. "No es un ejercicio academico o te&oacute;rico. Las vidas de la gente est&aacute;n en riesgo.<p>
"Las mujeres, las minor&iacute;as, la comunidad homosexual, los pobres y muchos otros, exepto los pocos ricos privilegiados, enfrentar&aacute;n las consecuencias reales del resultado de esta elecci&oacute;n. A consecuancia, debemos ver el efecto de nuestros votos colectivamente, no simplemente de acuerdo a lo que significa para nosotros individualmente".<p>
Esta declaraci&oacute;n es solo una de muchas similares que se pueden citar. Pero la verdad es que su pedido refleja los que los Dem&oacute;cratas reiteran en todas las elecciones. Los Dem&oacute;cratas siempre pueden contar con que los liberales, los l&iacute;deres sindicales y los de los derechos civiles--que se pasan casi todo el tiempo siendo ignorados o rechazados por el Partido Dem&oacute;crata--denuncien como "elitistas" a los activistas que quieren algo mejor que el Partido Dem&oacute;crata, acus&aacute;ndolos de que no les importan las graves consecuencias que sufrir&aacute; la gente com&uacute;n si gana el Republicano.<p>
Antes de chantajear en base a la clase y a la raza de la gente que quiere votar por una alternativa de izquierda que realmente refleje sus posiciones, estos l&iacute;deres debieran preguntarse que reciben a cambio de sus efuerzos por justificar el apoyo a los Dem&oacute;cratas. La respuesta es casi nada.<p>
Solo basta con observar el record de la administraci&oacute;n de Clinton. Durante los ocho a&ntilde;os de su mandato, los abortos se hicieron m&aacute;s dif&iacute;ciles de obtener. El porcentaje de trabajadores sindicalizados disminuy&oacute;. La disparidad en los ingresos se multiplic&oacute; <i>por factor 10</i>. La cantidad de gente en las prisiones (desproporcionalmente negra y latina) casi se duplic&oacute;. Y la cantidad de gente que fue expulsada el ej&eacute;rcito por ser homosexual tambi&eacute;n aument&oacute;. Y para colmo Clinton elimin&oacute; el sistema de asistencia social a los pobres.<p>
Entonces cuando los liberales hablan de que las vidas de la gente est&aacute;n en riesgo si gana un Republicano, deber&iacute;amos preguntar cuantas vidas han sido ya sacrificadas bajo el mandato de las administraciones Dem&oacute;cratas. Los Dem&oacute;cratas son c&oacute;mplices, no opositores, de estos ataques.<p>
Si los liberales y progresistas siempre desfilan tras los Dem&oacute;cratas y se oponen a cualquier alternativa de izquierda, las fuerzas corporativas que dirigen al partido exigir&aacute;n que los candidatos se muevan cada vez m&aacute;s hacia la derecha para proseguir con campa&ntilde;as "centristas"--marginalizando toda demanda de cualquier pol&iacute;tica que realmente beneficie al pueblo trabajador.<p>

<b>Por supuesto que debemos construir los movimientos. &iquest;Por qu&eacute; no podemos hacer las dos cosas--organizar luchas de base <i>y</i> votar por el "mal menor" el d&iacute;a de las elecciones?</b><p>

Parece muy sencillo: votar s&oacute;lo toma unos pocos minutos, y podemos dedicar el resto del tiempo a constru&iacute;r los movimientos. Pero si de veras crees que a trav&eacute;s de las elecciones pueda haber esperanza de cambio social, entonces "unos pocos minutos el d&iacute;a de las elecciones" no es suficiente. <p>
Este a&ntilde;o la confederaci&oacute;n sindical AFL-CIO gastar&aacute; una cantidad sin precedentes para propulsar el voto por Kerry. Esos millones se podr&iacute;an gastar, por exemplo, en sindicalizar a los trabajadores de Wal-Mart--cosa que adelantar&iacute;a la causa sindical mucho m&aacute;s. As&iacute; que esta estrategia de votar por mal manor desv&iacute;a nuestros recursos lejos de las luchas m&aacute;s importantes.<p>
<i>Obrero Socialista</i> no se opone como cuesti&oacute;n de principio a votar. A lo que nos oponemos es a que el pueblo trabajador desperdicie su voto en un candidato que est&aacute; en contra de ellos en todas las cuestiones m&aacute;s importantes. As&iacute; es que el movimiento por el matrimonio gay que emergi&oacute; este a&ntilde;o ha sido descarrilado y saboteado por los liberales que piensan que la prominencia del asunto podr&iacute;a hacerle da&ntilde;o a Kerry. Entonces se supone que los partidarios del matrimonio para los gays y lesbianas voten por un candidato que se opone expl&iacute;citamente a que los gays y las lesbianas se casen.<p>
Cuando los movimientos se alinean detr&aacute;s de Dem&oacute;cratas como Kerry, se debilitan. Se acostumbran a bajar sus expectativas y a dejar sus demandas en el limbo. Por eso es importante no conformarse con "Cualquiera Menos Bush"--y apoyar a una alternativa genuina que rompa con status quo bipartidista.<p>
<I>Traducci&oacute;n de Federico Moreno</I><P>


<?php include "../../legacy-includes/BottomNavLinksObrero.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdObrero.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
