<html>
<head>

<title>
Who was the real Jesus?
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="4">Was he calling for armed rebellion or preaching obedience?</font><BR>
<font face="Times New Roman, Times, serif" size="5"><b>Who was the real Jesus?</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">December 13, 2002 | Page 12</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>GEORGE W. Bush says that Jesus' teachings are the "foundation for how I live my life." However, with Christmas approaching, Bush seems to have forgotten all about "Blessed are the peacemakers" as he plans a war that will take thousands of Iraqi lives. As BRIAN JONES shows, a look at the historical roots of Christianity points to a different answer to the perennial question, "What would Jesus do?"</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3">
<P>THE FACT is that we know almost nothing about what Jesus did. Despite all that is attributed to Jesus--performing amazing miracles, healing the sick, turning water into wine, making the dead rise--none of his contemporaries seemed to notice him at all.</P>
<P>Not a single word was written about Jesus until at least 37 years after his death. The four books of the New Testament called the Gospels gave only one version of Jesus' life, which the Church deemed the official version 400 years after his death.</P>
<P>So we can't know what the real Jesus was like, or even if there was such a person--but only speculate based on what we know about the society around him and the religion that developed in the centuries after him.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3"><P>TWO THOUSAND years ago, Jerusalem was one of the largest and wealthiest cities in the Roman Empire. Many of its residents lived off of the commerce generated by flocks of pilgrims who came to visit the holy city and the Temple in particular.</P>
<P>The majority of Jews were artisans and traders who eked out a living on the margins of the economy. They sharply resented Roman rule and taxation and frequently lashed out at their oppressors in waves of riots and uprisings. The first to feel their anger were the rabbis and Jewish officials who collaborated with the Romans, ran the city, guarded the wealth of the Temple, and, in the process, grew wealthy themselves.</P>
<P>Ancient Palestine, and especially Jerusalem, was not only the birthplace of Christianity, but a hub of radicalism. Tensions between the rulers and the ruled flashed on and off for many years, and finally broke out into all-out war from 66 to 70 A.D.</P>
<P>Josephus, a Jew who was handsomely rewarded for switching over to the side of the Romans, wrote a detailed account of the revolt titled <I>The Jewish War</I>. He described Jerusalem as a seething cauldron of Jewish sects, some conservative and some quite radical, competing for the hearts and minds of the city.</P>
<P>The Pharisees and Sadducees, for example, adapted themselves to Roman rule--the Pharisees representing the followers of the old line of hereditary rabbis, and the Sadducees representing the corrupt class of Jewish collaborators.</P>
<P>The Essenes were a sect that sought to escape the evils of society by forming their own. "They eschew pleasure-seeking as a vice and regard temperance and mastery of the passions as a virtue," Josephus writes of the Essenes. "Contemptuous of wealth, they are communists to perfection."</P>
<P>Perhaps the most radical were the Zealots, who combined obedience to Jewish laws with organizing to overthrow the rich and powerful. Josephus identified the Zealots as the backbone of the resistance to the Roman army.</P>
<P>This is why parts of the Gospels burn with class hatred. In Luke 6:20, Jesus not only proclaims "Blessed are the poor," but also "Woe to you who are rich&#133;Woe to you who laugh now, for you will mourn and weep."</P>
<P>These words speak volumes about the early Christian movement--that it tried to appeal to the class anger brewing in ancient Palestine and was likely one of the many radical sects at war with the Romans. "Do you think I came to earth to bring peace?" Jesus says. "No&#133;I came to earth to bring fire, and how I wish it were already kindled!"</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3">
<P>OF COURSE, there's another side to the New Testament. At times, Jesus sounds as if he's advocating peace between the classes, discouraging class struggle and preaching obedience.</P>
<P>On one page, he instructs his followers, "If you don't have a sword, sell your cloak and buy one." (Luke 22:36). But a few pages later, he's angry that they took up arms: "Am I leading a rebellion, that you have come with swords and clubs?" (Luke 22:52).</P>
<P>There's an explanation for these contradictions. Christianity wasn't only a set of religious ideas, but an organization of human beings dealing with problems in the real world. Many believed that a victory over the Romans and the advent of the Messiah (or savior) went hand in hand. Countless individuals came forward claiming to be prophets, or to be the Messiah, and tried to lead attacks on the Romans. "[T]hey schemed to bring about revolutionary changes by inducing the mob to act as if possessed," wrote Josephus, "and by leading them out into the desert on the pretense that there God would show them signs of approaching freedom."</P>
<P>In 70 A.D., however, the Jewish revolt was defeated once and for all, the Temple destroyed and thousands slaughtered. The hope for "revolutionary changes" was crushed. The early Christian movement--and consequently the Gospels--was not only shaped by the revolt, but also by its defeat.</P>
<P>If Christianity's origins were in the struggle of the oppressed, then once hope of victory was extinguished, its message became consolation for the oppressed.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3">
<P>MANY PEOPLE were attracted to Judaism because of the promise of joining the "chosen people." And for an increasingly cosmopolitan population, the idea of living under the protection of a single God who watched over all lands and transactions, regardless of the local customs and beliefs, was an even stronger inducement.</P>
<P>Saul of Tarsus was a Jewish, Greek-speaking traveling artisan who "Romanized" his name to Paul--and in a manner of speaking, he "Romanized" Judaism as well. Paul dropped the strict rules about circumcision and diet, kept the class anger from the stories about the Jewish rebel named Jesus, and added the story of a resurrection that promises eternal life after death. That marked the real creation of a new religion.</P>
<P>The new religion had universal appeal--consoling the poor and providing the rich a sense of community and an outlet for protest against the abuses of the decaying empire, without actually threatening their own wealth. By advocating social equality only in the afterlife, Christianity protected the wealthy from the hatred of the poor, while recruiting both. Within two generations, the congregations were large enough to support full-time officials.</P>
<P>As the New Testament was written and rewritten hundreds of times, disagreements over what constituted the "official" message of Jesus broke out everywhere. Greater centralization of authority and organization was needed, and Christianity quickly became an institution, soon as vast as the Roman Empire itself. It penetrated the higher social layers, became better funded and eventually seduced even the emperors. In 330 A.D., it became the official--and brutally enforced--Roman religion.</P>
<P>The New Testament still reflects the early struggles, but was heavily edited over generations to sound more pro-Roman. So in the space of 500 years, the religious ideas of a poor Jewish sect fighting for revolution became the official religion of the world's largest empire, and--surviving the collapse of that empire--its church became the largest landowner in the world.</P>
<P>Contrary to the vision of society that Christians like George W. Bush advocate, the real Jesus most likely hated oppression and dreamed of a world of equality. The problem was that it could only be a dream. There wasn't enough wealth to go around for that to be a reality. Today, however, there is more than enough to provide for everyone on earth. The conditions exist for a truly equal society--socialism.</P>
<P>This holiday season, we should remind Bush and his oil baron buddies that it will be "easier for a camel to pass through the eye of a needle, than for a rich man to enter the kingdom of heaven"--when we organize a "judgment day" in this world. </P>

<?php include "../../legacy-includes/BottomNavLinks.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
