<html>
<head>

<title>
Sinking deeper
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<font face="Arial, Helvetica, sans-serif" size="2"><b>EDITORIAL</b></font><br>
<font face="Times New Roman, Times, serif" size="5"><b>Sinking deeper</b></font><p>
<font face="Arial, Helvetica, sans-serif" size="2">June 8, 2007 | Page 2</font><p>

<font face="Times New Roman, Times, serif" size="3">THE BUSH administration is lurching from one disaster to another in the Middle East. But the more they struggle to get out of the quicksand, the deeper they sink--and the higher their lies and hypocrisies pile up.<p>
Take the example of Iran--a point on the Bush administration's so-called "axis of evil" and target of threats of military attack by U.S. politicians of both mainstream parties.<p>
In mid-May, U.S. officials were circulating rumors that they expected a deadly "summer offensive" in Iraq--organized by al-Qaeda and other Sunni insurgents working in alliance with the <i>Iranian </i>government's Shia militia allies.<p>
Of course, al-Qaeda and the Shia militias in Iraq are sworn enemies, battling one another in a civil war that the U.S. stoked from the beginning of its occupation--but that didn't stop anonymous "U.S. officials in Baghdad" from peddling the "summer offensive" story to the media.<p>
This is the latest claim generated by the Washington rumor mill, along with Iran's supposedly imminent capability to produce nuclear weapons--or, for that matter, Iraq's nonexistent weapons of mass destruction and ties to al-Qaeda.<p>
On May 23, the U.S. amassed nine warships in the Persian Gulf in a show of force off the coast of Iran, the largest daytime assembly of ships since the 2003 Iraq invasion.<p>
Yet five days later, U.S. officials were meeting with Iranian officials in the first bilateral meeting of its kind in almost 30 years (this, of course, doesn't count the "unofficial" visit in 1986 of Robert McFarlane of the Reagan administration--to sell weapons to Iran and funnel the proceeds to the contra guerrillas fighting the left-wing government in Nicaragua).<p>
In the end, U.S. Ambassador to Iraq Ryan Crocker and Iranian Ambassador Hassan Kazemi-Qomi came out of the meeting with a lot more agreement than you might have thought after all the saber-rattling.<p>
"The terms put forth by the Iranians are so close to the U.S. position on Iraq that, with little exception, they could have been printed on State Department stationary and no one would have noticed the difference," noted Stratfor analyst Reva Bhalla.<p>
But during the week following the meeting, Secretary of State Condoleezza Rice had to bend over backwards to make assurances that Dick Cheney wasn't about to order an invasion of Iran.<p>
Meanwhile, in Iraq, three months after Bush ordered a "surge" of more than 20,000 troops to improve security, U.S. commanders say the operation has fallen far short of its goals. U.S. forces control fewer than a third of Baghdad's neighborhoods, according to a Pentagon assessment obtained by the <i>New York Times</i>.<p>
Violence, hunger and humiliation are still a day-to-day reality for most Iraqis. For example, in the Amiriya neighborhood in western Baghdad, a curfew imposed by U.S. troops and Iraqi authorities to "restore calm" between rival Sunni militant groups has cut off supplies of necessities.<p>
"We have already run out of meat, vegetables, mineral water and fuel for the generator," Amin, a father of five, told a reporter. "We have only flour and eggs, and are forced to drink dirty water. I have just eight blood pressure tablets left, and it will be a real catastrophe for me if I can't get more."<p>
May was the third-deadliest month for U.S. troops since the 2003 invasion, with 127 U.S. fatalities. "It is very clear that the number of attacks against U.S. forces is up" and they have grown more effective, Major Gen. James Simmons, deputy commander for operations in Iraq, told the <i>Washington Post.</i><p>
Even by the twisted standards of the Bush administration, the crisis has reached a new low. U.S. officials admit that "benchmarks" set for the Iraqi government won't be met, including passage of a proposed oil law. According to a report in the <i>Times, </i>White House officials are talking about reducing the number of troops in Iraq to 100,000 by September 2008.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">THE SPIRALING crisis in Iraq offers Democrats a superb opportunity to take a stand against the Bush White House.<p>
But after finally challenging the administration by attaching a highly qualified troop withdrawal to Bush's request for more than $100 billion in war spending, the Democrats last month backed away from the showdown--and handed "Mr. 28 Percent," as antiwar activist Cindy Sheehan called Bush, one of his few-and-far-between victories.<p>
According to an ABC News/<i>Washington Post </i>opinion poll, the Democrats' 24-point lead over Republicans on which party was providing leadership has collapsed into a dead heat. The overall job approval rating for Democrats dropped from 54 percent to 44 percent--with the poll attributing the decline almost entirely to the war spending vote.<p>
The Democrats had a chance to give voice to the antiwar majority in public opinion and increase the pressure on the Bush regime. Instead, they caved.<p>
Ultimately, the Bush administration's crisis and the Democrats' inability to take a stand have the same source.<p>
Because their top priority is maintaining U.S. economic, political and imperial power, the two mainstream parties face a common dilemma about Iraq. On the one hand, the catastrophe of the occupation has strained the world's most powerful military to the breaking point and stoked bitterness toward the U.S. in every corner of the world. On the other, withdrawing from Iraq would be the worse defeat ever for U.S. imperialism.<p>
So the Bush administration continues to buy time in the hope that U.S. fortunes will turn--and the Democrats retreat from any tough action, rather than bear the responsibility for admitting defeat.<p>
The key to putting an end to the occupation of Iraq lies outside Washington--in building on the anger at the politicians' inaction to organize a bigger, stronger and more determined antiwar struggle.<p>

<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
