<html>
<head>

<title>
The Middle East after the Iraq war
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="4">A roundtable discussion at Socialism 2003</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>The Middle East after the Iraq war</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">July 11, 2003 | Page 6</font></p>

<P><font face="Times New Roman, Times, serif" size="3">THE BUSH gang has made no secret of their plan to remake the Middle East--in whatever image they and their pals in Corporate America choose. The quick U.S. success in toppling the government of Saddam Hussein in Iraq was a step in this direction, and the U.S.-backed "road map" negotiations between Israel and the Palestinians represent another element.</P>
<P>But the quick war in Iraq has given way to a long and bloody occupation, and the road map has already been pushed off course by renewed violence. Meanwhile, far from producing a new era of stability, the invasion of Iraq has stoked generalized anger and opposition across the Middle East. What's next? Here, <I>Socialist Worker </I>reprints excerpts of a roundtable discussion from a meeting at the Socialism 2003 conference in Chicago last month. The speakers included:</P>
<P>--<b>NASEER ARURI</b> is the author of numerous books, including Dishonest Broker: America's Role in Israel and Palestine. He formerly served as a member of the Palestinian National Council.</P>
<P>--<b>RANIA MASRI</b> is a human rights advocate and director of the newly formed Southern Peace Research and Education Center, at the Institute for Southern Studies in Durham, N.C. She contributed to the books <I>Iraq Under Siege, </I>published by South End Press, and <I>The Struggle for Palestine, </I>published by Haymarket Books.</P>
<P>--<b>LANCE SELFA</b> is a columnist for <I>Socialist Worker. </I>He edited the recently released book <I>The Struggle for Palestine </I>and writes frequently for the <I>International Socialist Review.</i></P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<P><font face="Times New Roman, Times, serif" size="4"><B>Naseer Aruri</B></P>
<P><font face="Times New Roman, Times, serif" size="3">MUCH IS being said about the road map to Middle East peace, about the two sides having reached an agreement, and the rumors about when they will be released. One recent newspaper report said that the Palestinians have made their own announcement that the Israelis are accepting the settlement in principle--with the usual conditions. </P>
<P>So the road map has been pulled out of the drawer. As you know, it has been preceded by a lot of plans. As I look as these plans--which started with the Rogers plan in 1969, all the way up to today's plan--they seem to have always followed a general war in the Middle East, or a Palestinian Intifada [uprising]. Why is it that when we look at these American-backed plans--and I often wonder whether they were really meant for implementation--they seem to follow wars?</P>
<P>The Rogers Plan came after the 1967 war [waged by Israel against its Arab neighbors, which resulted in Israel seizing the Occupied Territories of Gaza and the West Bank]. The Rogers plan was supposed to be based on United Nations Resolution 242. In 1975, there was the Sinai Accords, which was a product of the shuttle diplomacy of Henry Kissinger. It came after another war in October 1973.</P>
<P>The Camp David agreement in 1978 also came after the 1973 war. The Reagan plan of 1982 followed almost immediately after the Israeli invasion of Lebanon. It didn't really talk about the occupation of Palestinian land, and it didn't say anything about the Palestinians, except that the Israelis would withdraw and deliver the area to Jordan, not to the PLO. You'll notice that even though these plans were promoted, presented and initiated by the sole peacemaker who was also the strategic partner of Israel--the U.S. government--nevertheless, in most cases, Israel rejected them.</P>
<P>The Shulz plan of 1988 came in the context of the Intifada. There was fear that the first Intifada would penetrate the Arab world--that it would be infectious and that there would be social revolutions erupting in the Arab world. So Mr. Shulz came up with his plan, which was disrespectfully rejected by Israeli Prime Minister Yitzhak Shamir, who said that the only part of the plan that he accepted was the signature of Secretary of State Schulz.</P>
<P>Obviously, the Madrid negotiations and the Oslo "peace" process were the product the so-called Gulf War of 1991--the Gulf Massacre against Iraq. Bush I--whose doctrine was "what we say goes"--wanted to tell the Israelis that the U.S. smashed the capability of Iraq as a state, and therefore you are not the superpower in the area. </P>
<P>Bush I wanted to let the Israelis know that the question of peace and war would have to be dealt with by the superpowers. From Madrid, they go to Oslo--though in between, there were many shuttles that the Israeli delegation made to Washington, but never arrived at an agreement until Israel was able to impose its conditions. And that's why there was an Oslo--because the Israeli conditions were accepted, at least implicitly.</P>
<P>If we look at these plans, why have they been so impossible to complete? The answer I've always given is that irrespective of who was at the helm in Israel--whether it was the Labor Party or the Likud Party or anyone else--there was a strategic position that the area that lies between the Jordan River and the Mediterranean Sea can't accommodate but a single sovereignty. And that is Israel.</P>
<P>There was so much nonsense about major differences between Likud and Labor. When you look at the Allon plan from back in 1967, you really see in it the elements of what exists today--that is to say, the so-called bantustanization solution. </P>
<P>If you look at the Sharon plan of the early 1980s, that also has these fragmented little bantustans for Palestinians, it is not in principle that different from Allon, except that with Allon, you had more territories for the Palestinians. By the time you got to Sharon, that territory only added up to about 42 percent of the West Bank. So there wasn't really much question that the Palestinians would not receive any form of sovereignty under any one of the plans.</P>
<P>Now we have the road map, which also followed a war--what they call the "war on terrorism," which is really the war for Pax Americana, the war for U.S. imperialism. The road map is a sound bite, an act on a stage. It's conflict management rather than a peace plan. It's described by the authors as performance-based--if you perform and live up to the requirements, you will me rewarded. So what will I get? I'll let you know later. </P>
<P>The road map is based on a number of strange notions that would be unacceptable to any self-respecting person. One assumption in the road map is that the Israeli occupation is normal and that resistance is abnormal--that's really the meaning of a unilateral ceasefire.</P>
<P>Give me a break. We're looking at Israel, a major regional superpower, and the Palestinians, a nationalist movement that has been battered over the years, especially in the spring of 2002. Ceasefire? The expectation here is that the ceasefire will be declared by the Palestinians unilaterally.</P>
<P>We're told that there were 100 conditions to the road map that the Israelis thought about late last year, and these conditions have been reduced to 14. By the time you read the road map, there's hardly anything left. </P>
<P>And the unilateral ceasefire that the Palestinians are expected to declare is not really sufficient for the Israelis because Israeli Prime Minister Sharon and his cabinet have been making is very clear that it's not a question of ceasefire. It's a question of dismantling of the "terror infrastructure"--i.e., we want Abu Mazen in charge of the Palestinian Authority, Mahmoud Abbas, the new prime minister.</P>
<P>Another assumption is that there is conditionality over reciprocity and mutuality here. The threshold of requirements is raised so high that it will be impossible perhaps for Abbas to meet the requirements made of him. </P>
<P>Like Oslo, there is a lot of gridlock in it. The language is problematic. Yet on the face of it, when you look at the road map, you find a lot of terms that were excised from Oslo. Oslo collapsed over the absence of a number of these crucial terms. The term occupation, for example, does not appear in the hundreds of pages of documents that make up Oslo. </P>
<P>The endgame of a Palestinian state, let alone the terms "independent" and "contiguous"--none of this was in Oslo, but all of these things appear in the road map. This certainly raises a question of why Sharon and his cabinet would accept this. Three of the parties in Sharon's cabinet campaigned on ethnic cleansing. They're advocates of transfer. So why would these people in the cabinet, together with Sharon--who has been talking about a state for the Palestinians in Jordan, and who have been urging Israeli people to go and grab these supposed illegal outposts--accept this?</P>
<P>Another important question is how come there was no mention whatsoever during this discussion about the road map of a reality on the ground that would certainly render any agreements superfluous--that is, the so-called separation wall that Israel is constructing to seal off the Occupied Territories.</P>
<P>The Palestinians call it the apartheid wall, while other people have referred to it as the new Berlin Wall. Here is a wall that is already 120 kilometers long. When finished, it will be 347 kilometers in length. </P>
<P>It's being done at the cost of $1.6 million per kilometer, so that comes out to $5.6 billion. I'm sure that part of that is being paid for by you and me--since Israel is dependent on aid from the U.S. government. As I speak of this, 12,000 Palestinians are being displaced. That includes 14 villages. There is a four-meter-deep trench on either side of the wall, a trace path to register footprints, an electronic warning fence with barbed wire and two-lane roads for the military patrols. </P>
<P>When all is said and done, you are talking about 232,000 people in 72 communities who will be affected by this. The estimated number of Palestinians who will be totally isolated by it, mainly in East Jerusalem, is between 250,000 to 300,000. Yet there is an absence of any discussion of this wall--which certainly is not consistent with the road map and all the talk about peace.</P>
<P>It seems to me that what Sharon is doing by raising the threshold so high is betting on Abbas' failure. There are enough loopholes and gridlock that would make it easy for Sharon to say, "Yes, I accept it in principle, with conditions, etc."</P>
<P>There is a 35-year-old legacy of a failed peace process. As long as the "peacemaker" is Israel's bankroller, chief military supplier, chief diplomatic backer and also co-belligerent, I don't think that we will really see any peace. </P>
<P>The issue of peace and war is long term, and peace cannot come from these ceasefire agreements. It will have to come through a long-range struggle that is going to affect both Palestinians and Israelis. The time for the two-state solution is gone. You may blame the architects of Oslo, who might have unwittingly paved the road for a single state and a single struggle.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<P><font face="Times New Roman, Times, serif" size="4"><B>Rania Masri</B></P>
<P><font face="Times New Roman, Times, serif" size="3">IF WE believed Fox, MSNBC and CNN, we would believe that we were in a really good situation--that the war is over, that the U.S. is liberating an oppressed people and, out of the goodness of our hearts, reconstructing this country. We should feel really good about ourselves--that's what we're told. </P>
<P>I wonder why we don't feel so good about ourselves. First of all, there's no postwar situation. The U.S. soldiers will tell you this. The Iraqis on the ground will tell you this. We have had, since Bush declared the war to be over on May 1, more than 55 U.S. soldiers killed by Iraqis. </P>
<P>The way it's presented in the press is as if these soldiers just happen to be touring the country. I want to stress very clearly that it is legal for people to kill an occupying force. But I say this very hesitantly, because we do not have a volunteer army. We have an army which people are forced to join because they don't have a job, because they don't have an education. </P>
<P>I regard the vast majority of these U.S. soldiers to be victims of this policy. They go there and kill, and they come home and they take that anger and that training to kill, and they direct it against their spouses. We have in military families across the country a much higher rate of domestic violence than we have in civilian families. We have to keep that in mind when we talk about the victims of this war. </P>
<P>We also have to keep in mind that what the U.S. and British soldiers are doing in Iraq looks exceeding like what the Israeli soldiers are doing to Palestinians in Ramallah--destruction of homes, terrorizing people at checkpoints, harassment, strip searching. And they are doing all of this in the name of security and self-defense. Iraq looks exceedingly like an occupied territory.</P>
<P>Not only is the war not over, but the war has continued. We can say that the war began with the British occupation of Iraq in the early 20th century--with that striving to first privatize Iraq's oil resources. And then continued with the U.S. influence in bringing the Baathist regime to power. The U.S. supported the Baathist war crimes and supported both Iraq and Iran during the Iran-Iraq war of the 1980s.</P>
<P>Then there are the U.S. phases of the war: Phase number 1, the Gulf War; phase number 2, the economic sanctions; phase 3, the 2003 bombing and invasion; and phase 4, the occupation and corporatization of Iraq. In no way, shape or form is the war over. And in no way, shape or form do any of us think that the country is liberated. The only liberation that is happening in Iraq is an economic liberalization. </P>
<P>This administration doesn't even have the know-how to build a democracy. And when I say that, I don't mean just the Republicans. I want to make that clear.</P>
<P>The majority of activists and leftists and organizers continue to use this word "reconstruction." Reconstruction is a very positive word. It means that if I destroyed a school, I rebuild the school. If I destroyed a hospital, I rebuild a hospital. But if I destroyed a school, and I rebuild a military camp, I don't see where the reconstruction is. </P>
<P>We don't have Iraq being reconstructed the way it was. We have Iraq being deconstructed--Iraq being transformed into something that the U.S. wants it to be. First, and most importantly, economically. The beauty of having the Bushies in power is that they really make it easy to analyze, because they just tell you what they are doing. When you have a Democrat in power, you have to try and figure it out. The Republicans just tell us. </P>
<P>[The U.S. colonial administrator] Paul Bremer has told us that Iraq is open for business--that the primary goal of the reconstruction is to shift Iraq away from a state-dominated economy and into a free-market system. Then you have what Bush has declared he wants, which is a U.S.-Middle East free trade area in 10 years. This will allow Israel not only to occupy our land militarily but also occupy our land economically.</P>
<P>It's all in the effort to privatize. Bremer spelled out his plan that contracts are pending to sell everything from oil technologies to transportation service, telecommunications, Iraqi ministries and everything else. When he spoke at the World Economic Forum, he laid out this plan: "Start reform of Iraq's financial sector in order to provide liquidity and credit for the Iraqi economy." Credit by who, liquidity of what? He said: "Remove the barriers for entry for new firms, remove the commercial laws, discourage private investment, lift unreasonable restrictions on property rights, develop an open-market trade policy, providing for a level playing field with regional trade partners."</P>
<P>They have told us exactly who they want to run the country. To run the oil sector, let's take the former head of Shell--because they did such a good job in Nigeria. To run the agriculture sector, the former senior executive of the Cargill Corporation, the biggest grain exporter in the world.</P>
<P>The consequences of this economic plan are horrendous, especially when we put them on top of the 12-and-a-half years of sanctions and the decades of oppression that the Iraqis have gone through. According to the UN World Food Program, one in five Iraqis suffers from chronic poverty already. And yet we had the former deputy high commissioner for refugees at the UN say that the challenges of enduring the sanctions may have been good preparation for the free market.</P>
<P>In other words, it's good that you suffered as you did, because you now have the thick skin to suffer some more. At the same time that their public sector is being privatized, as their social safety net is being removed, Halliburton will privatize Iraqi oil, and Bechtel will privatize Iraqi water, as they did in Bolivia.</P>
<P>Then there's Research Triangle Institute. Here's one that people don't really talk about because typically the way that we've evaluated corporations is whether they're in bed with the Bushies. Because the Research Triangle Institute has given zero dollars to the Republican Party, there's been no discussion about them. </P>
<P>But the Research Triangle Institute has a long history of moving public sectors to private corporations. In South Africa, they led the effort to privatize the water, which led to a situation in which the people of South Africa couldn't afford clean water--and to an outbreak of cholera killing 300 people that we know of. Research Triangle Institute is already working to privatize Iraqi water. </P>
<P>And the U.S. is deconstructing more than the economy. According to what they've told us, they plan to build three permanent military bases in Iraq. </P>
<P>It's no coincidence that the first foreign mission in Iraq that was ransacked, looted and destroyed was the Palestinian mission. Bremer has stated that the foreign policy that they want from the Iraqi-appointed government is to build relationships with Israel, open the oil pipeline to Haifa and basically surrender Palestinian rights and Palestinian solidarity. Add this on top of the fact that Israelis in large numbers are going into Iraq and purchasing large quantities of land and getting these "reconstruction" contracts. Add this to the fact that 90,000 Palestinians live in Iraq--like Palestinian refugees from Haifa--and they are now under threat of eviction. There's a new refugee camp in Iraq for these Palestinians. This an extremely dangerous situation.</P>
<P>I just want to end by reminding us all that are numerous ways we can examine the occupation of Iraq. We can either look at it through the lens of military occupation and the drive for empire. Or through the lens of racism that is ever-present in the U.S. and continuing to increase. </P>
<P>And in addition to these first two angles, we have to look at it through the lens of corporate power--and link the privatization effort that the U.S. is pushing in Iraq to the privatization effort that the U.S. government is pushing for us here at home. They're one and the same.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<P><font face="Times New Roman, Times, serif" size="4"><B>Lance Selfa</B></P>
<P><font face="Times New Roman, Times, serif" size="3">I WANT to start with what the U.S. won out of this war. Because in the face of massive world opposition, it invaded and occupied a country that posed no threat, had no credible means of defense--didn't even have the ability to protect its own airspace. It killed thousands of people--probably many more than we even know--and we're talking about an occupation that is going to be measured in decades probably. </P>
<P>The U.S. now believes that it is going to remake the Middle East, issuing threats right and left to Iran and Syria, forcing the "road map" for peace down Palestinians' throats. After establishing the "facts on the ground" by occupying Iraq, it got European countries that had opposed the war to sign onto the occupation--to agree to back this as a U.S.-British occupation through the UN Security Council.</P>
<P>And there's the demonstration effect of the war itself. The idea that it was a pre-emptive war was a message to other countries in and outside the so-called "axis of evil" that the U.S. was prepared to name enemies and go to war with them--so they'd better get in line right now. The neoconservatives who are the intellectual godfathers of this envision a series of what they call "small wars" to enforce U.S. domination.</P>
<P>I'd like to talk about Bush's lies about weapons of mass destruction. One recent UN report said that there was no credible evidence that Iraq had anything to do with al-Qaeda. We said all along that weapons of mass destruction as a reason for the war was a fabrication and a ruse to win popular support here in the wake of September 11--when the war was about something completely different.</P>
<P>We also argued that, despite the massive outpouring of opposition, the war was going to happen--that it wasn't going to be stopped. This was because of the politics of the war. Because it was a war for oil and empire as far as the U.S. government and the people in the driver's seat were concerned, they were going to make sure the war happened no matter what. They weren't going to let the UN stop it, and they weren't going to let Jacques Chirac get in their way. They were going to have a war. </P>
<P>The war wasn't driven finally by Dick Cheney or Halliburton--in other words, the U.S. didn't go in because Cheney is the head of Halliburton, though they were the beneficiaries, as Rania laid out. But beyond this, there was a desire to control the second-largest reserves of oil in the world. </P>
<P>Oil is a strategic resource to the U.S., and any country that has a stranglehold on that main resource has a political lever against all their rivals that could potentially be a challenge to the U.S., economically and militarily. The U.S. getting its hands on that oil, which will actually become more important in the future of the world economy, means that it will have a stranglehold over the world economy. And over the countries that are the main demanders of that oil in the future--predominately, India and China, countries that the U.S. sees as somewhere down the line in this century becoming potential rivals for control, or at least competitors on the Eurasian land mass.</P>
<P>Now there is a question about whether the U.S. can really remake the Middle East. The neoconservatives use a lot of ideological phraseology about spreading democracy--that Iraq is the first domino in a kind of reverse domino effect. </P>
<P>I have no idea whether the Bush people really believe this stuff or not. It sounds good on the think-tank circuit, but from our point of view, it's pretty unlikely that they really do mean this. Because if you look at what they're doing in Iraq--the U.S. is basically setting up a government whose only reason for being is to sign onto the alliances with Israel, to sign away Iraqi resources to U.S. corporations and so on.</P>
<P>Obviously, that's no democracy. We also know that if there was actual democracy in places like Saudi Arabia, it's very likely that whoever would get elected would not be the kind of people the U.S. would be interested in dealing with. So a lot of this stuff is hot air. But what they do want is "stable"--or pro-U.S.--governments. </P>
<P>What they also mean by remaking the Middle East--something that is probably closer to reality than the rhetoric--is to reorganize the structure of control and reorganize the deployment of U.S. troops and war materiel around the region. The want to redistribute the U.S. military footprint by putting all of their major military assets in small Gulf countries with small populations and ruling classes completely tied to the U.S. </P>
<P>Is Iran next on Bush's hit list? We have to say that it's certainly possible, because with Iraq out of the way, Iran is the major player in the Gulf that isn't in U.S. orbit. But after the war in Afghanistan and in the Gulf, the U.S. military essentially rings Iran with troops and bases. Bush has warned Iran already that it will not be allowed to have nuclear weapons. And his attack dog John Bolton, a State Department official now, slipped the leash the other day and actually said that the Bush administration would go to war to prevent Iran from getting nuclear weapons.</P>
<P>Invading Iran would not be like invading Iraq. The population is three times the size. The land mass is four times the size. The population has generally rallied around the regime when faced with foreign threat. It has more popular legitimacy in some ways in that Iran has an elected president. Unlike the U.S.</P>
<P>When they talk about going after Syria and Hezbollah, again, you're talking about going after a particular organization that is highly integrated into a society--and an organization that is looked on as nationalist heroes for having driven Israel out of Lebanon. This is big talk coming out of the U.S. administration. Whether they can actually pull this all off is still an open question. </P>
<P>They definitely have an advantage, but the war continues in Iraq, and each day that the war continues, resistance grows. Fifty-five U.S. soldiers have been killed since the end of the so-called war. And I think that number will only get bigger as the war goes on. At least a third or half of U.S. combat power is right now tied down in Iraq, and it looks like the Pentagon will have to increase that to put down what looks like the beginning of a developing mass anti-imperial, anti-colonial opposition to the occupation. </P>
<P>Like all empires before, the U.S. thinks that it's invincible. And the people in charge talk about how they're bringing civilization to backward people and all that. But they're setting themselves up for a fall, because the growing opposition to the occupation will continue. We must support it--and demand that the U.S. get out, with no qualifications. Our starting point is that the U.S. has to get out of Iraq.</P>
<P>The longer the occupation goes on, the more the question will exist in U.S. society. I think there is already a fair amount of questioning below the surface that never ends up in the opinion polls. </P>
<P>But many soldiers themselves and their families, when they hear these reports, have to ask, "What the hell are we doing there? Democracy? What is this?" The underlying result is that poor or working-class people from this country are being sent overseas to oppress other people. That has the same kind of effect it had in Vietnam. At the same time, back home, jobs are being cut, schools are growing worse, veterans' benefits are being cut. </P>
<P>You can see how the underlining class dynamics can come to the surface. It's our job to offer a political explanation for that and help get people to see the possibilities in that. To be better able to respond to these events--to not be confused by the lies that comes out in the media--we have to develop a clear anti-imperialist point of view. </P>
<P>This used to be thought of as leftist rhetoric. But in the last two years, imperialism and even the word itself has been rehabilitated for use by the right--held up as a good thing. Max Boot, one of the main ideologues of the right, has said: "If we want Iraq to avoid becoming a Somalia on steroids, we better get used to U.S. troops being deployed there for years, possibly decades to come. If that raises hackles about American imperialism, so be it. We're going to be called an empire whatever we do, so we might as well be a successful empire."</P>
<P>The people in this room will agree that we aren't interested in the U.S. being a successful empire. We're interested in that empire being stopped. We're interested in giving solidarity to those fighting against it. We're interested in helping to organize a resistance to it here. We're interested in seeing it defeated. </P>
<P>Forget Max Boot. It's better to talk about someone like Mark Twain, who said over 100 years ago--in relationship to the U.S. occupation of the Philippines--that he used to think of himself as an imperialist because he believed the idea that the U.S. was brought into the world to spread democracy. But, he said, "The more I've thought about it since, I've seen that we do not intend to free but to subjugate the people of the Philippines. We've gone there to conquer, not to redeem. So I am an anti-imperialist, I am opposed to having the eagle put its talons on any other land."</P>
<P>That's where we stand. We are opposed to the eagle spreading its wings in the Middle East and anywhere else in the world. We have to commit ourselves to build an antiwar movement that also sees anti-imperialism at the core of its struggle. The antiwar movement was a tremendous upsurge around the world, and we have to state that proudly. </P>
<P>But we also recognize that it didn't stop the war. We don't draw the conclusion that this was impossible. We have to get into a dialogue with people who were involved in it and say that the underlying reason we were not able to stop the war is because of the system drove that war. </P>
<P>We have to draw the conclusion that it's not good enough to organize an antiwar movement, or even an anti-imperialist movement. We have to organize a movement to get rid of the system that breeds wars. We need to talk about building a socialist alternative as well.</P>


<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
