<html>
<head>

<title>
"Standing up against hatred"
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<font face="Times New Roman, Times, serif" size="4">Protesting anti-Muslim cartoons</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>"Standing up against hatred"</b></font><p>
<font face="Times New Roman, Times, serif" size="2"><b>By Hank Levine and Elizabeth Schulte</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | March 10, 2006 | Page 12</font><p>

<font face="Times New Roman, Times, serif" size="3">RIGHT-WINGERS tried to fan the flames of anti-Muslim and anti-Arab hate at the University of California-Irvine (UCI) on February 28, sponsoring a meeting titled "Unveiling the Cartoons."<p>
Following the lead of a few college newspapers that reprinted cartoons depicting the prophet Muhammad as a terrorist, the UCI College Republicans sponsored the public meeting to display the offensive caricatures.<p>
But Arabs, Muslims and their supporters didn't take this provocation sitting down. As many 1,000 people turned out to counter the racists' message, outnumbering the Republicans' audience.<p>
"We are standing up against racism and hatred. We are not going to let it happen, not here," said Quanita of the Muslim Student Union (MSU). Students at the protest wore armbands to express their solidarity and held banners saying "Stop Islamophobia!"<p>
The protest brought together a variety of student and activist groups--such as Students for Peace and Justice, the African Student Union and the Pakistani Student Association. New alliances were formed to fight bigotry directed against Muslims. Students from neighboring colleges carpooled from Los Angeles, Riverside and San Diego to join the demonstration.<p>
The right-wing meeting was organized by the United American Committee (UAC), which isn't a UCI group but was allowed to hold its event because, despite requests from the MSU, the College Republicans agreed to sponsor it.<p>
Groups like the UAC sponsor these events in the name of freedom of speech. But in the advertisement for the meeting, the UAC promised to "address the issue of mainstream Islamic organizations who may act as apologists for terror" and "delve into activities of certain groups and will seek to answer questions over exactly where allegiances lie in these troubling times."<p>
In other words, to spread fear and suspicion about Arabs and Muslims. "The agenda is to spread Islamophobia and create hysteria against Muslims similar to what happened to the Jews in Nazi Germany," said Osman Umarji, an Irvine graduate and former MSU president.<p>
The confidence of groups like the UAC to spread their filthy ideas is tied to the general climate of anti-Arab hysteria generated by the U.S. "war on terror."<p>
"There's a sentiment that it is okay to be anti-Muslim and anti-Arab," Ahmed Rehab, Chicago communications director for the Council on American-Islamic Relations, said in an interview. "It's not okay to be anti-Black or anti-Jew right now--it's out of vogue. It's quite in vogue to be anti-Muslim and anti-Arab, and that's really unfortunate and has to change because bigotry against one is bigotry against all. <p>
"Those individuals who are leading the anti-Muslim battle are doing so for their own political purposes...We need to be vigilant as to their rhetoric and discourse, and not fall for it and not be dragged into it. There is not clash of civilizations; there is no inherent war with Islam that we are fighting, and we have to come to terms with that."<p>
In protests and public meetings, antiracists are starting to get organized. Last week, more than 100 people turned out for a meeting sponsored by the Brooklyn-based Coney Island Avenue Project titled "Being Muslim Is Not a Crime." <p>
The meeting linked law enforcement's victimization of Arab and Muslim immigrants and the climate of suspicion that has been whipped up in the aftermath of September 11. Tushar Sheth of the Asian American Legal Defense and Education Fund, spoke about how the New York police have exploited loopholes in the law to inquire about immigrant status and harass immigrants. <p>
Speakers also highlighted the demonization of Arabs for political gain during recent revelations that U.S. ports were set to be managed by a business based in the United Arab Emirates. This includes a comment by New Jersey Democratic Sen. Frank Lautenberg, who said, "We wouldn't transfer the title to the devil; we're not going to transfer it to Dubai."<p>
We have to organize to oppose anti-Arab and anti-Muslim attacks, in whatever form they take.<p>
<i>Deepa Kumar and Aaron Amaral contributed to this report</i>.<p>

<?php include "../../legacy-includes/BottomNavLinks.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
