<html>
<head>

<title>
&iquest;Cu&aacute;les son los pr&oacute;ximos pasos para el movimiento pro inmigrante?
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<font face="Times New Roman, Times, serif" size="5"><b>&iquest;Cu&aacute;les son los pr&oacute;ximos pasos para el movimiento pro inmigrante?</b></font><p>
<font face="Times New Roman, Times, serif" size="2"><b>Por Lee Sustar</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | 5 de marzo de 2007 | Bolet&iacute;n de Obrero Socialista</font><p>

<font face="Times New Roman, Times, serif" size="3">EN MEDIO de crecientes redadas en contra de los trabajadores indocumentados y una nueva oleada de legislaci&oacute;n anti-inmigrante al nivel estatal, el movimiento por los derechos de los inmigrantes, est&aacute; debatiendo que es dable esperar y como reaccionar ante la legislaci&oacute;n migratoria discutida en el Congreso, mientras construye redes de respuestas r&aacute;pidas para proteger a la comunidad inmigrante contra las redadas.<p>
Lo que est&aacute; apareciendo es una estrategia condensada en la frase "legalizaci&oacute;n para todos", que consiste en rechazar cualquier propuesta legislativa que solo incluya en los programas de trabajadores hu&eacute;spedes a los trabajadores indocumentados que hayan vivido en los EE.UU. por un per&iacute;odo determinado de tiempo, excluyendo al resto.<p>
Esta idea tiende a unificar tanto a las organizaciones que han aceptado el programa de trabajadores hu&eacute;spedes como a grupos de militantes en derechos de los inmigrantes m&aacute;s radicalizados que se oponen a tales medidas por considerar que las mismas crean ciudadanos de segunda clase, seg&uacute;n sostiene Nativo L&oacute;pez, presidente de la Asociaci&oacute;n Pol&iacute;tica Mexicano-norteamericana. "Legalizaci&oacute;n para todos, as&iacute; como la desmilitarizaci&oacute;n de la frontera, se han transformado en una base m&iacute;nima para la alianza", dijo L&oacute;pez en una entrevista.<p>
Basado en su experiencia en las recientes conferencias realizadas en Los Angeles el 19 y 20 de enero y en Phoenix el 3 de febrero, que juntaron una amplia gama de grupos pro inmigrantes y sindicatos, L&oacute;pez dijo que cree que la mayor&iacute;a de los activistas "no aceptan la idea de que se deba renunciar a los derechos adquiridos, como el debido proceso y su correspondiente revisi&oacute;n judicial, a cambio de una visa temporaria".<p>
Como una alternativa a las propuestas de trabajadores hu&eacute;spedes, L&oacute;pez propone que todos los inmigrantes puedan buscar trabajo bajo el programa vigente de certificaci&oacute;n del Departamento de Trabajo.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">DESDE LA primavera pasada, cuando en el movimiento el nivel de movilizaciones alcanz&oacute; un nuevo pico, el tema de los trabajadores temporarios se ha convertido en pol&eacute;mico.<p>
Esas protestas reflejaron la unidad del movimiento por los derechos de los inmigrantes en oposici&oacute;n a la HR 4437, una propuesta de ley patrocinada por el representante republicano James Sensenbrenner de Wisconsin que hubiera puesto en situaci&oacute;n delictiva a cerca de 12 millones de trabajadores indocumentados y a todos aquellos que los ayudasen.<p>
Pero el movimiento se dividi&oacute; sobre la legislaci&oacute;n propuesta por el Senado, y promovida por el sector empresarial, que hubiera acrecentado la aplicaci&oacute;n de la ley y creado un sistema de tres categor&iacute;as de trabajadores hu&eacute;spedes atando el status migratorio de los trabajadores a sus empleadores.<p>
La propuesta definitiva de la ley, conocida como Hagel-Mart&iacute;nez por los dos senadores que la patrocinaron, fue tan mal vista, que incluso muchos de quienes al comienzo la apoyaron, opinaron que era mejor que ninguna legislaci&oacute;n fuera aprobada antes de las elecciones de noviembre.<p>
Ahora, son las grandes empresas las que est&aacute;n al tim&oacute;n de una nueva propuesta de ley migratoria del congreso con mayor&iacute;a dem&oacute;crata, y una vez m&aacute;s, el esfuerzo es apoyado por el Sindicato Internacional de Empleados de Servicios (SEIU) y UNITE HERE, el sindicato textil y de personal de hoteler&iacute;a. Auto-titul&aacute;ndose la Alianza pro reforma Migratoria 2007, esta coalici&oacute;n llev&oacute; a cabo una conferencia de prensa telef&oacute;nica el 18 de enero llamando a reintroducir una legislaci&oacute;n basada en los principios de la Hagel-Mart&iacute;nez.<p>
Presentada como el proyecto de ley S 2611 fue apropado por el senado pero no logr&oacute; convertirse en ley. El proyecto Hagel-Mart&iacute;nez hubiera dividido a los trabajadores inmigrantes en tres categor&iacute;as, y al menos 2 millones hubieran sido forzados a abandonar el pa&iacute;s.<p>
Esta divisi&oacute;n en tres categor&iacute;as ser&aacute; la base probable para cualquier legislaci&oacute;n futura, de acuerdo con Tamar Jacoby del neoconservador Manhattan Institute. "Existe la idea de que con los Dem&oacute;cratas [controlando el Congreso], las tres categor&iacute;as ser&aacute;n desechadas", dijo en una conferencia de prensa. "Nadie de nosotros cree que esto ocurra".<p>
Eliseo Medina vicepresidente del SEIU, que tambi&eacute;n estuvo en la conferencia de prensa telef&oacute;nica, coincidi&oacute; con Jacoby, aun cuando el sindicato dej&oacute; constancia de su oposici&oacute;n al sistema de tres categor&iacute;as contenidos en el proyecto Hagel-Mart&iacute;nez, mucho despu&eacute;s que el proyecto expir&oacute; cuando el anterior Congreso cerr&oacute;.<p>
Hagel-Mart&iacute;nez hubiera creado un engorroso "camino a la ciudadan&iacute;a" para aquellos que hubieran vivido en el pa&iacute;s cinco a&ntilde;os o m&aacute;s, forzando a aquellos con m&aacute;s de dos a&ntilde;os y menos de cinco a salir del pa&iacute;s y re-entrar para solicitar una categor&iacute;a temporaria, excluyendo al resto.<p>
El Consejo Nacional de la Raza apoy&oacute; una vez m&aacute;s el programa de trabajadores hu&eacute;spedes como parte de lo que los funcionarios de la organizaci&oacute;n llaman un arreglo necesario.<p>
El Sindicato Internacional de Empleados de Servicios (SEIU) , como sea, ha cambiado su tono. A pesar de que el sindicato hab&iacute;a apoyado la Hagel-Mart&iacute;nez, el presidente y la tesorera del SEIU, Andrew Stern y Anna Burger, escribieron hace poco al Senador Ted Kennedy (Dem&oacute;crata por Massachussets) que ya que el proyecto de ley "afortunadamente muri&oacute;," el nuevo Congreso deber&iacute;a tomar una perspectiva diferente.<p>
Y agregaron: "El Congreso no deber&iacute;a estar satisfecho con un programa que legalizar&iacute;a entre 6 y 8 millones, cuando alrededor de 11 a 12 millones de individuos est&aacute;n indocumentados viviendo dentro de nuestras fronteras". "Debemos enfrentar el hecho de que a&uacute;n siendo respetuosos de las leyes, los trabajadores indocumentados que residen por muchos a&ntilde;os, no van a salir del pa&iacute;s voluntariamente."<p>
Renee Saucedo del Centro La Raza, un grupo comunitario de San Francisco que da apoyo legal a jornaleros manifest&oacute; que si bien el SEIU retir&oacute; la palabra "hu&eacute;sped" y ahora aboga por un programa "nuevo trabajador", no ha cambiado el hecho que aun est&aacute; colaborando con los empleadores para crear una amplia categor&iacute;a de trabajadores con menos derechos.<p>
"Est&aacute;n tratando de endulzarlo," dice Saucedo quien tambi&eacute;n es miembro del SEIU. "Ellos dicen que no se trata del viejo programa bracero donde est&aacute;s atado a un empleador. Desafortunadamente no por eso es menos da&ntilde;ino. Los programas de trabajadores hu&eacute;spedes condicionan el status migratorio al empleo, lo que facilita la explotaci&oacute;n del trabajador inmigrante."<p>
"No entiendo porqu&eacute; un sindicato apoya esto cuando hay otras opciones," tales como una simple residencia, dijo ella.<p>
Ana Avenda&ntilde;o, consejera general asociada de la AFL-CIO, tambi&eacute;n cree que un reordenamiento del proyecto Hagel-Mart&iacute;nez no desafiar&iacute;a el marco legal que crear&iacute;a ciudadanos de segunda clase entre los trabajadores indocumentados. Ella rechaz&oacute; el argumento hecho por algunos que apoyan el proyecto Hagel-Mart&iacute;nez, tal el caso del representante Luis Guti&eacute;rrez, Dem&oacute;crata por Illinois, que sostiene que un programa de trabajadores hu&eacute;spedes al menos ofrece una alternativa humana al cruce de los desiertos en la frontera muchas veces mortales.<p>
"Son tr&aacute;gicas las muertes en el desierto, pero todos los d&iacute;as un trabajador mexicano muere en su trabajo en los EE.UU., y esto es igualmente tr&aacute;gico", dijo. "No podemos enfocarnos solo en las muertes en el desierto e ignorar las muertes en los lugares de trabajo. Y al establecer un programa de trabajadores hu&eacute;spedes es exactamente eso lo que hacemos."<p>
Incluso si el sistema de categor&iacute;as propuesto por el proyecto Hagel-Mart&iacute;nez es desestimado, el hecho es que los trabajadores hu&eacute;spedes carecer&aacute;n de sus derechos. Ya que la estrategia de "legalizaci&oacute;n para todos" puede ser interpretada para incluir el programa de trabajadores hu&eacute;spedes, la unidad con respecto a este eslogan puede mover hacia la derecha a los grupos pro inmigrantes que en el pasado han abogado por la amnist&iacute;a.<p>
As&iacute; mientras el Congreso debate una legislaci&oacute;n migratoria que crear&aacute; un sistema de trabajadores temporales, el movimiento por los derechos de los inmigrantes estar&aacute; una vez m&aacute;s envuelto en sus propios debates sobre si el compromiso es aceptable.<p>
Cualquiera que sea la legislaci&oacute;n que salga del Congreso, seguramente va a contener disposiciones m&aacute;s estrictas con el fin de capturar los votos de los republicanos y servir de pantalla derechista a los dem&oacute;cratas. Como lo declarara Jacoby del Manhattan Institute en la conferencia de prensa telef&oacute;nica de la Alianza por la Reforma Migratoria 2007. "Hay que restablecer la mano dura y el imperio de la ley".<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">LA MANO dura, por supuesto, ya est&aacute; en su apogeo, con las redadas en fuentes laborales llevadas a cabo por la Oficina de Inmigraci&oacute;n y Aduanas (ICE) del Departamento de Seguridad Interior (DHS), y con las polic&iacute;as locales que han comenzado a aplicar la ley federal de inmigraci&oacute;n bajo presi&oacute;n de los pol&iacute;ticos anti-inmigrantes.<p>
Las legislaturas estatales propusieron un total de 550 proyectos de ley anti-inmigrantes en el a&ntilde;o 2006, 75 de las cuales se convirtieron en ley, de acuerdo con la Conferencia Nacional de Legislaturas Estatales.<p>
Legisladores en Georgia, Arizona, Virginia, Colorado, Texas, Carolina del Sur y otros estados han redactado sus propias leyes al estilo de la Sensenbrenner que impide el acceso de los indocumentados en las escuelas p&uacute;blicas, en la ayuda social, niega licencias de conducir, y mucho m&aacute;s. Un legislador de Arizona desea impulsar un plebiscito para penalizar dentro de su estado a los indocumentados.<p>
Los federales, sin tener una legislaci&oacute;n del congreso que los avale, ponen el tono para estos ataques con altamente publicitadas redadas, como la realizada por la migra a las plantas faenadoras de carne de Switf &amp; Co, llevada a cabo en seis estados el pasado mes de diciembre. En la ocasi&oacute;n 1.282 trabajadores fueron arrestados, 247 de ellos acusados de robo de identidad, y para mediados de febrero 300 hab&iacute;an sido deportados. En la actualidad contin&uacute;an las deportaciones de acuerdo al ICE.<p>
Mart&iacute;n Unzueta, quien es parte del Chicago Workers Collaborative, un grupo por los derechos laborales de los inmigrantes, dice que las acusaciones por robo de identidad son un pretexto. "Los trabajadores que compran un n&uacute;mero falso de seguridad social no tienen idea a quien pertenece, y muchos n&uacute;meros ni siquiera existen", dijo Unzueta, quien est&aacute; ayudando a organizar una red de respuestas r&aacute;pidas para aquellos afectados por las redadas en el &aacute;rea de Chicago.<p>
M&aacute;s a&uacute;n, en las redadas a Swift, obreros latinos fueron racialmente discriminados, segregados de los afro-americanos y anglosajones por agentes del ICE armados hasta los dientes, se&ntilde;al&oacute; Avenda&ntilde;o de la AFL-CIO. Al mismo tiempo el castigo para los empleadores luego de estas redadas no ha sido m&aacute;s que simb&oacute;lico.<p>
Al contrario, funcionarios del DHS han estado presionando a los empleadores para que ellos mismos se conviertan en agentes migratorios. Esto requiere que se expanda el programa piloto que verifica los n&uacute;meros de la seguridad social en una base de datos en l&iacute;nea, la que es frecuentemente incorrecta, a uno m&aacute;s extenso conocido como el Acuerdo Mutuo del ICE entre Gobierno y los Empleadores ( IMAGE por sus siglas en ingl&eacute;s).<p>
Bajo IMAGE, los empleadores le permiten al ICE monitorear los documentos de status migratorio, conocidos como "formularios I-9", as&iacute; como los n&uacute;meros de seguridad social. "Lo positivo para quienes participan es que ellos est&aacute;n mejor equipados para saber si su fuerza laboral es legal, y es menos probable que ICE llegue a golpear a sus puertas inesperadamente, interfiriendo con sus actividades," dijo el agente del ICE Matthew Allen al <i>Washington Post.</i> "Es una inversi&oacute;n el mantener una fuerza laboral segura."<p>
Smithfield Food obtuvo un reembolso en la inversi&oacute;n en IMAGE en enero pasado cuando agentes del ICE arrestaron a 21 trabajadores en la enorme planta procesadora de puercos que la compa&ntilde;&iacute;a posee en Carolina del Norte, all&iacute; donde la empresa viene resistiendo ferozmente a la sindicalizaci&oacute;n de los trabajadores por a&ntilde;os.<p>
"Uno puede decir que [los funcionarios del ICE] est&aacute;n tratando que los empleadores se comprometan m&aacute;s con el programa de verificaci&oacute;n y la alternativa presidencial de un amplio programa de trabajadores hu&eacute;spedes", dijo L&oacute;pez.<p>
Acordando en el mismo sentido Justin Akers Chac&oacute;n, coautor del libro <i>No One is Illegal, </i>expres&oacute;: "Aunque los empleadores puedan ser 'castigados' por sus acciones, ellos no constituyen el verdadero blanco". "Identificar y arrestar trabajadores indocumentados, o demostrar el potencial para hacerlo, es una estrategia para presionar el acatamiento de los sindicatos con el programa de trabajadores hu&eacute;spedes, y para condicionar a los trabajadores a un rol pasivo".<p>
Avenda&ntilde;o espera que esta modalidad contin&uacute;e. Mientras los empleadores necesitan el trabajo de los inmigrantes, ellos pueden evadir las penalidades si colaboran con la DHS seleccionando a determinados trabajadores a fin de intimidar al resto, manteniendo los bajos salarios y no permitiendo la sindicalizaci&oacute;n de los trabajadores, a la vez que, dijo Ana Avenda&ntilde;o "tener a su disposici&oacute;n un interminable fondo de mano de obra para poder explotar".<p>
"En los procedimientos de aplicaci&oacute;n de la ley se ignoran los derechos civiles y de los trabajadores", y agreg&oacute;, "Ahora vemos m&aacute;s autorizaciones para que la polic&iacute;a local act&uacute;e como agentes de la ICE".<p>
En el futuro, un constante flujo de cartas federales "No match" se&ntilde;alando discrepancias entre los n&uacute;meros de seguridad social del trabajador y los que se encuentran en los archivos del gobierno va a incrementar la presi&oacute;n.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">EE.UU. no va a deportar a los doce millones de trabajadores indocumentados, pero ha creado un aparato de aplicaci&oacute;n de la ley por medio de la cual podr&iacute;a deportar a cualquiera de ellos en cualquier momento, dando as&iacute; una enorme ventaja a los empleadores.<p>
El Congreso no se interesa en las violaciones a los derechos humanos. "En el congreso no hay nadie que quiera tomar medidas en estos temas", dijo Avenda&ntilde;o, se&ntilde;alando que el Senador Jeff Sessions, Republicano por Alabama, recientemente obtuvo una votaci&oacute;n de 94 a 0 a favor de una enmienda al proyecto de ley del sueldo m&iacute;nimo que proh&iacute;be a las compa&ntilde;&iacute;as contratar trabajadores indocumentados por siete a&ntilde;os a menos que adhieran al programa piloto b&aacute;sico, que las har&iacute;a inmune a tales penalidades.<p>
Por fuera de los lugares de trabajo, los agentes de la ICE agresivamente se han desplazado hacia los barrios inmigrantes, por ejemplo con la Operaci&oacute;n Wrangler que supuestamente estaba dirigida a inmigrantes envueltos en la distribuci&oacute;n de drogas, o la Operaci&oacute;n Return to Sender, dirigida a aquellos que han fallado en cumplir con las ordenes de deportaci&oacute;n.<p>
Fue nada menos que el secretario del DHS, Michael Chertoff quien dejo escapar que las redadas eran parte de una perspectiva migratoria de buen-polic&iacute;a-mal polic&iacute;a de la administraci&oacute;n Bush.<p>
"Cada vez que un agente de la Guardia Fronteriza transporta un cargamento de personas que se desempe&ntilde;ar&aacute;n en el servicio dom&eacute;stico o jardineros a alg&uacute;n lado para ser retornados, no est&aacute; buscando narcotraficantes ni cargamentos de drogas," Chertoff les dijo a los reporteros en la Ciudad de M&eacute;xico el 16 de febrero. "As&iacute; que para mi, una reforma migratoria completa que tome en cuenta a los inmigrantes econ&oacute;micos de hecho facilitar&iacute;a la aplicaci&oacute;n de la ley, porque nos permitir&iacute;a enfocarnos m&aacute;s en la gente que nosotros no queremos en el pa&iacute;s bajo ninguna circunstancia, o sea los criminales y gente peligrosa."<p>
Con la mano dura del ICE y los gobiernos estatales por un lado y las maniobras pol&iacute;ticas del Congreso por el otro, el movimiento por los derechos de los inmigrantes esta desarrollando planes de protesta, cabildeo y campa&ntilde;as de defensa en las semanas y meses venideros, dijo Jose Artemio Arreola, miembro del concejo ejecutivo del Local 73 de la SEIU en Chicago y una figura clave en el Movimiento 10 de Marzo, que organizara la primera marcha masiva del a&ntilde;o pasado.<p>
Mientras solo algunos de los grupos por los derechos de los inmigrantes que el a&ntilde;o pasado lideraron las marchas han asumido el llamado a repetir el boicot del 1ro de Mayo, ese d&iacute;a seguramente se transformar&aacute; en un foco de renovado activismo por los derechos de los inmigrantes.<p>
"No quiero que ninguno sea excluido," de la legislaci&oacute;n migratoria, dijo Arreola. "Necesitamos aumentar la presi&oacute;n."<p>
<i>Traducido por Orlando Sep&uacute;lveda y Roberto Platzer</i><p>

<!--#include virtual="/legacy-includes/BottomNavLinksObrero.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdObrero.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
