<html>
<head>

<title>
Can NYC labor stop cuts?
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="4">Rally draws 30,000, but union leaders have no strategy</font><BR>
<font face="Times New Roman, Times, serif" size="5"><b>Can NYC labor stop cuts?</b></font></P>
<P><font face="Times New Roman, Times, serif" size="2"><b>By Michael Ware</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | May 9, 2003 | Page 11</font></P>
<font face="Times New Roman, Times, serif" size="3"><P>NEW YORK Mayor Michael Bloomberg threw 3,000 city workers out of work on May 2, just days after 30,000 rallied outside City Hall to protest budget cuts and layoffs--and some 1,400 more layoffs will soon follow. The rally, called by AFSCME District Council 37, was the union's first major response to the mayor's attack on city workers and social services.</P>
<P>As <I>Socialist Worker</I> went to press, Bloomberg and state legislators gave some ground, claiming to have reached a compromise that will avert further cuts to social services and more layoffs by raising taxes on higher incomes. The compromise still burdens the working class with higher taxes to resolve the deficit, however. State income tax will rise and sales tax in New York City will increase by three-eighths of a percent.</P>
<P>A three-year surcharge on individuals making over $100,000 a year will generate $400 billion. But Gov. George Pataki--like Bloomberg, a Republican--adamantly opposes any tax increases, staking out a pro-business position in the hope of gaining a national spotlight. He could veto the compromise, although legislators seem confident they could override.</P>
<P>Of course, business is screaming foul play, claiming every corporation will soon leave town. And with contract negotiations for city workers and teachers in their early stages, union workers will soon be asked to sacrifice again even if the deal goes through.</P>
<P>And despite the size of the rally, union leaders ducked the question, "What next?"</P>
<P>"People are upset (about layoffs)," Kenneth Mercer, a shop steward in AFSCME Local 1407, told <I>Socialist Worker</I>. "People have got mortgages, families to feed. Everyone's on edge right now."</P>
<P>Antiwar forces joined the march, and representative for United for Peace and Justice spoke onstage highlighting the hypocrisy of spending billions on war while education, health care and jobs suffer. The fact that municipal union leaders would appear on the same stage with antiwar voices is noteworthy.</P>
<P>Missing from the demonstration, however, were public school teachers and transit workers, whose union leaders spoke from the stage but failed to mobilize their membership. Instead, the United Federation of Teachers--which endorsed Pataki for re-election--rallied separately in Albany. </P>
<P>For his part, Transport Workers Union Local 100 President Roger Toussaint is trying to keep a lid on discontent within his union following the exposure of the fact that the Metropolitan Transit Authority's accounting tricks turned a 2003 surplus of $83 million into a $236 million deficit--which led the union to agree to concessions.</P>
<P>The city's $3.8 billion budget deficit is the worst since the city's fiscal meltdown in 1975. Yet Bloomberg and Pataki had refused to raise taxes, demanding that the city's poorly paid Black and Latino workforce pay for the deficits, brought on by tax cuts for the rich.</P>
<P>According to New York economist Michael Zweig, Pataki's tax cuts in the 1990s led to a $13 billion drop in tax revenues this year and an $11 billion state budget deficit. The crisis is artificial, generated by politicians currying favor with their rich patrons.</P>
<P>Education and social services are being devastated. As one shop steward from AFSCME Local 372 told <I>Socialist Worker,</I> "Education will be worse than it is now, with more dropouts and more incidents&#133;Are we preparing a new generation for failure? Is that what the mayor thinks is good for my children? Racism is definitely part of the equation."</P>
<P>City workers and teachers have public opinion on their side. A recent poll showed 84 percent of the public are against layoffs to balance the budget. But city workers are still recovering from decades of union corruption and concessionary contracts.</P>
<P>Communications Workers of America Local 1180, which represents city clerical supervisors, demanded that the city tax the rich, citing a 1 percent surcharge on individuals making over $250,000 a year would provide the mayor with the $600 million in savings he had demanded from the unions. The local has also run TV ads with wealthy New Yorkers showing relief that their millions won't be taxed.</P>
<P>It's about time that a union took the lead in demanding higher taxes for the rich. The missing element that could stop the further bleeding of jobs and the speedup of productivity increases is rank-and-file pressure from below through job actions and greater militancy.</P>
<P>A serious fightback will not appear overnight. Despite the recent setbacks, union activists should continue to fight layoffs and givebacks with the understanding that even in defeat, lessons will be learned that can prepare the ground for greater militancy, democracy and solidarity in the labor movement in the future.</P>
<I><P>Hadas Thier and Peter Lamphere contributed to this report.</P></I>

<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
