<html>
<head>

<title>
&iquest;Es posible una revoluci&oacute;n en EE.UU.?
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<font face="Arial, Helvetica, sans-serif" size="2"><b>EL SENTIDO DEL MARXISMO</b></font><br>
<font face="Times New Roman, Times, serif" size="5"><b>&iquest;Es posible una revoluci&oacute;n en EE.UU.?</b></font><p>
<font face="Times New Roman, Times, serif" size="2"><b>Por Alan Maass</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | 28 de enero de 2005 | p&aacute;gina 3</font><p>

<font face="Times New Roman, Times, serif" size="3">UNA PARTE de los progresistas ha reaccionado a la victoria de George Bush en las elecciones presidenciales de 2004 con desesperanza. "Puede que en esta ocasi&oacute;n", comentaba amargamente la columnista de <i>The Nation,</i> Katha Pollit, "los votantes hayan elegido lo que realmente quieren: nacionalismo, guerras preventivas, orden en lugar de justicia, 'seguridad' a trav&eacute;s de la tortura, contraofensiva contra las mujeres y los gays, m&aacute;s desigualdad entre los ricos y los despose&iacute;dos, subsidios del Gobierno para las iglesias y el haces lo que digo o te caigo a patadas del presidente".<p>
Garry Wills, escritor liberal, lleg&oacute; a la conclusi&oacute;n de que EE.UU. hab&iacute;a renunciado a los "valores de la Ilustraci&oacute;n" y que el voto hab&iacute;a sido impulsado por el "fundamentalismo del electorado estadounidense". El editorial de la revista <i>Progressive</i> resaltaba que "el complejo de superioridad estadounidense es una profunda afecci&oacute;n que distorsiona nuestras percepciones y permite que los presidentes manipuladores den las &oacute;rdenes de ponernos en marcha". <p>
Semejante razonamiento coincide con el de los medios informativos de las grandes corporaciones sobre las elecciones, es decir que los reaccionarios rurales se rebelaron contra las ciudades, que la llamada de Bush a los "valores morales" y el conservadurismo social han sido el secreto de su &eacute;xito, y as&iacute; por el estilo.<p>
Realmente, esos razonamientos son en su mayor&iacute;a equivocados. Por ejemplo, la cantaleta de las estad&iacute;sticas de que el 22 por ciento de los electores afirman que los "valores morales" son su principal preocupaci&oacute;n no son una revelaci&oacute;n pues resulta que son los mismos resultados de las &uacute;ltimas tres elecciones presidenciales, seg&uacute;n <i>Los Angeles Times</i>-- incluyendo las dos ganadas por un Dem&oacute;crata. Y los mayores logros de Bush con respecto a los resultados del 2000 no provienen de las zonas rurales sino de los centros urbanos, es decir, de los lugares en donde Kerry debi&oacute; haber sido m&aacute;s fuerte.<p>
Ese es el verdadero secreto del &eacute;xito de Bush, el hecho de que Kerry y los Dem&oacute;cratas no ofrecieron razones para que el pueblo votara por ellos.<p>
Pero, los resultados electorales llevar&aacute;n a algunos a preguntarse si el objetivo al que aspiran los socialistas--una revoluci&oacute;n que cambie el sistema de poder de una clase dominante minoritaria, y establezca un nuevo sistema basado en la democracia y la igualdad--ha sido por lo menos pospuesto a alg&uacute;n lugar distante en el futuro, si no es que ha sido comprobado como poco realista.<p>
Esto pone de relieve algo que es m&aacute;s importante que el an&aacute;lisis del resultado de las elecciones, y es el hecho de que las elecciones de 2004 quedan tan lejos de una revoluci&oacute;n que el llegar a conclusiones a partir de esto es bastante in&uacute;til.<p>
Las elecciones de 2004 ofrecieron un debate yerto entre los candidatos de dos partidos pro-capitalistas que tienen m&aacute;s en com&uacute;n que lo que los separa. Una revoluci&oacute;n socialista se trata de un debate pol&iacute;tico que florezca en cada rinc&oacute;n de la sociedad-- con las masas entrando en acci&oacute;n para usar su poder colectivo con el fin de establecer nuevas prioridades. Comparar las dos realidades es como comparar una canasta de manzanas con un plant&iacute;o de naranjas.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">&iquest;PERO NO es ut&oacute;pico hablar de revoluci&oacute;n en Estados Unidos en primer lugar? Esta es la objeci&oacute;n que los socialistas o&iacute;mos siempre. En realidad, la pregunta no debe ser <i>si</i> una revoluci&oacute;n puede ocurrir en Estados Unidos. Sino debiera ser si <i>otra</i> revoluci&oacute;n puede ocurrir, puesto que Estados Unidos ya ha tenido dos.<p>
Una de las cosas m&aacute;s raras en Estados Unidos es el hecho de que sus l&iacute;deres pol&iacute;ticos que est&aacute;n comprometidos con una sociedad de ley y orden social, regularmente celebran los or&iacute;genes de este pa&iacute;s que se basan en una sangrienta revoluci&oacute;n con la que obtuvo la independencia del dominio brit&aacute;nico. La Revoluci&oacute;n Estadounidense no se logr&oacute; con la firma de la Declaraci&oacute;n de Independencia, sino gracias a la resistencia de las masas y de una guerra de liberaci&oacute;n que dur&oacute; largos a&ntilde;os. <p>
La revoluci&oacute;n result&oacute; en el establecimiento de un nuevo sistema radical de gobierno representativo y probablemente en la democracia m&aacute;s desarrollada del mundo en aquella &eacute;poca. Los nuevos Estados Unidos no eran un democracia consistente--despu&eacute;s de todo los cr&iacute;menes sangrientos de la esclavitud permanecieron intactos--pero constituyeron un avance revolucionario respecto a lo que exist&iacute;a antes. <p>
Estados Unidos experiment&oacute; otra revoluci&oacute;n social 90 a&ntilde;os despu&eacute;s: la Guerra Civil de 1861-65 que acab&oacute; con el sistema esclavista del Sur. La importancia de esta guerra ha quedado encubierta hasta hoy por los mitos sobre los generales que la dirigieron, y por otras trivialidades sin sentido como la "cultura sure&ntilde;a". La realidad es que al liberar a los esclavos, la Guerra Civil impuso la mayor expropiaci&oacute;n de propiedad privada de cualquier &eacute;poca en la historia del mundo. <p>
El resultado de esta revoluci&oacute;n se atribuye habitualmente a Abraham Lincoln y quiz&aacute;s a unos cuantos generales del ej&eacute;rcito, pero se ignora el papel desempe&ntilde;ado por un sinn&uacute;mero de personas. Esto incluye a los propios esclavos negros que jugaron un papel crucial en la lucha, como lo hicieron los agitadores del movimiento abolicionista del Norte o los soldados del ej&eacute;rcito norte&ntilde;o que lucharon y murieron para derrotar a la Confederaci&oacute;n del sur. <p>
Esas no fueron revoluciones socialistas porque ambas preservaron el sistema capitalista de la propiedad privada, pero nadie puede decir que la Guerra de 1776 y la Guerra Civil no transformaran profundamente la sociedad estadounidense, y no de forma gradual sino con grandes convulsiones. <p>
El siglo y medio transcurrido desde entonces tambi&eacute;n ha experimentado grandes convulsiones. Por ejemplo, en 1919, tras la carnicer&iacute;a de la Primera Guerra Mundial y a pesar de la histeria derechista contra los inmigrantes y los radicales, EE.UU. se vio envuelto en una ola de huelgas sin precedente que afect&oacute; a uno de cada cinco obreros. <p>
El punto culminante fue la huelga general de Seattle de 1919. Inspirada parcialmente en la revoluci&oacute;n rusa de 1917, m&aacute;s de 100,000 obreros--en una ciudad de 250,000--apoyaron la huelga general convocada por el Consejo Central de Trabajadores de Seattle para evitar que los due&ntilde;os de las grandes empresas navieras rompieran sus sindicatos. De repente, Seattle qued&oacute; paralizada y sus gobernantes se vieron incapaces de restaurar el orden. Pero lo m&aacute;s impresionante fue la manera en que los obreros se organizaron para suministrar los servicios esenciales durante la huelga, de forma que dirigieron la ciudad colectivamente por medio de un Comit&eacute; de Huelga General compuesto por representantes de comit&eacute;s de huelga locales. <p>
Hay otros ejemplos en el siglo XX estadounidense. Los a&ntilde;os treinta fueron la d&eacute;cada de la Gran Depresi&oacute;n, cuando millones de familias se vieron sumidas en la pobreza y la desesperaci&oacute;n pero fue tambi&eacute;n la d&eacute;cada en la que los obreros consiguieron implantar los sindicatos en las industrias b&aacute;sicas.<p>
Los a&ntilde;os 50 se recuerdan por el <i>Macartismo</i> y la cacer&iacute;a de brujas anticomunista pero tambi&eacute;n fueron los a&ntilde;os en que se iniciaron las primeras luchas de los movimientos a favor de los derechos civiles. En la d&eacute;cada siguiente esos movimientos crecieron hasta derrumbar el sistema de segregaci&oacute;n conocido como <i>Jim Crow </i>en el Sur, e inspiraron otras luchas que afectaron el tu&eacute;tano de la sociedad estadounidense, desde el movimiento contra la guerra en Vietnam, hasta el de los derechos de la mujer, y el de los derechos de gays y lesbianas. <p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">MUCHAS DE la opiniones acerca del profundo conservadurismo en Estados Unidos y de su amplia extensi&oacute;n demogr&aacute;fica ya se hab&iacute;an escuchado con anterioridad, especialmente durante la &eacute;poca del denominado <i>Sue&ntilde;o Americano</i> (American Dream). <p>
En los a&ntilde;os siguientes a la Segunda Guerra Mundial, hab&iacute;a algo de cierto al respecto. Para la mayor&iacute;a de los trabajadores del pa&iacute;s--no para todos pero s&iacute; para la mayor&iacute;a--el sistema parec&iacute;a que les proporcionaba modestos aumentos en su calidad de vida y promet&iacute;a una vida mejor para ellos y para sus hijos. Pero hoy el <i>Sue&ntilde;o Americano</i> es un cad&aacute;ver. En los &uacute;ltimos 25 a&ntilde;os se ha producido un enorme cambio en la distribuci&oacute;n de los ingresos a favor de los muy ricos. Y desde que empez&oacute; a la recesi&oacute;n en 2001, en estos cuatro a&ntilde;os, los ingresos familiares promedio se han reducido si consideramos la tasa de inflaci&oacute;n. <p>
Para quienes siempre han padecido la peor de las suertes, las condiciones han empeorado. Los afro-americanos siguen padeciendo una tasa de desempleo que supera dos veces el promedio nacional, a la vez que sufren el grueso del incremento en el encarcelamiento a ra&iacute;z de la pol&iacute;tica de ley y orden de los pol&iacute;ticos. Mientras tanto, muchas de las reformas conseguidas como resultado de los movimientos por los derechos civiles y del poder negro--desde la acci&oacute;n afirmativa para superar la discriminaci&oacute;n, hasta los programas de ayuda contra la pobreza que daban ayudas a los m&aacute;s vulnerables--est&aacute;n siendo desmanteladas a paso apresurado. <p>
En vista de todo esto, ser&iacute;a absurdo afirmar que los trabajadores estadounidenses est&aacute;n contentos con el deterioro de su calidad de vida, y mucho menos con el mundo violento, lleno de guerras y contaminaci&oacute;n en que viven. <p>
Las encuestas de opini&oacute;n p&uacute;blica muestran que los estadounidenses comunes est&aacute;n muy lejos de sentirse contentos con las prioridades de la administraci&oacute;n Bush. Una de estas, realizada por el <i>Wall Street Journal</i>, encontr&oacute; que m&aacute;s de la mitad de los encuestados estar&iacute;a dispuesto a pagar m&aacute;s de $2,000 en impuestos anuales para garantizar servicios de salud a los m&eacute;dico indigentes. Lo mismo ocurre con el subsidio de la educaci&oacute;n p&uacute;blica.<p>
Y a pesar de las rabietas de derecha cristiana, una considerable mayor&iacute;a de los estadounidenses creen que el aborto debe seguir siendo legal y m&aacute;s de la mitad apoya alguna forma de reconocimiento oficial--bien sea matrimonio o uniones civiles--para los gays y lesbianas. Este &uacute;ltimo asunto--los derechos de los gays y lesbianas--tiene especial relevancia porque representa un cambio radical de actitud en los &uacute;ltimos diez a&ntilde;os, a pesar de los retrocesos continuos en el debate pol&iacute;tico en Washington tanto durante los mandatos de Bill Clinton como en el de Bush. <p>
No existe raz&oacute;n para creer que el pueblo trabajador haya sido enga&ntilde;ado para que acepte un baj&oacute;n en su calidad de vida. Y la realidad es que seg&uacute;n pasa el tiempo esas condiciones van de mal en peor, en lugar de mejorar, sin indicios de que la situaci&oacute;n cambie de direcci&oacute;n.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">POR NUESTRA parte existe el potencial para ponernos en acci&oacute;n en muchos, muchos asuntos. Pero lo que determina el nivel de lucha es nivel de confianza y organizaci&oacute;n. Y en las &uacute;ltimas d&eacute;cadas se ha producido un retroceso en los movimientos obreros, en los de la lucha por los derechos de los afro-americanos y de otras causas progresistas. Todo esto ha impactado <i>c&oacute;mo</i> la gente se organiza para luchar, o incluso si est&aacute; dispuesta a luchar. <p>
Por ejemplo, los sindicatos han sufrido los ataques de las corporaciones estadounidenses desde finales de los 70, por lo que la proporci&oacute;n de trabajadores sindicalizados ha disminuido continuamente hasta llegar al 13 por ciento actualmente, e incluso menos en el sector privado. Una de las principales razones ha sido la pasividad de los l&iacute;deres sindicales ante esta ofensiva. Los l&iacute;deres del movimiento obrero creen que las huelgas y las acciones militantes--especialmente cuando implica desafiar las leyes--son m&eacute;todos del pasado que causan m&aacute;s da&ntilde;o que bien. En su lugar, han invertido sus esfuerzos en procurarse el favor de Washington.<p>
El apoyo a los Dem&oacute;cratas ha sido desastrosamente ineficaz para los sindicatos. Pero la actitud defensiva de los sindicatos es una profec&iacute;a destinada a auto cumplirse. Cualquier enfrentamiento entre los sindicatos y los patrones en que los sindicatos presentan una oposici&oacute;n de pacotilla, o peor aun ninguna oposici&oacute;n, fortalece la autoconfianza y fortaleza del otro bando y debilita al nuestro. Estas son las circunstancias que llevan a la gente a creer que no es posible vencer y son las que conducen a hacer concesiones para conservar su empleo en lugar de arriesgarse a luchar por m&aacute;s.<p>
Pero decir esto no significa que debamos aceptar el estereotipo de que los trabajadores en Estados Unidos son ap&aacute;ticos y conservadores. El nivel de lucha de clases se mantiene bajo pero en todas las ciudades de Estados Unidos se producen luchas<i> </i>con muchos motivos: huelgas, protestas contra la violencia policial, manifestaciones a favor del matrimonio gay, o de oposici&oacute;n a los ataques contra los inmigrantes.<p>
El ejemplo m&aacute;s evidente es la oposici&oacute;n a la guerra y ocupaci&oacute;n de Irak por Washington. Cuando la pandilla de Bush estaba preparando su invasi&oacute;n a principios de 2003, millones de personas salieron a manifestarse y protestar en todo el pa&iacute;s, sin mencionar las realizadas en el resto del mundo, lo que llev&oacute; al <i>New York Times</i> a declarar que "puede que todav&iacute;a existan dos superpotencias en el planeta: Estados Unidos y la opini&oacute;n p&uacute;blica mundial". <p>
Desgraciadamente, las elecciones estadounidenses detuvieron las acciones contra la guerra, en gran medida porque los l&iacute;deres del movimiento se volcaron en apoyo a John Kerry a pesar de que este favorec&iacute;a la guerra. Pero ello no quiere decir que la administraci&oacute;n de Bush haya conseguido que su guerra y ocupaci&oacute;n sean populares. Todo lo contrario, la brutalidad de la ocupaci&oacute;n--y el creciente n&uacute;mero de v&iacute;ctimas entre los soldados estadounidenses--ha preparado el terreno para que el movimiento se vuelva a poner en marcha. <p>
Cuando las luchas emergen y se relacionan pueden desarrollarse con notable rapidez. Ese fue el caso, por ejemplo, de los tronquistas (Teamsters) cuando se fueron a la huelga contra la UPS en 1997. En medio del llamado "milagro econ&oacute;mico" los medios de comunicaci&oacute;n principales tuvieron que dejar sus f&aacute;bulas felices e investigar el asunto de la avaricia corporativa y la baja en la calidad de vida que la huelga trajo al primer plano. <p>
En una escala mayor, algo parecido se puede decir de los momentos culminantes de lucha en la historia de EE.UU. Las grandes insurrecciones de trabajadores de los a&ntilde;os 30 fueron precedidas en contraste por las de los a&ntilde;os 20, cuando la clase dominante estaba a la ofensiva, y los sindicatos establecidos parec&iacute;an estar desfalcados, a punto de sucumbir. De la misma manera, el radicalismo de lo a&ntilde;os 60 fue precedido por el conservadurismo de los 50.<p>
Es importante recordar que la lucha por los derechos civiles de los a&ntilde;os 60 emergi&oacute; a&ntilde;os antes con batallas menos conocidas que envolvieron un n&uacute;mero modesto de personas, iniciadas durante un periodo hoy considerado como profundamente conservador. Para los individuos que estaban dispuestos a alzar su voz no hab&iacute;a garant&iacute;a alguna de que podr&iacute;an eventualmente derrotar al <i>Jim Crow.</i> Muy al contrario, el sistema racista parec&iacute;a todo poderoso, capaz de afrontar cualquier desaf&iacute;o. Pero a final fue derrotado, lo que se torn&oacute; en algo hist&oacute;rico.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">LOS IDE&Oacute;LOGOS que defienden el <i>status quo</i> est&aacute;n siempre dispuestos a proclamar "el fin de la historia"-- un periodo de calma social y de conservadurismo. Pero una sociedad cimentada en la injusticia y la desigualdad nunca estar&aacute; pacificada por completo. Esa es la lecci&oacute;n que ofrecen los estados policiales m&aacute;s brutales, y es tambi&eacute;n la realidad de sociedades como la estadounidense que presentan una m&aacute;scara de democracia y libertad.<p>
Cuando las luchas emergen siempre comienzan peque&ntilde;as. Pero esas batallas iniciales son cruciales para la formaci&oacute;n de las ideas en las gentes que se unir&aacute;n para dar pasos m&aacute;s importantes. Por ejemplo, los estudiantes negros universitarios que se unieron al movimiento por los derechos civiles a principios de los a&ntilde;os 60 estaban motivados por ideas relativamente conservadoras sobre el derecho a ocupar su lugar en el sistema capitalista. <p>
Unos pocos a&ntilde;os despu&eacute;s, muchos miembros del SNCC (Comit&eacute; de Coordinaci&oacute;n de Estudiantes No Violentos) se consideraban revolucionarios. Fueron testigos de las Marchas por la Libertad para acabar con la segregaci&oacute;n en las l&iacute;neas de autobuses interestatales, del asesinato de los voluntarios a favor de los derechos civiles durante el Verano de la Libertad en su proyecto de inscripci&oacute;n de votantes negros en 1964, y de la traici&oacute;n del Partido Dem&oacute;crata al no aceptar delegados a favor de los derechos civiles en su convenci&oacute;n nacional de 1964. Esas experiencias les convencieron de que la lucha contra la injusticia racial s&oacute;lo pod&iacute;a ganarse uni&eacute;ndola a la lucha contra otras injusticias, y luchando al mismo tiempo por otro tipo de sociedad. <p>
Esta transformaci&oacute;n se repiti&oacute; en los 60 y a principios de los 70. Los estudiantes que actuaron como voluntarios en el Verano de la Libertad usaron las destrezas que aprendieron en el movimiento por los derechos civiles para organizar las protestas contra la guerra de Vietnam. Por su parte, veteranos de esta lucha, a su vez lanzaron la lucha por los derechos de la mujer, incluyendo el del aborto. Los movimientos modernos de gays y lesbianas surgieron en 1969 con la creaci&oacute;n del Frente de Liberaci&oacute;n Gay, una organizaci&oacute;n que tom&oacute; su nombre del Ej&eacute;rcito de Liberaci&oacute;n de Vietnam.<p>
Hoy, a los medios de comunicaci&oacute;n les gusta hablar de forma despectiva de los movimientos de los a&ntilde;os sesenta. Sin embargo estos son la prueba de que las ideas pueden cambiar con enorme rapidez. En momentos de semejante ebullici&oacute;n social, millones y millones de personas que hab&iacute;an centrado su energ&iacute;a en otros asuntos de pronto concentraron su atenci&oacute;n en la transformaci&oacute;n de la sociedad. <p>
Esto es lo que hace posible una revoluci&oacute;n, la participaci&oacute;n de las masas. La caricatura de la revoluci&oacute;n que presentan muchos historiadores es la de un peque&ntilde;o grupo de fan&aacute;ticos armados que toman el control del Gobierno y se sirven de &eacute;l para enriquecerse. Pero esto no tiene nada que ver con el socialismo aut&eacute;ntico. El momento decisivo en cualquier revoluci&oacute;n llega cuando, seg&uacute;n escribi&oacute; el revolucionario ruso Leon Trotski, las masas "rompen las barreras que les excluyen del escenario pol&iacute;tico, dejan de lado a sus representantes tradicionales y crean a trav&eacute;s de su propia interferencia la base de un nuevo r&eacute;gimen".<p>
Ese momento constituye el acto final de una revoluci&oacute;n, el cl&iacute;max de un periodo mucho m&aacute;s largo de luchas en el cual los dirigentes de una sociedad se enfrentan a una crisis creciente, al mismo tiempo que los trabajadores cada vez son m&aacute;s conscientes de su propia fuerza. Al principio del proceso, los objetivos de cambio pueden ser modestos, quiz&aacute;s unas pocas reformas en la manera en que funciona el sistema. Pero la lucha plantea cuestiones m&aacute;s profundas, y la gente comienza a percibir las conexiones entre sus propias luchas y otros asuntos, incluyendo la propia naturaleza del sistema.<p>
Obviamente, estamos a a&ntilde;os de distancia de semejantes revueltas. En efecto, la dificultad hoy estriba en que una gran parte de la organizaci&oacute;n y las iniciativas para la lucha tienen que ser levantadas de nuevo. Pero teniendo en cuenta la historia de este pa&iacute;s, ser&iacute;a tonto afirmar que la revoluci&oacute;n es imposible, a pesar de la imagen de pasividad social que ofrecen los medios de comunicaci&oacute;n.<p>
La revoluci&oacute;n no s&oacute;lo es posible en Estados Unidos sino que es absolutamente necesaria y urgente para acabar con la pobreza, la guerra y la opresi&oacute;n--y para crear una nueva sociedad basada en la justicia y la libertad. <p>
<i>Originalmente traducido para Rebeli&oacute;n.org por Felisa Sastre</i> <p>

<!--#include virtual="/legacy-includes/BottomNavLinksObrero.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdObrero.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
