<html>
<head>

<title>
&#161;No a la guerra por petr&oacute;leo e imperio!
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<P><font face="Times New Roman, Times, serif" size="4">Desde Estados Unidos, en el vientre de la bestia decimos:</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>&#161;No a la guerra por petr&oacute;leo e imperio!</b></font></P>
<P><font face="Times New Roman, Times, serif" size="2"><b>Por Elizabeth Schulte, Lee Wengraf, Chris Brown y H&eacute;ctor Reyes</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | 18 de abril de 2003</font></P>

<P><font face="Times New Roman, Times, serif" size="3">La mayor parte de este recuento ha sido previamente publicada en el peri&oacute;dico <I>Socialist Worker, </I>producido semanalmente por la International Socialist Organization. Este puede ser le&iacute;do en la red en la siguiente direcci&oacute;n: www.socialistworker.org. Tambi&eacute;n en esa p&aacute;gina hay un enlace a nuestro suplemento en espa&ntilde;ol, <I>Obrero Socialista, </I>que es publicado cada dos meses.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>
<font face="Times New Roman, Times, serif" size="3">

<P>Desde meses antes de que Estados Unidos (EE.UU.) lanzara todo su bestial poder&iacute;o militar contra Irak, sectores significativos del pueblo estadounidense se hab&iacute;an derramado en las calles del pa&iacute;s en oposici&oacute;n a esta guerra asesina. </P>
<P>El 15 de febrero m&aacute;s de medio mill&oacute;n de personas marcharon por las calles de Nueva York en oposici&oacute;n a la guerra, muy a pesar de que el billonario alcalde de la ciudad, Michael Bloomberg, orden&oacute; a la polic&iacute;a de la ciudad a que impidiera el paso de los manifestantes usando barricadas. Al d&iacute;a siguiente, un cuarto de mill&oacute;n de personas hicieron lo mismo en San Francisco.</P>
<P>Tan pronto como comenz&oacute; la guerra los pol&iacute;ticos de todos los bandos cerraron filas y se unieron al chantaje de Bush al reclamarle al pueblo estadounidense a que apoyaran a "sus tropas" a pesar de sus opiniones respecto a la guerra. Aprovechando la preocupaci&oacute;n de los familiares y amigos de los soldados mandados a Irak (la inmensa mayor&iacute;a de clase trabajadora, y el 40 por ciento negros o latinos), Bush se sali&oacute; con la suya y logr&oacute; que su chantaje emocional subiera el apoyo a la guerra a cerca de un 70 por ciento de la poblaci&oacute;n. </P>
<P>Para esto cont&oacute; con el apoyo incondicional de las mega corporaciones due&ntilde;as de las cadenas de noticias. NBC, CNN, FOX y otras cadenas han actuado como fotutos de la administraci&oacute;n de Bush, presentando casi exclusivamente la versi&oacute;n del Pent&aacute;gono de los eventos, ignorando, minimizando o vilificando las grandes protestas que se han dado contra la guerra, y marginando informaciones sobre el alto costo que ha pagado el pueblo iraqu&iacute; en t&eacute;rminos de la destrucci&oacute;n de sus ciudades, la falta de electricidad, agua y comida y la muerte de sobre mil civiles (entre ellos muchos ni&ntilde;os), con muchos miles m&aacute;s de heridos.</P>
<P>Muy a pesar de todo esto, la oposici&oacute;n de millones de estadounidenses a la guerra se ha hecho sentir. Tan pronto como se supo que la guerra hab&iacute;a comenzado, los opositores de la guerra comenzaron a poner en acci&oacute;n planes para protestas que se hab&iacute;an elaborado meses antes.</P>
<P>La respuesta fue inmediata y abrumadora: &#161;Alto a la guerra contra Irak!, fue el grito. Cientos de miles de personas en docenas de ciudades, de variados sectores de la poblaci&oacute;n, en acciones grandes y peque&ntilde;as, se tiraron a las calles durante d&iacute;as luego del comienzo del ataque sangriento de EE.UU. contra Irak. </P>
<P>La masiva protesta de m&aacute;s de un cuarto de mill&oacute;n de personas el 22 de marzo en la ciudad de Nueva York fue demasiado grande como para que los medios de noticias la ignoraran. Los cartelones en la protesta expresaban la c&oacute;lera por la brutalidad y la hipocres&iacute;a de la guerra de Bush: "No m&aacute;s sangre por petr&oacute;leo", "Mandando a nuestros hijos a matar a sus hijos", "Bush y compa&ntilde;&iacute;a son armas de destrucci&oacute;n masiva", "Cero guerra por imperio", "El cambio de r&eacute;gimen comienza en casa", y simplemente "&#161;No a la guerra!" </P>
<P>Susan Klitzman, cuya hermana Karen muri&oacute; en los ataques a&eacute;reos del 11 de septiembre, se declar&oacute; en contra de la guerra. "Cada persona que muere, afecta a centenares", dijo Klitzman. "Y estamos matando a miles ahora mismo en Irak. Pienso en los miles de vidas inocentes que est&aacute;n siendo destruidas". Grupos que abogan por la paz se movilizaron por todas partes del noreste de los EE.UU., incluyendo a grupos anti-guerra de escuelas superiores y universidades. "Es importante que nuestras voces sean o&iacute;das", dijo Paul Brunetti, un estudiante de primer a&ntilde;o en la Universidad CW Post de Long Island. "Esto se supone sea una democracia, pero el gobierno no escucha", recalc&oacute; la profesora de matem&aacute;ticas Ann Burns. </P>
<P>La protesta de Nueva York fue la m&aacute;s grande de las demostraciones que se llevaron a cabo en las ciudades m&aacute;s grandes del pa&iacute;s durante ese fin de semana, con unas 250 mil personas. En Chicago, una de las protestas m&aacute;s grandes durante las primeras 24 horas despu&eacute;s del comienzo de la guerra creci&oacute; hasta llegar a unas 15,000 personas, que marcharon por el centro de la ciudad tomando parte en una desobediencia civil masiva que tom&oacute; los ocho carriles de la avenida Lake Shore Drive. "No me vas a creer", dijo un manifestante al peri&oacute;dico <I>Socialist Worker</I>, "pero yo pertenezco a la Reserva del Ej&eacute;rcito. Fui un soldado en el Medio Oriente en los ochentas. No tolero lo que ellos quieren hacer ah&iacute;. Este ser&aacute; mi &uacute;ltimo periodo con ellos".</P>
<P>Cuando los manifestantes marcharon por las calles del centro de la ciudad, la polic&iacute;a, abrumada y confundida por la inmensa muchedumbre frecuentemente tuvo que apartarse para darle paso por las calles a los manifestantes. "&#191;De qui&eacute;n es esta guerra? &#161;Su guerra! &#191;De qui&eacute;n son las calles? &#161;Nuestras calles!" coreaba la muchedumbre. Hab&iacute;a una atm&oacute;sfera jubilosa cuando los que marchaban tomaron Lake Shore Drive, saltaron sobre las vallas que dividen la carretera y comenzaron a zigzaguear por entre las cuatro largas filas de carros ataponados que intentaban fluir en direcci&oacute;n contraria.</P>
<P>El d&iacute;a siguiente, el alcalde de Chicago, Richard Daley, intent&oacute; pintar un cuadro de gente furiosa atrapada en sus veh&iacute;culos. Pero eso contrastaba tajantemente con lo que los manifestantes presenciaron--muchos conductores que hac&iacute;an el signo de la paz con sus dedos, que tocaban sus bocinas, o que chocaban manos con los que marchaban. </P>
<P>Varias horas despu&eacute;s, la polic&iacute;a evidentemente decidi&oacute; acabar con la protesta. Filas de polic&iacute;as con equipo antimotines rodearon lo que quedaba de la marcha--dos a tres mil personas--cuando trataban de entrar a la Avenida Michigan--distrito repleto de tiendas caras para los ricos. La polic&iacute;a primero detuvo a cualquiera que pareciera ser un organizador del evento, en varios casos tir&aacute;ndolos al suelo y golpe&aacute;ndolos, y luego comenz&oacute; a arrestar gente al azar. Como venganza por haber perdido el control de las calles, la polic&iacute;a mantuvo a m&aacute;s de 600 personas bajo arresto por lo menos por 12 horas--a algunos por m&aacute;s tiempo. </P>
<P>Pero si los oficiales de Chicago pensaban que podr&iacute;an intimidar con esto a los manifestantes anti-guerra, se equivocaron. El d&iacute;a siguiente, unas 10,000 personas se reunieron y marcharon mientras que los aviones de guerra de EE.UU. comenzaban su bombardeo de Bagdad siguiendo la brutal estrategia que el Pent&aacute;gono denomina "Shock and Awe". </P>
<P>El mismo patr&oacute;n se repiti&oacute; en San Francisco, donde decenas de miles del &aacute;rea de la bah&iacute;a tomaron las calles el d&iacute;a que la guerra comenz&oacute;. La polic&iacute;a detuvo a m&aacute;s 2,200 personas y brutalmente golpe&oacute; y roci&oacute; a cientos con el odioso aerosol de pimienta ("pepper spray") durante dos d&iacute;as. Pero fracasaron en romperle el esp&iacute;ritu al movimiento anti-guerra. El 22 de marzo, una demostraci&oacute;n de m&aacute;s de 80,000 personas se tir&oacute; a las calles otra vez. </P>
<P>"Requiere valor el estar aqu&iacute; frente a estos polic&iacute;as represivos que est&aacute;n por todas partes, pero es urgente y necesario confrontar Bush y al sistema", dijo Masha Albrecht al peri&oacute;dico <I>Socialist Worker</I>, quien es maestra en San Francisco. "La habladur&iacute;a de Bush acerca de la construcci&oacute;n de la democracia en Irak y de liberar a su gente es todo mierda", dijo Chrissy Dressler, una estudiante universitaria de Sacramento. "Nosotros no tenemos democracia y liberaci&oacute;n aqu&iacute; en los EE.UU., excepto aqu&iacute; en las calles, donde hoy nosotros tenemos el control". </P>
<P>Adem&aacute;s de estas demostraciones grandes, tambi&eacute;n hubo innumerables acciones a trav&eacute;s del pa&iacute;s, tanto grandes como peque&ntilde;as. Como por ejemplo lo fueron: una ocupaci&oacute;n de un edificio en la Universidad de California en Berkeley; la toma del puente de la Avenida Massachusetts en Boston; veteranos que se concentraron contra la guerra en Washington, D. C.; marchas, protestas y vigilias con velas desde Madison, Wisconsin., a Greensboro, Carolina del Norte, y desde Burlington, Vermont, hasta el estado de Bush, Texas. </P>
<P>Una semana despu&eacute;s, la protesta anti-guerra m&aacute;s grande en Boston desde la guerra de Vietnam atrajo a unas 25 mil personas de toda el &aacute;rea de Nueva Inglaterra. La concentraci&oacute;n fue organizada por la coalici&oacute;n llamada Unidos por la Paz y la Justicia, y cont&oacute; con la representaci&oacute;n de variados sectores, incluyendo a estudiantes, veteranos de guerra, el movimiento obrero y padres de personal militar. Protestas de todo tipo siguieron ocurriendo por todo el pa&iacute;s resultando en cientos de arrestos en Nueva York y otras grandes ciudades.</P>

<p><font face="Times New Roman, Times, serif" size="4"><b>Activistas estudiantiles inician acciones</b></font></P>
<P><font face="Times New Roman, Times, serif" size="3">Los estudiantes universitarios y de escuela superior de muchas partes de los EE.UU. trataron de coordinar acciones para protestar la guerra contra Irak. El 24 de marzo mil estudiantes de la Universidad Estatal de San Francisco (SFSU) dieron su apoyo a una concentraci&oacute;n convocada por el grupo Estudiantes Contra la Guerra (SAW). Cu&aacute;ndo el presidente de la universidad, Robert Corrigan, trat&oacute; de prevenir el evento dici&eacute;ndole a los estudiantes que "discutieran calmadamente" la carnicer&iacute;a, los estudiantes tomaron el podio y lo convirtieron en un foro p&uacute;blico contra la guerra. </P>
<P>Entonces, marcharon al edificio de la administraci&oacute;n, y cientos de ellos comenzaron una ocupaci&oacute;n pac&iacute;fica de este sent&aacute;ndose en el piso, y coreando "&#191;De qui&eacute;n es esta escuela?, &#161;Nuestra escuela!, &#191; De qui&eacute;n es esta guerra?, &#161;Su guerra!" Los estudiantes de SAW exigieron que la universidad cese la cooperaci&oacute;n con el acoso del FBI--la polic&iacute;a federal-- contra estudiantes y acad&eacute;micos internacionales, que levante las sanciones contra el la Uni&oacute;n General de Estudiantes de Palestina de SFSU por una protesta pac&iacute;fica que &eacute;sta organiz&oacute; el a&ntilde;o pasado, que no aumente el costo de la matr&iacute;cula y que no despida a ning&uacute;n trabajador. </P>
<P>El mismo d&iacute;a, los estudiantes desalojaron sus aulas en la Universidad de Illinois en Chicago, y unos 800 asistieron a una manifestaci&oacute;n que ofreci&oacute; el micr&oacute;fono a quien quisiera hablar contra la guerra. El d&iacute;a en que la guerra comenz&oacute;, 7,000 estudiantes se api&ntilde;aron en la Plaza Sproul de la Universidad de California en Berkeley , y cientos ocuparon el Edificio Sproul, al sentarse en el suelo pac&iacute;ficamente. Despu&eacute;s de varias horas, la polic&iacute;a comenz&oacute; a arrestarlos usando fuerza contra gente que no resist&iacute;a el arresto y empuj&aacute;ndolos contra las puertas de metal y por las escaleras. Cerca de 120 personas fueron arrestadas. </P>
<P>En la Universidad de Texas en Austin, la polic&iacute;a del recinto agredi&oacute; e hiri&oacute; a un activista que escrib&iacute;a con tiza en una pared anunciando una protesta de emergencia como respuesta a la guerra. Pero este acoso no impidi&oacute; que al d&iacute;a siguiente unos 1,000 estudiantes protestaran contra la guerra. Miles de estudiantes de escuelas superiores salieron de sus salones de clases por todo el pa&iacute;s para unirse a las protestas en contra de la guerra.</P>
<P>El 5 de abril miles de estudiantes organizaron protestas regionales que tomaron las calles de Oakland, California, Chicago, y Washington, D.C. bajo la consigna de "Dinero para las escuelas, no para la guerra". Estas acciones fueron convocadas por la Red de Escuelas contra la Guerra (CAN, por sus siglas en ingl&eacute;s), tratando de enfatizar las prioridades injustas de la administraci&oacute;n de Bush que se va a gastar sobre 100 mil millones de d&oacute;lares en la guerra contra Irak mientras que los gobiernos estatales se encuentran en crisis econ&oacute;mica y proyectan despedir maestros, recortar servicios, y reducir el n&uacute;mero de cursos y programas educativos.</P>

<P><font face="Times New Roman, Times, serif" size="4"><b>"Esto forma parte de una guerra [dom&eacute;stica] contra los trabajadores"</b></font></P>
<P><font face="Times New Roman, Times, serif" size="3">Durantes los &uacute;ltimos meses, activistas obreros han organizado una oposici&oacute;n sin precedentes dentro de las uniones contra la guerra. Muchos cap&iacute;tulos ha aprobado resoluciones anti-guerra, y un grupo de activistas fund&oacute; en enero una coalici&oacute;n obrera nacional llamada Trabajadores de EE.UU. contra la Guerra (USLAW, por sus siglas en ingl&eacute;s). Inclusive el Consejo Ejecutivo de la federaci&oacute;n nacional de uniones, la AFL-CIO, aprob&oacute; una resoluci&oacute;n que criticaba a George W. Bush por su campa&ntilde;a a favor de la guerra durante su convenci&oacute;n anual en febrero. </P>
<P>Desgraciadamente, la federaci&oacute;n dobl&oacute; las patas tan pronto como la guerra comenz&oacute;, cuando el presidente de la AFL-CIO, John Sweeney, hizo una declaraci&oacute;n "haciendo un llamado patri&oacute;tico" a apoyar a su pa&iacute;s. Pero muchos trabajadores de base no se han tragado ese cuento. El 22 de marzo, durante la inmensa demostraci&oacute;n en la ciudad de Nueva York, Dorothee Benz esboz&oacute; las cuestiones que enfrentan los trabajadores. </P>
<P>"El dinero gastado en la guerra en vez de en las necesidades sociales es un crimen", dijo Benz, quien es dirigente del Cap&iacute;tulo 1180 del Sindicato de Trabajadores de Comunicaciones, que representa a trabajadores municipales de Nueva York. "Esta guerra es parte de la guerra dom&eacute;stica contra los trabajadores. Ellos no le piden sacrificios a ning&uacute;n otro sector excepto a nosotros". </P>
<P>Los miembros del grupo Trabajadores de la Ciudad de Nueva York Contra la Guerra (NYCLAW), que se form&oacute; inmediatamente despu&eacute;s de los ataques a&eacute;reos del 11 de septiembre, formaban un contingente visible en la protesta , marchando bajo la consigna "Los enemigos de los trabajadores est&aacute;n en la Casa Blanca y en las Juntas de Directores Corporativas, no en Irak". "Es injusto atacar un pa&iacute;s que no nos ha atacado, y es el pueblo trabajador quien pagar&aacute; el precio", dijo Michael Letwin, co-coordinador de NYCLAW, en una conferencia de prensa el d&iacute;a que la guerra comenz&oacute;.</P>
<P>Ahora que la administraci&oacute;n de Bush se apresta a organizar la ocupaci&oacute;n de Irak luego de la miseria, muerte y destrucci&oacute;n que ha causado, insiste en presentarla como la liberaci&oacute;n de este pa&iacute;s. Lo cierto es que convertir&aacute; a Irak en una colonia petrolera, rob&aacute;ndole su riqueza al pueblo iraqu&iacute; e ignorando las necesidades de una poblaci&oacute;n que ha padecido de 13 a&ntilde;os de sanciones econ&oacute;micas y dos sangrientas guerras. Y para ello pretender&aacute; la cooperaci&oacute;n de los trabajadores iraqu&iacute;es en su explotaci&oacute;n--particularmente de los obreros de la industria petrolera. </P>
<P>Es s&oacute;lo cuesti&oacute;n de tiempo antes que la mentira de la liberaci&oacute;n sea confrontada por el mismo pueblo iraqu&iacute; exigiendo justicia. Esto es un potencialmente inmenso dolor de cabeza para Bush y sus secuaces, sin contar el extremo rencor y desprecio que se han ganado en el <I>Medio Oriente </I>y en el resto del mundo.</P>
<P>Pero mientras tanto, despu&eacute;s de que Bush y sus socios de las grandes cadenas de noticias se recuperen de la org&iacute;a de celebraci&oacute;n sobre la supuesta liberaci&oacute;n, no podr&aacute;n escapar tampoco las realidades dom&eacute;sticas. Una econom&iacute;a estancada en la que millones de personas han perdido sus empleos. Millones de personas que se han visto frontalmente atacadas o marginadas por las pol&iacute;ticas de Bush. Ataques contra las minor&iacute;as raciales--que sin embargo se encuentran sobre representadas en el ej&eacute;rcito--contra los derechos de los trabajadores, contra las mujeres y su derecho al aborto, recortes en los impuestos para los ricos, y recortes en los servicios sociales para los trabajadores y los pobres. </P>
<P>A pesar de la abrumadora propaganda e intimidaci&oacute;n un 30 por ciento del pueblo estadounidense se mantuvo firme en su oposici&oacute;n a la guerra contra Irak, y rechazar&aacute; su ocupaci&oacute;n. Este segmento de la poblaci&oacute;n ha llegado a entender de una forma u otra que la guerra contra Irak no era para su beneficio. Seg&uacute;n pase el tiempo, muchos otros de los que fueron manipulados para apoyar la guerra llegar&aacute;n a las mismas conclusiones porque nada bueno vendr&aacute; para ellos de &eacute;sta, mientras se les pide que paguen por las consecuencias--en t&eacute;rminos econ&oacute;micos y sociales. Y si Bush o sus sucesores intentan otra pr&oacute;xima guerra, el por ciento de los que firmemente se rehusar&aacute; a apoyarla incrementar&aacute;.</P>
<P>Estas son las crecientes contradicciones que la clase gobernante estadounidense enfrenta dom&eacute;stica e internacionalmente. Cada vez que intenten estirar su imperio se les har&aacute; cada vez m&aacute;s dif&iacute;cil el poder mantenerlo. Y mayor el n&uacute;mero de personas que llegar&aacute; a la conclusi&oacute;n de que contra el imperio lo &uacute;nico que resta hacer es combatirlo con un s&oacute;lido movimiento anti-imperialista, tanto desde las entra&ntilde;as de la bestia como en el resto del mundo.</P>

<?php include "../../legacy-includes/BottomNavLinksObrero.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdObrero.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
