<html>
<head>

<title>
Taking their anti-immigrant hate on the road
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<font face="Times New Roman, Times, serif" size="4">Republican right-wingers hold "field hearings"</font> <br>
<font face="Times New Roman, Times, serif" size="5"><b>Taking their anti-immigrant hate on the road</b></font><p>
<font face="Arial, Helvetica, sans-serif" size="2">July 14, 2006 | Page 16</font><p>

<font face="Times New Roman, Times, serif" size="3"><b>JUSTIN AKERS CHAC&Oacute;N reports on a campaign of hate against immigrants led by some of the country's most powerful politicians.<p></b>

<font face="Times New Roman, Times, serif" size="3">HOUSE REPUBLICANS launched a series of "immigration hearings" in U.S. border towns, kicking off a summer campaign they hope will whip up anti-immigrant sentiment and corral public opinion against any form of legalization in future legislation.<p>
Ignoring even the pretense of impartiality, the hearings on "border vulnerabilities and international terrorism" are closed-door, invite-only political theater. They are being spearheaded by the House Committee on International Relations and Subcommittee on International Terrorism and Nonproliferation--two bastions of the anti-immigrant Republican right. <p>
Late last year, the House passed legislation, named for its sponsor Rep. James Sensenbrenner (R-Wis.), which criminalizes all 12 million undocumented workers living in the U.S., along with anyone who aids them.<p>
This year, the Senate passed a "compromise" that incorporates most of the enforcement provisions from Sensenbrenner, but also includes a business-backed guest-worker program and a highly restrictive path to legalization for some undocumented immigrants.<p>
This summer's hearings are part of the House Republicans' response--that they won't accept the highly punitive Senate bill if there is any legalized status for the undocumented.<p>
Ultimately, the hearings are aimed at bringing together national anti-immigrant forces bent on making immigration the "litmus test" issue in November congressional elections--and rehabilitating the criminalization provision at the heart of the Sensenbrenner Bill, which was set back by the massive immigrant rights protests of the past several month.<p>
Despite their triumphal posturing, the Republicans are trying to stabilize their party as it staggers under the weight of its own failures. From the Iraq war to the seemingly endless corruptions scandals, the GOP is grasping for an issue to salvage its image and paper over its fractures going into November. <p>
They have only been able to take the initiative on immigration because the bipartisan Washington establishment is united in support of tougher border enforcement and a crackdown on the undocumented. <p>
But Republicans are divided over the endgame. <p>
For the Bush administration, securing a guest-worker program for Corporate America is the top priority. In this, Bush has the united support of the Democratic Party and liberal groups that function as its auxiliaries. <p>
The Republican right, however, hopes that playing the anti-immigrant card will give them an advantage in the midterm elections.<p>
They are openly joining forces with the Minutemen and other vigilante organizations, which have been able to grow and take more bold actions in the climate generated by Washington's renewed attacks on immigrants. <p>
For instance, the San Diego hearing in early July included representatives from one Minuteman splinter group called Friends of the Border Patrol, which organizes immigrant hunts along the border with Mexico when not sharing the platform with Republican politicians.<p>
The right wants to push the immigration issue onto the comfortable terrain of "national security." One of the organizers of the immigration show trials, California Rep. Ed Royce, justified the hearings by stating, "It's elementary that to defend ourselves against our determined and resourceful enemies, our border must be secure." <p>
For their part, the Democrats played a key role in linking the issue of the border with "war on terror."<p>
Previous to Bush sending National Guard troops to the border, Democratic Govs. Janet Napolitano of Arizona and Bill Richardson of New Mexico ordered the Guard to "help" solve a "state of emergency" at the border.<p>
Likewise, after initially refusing to take part in the current hearings, Democrats from the Congressional Hispanic Caucus came on board only to "drive home the idea that Republicans have failed to address illegal immigration," the <i>New York Times </i>reported. They also supported a rival hearing in Philadelphia, sponsored by Republican Sen. Arlen Specter, which differed only in that it promoted Corporate America's "need" for a guest-worker program.<p>
A majority of Americans continue to disagree with both the far right and the "moderates" in their efforts at criminalization. For instance, a June AP-Ipsos poll showed that 52 percent of people believe that immigrants have a positive influence on the U.S., up 10 percentage points from 2004.<p>
But in Washington, the political discussion is dominated by the right. And according to press reports, the Bush administration is showing signs of capitulating, with an openness to "enforcement-only" legislation that abandons a "path to legalization." <p>
While Corporate America and the right wing duel over the acceptable "degree" of immigrant criminalization, the hearings also revealed support for immigrant rights.<p>
About 100 immigrant rights protesters--prevented entry into the San Diego "hearings"--laid out 4,000 crosses in the vicinity in memorial to the migrant workers who have died crossing the border. <p>
The challenge is to build on this spring's enormous immigrant rights demonstrations to create a national movement that can beat back both the right's attempts to scapegoat, and any legislation that doesn't include amnesty and full legalization for all immigrants.<p>

<?php include "../../legacy-includes/BottomNavLinks.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
