<html>
<head>

<title>
News and reports
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<font face="Times New Roman, Times, serif" size="5"><b>News and reports</b></font><P>
<font face="Arial, Helvetica, sans-serif" size="2">February 11, 2005 | Pages 10 and 11</font><p>

<font face="Times New Roman, Times, serif" size="3"><B>OTHER STORIES BELOW:</B><BR>
<A HREF="#War">No to war and occupation</A><BR>
<A HREF="#Abortion">Defend abortion rights</A><P>

<font face="Times New Roman, Times, serif" size="4"><b>Housing is a right</b></font><br>
<font face="Times New Roman, Times, serif" size="2"><b>By Cindy Klumb</b></font><p>

<font face="Times New Roman, Times, serif" size="3">NEW YORK--A few thousand people gathered in front of City Hall February 2 to demand affordable housing. More than 100 local housing advocacy groups, community groups, neighborhood associations and unions sponsored the Housing Here and Now March.  <p>
Homeless individuals and families joined low-income New Yorkers who are victims of the city's skyrocketing rents. A group of children from the Bronx carried signs that said it all: "The average age of a homeless person in NYC is 9 years old." <p>
Another man, a sanitation worker, lives with his parents, while his wife and children live with hers. When he went to apply for housing assistance, he was told that he could only get help if he and his family went into the shelter system. One of his children has special health needs, so he and his family are forced to live separately. <p>
In December 2004, 36,200 men, women and children were sleeping each night in city shelters, including 15,000 children, 12,600 adult family members and 8,600 single adults. Many more homeless New Yorkers are doubling up with family and friends or sleeping in parks and on trains.<p>
The purpose of the march was to put pressure on Mayor Bloomberg and the City Council to guarantee affordable housing to all New Yorkers. <p>
The march had five main demands. First, protesters want city and state officials to make good on promises made in the 1980s to use revenues generated by the Battery Park City Authority (BPCA) to create affordable housing. So far, only a small portion of the funds has been used for this purpose. <p>
BPCA generates more than $75 million annually and will produce $1 billion more during the next decade, which would be enough to build more than 10,000 new affordable housing units and repair 5,000 existing units. The mayor wants to use some of this money to help finance the West Side Stadium.<p>
Second,<b> </b>Mayor Bloomberg has proposed the re-zoning of dozens of neighborhoods that potentially could create 80,000 new units of housing, but currently there's no guarantee that any of the new housing will be affordable. The demand for "inclusionary zoning" would mandate a minimum of 30 percent of new units for low- and moderate-income New Yorkers.<p>
Third, marchers want to repeal a 30-year-old state law that has prevented the city from strengthening rent regulations and protections for tenants in one third of all housing citywide. Fourth, the city should provide permanent housing for people living with AIDS instead of wasting thousands of dollars each month for emergency shelter of homeless which is more costly.<p>
And fifth, protesters want the city to strengthen its enforcement of housing-code by violations by the city's landlords. In 2002, there were more than 300,000 housing-code violations, 20 percent considered "immediately hazardous."<p>
<font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a></font><br>
<br>
<p><a name="War"></a><font face="Times New Roman, Times, serif" size="4"><b>No to war and occupation</b></font><p>

<font face="Times New Roman, Times, serif" size="3">ACTIVISM AGAINST military recruiters on campus is gathering momentum.<p>
A crowd of students, including members of the Campus Antiwar Network (CAN), protested the presence of military recruiters at the New York University Law School February 4. The recruiters were interviewing candidates for positions within the Judge Advocate General Corps (JAG) of the U.S. Navy--a military branch whose function includes prosecuting soldiers who refuse to fight in Iraq like Pablo Paredes. <p>
The students carried signs with anti-discrimination slogans like "don't ask, don't tell, don't recruit here," "Dick Cheney, let your daughter serve," and "racist, sexist, anti-gay, JAG go away," as well as antiwar slogans like "troops out now," "don't prosecute war resisters," and even "we will not be pawns of imperialism!" <p>
Whenever the recruiters were brave enough to step out of their conference room, they were met with chants like "shame, shame, shame," and "we say no to occupation, go back to your recruiting station!" <p>
In Chicago, close to 50 antiwar activists came together for a follow-up organizing meeting of the Chicagoland Coalition Opposed to the Militarization of Youth (CCOMY) January 29. <p>
People from a wide range of organizations attended the meeting, including American Friends Service Committee, Vietnam Veterans Against War, Veterans for Peace, the Chicago Teachers Union, Illinois Federation of Teachers, Students for Social Justice, Save Senn [High School] Coalition, Students Against the Militarization of Youth, the International Socialist Organization, and a group starting a conscientious objectors list serve.<p>
The serious mood of the meeting was serious, reflecting urgency in what seems to be an increasingly organized movement against military recruitment in Chicago. <p>
A number of people spoke to the connections between the occupation in Iraq and the city's campaign to privatize schools, known as Renaissance 2010, which allows for public high schools to be turned into military academies, a move that disproportionately targets Blacks and Latinos and other immigrants.<p>
The meeting focused on several issues, including how to link high school students and teachers with community activists to oppose recruiters when they visit. Also, meeting participants discussed the need to create anti-recruitment literature to debunk the myths military recruiters tell students, as well as creating a speaker's bureau (especially of antiwar veterans) who would be willing to give testimony at campus meetings about why students should not enlist. The group will be meeting again in three weeks to discuss future plans, including the possibility of a citywide anti-recruitment conference sometime in the spring.<p>
<i>Dave Rory and Elizabeth Lalasz contributed to this report.</i> <p>
<font face="Arial, Helvetica, sans-serif" size="2"><a href="#Top">Back to the top</a></font><br>
<br>
<p><a name="Abortion"></a><font face="Times New Roman, Times, serif" size="4"><b>Defend abortion rights</b></font><br>
<font face="Times New Roman, Times, serif" size="2"><b>By Zoe Muth</b></font><p>

<font face="Times New Roman, Times, serif" size="3">SEATTLE--One week after marching and rallying to celebrate the 32nd anniversary of <i>Roe v. Wade </i>and protest attacks on a woman's right to a safe, legal abortion, activists again took to the streets.<p>
When pro-lifers organized a "Silent no more" demonstration, pro-choice forces organized a counter-protest. As anti-choice women held signs reading, "I regret my abortion," we chanted our message loud and clear--"Not the church, not the state, women must decide their fate!" and "Pro-life, your name's a lie, you don't care if women die!" We passed out flyers and spoke with the press about our demands, including free, accessible abortion, no forced sterilizations and universal health care.<p>
The positive response from passersby shows that the majority of Americans do not support Bush's anti-choice administration. We must continue taking to the streets to challenge these attacks and encourage others to speak out.<p>
<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
