<html>
<head>

<title>
Glaring malice of war
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="4">How Iraqis will suffer after the U.S. invasion</font><BR>
<font face="Times New Roman, Times, serif" size="5"><b>Glaring malice of war</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">March 28, 2003 | Page 4</font></p>
<font face="Times New Roman, Times, serif" size="3"><P><b>George Capaccio is an activist who has traveled to Iraq nine times since 1997, delivering medicine, toys and money to Iraqi families suffering under U.S. and UN-imposed economic sanctions. He submitted this article to <I>Socialist Worker.</I></b></P>

<P>In 1996 TV reporter Leslie Stahl conducted what has become a legendary, oft-quoted interview with former Secretary of State Madeline Albright. Ms. Stahl questioned the former Secretary about the US government's policy toward Iraq. Drawing upon reports issued by UN agencies documenting the humanitarian crisis in Iraq, Ms. Stahl asked if the death of half-a-million Iraqi children from sanctions was a price worth paying. "Yes, we think the price is worth it," the former Secretary of State replied. I have often wondered whom she thought was paying this price. Certainly not the US government. </P>
<P>Seven years later comprehensive economic sanctions remain as deadly and as costly as they were in 1996. And the price continues to climb--in the number of innocent Iraqis who have died as a direct consequence of these sanctions. Presently, the Bush Administration is hell bent on launching a "pre-emptive"war against Iraq that the UN estimates could cost another one million lives, most of whom will be children since nearly 50 percent of Iraq's population is under the age of fifteen. This too must be a "price worth paying" to our Washington warriors and the merchants with whom they sleep.</P>
<P>In my own, minuscule way, I too have been paying a price throughout these years of sanctions and threats of war. But before I delve into this price, I wish to add a brief disclaimer: I am hardly a boastful person. Self-effacing is a more apt description. I would rather keep to myself whatever successes have come my way. Even among close friends, I am reluctant to share my achievements. </P>
<P>But, as they say, desperate times call for desperate measures. And what could be a more desperate time than this when that "big green machine," the US Army, along with the 101st Airborne, Special Forces, a fleet of aircraft carriers, and a slew of unbelievably destructive weapons, is about to come crashing down on a country that has done us no harm nor has the capacity to offer more than temporary resistance to our overwhelming might.</P>
<P>What then is the "desperate measure" I feel called to take? To tell about a sacrifice I have made and continue to make for the sake of the people of Iraq. I am proud of what I have done. My sacrifice is a way of taking a stand, a way of resisting and countering the cruelty and inhumanity of the men and women who purport to lead this country. In absolute terms, it isn't much, what I do. It won't stop the next Gulf War; it certainly hasn't ended the sanctions. </P>
<P>But for a few Iraqi families it has meant, on occasions, the difference between life and death. More typically, the price I have paid, the sacrifice I have made, has given these families something more than government food rations as their primary, if not sole, safety net. </P>
<P>I have made nine trips to Iraq since 1997, and have traveled and worked there with various organizations including Voices in the Wilderness, American Friends Service Committee, and the Middle East Council of Churches. Initially, I wanted to witness the effects of sanctions on the lives of ordinary Iraqis in order to serve as a more credible advocate, in my own country, for the people of Iraq.</P>
<P>Perhaps it is the still-radiating influence of my Italian American upbringing. Then too it might have something to do with the unsurpassed generosity, hospitality, and warmth of the Iraqi people. Whatever the reason(s), during my time in Iraq, I have succeeded in creating many deep and lasting ties with a number of families. You might say we are part of one quite large, extended family whose members live in Boston as well as in Baghdad. </P>
<P>When I think of Baghdad, the first thing that comes to mind is not the dictator and his palaces, nor his suspected store of prohibited weapons, nor even the nefarious web of prisons and torture chambers that have brought so much suffering to the Iraqi people. Nor do I hear what by now has become a <I>de riguer</I> refrain repeated by Prince George and his hungry minions: "He gassed his own people." When this refrain does occur to me, it comes in a full metal jacket of information, rather like a pronouncement from some dark chronicle of murderous complicity: "He gassed his own people under the noses and in clear view of the Reagan Administration, which provided unconditional technical, diplomatic, and military support." </P>
<P>No, when I think of Baghdad and Iraq, I see my sisters and brothers, and my ever-increasing flock of nephews and nieces. I hear my niece Sharook asking me over the phone about my father (who recently broke his hip) and assuring me in her sweet soft voice and trembling English that she along with her mother and aunts is praying for his recovery. I remember the day her cousin Yassir, a fifteen-year-old champion soccer player, pressed into my hand the blue-ribboned medal he received from his school for excellence on the soccer field. He insisted I keep it. Stunned by his desire to part with something so precious, I tried to give the medal back. Yassir would not hear of it. "I love you, George," he said in Arabic. "Please keep this gift and do not forget me, ever."</P>
<P>Just the other day his mother Suha and I were talking on the phone. Before we hung up, she asked me what I would like her to send me. She explained that a fellow American, working in Baghdad with Voices in the Wilderness (a longtime anti-sanctions organization) would deliver her present to me. Earlier in our conversation, I had tried as best I could to alert the family to a likely timetable for a U.S. invasion and to urge them to evacuate Baghdad as soon as possible. </P>
<P>Suha understands the danger and is planning to move temporarily to a farming area south of the city. Nevertheless, she has decided to bake me a big batch of <I>klege</I>, a traditional Iraqi dessert which she knows I covet, and send it to my wife and I. </P>
<P>After we said our goodbyes, I happened upon an article in the <I>Sydney Morning Herald</I> entitled "One Minute to Midnight, and the Deadly Baghdad Canyons Wait." The author, Paul McGeough, attempts to help readers understand the pitfalls of bringing U.S. forces into the city. Unconcerned with the suffering this will cause the already over-burdened, battle-scarred, and resource-depleted populace, McGeough sifts through the views of defense analysts and Army generals. One of them, Barry McCaffrey, says, "They're not going to believe what we do to them. . . This ain't one Ranger company and 100 Delta Force guys. "(Here, the good general, and former commander of forces responsible for the slaughter of retreating Iraqi soldiers on the infamous Highway of Death from Kuwait to Basra, is hearkening back to U.S losses in Mogadishu, Somalia, according to McGeough.) </P>
<P>"This would be the 3rd Infantry Division/Mechanized. They're going to drive M1A2 tanks down the street with a 120mm gun and fire five rounds into a lower floor and bring the building down." </P>
<P>McCaffrey's words speak for themselves. No gloss is necessary to bring out their glaring malice and callousness. Of course, what he fails to say is that families dwell in those buildings--families like those of Suha and her four sons, and her husband Karim who can't work because of severe heart problems. During a visit, he will invariably slip off to his garden and return bearing a prim yellow rose, which he entrusts to me as if it were a rare jewel he knows I will always treasure.</P>
<P>Suha's is one of nine Iraqi families I am committed to helping through a trust fund I set up a few years ago. Sometime after my third visit to Iraq in 1998, I decided to provide monthly remittances to families I had befriended. At the time, these were Shia Muslim families in dire need of assistance. I made their acquaintance through the good graces of our hotel receptionist, a young Chaldean Catholic woman who, though impoverished herself, reached out to those in even greater need. With the help of her parish church, she provided food and blankets to several Muslim and Christian families in Baghdad, and helped with finding jobs and homes for those who had migrated from northern Iraq.</P>
<P>The example of her faith, her good works, and her loving adherence to the Sermon on the Mount inspired me to undertake something similar on my own. Shortly after our friendship blossomed, she was forced to flee Iraq with her entire family, and now lives in Canada. I inherited, in a manner of speaking, six families whom she once assisted and took me to visit each time I came to Baghdad. I have since expanded our circle of care to include three more families.</P>
<P>I wish I were a rich man. But I am not. I earn my daily bread as a storyteller and artist-educator. Not much money in that. In the beginning, I put in extra weekend shifts at one of my jobs in order to keep the remittances flowing. I also cut back on expenses in order to meet my new responsibilities. Vacations were out of the question as were weekends away. I had to keep driving the same old, rusted out clunker and make do with an aging wardrobe as well. Books, records, meals out--ancient history.</P>
<P>Now, after much tinkering with different ways to keep the trust fund solvent and to make sure the money got to the families in a timely fashion, I provide seventy-five dollars every three months in cash to each of the nine families. Either I personally deliver this assistance or send it over with a fellow activist.</P>
<P>The quarterly payments help the families purchase food that is more nutritious than what they receive from government rations. It also enables them to buy medicine at the local pharmacies. As in any family, emergencies or crises arise when extra funds are necessary. So far, I've been able to handle such occasions. </P>
<P>The first order of business when I arrive in Baghdad is to visit as many of the families as I can. In one of my covert identities as "Baba Noel" (Father Christmas), I have been known to pop in unannounced with a duffel bag stuffed with toys and other gifts, plus clothes, and a sizable cache of vitamins, aspirin, and other handy household medicines.</P>
<P>All in all, I've distributed about twenty-five thousand dollars to these families over a five-year period. The money has come from the sweat of my brow and the kind donations of my growing community of friends and supporters. Instead of launching cruise missiles on Iraqi cities or increasing people's suffering by tightening the sanctions or threatening them with cataclysmic war, we have freely and joyfully given them direct material aid along with consistent spiritual support. </P>
<P>A few achievements I am especially proud of:</P>
<P>Making it possible for Najra, a teacher, artist, and mother of three, to afford a caesarean section in a clean, well-staffed clinic; and recently, to receive treatment for an inflamed ulcer.</P>
<P>Paying for the reconstruction of two ceilings in Najra's home damaged during a cruise missile attack in 1993.</P>
<P>Purchasing a refurbished sewing machine in Baghdad's Arab <I>suq </I>so that she could start a new career making children's clothes for friends and neighbors.</P>
<P>Obtaining and delivering a thousand dollars worth of chemotherapy drugs for a young mother with cancer in both breasts (the drugs are often not available, even in Baghdad, or are inferior to what we have in this country).</P>
<P>Enabling a twelve-year-old girl named Ghada to have a kidney stone removed at a private hospital.</P>
<P>Raising part of the money for a special evacuation fund for all nine families in the likely event of an American invasion.</P>
<P>This is only a sampling of the good that has flowed from the price I have paid to bring justice and peace to the people of Iraq. And yes, Madeline, it is a price worth paying. In return for my "sacrifice," I receive infinitely more than I give. And through this free and loving exchange, I have come to see, perhaps more clearly than at any other time in my life, the shabby immorality of people like George Bush and the mean little men who surround him--men who speak about rescuing the Iraqi people from the clutches of an evil dictator and replacing tyranny with democracy while preparing to massacre hundreds of thousands of innocent Iraqis to achieve their stated aims.</P>
<P>Something else I have come to understand more deeply: the wrongness of using violence or the threat of violence to create change, especially when the aggressor--in this case the United States military and its political minders--possesses all or most of the means of force. As an unofficial diplomat of sorts, I have built many bridges in Iraq--between my self and the culture I represent, on the one hand, and the people and culture of Iraq. </P>
<P>I like to think that when my friends and relatives in Iraq think of America, the first thing that comes to mind is not the bombast and war-lust of George Bush or the megatons of explosives he is prepared to use. No, I trust that what comes to mind for my friends and relatives are the times we have spent together and the love we have exchanged. </P>
<P>Like the time Fatima and her sisters and I piled into a battered old orange and white taxi and traveled across town to a large but rather creaky amusement park. For the better part of a languid October evening, the children had the time of their lives. While I supervised, they rode the carousel, the ferris wheel, and of course the bumper cars; picked off wisps of cotton candy I bought from a vendor; and paddled around a weedy lagoon while a young man sang on a boat that went by.</P>
<P>Or the time I whipped up a real Italian dinner for Suha and her family. During the meal, she and her husband, who had never eaten spaghetti before, began playfully sucking on separate ends of the same strand until their lips touched and they gave each other a brief kiss. Their young sons were so embarrassed they didn't know whether to cover their faces or leave the room. </P>
<P>This past December I called on Najra and her husband Rahim, a six-foot-six Islamic scholar and a first-class wit. In one of his wickedly impish moods, he set his wife's reading glasses on the tip of his nose, covered his head with the black and white <I>kufiyah</I> I had brought him from Amman, and impersonated Najra while I videotaped him "for all of my American fans," he said. Rahim discussed in a faux erudite tone the aesthetic theories behind "his" art, samples of which were displayed on the walls of their living room. He concluded his presentation with an unexpected twist by launching into a medley of Tom Jones' hits, notably "It's Not Unusual" in scratchy English. Najra and I scooted outside to catch our breath from laughing so hard.</P>
<P>A few years ago Najra and Suha, who is her sister-in-law, baked a cake for me in honor of the Easter <I>Eid. </I>As we were drinking Pepsi and sharing the cake, Najra asked if I could provide any clothes for her husband, who had been wearing the same shirt for years. For some reason, I had an extra shirt in my book bag and gave it to her. Suha whispered something to Najra. The two then started chuckling while speaking to each other in Arabic. </P>
<P>"Okay, what's so funny?" I asked. Najra answered me in English. "Suha says that if you stay any longer in Iraq you will have no clothes left and when you step off the plane your wife will see a naked man. She also says you must call the President and tell him, 'Please, no more sanctions on Iraq. The people need so much they are making me a poor man with no money and no clothes.'"</P>
<P>An obvious question: how can my limited effort in providing minimal assistance to a handful of families serve the greater goal of dissolving the tension between Iraq and the United States and bringing relief to all the people? I recall a proverb I once heard from an Iraqi artist: when two elephants fight, he said, only the grass suffers. So it is that from the "grass," real change will come. The work I do in Iraq is quintessentially grassroots, person-to-person activism. Not only do I bring material aid; I also listen to people's stories and share the truth of my own life experience. As far as possible, I witness and acknowledge what people are enduring under sanctions and the threat of war. Furthermore, I honor their culture, language, and customs, and try to create balanced relationships based on mutual respect.</P>
<P>Given the complexity of the crisis that now exists, I do not for a moment believe that what I have done could be construed as a template for a large-scale, nonviolent solution. On the other hand, the spirit in which I have carried on this work is something I would most definitely put forward as an alternative to the current whoops and hollers for war.</P>

<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
