<?php


/**
 * @file
 * Contains custom code necessary for SW migrations.
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Migrate callback function to map story weights into the new values.
 *
 * @param array $story_weight
 *   Nested array keyed by 'value' and 'delta'. We only care about the value.
 *
 * @return integer
 *   The story weight in D8 (-10 to 10) based on the D6 values (-5 to 5).
 */
function sw_migrate_story_weight_map(array $story_weight) {
  switch ($story_weight['value']) {
    case -5:
      return -9;
    case -4:
      return -6;
    case -3:
      return -3;
    case -2:
      return -1;
    case -1:
      return 1;
    case 0:
      return 3;
    case 1:
      return 5;
    case 2:
      return 7;
    case 3:
      return 8;
    case 4:
      return 9;
    case 5:
      return 10;
  }
}

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for 'upgrade_d6_file'.
 *
 * If the D6 {files} table has an empty timestamp, lookup the creation date of
 * the image node the file is attached to (if possible).
 */
function sw_migrate_migrate_upgrade_d6_file_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();
  $img_timestamp = 0;
  if (empty($values['timestamp'])) {
    $img_timestamp = $source
      ->getDatabase()
      ->query('SELECT n.created FROM {content_type_image} c INNER JOIN {node} n ON c.vid = n.vid WHERE c.field_image_fid = :fid', [
        ':fid' => $values['fid']
      ])
      ->fetchField();
  }
  $row->setSourceProperty('img_timestamp', $img_timestamp);
}
