<?php

/**
 * @file
 * Contains custom code necessary for SW migrations.
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Migrate callback function to replace ' and " with fancy quotes as needed.
 *
 * @param string $plain_text
 *
 * @return string
 *   The given input with ' and " replaced with fancy quotes as needed.
 *
 * @todo Make this HTML-aware for use with formatted fields?
 */
function sw_migrate_fancy_quotes($plain_text) {
  $preg_map = [
    '‘' => '@^\'@',
    ' ‘' => '@ \'@',
    '’' => '@\'@',
    '“' => '@^"@',
    ' “' => '@ "@',
    '”' => '@"@',
  ];
  return trim(preg_replace(array_values($preg_map), array_keys($preg_map), $plain_text));
}

/**
 * Migrate callback function to map story weights into the new values.
 *
 * @param array $story_weight
 *   Nested array keyed by 'value' and 'delta'. We only care about the value.
 *
 * @return integer
 *   The story weight in D8 (-10 to 10) based on the D6 values (-5 to 5).
 */
function sw_migrate_story_weight_map(array $story_weight) {
  switch ($story_weight['value']) {
    case -5:
      return -9;
    case -4:
      return -6;
    case -3:
      return -3;
    case -2:
      return -1;
    case -1:
      return 1;
    case 0:
      return 3;
    case 1:
      return 5;
    case 2:
      return 7;
    case 3:
      return 8;
    case 4:
      return 9;
    case 5:
      return 10;
  }
}

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for 'upgrade_d6_file'.
 *
 * If the D6 {files} table has an empty timestamp, lookup the creation date of
 * the image node the file is attached to (if possible).
 */
function sw_migrate_migrate_upgrade_d6_file_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();
  $img_timestamp = 0;
  if (empty($values['timestamp'])) {
    $img_timestamp = $source
      ->getDatabase()
      ->query('SELECT n.created FROM {content_type_image} c INNER JOIN {node} n ON c.vid = n.vid WHERE c.field_image_fid = :fid', [
        ':fid' => $values['fid']
      ])
      ->fetchField();
  }
  $row->setSourceProperty('img_timestamp', $img_timestamp);
}

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for 'upgrade_d6_taxonomy_term'.
 *
 * Count the number of nodes associated with each term.
 *
 * Set a 'valid_term' property in the source row only if the vocabulary is
 * 'Topics' or 'Image galleries' (where we always preserve the terms) or the
 * term is associated with at least 1 node.
 *
 * @see http://tasks.socialistworker.org/node/983
 */
function sw_migrate_migrate_upgrade_d6_taxonomy_term_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();
  $node_count = $source->getDatabase()
      ->query('SELECT COUNT(*) FROM {term_node} tn INNER JOIN {node} n ON tn.vid = n.vid WHERE tn.tid = :tid', [
        ':tid' => $values['tid']
      ])
      ->fetchField();
  $row->setSourceProperty('node_count', $node_count);
  // Terms from topic (2) and image gallery (14) are always valid.
  // Otherwise, this term is only worth migrating if it has nodes.
  $valid_term = $values['vid'] == 2 || $values['vid'] == 14 || !empty($node_count);
  $row->setSourceProperty('valid_term', $valid_term ? 1 : 0);

  // Special vocabulary-specific handling.
  switch ($values['vid']) {
    case 1:
      _sw_migrate_d6_taxonomy_term_prepare_row_section($row, $source, $migration);
      break;

    case 5:
      _sw_migrate_d6_taxonomy_term_prepare_row_issue($row, $source, $migration);
      break;

    case 12:
      _sw_migrate_d6_taxonomy_term_prepare_row_series($row, $source, $migration);
      break;

  }
}

/**
 * Private helper to prepare a migration row for a 'issue' taxonomy term.
 */
function _sw_migrate_d6_taxonomy_term_prepare_row_issue(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();

  // If there's a timestamp record in {sw_issue_dates}, use it.
  $datestamp = $source->getDatabase()
    ->query('SELECT pub_date FROM {sw_issue_dates} WHERE issue_num = :number', [':number' => $values['name']])
    ->fetchField();
  if (!empty($datestamp)) {
    $issue_date = format_date($datestamp, 'custom', 'F j, Y');
  }
  // Otherwise, see if there's custom text in {sw_issue_date_text}.
  else {
    $issue_date = $source->getDatabase()
      ->query('SELECT date_text FROM {sw_issue_date_text} WHERE issue_num = :number', [':number' => $values['name']])
      ->fetchField();
  }
  if (!empty($issue_date)) {
    $row->setSourceProperty('issue_date', $issue_date);
  }
}

/**
 * Private helper to prepare a migration row for a 'section' taxonomy term.
 */
function _sw_migrate_d6_taxonomy_term_prepare_row_section(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();

  // Ignore department parent values, we want everything to be top-level as a section.
  $row->setSourceProperty('parent', 0);

  // Force the weights how we want in the new world:
  switch ($values['tid']) {
    case 11:    // Editorials
      $weight = 0;
      break;
    case 7:     // Labor
      $weight = 1;
      break;
    case 8:     // Activist News
      $weight = 2;
      break;
    case 6:     // History and Traditions
      $weight = 3;
      break;
    case 9:     // Readers' Views
      $weight = 4;
      break;
    case 17255: // Obrero Socialista
      $weight = 5;
      break;
  }
  if (isset($weight)) {
    $row->setSourceProperty('weight', $weight);
  }
}

/**
 * Private helper to prepare a migration row for a 'series' taxonomy term.
 */
function _sw_migrate_d6_taxonomy_term_prepare_row_series(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();
  $variable_names = [
    'sw_series_labels_' . $values['tid'],
    'sw_series_insert_story_list_length_' . $values['tid'],
  ];
  $series_variables = $source->getDatabase()
    ->query('SELECT name, value FROM {variable} WHERE name IN (:values[])',
            [':values[]' => $variable_names])
    ->fetchAllAssoc('name', PDO::FETCH_ASSOC);

  // Declare defaults, since we only set variables in SW 2.0 to override them.
  $show_story_labels = TRUE;
  $series_insert_list_length = -1;  // Show all
  if (isset($series_variables[$variable_names[0]]['value'])) {
    $show_story_labels = unserialize($series_variables[$variable_names[0]]['value']);
  }
  $row->setSourceProperty('show_story_labels', $show_story_labels);
  if (isset($series_variables[$variable_names[1]]['value'])) {
    $series_insert_list_length = unserialize($series_variables[$variable_names[1]]['value']);
  }
  $row->setSourceProperty('series_insert_list_length', $series_insert_list_length);
}

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for 'upgrade_d6_node_story'.
 *
 * Handles section, topic and story type terms, and optional custom story label.
 *
 * @see http://tasks.socialistworker.org/node/982
 * @see http://tasks.socialistworker.org/node/984
 */
function sw_migrate_migrate_upgrade_d6_node_story_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();
  $node_terms = $source->getDatabase()
      ->query('SELECT td.tid, td.vid, td.name FROM {term_node} tn INNER JOIN {term_data} td ON td.tid = tn.tid WHERE tn.vid = :vid',
              [':vid' => $values['vid']])
      ->fetchAllAssoc('tid', PDO::FETCH_ASSOC);

  $node_vocabs = [];
  foreach ($node_terms as $tid => $term) {
    $node_vocabs[$term['vid']][$tid] = $term;
  }

  // Most departments are dropped, a few are merged. Use the callback map function.
  if (!empty($node_vocabs[1])) {
    $term = array_shift($node_vocabs[1]);
    $row->setSourceProperty('sw3_section_tid', sw_migrate_section_id_map($term['tid']));
  }

  // These are all migrated exactly as-is.
  $vocab_map = [
    2 => 'sw3_topic_tid',
    5 => 'sw3_issue_number_tid',
    12 => 'sw3_series_tid',
  ];
  foreach ($vocab_map as $vid => $sw3_id) {
    if (!empty($node_vocabs[$vid])) {
      $term = array_shift($node_vocabs[$vid]);
      $row->setSourceProperty($sw3_id, $term['tid']);
    }
  }

  // These are potentially multi-valued, and need array support.
  $multi_value_vocab_map = [
    4 => 'sw3_contributors_terms',
    6 => 'sw3_city_terms',
    7 => 'sw3_state_terms',
    8 => 'sw3_country_terms',
    9 => 'sw3_keywords_terms',
  ];
  foreach ($multi_value_vocab_map as $vid => $sw3_id) {
    if (!empty($node_vocabs[$vid])) {
      $row->setSourceProperty($sw3_id, $node_vocabs[$vid]);
    }
  }

  // Story type is a special case, since we have to see if we need to preserve
  // the SW 2.0 value as a custom story label.
  // First, set what we think the story_type_tid should be
  if (!empty($node_vocabs[10])) {
    $sw2_story_type_term = array_shift($node_vocabs[10]);
    $sw3_story_type_tid = sw_migrate_story_type_id_map($sw2_story_type_term['tid']);
  }
  // If the 2.0 story type is defined
  // AND the 3.0 story type is undefined
  // AND either the story has no authors
  //     OR the story has more than 3 authors
  if (!empty($sw2_story_type_term['tid'])
      && empty($sw3_story_type_tid)
      && (empty($values['field_authors'])
          || count($values['field_authors']) > 3)
  ) {
    // Save the 2.0 story type as a custom story label for 3.0.
    $row->setSourceProperty('sw3_story_label', $sw2_story_type_term['name']);
    $sw3_story_type_tid = SW_STORY_TYPE_CUSTOM_TID;
  }
  $row->setSourceProperty('sw3_story_type_tid', $sw3_story_type_tid);

  // Handle normal and wide image fields, if possible.
  $sw3_main_image_id = sw_migrate_find_first_dme_img($values['field_body'][0]['value']);
  if (!empty($sw3_main_image_id)) {
    $row->setSourceProperty('sw3_main_image_id', $sw3_main_image_id);
    $sw3_wide_image_id = $source->getDatabase()
      ->query('SELECT nid FROM {content_type_image} WHERE field_original_image_nid_value = :nid AND field_image_crop_type_value = 6',
              [':nid' => $sw3_main_image_id])
      ->fetchCol();
    if (!empty($sw3_wide_image_id)) {
      $row->setSourceProperty('sw3_wide_image_id', $sw3_wide_image_id);
    }
  }
}

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for 'upgrade_d6_node_insert_box'.
 *
 * Handles topic and insert type terms.
 */
function sw_migrate_migrate_upgrade_d6_node_insert_box_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();
  $node_terms = $source->getDatabase()
      ->query('SELECT td.tid, td.vid, td.name FROM {term_node} tn INNER JOIN {term_data} td ON td.tid = tn.tid WHERE td.vid IN (2, 13) AND tn.vid = :vid',
              [':vid' => $values['vid']])
      ->fetchAllAssoc('vid', PDO::FETCH_ASSOC);

  // There's no special re-mapping or filtering needed for either of these.
  $row->setSourceProperty('sw3_topic_tid', $node_terms[2]['tid']);
  $row->setSourceProperty('sw3_insert_type_tid', $node_terms[13]['tid']);
}

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for 'upgrade_d6_node_image'.
 *
 * Handles section, topic and story type terms
 */
function sw_migrate_migrate_upgrade_d6_node_image_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $values = $row->getSource();
  $node_terms = $source->getDatabase()
      ->query('SELECT td.tid, td.vid, td.name FROM {term_node} tn INNER JOIN {term_data} td ON td.tid = tn.tid WHERE tn.vid = :vid',
              [':vid' => $values['vid']])
      ->fetchAllAssoc('tid', PDO::FETCH_ASSOC);

  $node_vocabs = [];
  foreach ($node_terms as $tid => $term) {
    $node_vocabs[$term['vid']][$tid] = $term;
  }

  // These are definitely single-value and migrated exactly as-is.
  $single_value_vocab_map = [
    14 => 'sw3_image_gallery_tid',
    15 => 'sw3_image_rights_tid',
  ];
  foreach ($single_value_vocab_map as $vid => $sw3_id) {
    if (!empty($node_vocabs[$vid])) {
      $term = array_shift($node_vocabs[$vid]);
      $row->setSourceProperty($sw3_id, $term['tid']);
    }
  }
  // These are potentially multi-valued, and need array support.
  $multi_value_vocab_map = [
    6 => 'sw3_city_terms',
    7 => 'sw3_state_terms',
    8 => 'sw3_country_terms',
    16 => 'sw3_image_provider_terms',
    17 => 'sw3_image_credit_terms',
    18 => 'sw3_image_server_folder_terms',
  ];
  foreach ($multi_value_vocab_map as $vid => $sw3_id) {
    if (!empty($node_vocabs[$vid])) {
      $row->setSourceProperty($sw3_id, $node_vocabs[$vid]);
    }
  }
}

/**
 * Migrate callback function to deal with taxonomy term IDs.
 *
 * This prunes terms from the Department/Section and Story type vocabularies
 * that we no longer need in SW 3.0. Used while creating the taxonomy terms
 * themselves via the update_d6_taxonomy_term migration.
 *
 * @param string $tid_vid_duple
 *   A string containing the D6 term ID (TID) and vocabulary ID (VID)
 *   delimited by '\'.  This gets around a limitation that the 'callback'
 *   process can only pass a single argument.
 *
 * @return integer
 *   The term ID we want to use, or 0 to drop this term.
 */
function sw_migrate_term_id_map($tid_vid_duple) {
  list ($tid, $vid) = explode('\\', $tid_vid_duple);
  switch ($vid) {
    case 1: // 2.0 Department ("Section" in 3.0)
      return sw_migrate_section_id_map($tid);

    case 10: // Story type
      // Analysis: will be re-purposed into 'Custom'
      if ($tid == 391) {
        return $tid;
      }
      return sw_migrate_story_type_id_map($tid);

      // All other vocabularies, we want to create all terms.
    default:
      return $tid;
  }
}

/**
 * Callback function to deal with department/section taxonomy term IDs.
 *
 * This prunes terms that we no longer need in SW 3.0.
 *
 * @param integet $tid
 *   The term ID (TID) of the SW 2.0 Department.
 *
 * @return integer
 *   The term ID we want to use for the SW 3.0 Section, or 0 to drop this term.
 */
function sw_migrate_section_id_map($tid) {
  switch ($tid) {
    case 6:     // History and Traditions
    case 7:     // Labor
    case 8:     // Activist News
    case 9:     // Readers' Views
    case 11:    // Editorials
    case 17255: // Obrero Socialista
      return $tid;
      // Otherwise, drop the term.
    default:
      return 0;
  }
}

/**
 * Callback function to deal with story type taxonomy term IDs.
 *
 * This prunes terms that we no longer need in SW 3.0.
 *
 * @param integet $tid
 *   The term ID (TID) of the SW 2.0 Story type.
 *
 * @return integer
 *   The term ID we want to use for the SW 3.0 story type, or 0 to drop this term.
 */
function sw_migrate_story_type_id_map($tid) {
  switch ($tid) {
    case 393:   // Interview
    case 4556:  // Obituary
    case 2922:  // Roundtable
      return $tid;
      // Otherwise, drop the term.
    default:
      return 0;
  }
}

/**
 * Migrate callback function to (potentially) rename taxonomy terms.
 *
 * @param string $tid_name_duple
 *   A string containing the D6 term ID (TID) and term name delimited by '\'.
 *   This gets around a limitation that the 'callback' process can only pass a
 *   single argument.
 *
 * @return string
 *   The name we want to use for this term.
 */
function sw_migrate_term_name_map($tid_name_duple) {
  list ($tid, $name) = explode('\\', $tid_name_duple);
  switch ($tid) {
    case 391:
      return 'Custom';

    default:
      return sw_migrate_fancy_quotes($name);
  }
}

/**
 * Migrate callback function to (potentially) remap node/taxonomy term associations.
 *
 * @param integer $tid
 *   The term ID we're about to associate with a node.
 *
 * @return integer
 *   The term ID we actually want to use, or 0 to drop this term/node association.
 */
function sw_migrate_term_node_map($tid) {
  switch ($tid) {
    // Subterms of 'History and Traditions' are merging into their parent term.
    case 14:     // History/Paul D'Amato
    case 11172:  // History/Todd Chretien
      return 6;

    // 'Analysis' story type. This is being ditched in SW 3.0.  However, we're
    // converting this tid into the 'Custom' story type (so all the custom
    // code can already know what the ID will be). So, any story that is
    // classified with this should ignore it and have no story type.
    case 391:
      return 0;
  }

  // Otherwise, leave it alone and use whatever we were given. The migration
  // will check against the successfully imported terms, so other sections
  // and story types that were purged will be ignored.
  return $tid;
}

/**
 * Migrate callback function to try to find the first <dme:img> tag.
 *
 * This is used to populate field_main_image.
 *
 * @param string $body
 *   The D6 value of field_body.
 *
 * @return integer
 *   The media ID of the main image for this story (or 0 if there is none).
 */
function sw_migrate_find_first_dme_img($body) {
  $matches = [];
  return preg_match('@<dme:img nid=(\d+)@', $body, $matches) ? $matches[1] : 0;
}
