<html>
<head>

<title>
Washington's one-two punch
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<font face="Times New Roman, Times, serif" size="4">Repealing the estate tax &#8226; Tighter bankruptcy laws</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>Washington's one-two punch</b></font><p>
<font face="Times New Roman, Times, serif" size="2"><b>By Eric Ruder</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | April 22, 2005 | Page 12</font><p>

<font face="Times New Roman, Times, serif" size="3">ONE DAY after the House of Representatives showed its devotion to the super-rich by voting to repeal the estate tax, it delivered a swift kick to the poor--approving legislation to tighten the nation's bankruptcy laws.<p>
On both days, House Democrats joined the majority Republicans to pass the measures by solid margins. The bankruptcy bill now goes to George Bush to sign--which the president says he's "eager" to do. The estate tax repeal has to be passed by the Senate.<p>
Repealing the estate tax has long been a dream of Republicans. Currently, the tax requires that estates worth more than $1.5 million for individuals and $3 million for couples be taxed at 47 percent. <p>
In 2004, fewer than 1 percent of the estates of people who died paid any estate tax, and half the revenue generated by the tax came from estates worth more than $10 million. Under current guidelines, by 2009, the exemptions will rise to $3.5 million for individuals and $7 million for couples--meaning that a mere 0.3 percent of all estates will be subject to any tax.<p>
Opponents of the estate tax claim to be defending small business owners against government attempts to confiscate their private property when they die. But in reality, repeal of the estate tax will only benefit the children of the very richest Americans--while forcing the rest of us to foot the bill for lost tax revenue.<p>
Repeal of the estate tax would cost the government close to $1 trillion between 2012 and 2021, according to the Center on Budget and Policy Priorities. Instead of a giveaway to the richest Americans, this money could wipe out 58 percent of the $1.7 trillion that the government has borrowed from the Social Security trust fund to finance other spending--and put a speedy end to the supposed crisis in the government-run retirement system.<p>
One day after House members held out a helping hand to America's super rich, the House reconvened to approve new bankruptcy laws that will trap working class people under mountains of personal debt. The bill will require those who declare bankruptcy to repay a larger share of their debts and in many cases to sell their homes to do so. <p>
Credit card companies are delighted by the new law, which they spent millions to get passed. They are expected to take in an additional $1 billion annually as a result of the law.<p>
Lawmakers who voted for the legislation claimed they were making it harder for the system to be abused. But the truth is that overwhelming medical bills cause half of all bankruptcies. All it takes is one accident or serious illness to sink an entire household into debt--even people with health insurance, if their condition isn't adequately covered.<p>
Congress rejected every amendment to lessen the impact of the legislation on ordinary people. But lawmakers did see fit to leave in one loophole--the law does nothing to address the use of "asset protection trusts" by rich people looking to shield their assets from bankruptcy courts.<p>
If this all seems unfair, that's because it is. But it's standard operating procedure in a system where the politicians sell themselves to the highest bidders.<p>


<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
