<html>
<head>

<title>
Should the U.S. get out of Iraq now?
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<?php include "../../legacy-includes/Script.htmlf" ?>
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><?php include "../../legacy-includes/TopLogo.htmlf" ?></td>

<td width="270"><?php include "../../legacy-includes/TopAd.htmlf" ?>
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><?php include "../../legacy-includes/LeftButtons.htmlf" ?></td>

<td width="18"></td>

<td width="480" valign="top">
<?php include "../../legacy-includes/BodyInsert.htmlf" ?>

<font face="Times New Roman, Times, serif" size="4">A debate in the antiwar movement</font><br>
<font face="Times New Roman, Times, serif" size="5"><b>Should the U.S. get out of Iraq now?</b></font><p>
<font face="Arial, Helvetica, sans-serif" size="2">April 22, 2005 | Pages 6 and 7</font><p>
<font face="Times New Roman, Times, serif" size="3">ON APRIL 6, three voices of the antiwar movement came together to debate what attitude activists should take to the U.S. occupation of Iraq. The meeting, held in New York City, was organized by Brooklyn Parents for Peace. The three speakers were: <p>
-- ALEX RYABOV, who served in the Marine Corps during the invasion of Iraq and is cofounder of Iraq Veterans Against the War.<p>
-- ANTHONY ARNOVE, an author, activist and member of the editorial board of the <i>International Socialist Review. </i>He edited <i>Iraq Under Siege </i>and co-edited, with Howard Zinn, <i>Voices of a People's History of the United States.</i> <p>
-- ERIK GUSTAFSON, a veteran of the 1991 Gulf War and director of the <a href="http://www.epic-usa.org" target="_blank">Education for Peace in Iraq Center</a> (EPIC). Led and advised by Iraqis, returned soldiers and activists, EPIC works to end the war and ensure genuine self-determination for the people of Iraq.<p>
Here, with permission from the speakers, we print their presentations. Thanks to Charles Jenks of the <a href="http://www.traprockpeace.org" target="_blank">Traprock Peace Center</a> for the transcription of the meeting that this feature was based on. A pdf transcript of entire event, as well as sound files, can be found at <a href="http://www.traprockpeace.org" target="_blank">Traprock Peace Center Web site</a>.<p>
<font face="Arial, Helvetica, sans-serif" size="2"><b>Jump to the presentations below:<br>
<a href="#Alex">Alex Ryabov</a> | <a href="#Anthony">Anthony Arnove</a> | <a href="#Erik">Erik Gustafson</a></b></font><P>
<font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font><p>

<a name="Alex"></a><font face="Times New Roman, Times, serif" size="4"><b>ALEX RYABOV</b></font><p>

<font face="Times New Roman, Times, serif" size="3">MY NAME is Alex Ryabov. I am 22 years old, and I joined the Marine Corps straight out of high school. I was 17 years old. My reasons in a nutshell for joining were money for college, health benefits--and you know, other great things that I'd learn from the Marine Corps: discipline and honor, things like that. Also, I was somewhat naive at 17 years old. I was going to get a rifle. I was going to get to blow things up legitimately and get paid for it, so it seemed like a dream job. <p>
I went through boot camp and became a Marine. My motivation was pretty high, but it steadily declined over my time in the Marine Corps. When I got to the fleet and to my unit, which was an artillery unit, I began to see what the real Marine Corps was about, which includes a lot of bureaucracy. They'll tell you to work smarter, not harder--and there will be a common sense, straightforward way to do something, and you'd be pretty much told to bend over backwards and jump through hoops to get it done. <p>
Nevertheless, I continued on. From June 2002 through December 2002, we were in Japan for a scheduled deployment. Toward the end of 2002, word began circulating that we were going to war with Iraq--that there was a build-up going on. In the news, everyone was being told that Iraq had weapons of mass destruction, and Saddam was an imminent threat and all those things. <p>
Finally, in the beginning of January 2003, we were told that, yes, we would be going to Iraq. Our commanding officer spoke to us briefly, and then he and other officers went back inside. At this point, our first sergeant, who was the senior enlisted man in our unit, gathered us around and began to speak to us to prepare us for going to Iraq. He said, "In going over there, don't think you're going to be heroes. Don't think you're going over to Iraq to topple Saddam Hussein, find weapons of mass destruction, or to bring democracy to the Iraqi people." He said, "You're going to Iraq for one reason and one reason alone, and that's oil." <p>
I'm being quite serious when I say this. This man is a veteran of the first Persian Gulf War and has been in the Marine Corps 20-plus years, so he knows what he's talking about. But he continued on, saying that you're still going to go because you signed a contract. <p>
We began to prepare for going to Iraq. This included packing up our vehicles, guns--which were 155mm Howitzers--and the rest of our gear. I want to point out that this gear was not desert camouflage. It was green. So we had big, green trucks; big, green guns; and big, green camouflage netting that we actually did put up in the middle of the desert. You don't have to be affiliated with the military to know that that's not very smart. <p>
Our vehicles were completely unarmored. As far as body armor goes, we only had one ballistic plate instead of two. You're supposed to have one for your chest and one to protect your back. <p>
So we went over to Kuwait in the middle of February. We were in Kuwait for a little bit over a month, and I believe it was the morning of March 18, at about 2:30 Kuwait time, that we were woken up, told to get our things together--that we were moving out. As we began moving out, I know myself that I wasn't really afraid of bullets or conventional munitions that Iraqis were going to use against us, but by that time, there was fear of chemical and biological weapons. <p>
The very first sites where we'd begin to attack Iraq were at the Kuwaiti border because artillery can fire upwards of 15 miles away to really reach out and touch someone--except that when you reach out and touch someone with artillery, then there's nothing left of them. <p>
Things that really made an impact on me through my time in Iraq were, for one, seeing dead bodies for the first time. A lot of times, firefights would take place in the middle of a road, and we'd pass through the area about 20 or 30 minutes later or sometimes sooner than that. So we passed through an area where a firefight had taken place, and there were two dead Iraqi men lying in the middle of the road. One was lying sort of horizontal on top of the other one, with his eyes wide open and glazed over. There was no doubt in my mind that he was dead. You could tell that the man's soul was no longer in his body. <p>
Another thing to mention is that, in artillery, we're firing upward of 15 miles away, so you don't get to see what you're shooting at. As a result, you're somewhat desensitized from the killing. <p>
At one point, we were firing at an Iraqi artillery unit, and about 20 or 30 minutes later, we were passing through the area where they had been. We were told through our two-way radios to look at the right side of the road, because that's where they'd be. I looked at the right side of the road, and I didn't see them. I expected to see maybe pieces of vehicles, stuff like that. I saw a piece of metal here, a piece of metal a little further down--everything else looked like it had been put in a blender, spun around and poured back over the ground. It was completely indistinguishable. <p>
At the time I was in Iraq, I ended up blocking these things out because, had I tried to deal with them, I would have been no good to myself and no good to the rest of the unit. <p>
The thing that really had the most impact on me was when we were moving up to Tikrit. The windshield in my vehicle, along with several other vehicles, had been blown out because of flying gunpowder charges weighing in excess of 48 pounds. We were moving up to Tikrit--it was about 4 o'clock in the morning. <p>
The way artillery units work, the howitzer is stowed behind the truck, and it so happens that the end of the barrel lines up directly with the windshield on the vehicle behind it. The vehicle in front of us kicked up sand and dust, and came to a stop, and we were unable to see them--it was like a smokescreen put up in front of us. <p>
By the time my driver did see their vehicle, it was too late, and we ran directly into the howitzer. The howitzer--you can imagine is sort of a steel telephone pole--went through where the windshield used to be, brushed my right shoulder and went out the back of the cab. Then we backed up, and the entire roof came off our vehicle and fell to the ground. We were told to get the pieces off the ground, and we had to keep going. <p>
When daylight hit, aside from smoking a lot of cigarettes in a short period of time, I looked at my right shoulder. As you've seen, the desert uniforms are a light beige color. This entire shoulder was totally pitch black from the carbon and gunpowder residue from the barrel--meaning that, had it been another six inches to my left, I wouldn't be here right now. <p>
I came back from Iraq at the end of May 2003. When we had been over there and began the initial push into Iraq, Iraqi people were on the sides of the road, waving to us, sharing things, and kids were asking for candy. I remember one negative thing we did see was an old Iraqi woman thumbing her nose at us, and that was pretty self-explanatory. In a way, I guess it was a foreshadowing of things to come. <p>
When we did come back at the end of May and beginning of June, the sentiment of the Iraqi people began to shift: attacks being stepped up, things like that. CNN was on in the cafeteria, so every single meal I was eating, I was seeing the body count continue to rise on both sides. After a while, something just snapped in me, and I realized that this war, with everything else taken aside, was a complete waste of human life on both sides--and I realized that I was against it. <p>
The problem was that at this point, I still had about a year left in the Marine Corps, so I had to bite my tongue because if I had spoken my mind--if I had told my superiors and such how I felt--I would have very likely lost the benefits that I had almost died to keep. <p>
I finally got out of the Marine Corps and came home in the middle of May 2004. At that point, I knew I was against the war. I had all this anger and frustration, but no outlet for it. Michael Hoffman, who was in my unit, had gotten out about a year before I did, and I knew he had begun participating in peace movement rallies and things like that. He called me up in the beginning of June and said that there was a peace rally in Manhattan, and maybe I should come. <p>
I showed up, and I expected to see people our age--maybe early-to-mid twenties. The people I met were World War II veterans, Korean War veterans, Vietnam veterans and veterans all the way up to the current conflict, including families who had lost sons, friends and loved ones over there. I began seeing how extensive the peace movement really was. <p>
From there, at the end of July of 2004, we started Iraq Veterans Against the War in Faneuil Hall in Boston. Since then, we have been doing things ranging from phone interviews to speak-outs like this, forums, debates. <p>
I'd like to get into our official position as Iraq Veterans Against the War, and that is that we are calling for immediate withdrawal of U.S. troops from Iraq. The fact is that we should not have gone into Iraq to begin with. This is a topic unto itself, but the war in Afghanistan actually had some type of reasons for it. Osama bin Laden and al-Qaeda were responsible for 9/11, they were in Afghanistan, so we needed to go to Afghanistan to get them. <p>
In the case of Iraq, there was no clear line of reason. Iraq did not have weapons of mass destruction--which, I'd like to point out, the U.S. had sold to them to begin with, and a lot of people conveniently forget this. Saddam was not an imminent threat because even if he had those weapons of mass destruction, he did not have the means to get them to the United States. <p>
As far as him being an evil dictator and committing all kinds of crimes against his people, there are plenty of evil dictators throughout the world, but that doesn't mean that we need to parade around like the world police with a nightstick. You can't go invading every single country that has human rights violations. <p>
Since the invasion of Iraq, there are estimates as to how many Iraqi civilians have been killed. The lower end of the estimates are somewhere from 10,000 to 14,000, and the higher end, which I believe is a lot more accurate, is close to 100,000. And this is not including the Iraqi military--it's not including foreign fighters or insurgents or anything like that. Not to mention that upwards of 1,500 U.S. troops have been killed, and that number--this is sort of going off on a tangent--is not accurate because suicides are not counted, vehicle accidents are not counted, older troops who have been in for a while as they're dying are actually retired, so they're not counted in a complete death toll. <p>
Also, upwards of 10,000 U.S. troops have been injured, and that's ranging anywhere from losing feet or a toe to guys coming back with both arms missing, severe head trauma. And the dead and wounded are being brought back under the cover of night to hide the costs of this war from the American people. <p>
From the time that we came into Iraq, the Iraqi people--the ones that I saw--were happy to see us because they thought we were bringing Iraq some good. When we took down Saddam Hussein, the Baath Party and the Iraqi military, I thought that our mission was finished, we'd wrap things up and come back home, but that wasn't the case. <p>
Now you have U.S. Marines, the Army and other forces that are not trained as occupying forces. They're trained to go in, accomplish an objective, eliminate enemy forces, and that's it. Now these same forces are being used to police the Iraqi people. They're being used to try to control certain areas where military units instead of politicians are in control of an area, and they're charged with keeping order--making sure that there is no looting, and things like that go on. <p>
We've completely lost the trust of the Iraqi people. U.S. troops kicking down the doors of houses in the middle of the night because there's suspicion that the husband or another family member of a military agent there is somehow involved with the insurgents. We have countless examples of vehicles running checkpoints, and they get shot at, and the troops doing the shooting will check the vehicle, only to realize that it was civilians, and they found out that they had just killed an entire family.<p>
To sum things up, the Iraqi people do not want us in their country. The way the word "insurgents" has been misused on the news makes it seem like it's a new term for bad guys. The real definition of insurgent is someone who is rebelling against established authority, especially the government, and that's exactly what the Iraqi people are doing. <p>
In terms of people saying that we cannot withdraw our troops because Iraq would fall into chaos, we are the ones causing the chaos right now. We are the ones who are responsible for a lot of the killings, whether intentional or unintentional--vehicles running checkpoints, bombing runs gone astray, things like that. And a lot of times, where you have insurgent attacks aimed at the U.S. military, you have a lot of Iraqi people who are getting caught in the crossfire. This is sort of misusing the term, but in a way, they become like collateral damage in their attempts to kill, maim and destroy the U.S. military presence in the area. <p>
I'd just like to end by saying that we should call for the immediate withdrawal of our troops. Our government has taken us into Iraq, and I believe that we should leave it up to them--supervised--to come up with a strategy to get out of Iraq. <p>
<font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font><p>

<a name="Anthony"></a><font face="Times New Roman, Times, serif" size="4"><b>ANTHONY ARNOVE</b></font><p>

<font face="Times New Roman, Times, serif" size="3">WE FIND ourselves in a remarkable situation today that I think we have to take stock of. Despite all of the pro-war propaganda from the corporate media and despite what I would argue has been acquiescence of much of the left over the last year, a majority of people in the United States today believe that the consequences of the invasion in Iraq were not worth it, and are now opposing and questioning this war in a fundamental way. <p>
Particularly, they are questioning the rising consequences of this war in their communities, like the communities in Vermont that passed resolutions about the National Guard troops that are being sent to this conflict--like the communities and military families and veterans who are speaking out against this war. <p>
The official justifications for the war have all been exposed as complete fallacies. No weapons of mass destruction were found, no connections between Saddam Hussein and the Iraqi government and al-Qaeda or the attacks of September 11. The occupation has not paid for itself, as Paul Wolfowitz told us it would in the lead-up for the war. And U.S. soldiers, as Alex pointed out, have not been treated as liberators by the Iraqi people. <p>
Meanwhile, on the ground in Iraq today, there are more Iraqis in prison than at any point during the occupation. It's now up to around 8,900 officially detained, including people who are still detained in the Abu Ghraib prison, where some of the most extreme examples of torture and abuse took place, but which are by no means unique. There are almost certainly people who aren't being counted in those official numbers, because the United States is holding people outside of any possible international inspection. <p>
The British medical journal <i>The Lancet </i>has estimated in a very rigorous study that as many as 98,000 excess deaths occurred in Iraq as a consequence of the invasion in 2003. That's not counting people who have been killed by military occupation--people who were killed, for example, in the siege of Falluja. <p>
Electricity in Iraq remains at levels below even what existed under the severe sanctions that the country was subjected to under Saddam Hussein. Some $8 billion of money that was supposedly sent to Iraq for reconstruction efforts has gone completely missing and is totally unaccounted for. Unemployment, internal displacement, lack of access to safe drinking water--all of these problems continue to profoundly plague the people of Iraq. <p>
And, as Alex pointed out, people continue to be humiliated and killed and abused in the house-to-house searches that are going on, still with the participation of U.S. soldiers, although sometimes accompanied by local proxies. Iraqis are killed routinely with complete impunity at checkpoints, and we've seen in example after example that when evidence of abuse emerges, none of the officials are held responsible. <p>
None of the people overseeing the policies that allowed the torture in Abu Ghraib to take place--none of the people who set the framework for the rules of engagement in Iraq--are being held accountable. But also, more and more, we see examples of soldiers directly involved in the abuse and in killings being let off. <p>
And yet, many of the people who spoke out against this invasion, marched on February 15, who opposed sanctions for years before that are now suggesting that U.S. troops should stay in Iraq for the benefit of the Iraqi people. They say that despite these abuses and the torture and killing, and before that, the sanctions on Iraq--still, the U.S. government and the military troops sent into Iraq should stay for the benefit of the Iraqi people. <p>
Thus, we confront a strange situation of the antiwar movement mobilizing against the war and then supporting an occupation that is a direct result of that war. I think it's an incoherent condition, and one that we have to absolutely reject. Not having found weapons of mass destruction in Iraq, which was the first big lie of this invasion, the Bush administration has come up with a new big lie, and that is that Donald Rumsfeld, George Bush, Condoleezza Rice and Paul Wolfowitz are bringing democracy to the Iraqi people. <p>
But democracy has absolutely nothing to do with why the United States is in Iraq. In fact, the United States has no interest in seeing democracy in Iraq. <p>
The Bush administration invaded Iraq in 2003 for reasons of power politics, having to do with the U.S. desire to control Middle Eastern energy resources. <p>
Iraq has the world's second largest oil reserves. It sits in a region with two-thirds of the world's oil reserves, and it has been an essential axiom of U.S. foreign policy for decades that the U.S. will control those resources--not so that it can import all that oil from the Middle East into the United States, but so that it can control oil as a weapon of political power, including using oil as a weapon against military and economic competitors who increasingly dependent on those same energy resources from the Middle East. So for example, Europe, Japan, China and India import more of their energy resources from that region, and we have countries like China and India that are rapidly growing--that need to import more oil and are looking to the Middle East for their energy resources. <p>
The U.S. wants to maintain its control over the Middle Eastern energy resources as a leverage against any potential economic or military rival in the future. If you look at the national security strategy document of the United States, which was released in September of 2002, it lays this out very clearly. The U.S. wants to preserve the enormous gap that exists between itself and its potential military competitors, as well as the enormous gap between itself and any other potential competitor economically. <p>
The U.S. saw an opportunity in going into Iraq to extend its regional hegemony and thereby extend its global hegemony on the world stage. The hope of the United States in invading Iraq was to install a more favorable regime--one that would allow it to have military bases in Iraq. It also hoped by going into Iraq to have a staging ground for other intervention in the region, including military intervention and extending the doctrine of regime change, wherever possible, to other regimes that threaten U.S. interests and are destabilizing factors in the region, particularly Syria and Iran. <p>
We now know that the U.S. is establishing bases, hoping that they will become permanent bases in Iraq. The U.S. has its largest embassy anywhere in the world in Baghdad. And this has nothing to do with democracy. <p>
It's important to remind ourselves of the history of U.S. intervention in the Middle East--how the U.S. has consistently backed undemocratic regimes, whether Islamist or not, as long as those regimes ensured stability for the region. And how the United States has consistently undermined any popular, democratic, nationalist, communist, socialist or secular movement that might challenge the status quo in the region. <p>
This was illustrated with the support for the overthrow of Mossadeq in Iran in 1953, and then the support for the brutal regime of the Shah in Iran that followed. It's also the reason the United States for years was allied to Saddam Hussein--armed him, trained him, provided him strategic and military intelligence, and stood by the Iraqi government during the worst of its crimes against the Kurds, against the Iraqi people, against the Iranians against whom Saddam used chemical weapons. <p>
All of those things occurred with the patronage and support of the United States, and then those very crimes were trotted out in 1991 and again in 2003 to justify military intervention by the United States. <p>
The U.S. opposes genuine democracy in the Middle East for a few very simple reasons--one of which is that if the ordinary people of the region had a say in really determining things, they might use the profits from oil resources for social development and for human need, rather than those resources and the profits from them going to the major multinational oil companies based in the United States and the West. <p>
That's why the United States established transitional administrative law in Iraq and passed more than a hundred resolutions that will outlive the occupation, imposing neo-liberal measures and austerity measures that will be binding on whatever government comes to power. <p>
These involve opening every aspect of Iraq's economy other than oil to 100 percent foreign ownership. They retain the anti-worker laws that were set up under the regime of Saddam Hussein, and they lower taxes on the rich and on corporations in Iraq to standards that would only be dreamed of by the most greedy corporations in the United States. And they have ensured that while Iraqi oil will not be turned over to 100 percent foreign ownership, it will be controlled de facto by private companies and dominated by Western oil giants. <p>
Even the <i>New York Times </i>ran a column by Jeff Madrick, a mainstream economist, who said that the consequences of these policies would be, as he put it, "widespread cruelty." This is what he wrote: "By almost any mainstream economist's standard, the plan is extreme, in fact, stunning. It would immediately make Iraq one of the most open trade and capital flows in the world and would put it among the lowest taxed in the world, rich or poor. The new plan reduces the top personal and corporate tax rate to only 15 percent. It reduces tariffs on imports to 5 percent, and it abolishes almost all restrictions on foreign investment. It would allow a handful of foreign banks to take over the domestic banking system." <p>
This is about neo-liberalism, and it's about U.S. control: economic control and political control, not about helping the Iraqi people. It's not just antiwar activists in the United States or abroad who are coming to these conclusions. As Alex just eloquently pointed out, soldiers who are being sent to Iraq, reservists who are being called up for duty, see through these lies. <p>
As one member of the Texas Army National Guard said on March 15 on the radio program <i>Democracy Now!</i> "I believe it's an unjust war on our part. I do not believe this government intends to spread democracy in the Middle East. It's not in the interests of their security or our security. I believe it's all about oil and profits." <p>
Another soldier said this on the same show on March 15: "When I first went to Iraq, I actually believed what the government was saying--that we were searching for weapons of mass destruction, we were making the country safe for democracy, and things like that. But, when we got there, I quickly found another story. I quickly found that Iraqis didn't want us there. If soldiers had come into our country and had invaded us and had come into our homes, I would have fought back, too. I was seeing how the war felt from a lot of the Iraqis' point of view." <p>
Soldiers and their families and veterans are speaking out against this war. It's a vital part of the antiwar movement, and it takes a lot of courage. It's something that we absolutely have to support. <p>
The final argument that I want to address is the idea that the United States has an obligation to the Iraqi people and therefore has to stay to clean up the mess that it created and bring stability to Iraq. I think it should be clear by now that rather than bringing stability, the U.S. occupation is the source of instability and the source of ongoing suffering and violence. <p>
Washington isn't preventing civil war from breaking out. In fact, it is actually increasing factionalism and infighting among various groups in Iraq to serve its own interests. <p>
We have to do everything we can to force the United States out of Iraq so that the Iraqi people can determine their own future. The U.S. has no business lecturing people around the world about democracy--given the lack of democracy here at home and given the history of U.S. attempts to "impose democracy around the world." <p>
Does the United States have an obligation to the Iraqi people? Absolutely, and if we lived in a just world, when the U.S. was forced out of Iraq, it would be forced to pay reparations to the Iraqi people for the years during which it supported Saddam Hussein, for the years of sanctions, and for the crimes of this occupation. It should also be forced to pay reparations to the soldiers and their families and communities that are being torn apart by this war. <p>
I'll end with something that Mark Twain said when he was observing the imposition of "democracy" in the Philippines, which involved the massacre of thousands upon thousands of Filipino people. He said, "I am opposed to the eagle putting its talons on any other land." <p>
I think he was absolutely right, and, like Mark Twain did in his day, I think we need a new anti-imperialist league to oppose the U.S. putting its talons on any other land. We have to start right now by getting the U.S. out of Iraq. <p>
<font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font><p>

<a name="Erik"></a><font face="Times New Roman, Times, serif" size="4"><b>ERIK GUSTAFSON</b></font><p>

<font face="Times New Roman, Times, serif" size="3">I AM Erik Gustafson, the director of the Education for Peace in Iraq Center, an organization that focuses on improving humanitarian conditions, defending the human rights of the Iraqi people and bringing about democratic change in Iraq. We've been around since 1998, and our message has not changed over those years. <p>
I've got some amazing people in the office who spend week after week compiling the best news coverage in dispatches that we send out by email. We're one of those rare organizations that only sends out one or two e-mails per month, but it's an e-mail that you definitely always want to get.  (You can subscribe via EPIC's website at www.epic-usa.org).<p>
I also should mention that while the organization, EPIC's board of directors and myself have a clear position and <i>do not</i> support immediate withdrawal, we also do not believe the U.S. can stay in Iraq. Not all of our subscribers agree with our position, and there's often lively discussion.<p>
Since the March 2003 invasion, it is difficult for me to leave Washington because I feel like the change that has to happen right now depends on me and so many others--both inside the government (believe it or not), and also outside government, with the different non-governmental organizations--trying to bring about direct policy change. There are unbelievable policy battles going on in Washington right now, creating challenges and tremendous opportunities. <p>
So that's been a lot of my focus, and it's really pulled me away from the grassroots side of things. However, the grassroots end of things is absolutely crucial as well, and I absolutely commend Alex and Anthony and Brooklyn Parents for Peace. I see a few familiar faces in the crowd. <p>
There were mass rallies before the invasion. We can't forget that. It was by far, I think, the strongest, broadest antiwar effort that this country has seen since the latter years of the Vietnam War, and I think it was incredibly diverse in many ways. You had organizations that represented the radical left. You had organizations named Patriots for Peace, trying to show that it's also patriotic to oppose the rush to war. It was an absolutely incredible time. The churches have never been more united against a war. NGOs and civil society groups have never been more united against a war, and we can't forget that. <p>
But where we're at today is different. A lot of the effort to try to prevent the war--the debate between pro-war and antiwar in the lead-up to the invasion--was more than appropriate and can't be forgotten in terms of our own health as a democracy. But at this point, you can support it or you can oppose it, but it's still going to be here. <p>
The key difference between what's happening in Iraq and what we saw in Vietnam is that in the case of Vietnam, we knew clearly that once the United States left Vietnam, the war would end, and that's indeed what happened. We also clearly understood who would take over--who would be in charge when we left--and that indeed happened as well. <p>
In the case of Iraq, we don't know, and just as I saw the issue of Iraq highly politicized during the years of sanctions, I see it continue to be highly politicized to this day. I see it politicized by everyone, whether it's partisan politics inside the Beltway, or it's the discussions that I see when I'm on the lecture circuit. <p>
I'll give you one example of how it gets politicized. You talk with the President, or the White House communications staff, and how are they going to characterize what's happening in Iraq? How do they characterize the insurgency?  "Anti-Iraq forces," right--or "terrorism." But that only describes the most extreme faction of the insurgency. There are also pro-Iraqi forces, which include Sunni Arab nationalists and resistance fighters.<p>
You talk with antiwar organizers, including friends, and ask them what's going on in Iraq, and a number of these organizers talk as though all insurgents are part of a broad-based resistance. As though the deliberate targeting of innocent civilians or a particular ethnic or religious community is a legitimate form of resistance. It shows you how politicized it gets. <p>
In reality, there are three primary sources of political violence in Iraq right now. First, there is a resistance in Iraq because of the poor judgment and colossal failures of the Bush administration. Not just the decision to invade Iraq in the first place, but failing to address the aftermath and allowing the chaos to go on, month after month after month. <p>
Some of my older Iraqi friends, who had lived through the decade of military coups from 1958 to 1968, said, "Don't you Americans know how to run a proper military coup? You topple the regime. You capture the airwaves. You announce the fall of the old regime and tell the people who is now in power. Then you announce an immediate curfew, telling people to go to their homes and clear the streets." It's all about trying to establish order as quickly as possible. "Then you say, 'Show up to your jobs by 8 a.m. the following morning.'" It's about capturing the top of a regime without creating chaos.<p>
That's not what we saw--and very quickly, a lot of Iraqis began to question our intentions, for very good reasons. If we were still on the same original script that I believe the neo-cons--Paul Wolfowitz, Douglas Feith, Richard Perle and others--had, Paul Bremer would still be in Baghdad right now. Iraq's oil sector would be in the process of being privatized. There would not have been elections. And we would be going down the road to seeing Iraq become the next Vietnam. <p>
However, the neo-con dream ran up against a huge barrier. It's called reality, and it's the obstacles that Iraqis themselves--the Iraqi leadership, as well as the resistance--created for them. It was because of that original script that we saw a resistance. It's not just anti-Iraq forces. We are seeing a resistance concerned about U.S. intentions. Some of that is changing, and I would argue that what's crucial is bringing as many of those who are part of the resistance into the political process. <p>
Another source of political violence comes from a classic insurgency. We're talking about an organized effort to use violence to overthrow a constituted government--in this case, Iraq's transitional government. An effort to prevent any fundamental change in Iraq's political order. <p>
This includes a lot of those who were formerly part of the regime--and again, part of this is fueled by huge mistakes on the part of the Bush administration. Disbanding Iraq's national army was not a really smart idea--putting hundreds of thousands of men out on the streets with guns and no paycheck. The purging of 30,000 or more civil servants who were members of the Baath Party, despite the fact that many joined the party to be able to protect their families or to advance in their careers. They were also turned away onto the streets, many of them summarily. <p>
That fueled an insurgency among people in certain provinces--like Niniwa Province, where we saw a very small voter turnout in the election, about 17 percent; or Anbar Province, where voter turnout was 2 percent. These provinces don't feel like they have a stake in Iraq's future, and as a result, some Iraqis have chosen bullets over ballots in an effort to prevent the change that they fear might be coming. <p>
There is a third factor, and this we saw starting in August 2003, and progressively getting worse. My wife and I were on our honeymoon in Nova Scotia when we got word of the terrorist attack on the United Nations headquarters in Iraq. I've talked with UN officials, and to this day, it's as though I walked into the State Department under the Clinton administration, shortly after the "Black Hawk Down" incident. <p>
My wife is in Rwanda right now, which this week commemorates the anniversary of the genocide that took place there. The inability of the Clinton administration and the State Department to respond to a clear genocide is connected to what had occurred in Somalia, and the unwillingness to act on the part of Washington, D.C. to put any Americans at similar risk. That was a grave injustice that we cannot allow again. <p>
The terrorism that began with the August 2003 attack on the UN has continued. In 2004, more than 170 Shiite pilgrims were targeted and killed during the Ashura festival. In February, during the most recent Ashura festival, another 70 pilgrims were killed. Then the bombing in Hillah--killing 127 innocent civilians. We see it over and over again, terrorists killing noncombatants, especially Shiites. <p>
So those are the three factors. Those are the three primary sources of political violence, and that is what we leave the Iraqi people to, if we leave before the transitional government and the Iraqi people are able to provide for their own security. That's why I do not support an immediate withdrawal. <p>
However, there has to be a move toward withdrawal. I strongly believe that the most responsible way out of Iraq is through capacity-building, and capacity-building doesn't mean the United States goes with our people and builds institutions. It's about providing Iraqis with the assistance that they need to build their own institutions. <p>
I want to briefly outline the four goals of EPIC's peace plan for Iraq and emphasize that progress towards each of these goals is essential for ending the war in Iraq.<p>
The first goal is the protection of civilians and human rights. Abu Ghraib was an appalling failure. We're still seeing violations of human rights--both at the hands of Americans, I believe, and at the hands of Iraq's militias and transitional government. That can't happen. <p>
Second, we need to see progress in the development of Iraq's institutional capacity for security, the rule of law and the prevention of corruption. <p>
Corruption is a serious issue. It's a legacy of Saddam's regime. It's also the product of the past two years of chaos. The $8.8 billion that cannot be fully accounted for following the collapse of the entire banking system in Iraq. Ministries did not have adequate records for payroll because of post-invasion looting and destruction. Money was delivered to ministries to maintain payroll and try to get things restarted, and there was insufficient accountability when those billions of dollars were being dispersed. And by the way, that wasn't our money. That was Iraq's own oil revenue. <p>
Third, we need to see more Iraqi-led reconstruction and job creation. During the Great Depression, our own unemployment here went beyond 25 percent, and it was seen as destabilizing--as a national security threat. So the government created the WPA and initiated other efforts to put Americans back to work. We need to see the same efforts in Iraq. We're seeing unemployment rates of 30 percent or more among employable men in most provinces, creating a potential pool of recruits for the insurgency. <p>
Finally, we need to see increased political inclusion and reconciliation. Due to a poorly conceived election formula, Iraq's newly elected government does not proportionately represent all 18 provinces. Iraqi leaders will need to address that. And U.S. assistance should support a truth and reconciliation process similar to what South Africa has undergone.<p>
Regarding these four goals, I want to be very clear about this. We are seeing some progress, but not nearly enough. It is also important to recognize that much of the progress we are seeing is driven by Iraqi politics. But there are also some issues of concern. <p>
We saw progress last week when 64 Sunni clerics and scholars issuing a fatwa encouraging Sunni Arabs to join and cooperate with Iraq's emerging security forces--that's progress. The announcement today of the formation of a presidential council that will name Iraq's new prime minister. We're a step closer. We're not quite there. <p>
The Transitional Administrative Law that the U.S. advised--in at times a heavy-handed way, I think--is somewhat of a straightjacket. The more that Iraq takes steps away from the legacy of Paul Bremer, the better. <p>
The recent elections with 8 million Iraqis turning out to vote. The formation of a transitional government.  The writing of their own constitution. Another round of direct elections.  Every step is a step away from U.S. control. And coupled with effective capacity-building, we can end the need for U.S. forces to remain in Iraq. <p>
There are billions of dollars of U.S. assistance that have yet to be spent--money that has already been allocated by Congress. By promoting policies that support EPIC's four goals, we can create conditions that lead to a responsible U.S. withdrawal, while supporting Iraq's transition to a fully independent and stable democracy.<p>
<i>Eric submitted an edited version of his presentation for this feature</i>.

<?php include "../../legacy-includes/BottomNavLinks.htmlf" ?>

<td width="12"></td>

<td width="108" valign="top">
<?php include "../../legacy-includes/RightAdFolder.htmlf" ?>
</td>
</tr>
</table>

</body>
</html>
