<html>
<head>

<title>
Los EE.UU. acecha al presidente venezolano
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="5"><b>Los EE.UU. acecha al presidente venezolano</b></font></P>
<P><font face="Times New Roman, Times, serif" size="2"><b>por Bridget Broderick</b></font><font face="Arial, Helvetica, sans-serif" size="2"> | 5 de abril de 2002 | P&aacute;gina 3</font></P>
<font face="Times New Roman, Times, serif" size="3"><P>En lo que aparenta ser un ataque orquestado contra el presidente venezolano Hugo Ch&aacute;vez Fr&iacute;as, la prensa estadounidense y la dom&eacute;stica se han aliado con militares, los grandes negocios, la iglesia cat&oacute;lica, e incluso con altos oficiales de los sindicatos en protestas organizadas en las calles, en conferencias de prensa y en editoriales diarios exigiendo que el presidente renuncie a su cargo. </P>
<P>Desde su elecci&oacute;n en 1998, Ch&aacute;vez nunca ha sido popular con la clase gobernante venezolana, ni con los bur&oacute;cratas de la confederaci&oacute;n sindical principal, ni con las administraciones estadounidenses. Hasta hace poco Washington hab&iacute;a mantenido una postura de "espera" hacia Ch&aacute;vez para evaluar c&oacute;mo su ret&oacute;rica de revoluci&oacute;n, de soberan&iacute;a nacional, y contra el neoliberalismo "salvaje" se desarrollaba en la pr&aacute;ctica.</P>
<P>Para los adversarios de Ch&aacute;vez, &eacute;l ha excedido su autoridad al implementar leyes nuevas de reforma sobre la tierra, la educaci&oacute;n, y las regal&iacute;as del petr&oacute;leo que le corresponden al estado, as&iacute; como tambi&eacute;n por su cr&iacute;tica implacable contra la prensa. La administraci&oacute;n de Bush se ofendi&oacute; cuando el presidente venezolano denunci&oacute; la guerra de EE.UU. en Afganist&aacute;n como "una lucha terrorista contra el terrorismo".</P>
<P>Es dif&iacute;cil medir el respaldo verdadero del que gozan Ch&aacute;vez o su oposici&oacute;n. La prensa corporativa nacional se opone un&aacute;nimemente a Ch&aacute;vez, as&iacute; que los sondeos tienden a ser indicadores poco confiables.</P>
<P>Los analistas han comentado que los grandes medios de comunicaci&oacute;n en Venezuela se han convertido en un tipo de partido opositor dada la ausencia de un partido pol&iacute;tico con credibilidad. Los dos partidos pol&iacute;ticos principales, Acci&oacute;n Democr&aacute;tica (AD) y COPEI (el partido cristiano dem&oacute;crata), est&aacute;n desacreditados luego de 40 a&ntilde;os de corrupci&oacute;n y patronazgo pol&iacute;tico. Ch&aacute;vez gan&oacute; contundentemente las elecciones de 1998 sobre la base de una campa&ntilde;a populista en contra de la corrupci&oacute;n de estos partidos.</P>
<P>El 6 de marzo ambos partidos, junto a la Confederaci&oacute;n de Trabajadores Venezolanos (CTV)--bajo direcci&oacute;n adeca--trabajaron mano a mano con los grandes medios noticiosos, los oficiales de la c&aacute;mara de comercio (Fedec&aacute;maras) y la iglesia cat&oacute;lica para formular un programa nebuloso ("Bases para un Acuerdo Democr&aacute;tico") con el fin de reemplazar a Ch&aacute;vez. El nuevo acuerdo declara que el estado debe respetar la "autonom&iacute;a" de las instituciones--presumiblemente las petroleras, la prensa corporativa, la iglesia cat&oacute;lica y otros grandes terratenientes. </P>
<P>Desde noviembre, los enemigos de Ch&aacute;vez se han tornado m&aacute;s vociferantes y efectivos en organizar su oposici&oacute;n p&uacute;blica. Los l&iacute;deres empresarios convocaron a un "paro patronal" para protestar las 49 leyes nuevas de Ch&aacute;vez, las cuales inclu&iacute;an la reforma de la ley de tierras, un aumento en las regal&iacute;as estatales del petr&oacute;leo de 16.6 a 30 por ciento, y un aumento en los impuestos para petroleras extranjeras como Phillips Petroleum y Exxon-Mobil.</P>
<P>Los empresarios, los oficiales de la iglesia, los profesionales de clase media, y los bur&oacute;cratas de la CTV tomaron parte en una marcha el 10 de diciembre de 2001. El mismo d&iacute;a, miles de campesinos de todo el pa&iacute;s se reunieron en Caracas para celebrar la reforma de la ley de tierras de Ch&aacute;vez, la cual reparte los latifundios, o terrenos de m&aacute;s de 5,000 hect&aacute;reas. Cada lado insiste en que sus protestas son m&aacute;s grandes y que su apoyo ha ido creciendo. </P>
<P>En los Estados Unidos, los oficiales de m&aacute;s alto rango de la administraci&oacute;n han tomado la ofensiva tambi&eacute;n. Despu&eacute;s de los comentarios de Ch&aacute;vez acerca de la guerra estadounidense en Afganist&aacute;n, la administraci&oacute;n de Bush exigi&oacute; que Venezuela condenara "inequ&iacute;vocamente " al terrorismo, y que repudiara cualquier pa&iacute;s que Bush definiera como "terrorista".</P>
<P>El 5 de febrero Colin Powell expres&oacute; su preocupaci&oacute;n por como Ch&aacute;vez comprende el "sistema democr&aacute;tico". El d&iacute;a siguiente el director de la CIA George Tenet pronostic&oacute; que la situaci&oacute;n en Venezuela empeorar&iacute;a mientras el precio del petr&oacute;leo ca&iacute;a y el descontento con Ch&aacute;vez aumentaba. </P>
<P>Por lo visto esta cr&iacute;tica de EE.UU. envalenton&oacute; a algunos oficiales militares venezolanos. El 7 y 8 febrero, el Coronel de la Fuerza A&eacute;rea, Pedro Soto, y el Capit&aacute;n de la Guardia Nacional, Pedro Flores, llevaron a cabo una protesta peque&ntilde;a en que le pidieron al presidente venezolano que renunciara.</P>
<P>Manifestantes pro-Ch&aacute;vistas hicieron una contraprotesta frente al Palacio de Miraflores. Los inversionistas, temiendo inestabilidad, sacaron miles de millones de d&oacute;lares del pa&iacute;s. Pero cuando el Vice-almirante de la armada Carlos Molina Tamayo pidi&oacute; tambi&eacute;n la renuncia de Ch&aacute;vez el 18 de febrero, hubo poca respuesta. </P>
<P>La oposici&oacute;n dom&eacute;stica a Ch&aacute;vez ha crecido, pero no es el "argentinazo" que los medios estadounidenses pintan. El 13 de enero de 2002, <I>El Nacional</I> public&oacute; un documento an&oacute;nimo titulado "Manifiesto Militar de Caracas" que le advert&iacute;a a Ch&aacute;vez que cambiara la direcci&oacute;n econ&oacute;mica y pol&iacute;tica del pa&iacute;s.</P>
<P>El Coronel Soto reclama que un 75 por ciento de las fuerzas armadas est&aacute;n en contra de Ch&aacute;vez, pero que no han realizado ninguna rebeli&oacute;n activa. Soto tiene sus propios intereses. El era ayudante del ex-presidente Carlos Andr&eacute;s P&eacute;rez, que ahora espera rehabilitarse en la pol&iacute;tica venezolana. Ch&aacute;vez fue quien trat&oacute; de derrocarlo en un golpe militar infructuoso en 1992. </P>
<P>Sin embargo, hay indicios de que secciones del ej&eacute;rcito no est&aacute;n satisfechas con el presidente. El papel m&aacute;s prominente de los militares en las obras p&uacute;blicas del pa&iacute;s ha causado cierto descontento entre sus filas. Estas muestras de descontento son significativas--despu&eacute;s de todo, Ch&aacute;vez fue paracaidista, y concibe al ej&eacute;rcito como el coraz&oacute;n de sus "fuerzas revolucionarias".</P>
<P>Ch&aacute;vez encara hoy una crisis pol&iacute;tica dom&eacute;stica a la misma vez que enfrenta las fuerzas implacables del mercado mundial y "el neoliberalismo salvaje". El Fondo Monetario Internacional (FMI) ha expresado p&uacute;blicamente que apoyar&iacute;a econ&oacute;micamente a un r&eacute;gimen m&aacute;s sumiso y "democr&aacute;tico" en Venezuela.</P>
<P>Desde luego, a los EE.UU. no le importa la "democracia" tanto como la estabilidad de las inversiones estadounidenses en la compa&ntilde;&iacute;a petrolera del estado venezolano, Petr&oacute;leos de Venezuela (PDVSA). Venezuela es el tercer exportador mayor de petr&oacute;leo a los Estados Unidos, y fuera del Medio Oriente, el m&aacute;s grande. Las nuevas leyes de Ch&aacute;vez reducen considerablemente las ganancias de los amiguitos de Bush.</P>
<P>Frente a la creciente inestabilidad econ&oacute;mica y social en la Argentina y en Colombia, pa&iacute;s colindante con Venezuela, los EE.UU. preferir&iacute;an un gobierno m&aacute;s amistoso cuyos intereses coincidieran con los del FMI, con las ganancias petroleras, y con el Pent&aacute;gono. </P>
<P>Cu&aacute;ndo fuerzas dentro del ej&eacute;rcito venezolano y de la derecha pidieron recientemente a la administraci&oacute;n de Bush que opinara sobre un golpe militar, se les dijo que buscaran "medidas democr&aacute;ticas" para sacar a Ch&aacute;vez, ya que una mayor&iacute;a abrumadora lo hab&iacute;a elegido en 1998.</P>
<P>Los EE.UU. nunca se han opuesto a las dictaduras militares en base a criterios democr&aacute;ticos, sino que los juzga a partir de si el r&eacute;gimen mantiene abiertas las oportunidades para el "mercado libre" y las inversiones. Bush no ha dado p&uacute;blicamente la luz verde a un golpe militar en Caracas, quiz&aacute;s por temor a enredar la regi&oacute;n entera en un conflicto militar. Existe la posibilidad de un golpe de estado fomentado por los Estados Unidos (es decir, la CIA), aunque Washington prefiera respaldar un cambio de mando civil. </P>
<P>&#191;Es en realidad Ch&aacute;vez el "comunista" que dirige el pa&iacute;s hacia la perdici&oacute;n, como los medios nacionales lo han tildado? Como Ch&aacute;vez concibe la "Revoluci&oacute;n Bolivariana", tiene m&aacute;s que ver con abrirse un espacio nacional y regional en los mercados internacionales que fomentar una revoluci&oacute;n internacional de trabajadores. Aunque menosprecia el "neoliberalismo salvaje", el presidente busca activamente la inversi&oacute;n extranjera y no ha restringido la "flexibilidad laboral" de los patronos. </P>
<P>Siempre ha abogado por un tipo de "capitalismo con cara humana." En su primer discurso presidencial en 1999, Ch&aacute;vez lo expres&oacute; claramente: "Nuestro proyecto no es ni neoliberal ni estatal; exploramos el punto medio, donde la mano invisible del mercado se une con la mano visible del estado: tanto estado como sea necesario, y tanto mercado como posible."</P>
<P>Mientras algunas leyes nuevas favorecen a las peque&ntilde;as empresas, a los campesinos y al estado, muchas de estas reformas no benefician a los trabajadores. Una de las leyes nuevas para empleados p&uacute;blicos permite que Ch&aacute;vez declare ilegal una huelga si &eacute;l determina que las demandas del contrato son "fiscalmente irresponsables para la naci&oacute;n". Tambi&eacute;n permiten que el estado despida a las mujeres embarazadas sin aviso con tal de que se les d&eacute; seis meses de salario compensatorio.</P>
<P>Ch&aacute;vez ha desafiado a la confederaci&oacute;n sindical principal, la CTV, la cual nada tiene que envidiarle sus contrapartes sindicales mexicanas y argentinas en cuanto a su subordinaci&oacute;n completa a los partidos tradicionales corruptos que representan los intereses de la clase gobernante del pa&iacute;s. En diciembre de 2000, los electores aprobaron un refer&eacute;ndum que requer&iacute;a la elecci&oacute;n, en vez del nombramiento, de los oficiales sindicales.</P>
<P>Sin embargo, no era la intenci&oacute;n de Ch&aacute;vez el fomentar la independencia y la militancia de los trabajadores de base. Al contrario, esperaba meter a sus propios aliados pol&iacute;ticos en la burocracia. El candidato de su Movimiento V Rep&uacute;blica (MVR) no gan&oacute; y los trabajadores de base no consideran a Ch&aacute;vez como un aliado confiable contra los patronos. </P>
<P>La econom&iacute;a venezolana ha mejorado bajo Ch&aacute;vez, en gran parte debido al aumento en los precios del petr&oacute;leo durante los primeros dos a&ntilde;os de su r&eacute;gimen. La econom&iacute;a nacional ha crecido de 4 a 5 por ciento en los &uacute;ltimos dos a&ntilde;os, y la inflaci&oacute;n ha bajado de un 40 por ciento antes de Ch&aacute;vez al 13 por ciento en 2001.</P>
<P>En realidad la clase media y las corporaciones son las que se han beneficiado de esta econom&iacute;a, mas la fuga de capitales dom&eacute;sticos se estim&oacute; en $10 mil millones tan s&oacute;lo el a&ntilde;o pasado. </P>
<P>La mayor&iacute;a de los venezolanos--80 por ciento seg&uacute;n algunas estad&iacute;sticas--todav&iacute;a gana el salario m&iacute;nimo o menos. A pesar de que el desempleo ha bajado desde 1998, cerca de la mitad del pa&iacute;s est&aacute; desempleada o subempleada. Todav&iacute;a escasea la vivienda barata, y los venezolanos confrontan niveles desesperantes de crimen.</P>
<P>Aun no se ha diversificado suficientemente la econom&iacute;a del pa&iacute;s como para poder vencer su dependencia del petr&oacute;leo. Esto ha afectado el pa&iacute;s ya que el precio del petr&oacute;leo lleg&oacute; a bajar a $15 por barril en 2001. </P>
<P>Tradicionalmente los pobres y los desempleados han sido la fuente principal de apoyo de Ch&aacute;vez, pero aun en estos sectores su popularidad ha deca&iacute;do. Ch&aacute;vez mismo ha reconocido que ha bajado el n&uacute;mero de asistentes a sus manifestaciones pol&iacute;ticas. Con la ca&iacute;da de los precios del petr&oacute;leo, la falta de inversi&oacute;n extranjera y dom&eacute;stica, y las amenazas vociferantes de la clase gobernante, Ch&aacute;vez se ha refrenado de implementar pol&iacute;ticas que ayuden a los pobres.</P>
<P>El 13 de febrero , abandon&oacute; el cambio fijo del bol&iacute;var, provocando inmediatamente una inflaci&oacute;n que podr&iacute;a alcanzar el 30 por ciento este a&ntilde;o, seg&uacute;n algunos pron&oacute;sticos. Al mismo tiempo Ch&aacute;vez anunci&oacute; un recorte presupuestario de 22 por ciento y un recorte de 7 por ciento en el gasto p&uacute;blico porque se advirti&oacute; un d&eacute;ficit de $11 mil millones.</P>
<P>Aunque el presidente prometi&oacute; gastar $2 mil millones en reservas para los servicios sociales y de la vivienda, el programa de ajuste erosionar&aacute; definitivamente su popularidad con los pobres mientras empeoren sus condiciones de vida. Entretanto, el l&iacute;der ha adoptado un tono m&aacute;s conciliatorio con Fedec&aacute;maras, con los medios noticiosos, y con la Iglesia. </P>
<P>Independientemente de las buenas intenciones sobre la justicia social, la "revoluci&oacute;n" de Ch&aacute;vez no producir&aacute; un capitalismo m&aacute;s humano si la econom&iacute;a se empeora y los EE.UU. se sienten m&aacute;s confiados de imponer una "alternativa democr&aacute;tica". Los C&iacute;rculos Bolivarianos localizados en los vecindarios pobres sirven m&aacute;s como centros comunales, y a veces como fuente de "cuerpos calientes" que se puedan usar para confeccionar manifestaciones de respaldo p&uacute;blico las pol&iacute;ticas del presidente. No son organizaciones independientes que presionar&aacute;n Ch&aacute;vez para que cumpla sus promesas a los pobres. </P>
<P>No debemos compadecernos de las corporaciones venezolanas ni de las multinacionales, o de los militares que esconden sus intereses detr&aacute;s de llamados por "m&aacute;s democracia". Tenemos que criticar claramente a los pol&iacute;ticos y a las corporaciones estadounidenses y venezolanos por sus exigencias de aumentar sus ganancias sobre las espaldas de los trabajadores y los pobres. Nos oponemos categ&oacute;ricamente a cualquier intento por parte del gigante del norte de desestabilizar e intervenir en Venezuela (o en Colombia, o en la Argentina o dondequiera).</P>
<P>Pero los socialistas no necesitan mantener ilusiones en Ch&aacute;vez, como hacen muchos en la izquierda de Venezuela y de los Estados Unidos.</P>
<P>Algunos partidos y organizaciones de la izquierda, tales como el Partido Comunista de Venezuela (PCV), siguen apoyando sin cr&iacute;ticas a Ch&aacute;vez como un "revolucionario". Otros, como el Movimiento al Socialismo (MAS), que inicialmente formaba parte de la coalici&oacute;n gobernante de Ch&aacute;vez, ahora se ha unido a la oposici&oacute;n. La izquierda de los Estados Unidos se niega a criticar a Ch&aacute;vez porque &eacute;l represent&oacute; un cambio en contra de la oligarqu&iacute;a que estaba en el poder, y tambi&eacute;n porque es aliado de Fidel Castro.</P>
<P>Desgraciadamente, esta postura lleva a que los izquierdistas respalden pol&iacute;ticas presidenciales que, si no son poco democr&aacute;ticas, por lo menos son desfavorables hacia la mayor&iacute;a de los trabajadores y los pobres venezolanos. </P>
<P>Por supuesto, el fracaso del r&eacute;gimen de Ch&aacute;vez de aliviar la pobreza del pa&iacute;s y su dependencia del petr&oacute;leo se debe a factores internacionales econ&oacute;micos y pol&iacute;ticos. Pero tambi&eacute;n es verdad que la "Revoluci&oacute;n Bolivariana" se basa en el concepto errado de que al capitalismo se le puede poner una cara humana, especialmente en un pa&iacute;s que es el tercer abastecedor m&aacute;s grande de petr&oacute;leo de los Estados Unidos.</P>
<P>En &uacute;ltima instancia, el proyecto de Ch&aacute;vez no ha sido el desafiar al imperialismo en el mercado mundial, sino abrir un espacio m&aacute;s grande dentro de este para Venezuela. Esto no es un fracaso del "socialismo", es un fracaso del neoliberalismo "menos salvaje".</P>
<P>Los socialistas no tenemos que conformarnos con Ch&aacute;vez simplemente como "lo mejor que podemos lograr". Vergonzosamente, la mayor&iacute;a de la burocracia sindical venezolana se ha aliado a su clase gobernante en contra de Ch&aacute;vez.</P>
<P>Esto hace m&aacute;s urgente la tarea de organizar una izquierda y un movimiento obrero independientes que se opongan a las pol&iacute;ticas de "ajuste bolivariano". Los venezolanos deben tomar inspiraci&oacute;n del poder que han desplegado los movimientos organizados en la Argentina, y comenzar el proceso de construcci&oacute;n de un movimiento radical para defender reformas progresistas, mientras que luchan por un nuevo sistema libre de neoliberalismo e imperialismo.</P>

<!--#include virtual="/legacy-includes/BottomNavLinksObrero.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdObrero.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
