<html>
<head>

<title>
Stop this scapegoating
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Times New Roman, Times, serif" size="4">How the paranoia of their war came home to me</font><BR>
<font face="Times New Roman, Times, serif" size="5"><b>Stop this scapegoating</b></font></P>
<p><font face="Arial, Helvetica, sans-serif" size="2">May 31, 2002 | Page 8</font></p>
<font face="Times New Roman, Times, serif" size="3"><B><P>Dear <I>Socialist Worker</I>,</P>
</B><P>The paranoia generated by the "war on terrorism" came home to me today--literally. I found a note on my door from the apartment management warning residents that "terrorists may target American apartment communities by rigging explosives in units that they have rented." </P>
<P>The letter goes on to urge residents to "be vigilant and responsible if you observe any suspicious behavior within your community"--and to contact them immediately if "you see or learn of anything that could possibly endanger you or any of your neighbors." This is a perfect recipe for vigilantism and racist scapegoating. </P>
<P>Shortly after September 11, the apartment managers took it upon themselves, without consulting any of us, to hang American flags on every single apartment door. Now, in the name of safety and security, people are being asked to turn in their neighbors who may look "suspicious" (meaning act or speak differently)! What's next? </P>
<P>This is the logical outcome of Attorney General John Ashcroft's racial profiling. Apparently, if you are from the Middle East, you are guilty until proven innocent.</P>
<P>This is no different from the internment of Japanese Americans during the Second World War. But all the apologies from politicians decades later does not compensate for the trauma of the present. </P>
<P>This is why we have to organize a fightback today!</P>
<B><P>Deepa Lal,</B> Greensboro, N.C.</P>

<!--#include virtual="/legacy-includes/BottomNavLinks.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdFolder.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
