<html>
<head>

<title>
La rebeli&oacute;n Zapatista: Diez a&ntilde;os despu&eacute;s
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<P><font face="Arial, Helvetica, sans-serif" size="2"><b>LA IZQUIERDA EN DEBATE</b></font><BR>
<font face="Times New Roman, Times, serif" size="5"><b>La rebeli&oacute;n Zapatista: Diez a&ntilde;os despu&eacute;s</b></font></P>

<P><font face="Times New Roman, Times, serif" size="3">MIENTRAS QUE los patrones mexicanos brindaban por el nuevo a&ntilde;o el 1 de enero de 1994, m&aacute;s de 2,000 guerrilleros tomaron cuatro pueblos en el estado sure&ntilde;o de Chiapas. Declarando su intenci&oacute;n de marchar hasta Ciudad M&eacute;xico para derrocar al "mal gobierno", los miembros del hasta entonces desconocido Ej&eacute;rcito Zapatista de Liberaci&oacute;n Nacional (EZLN) desinflaron la petulancia de la clase gobernante mexicana. </P>
<P>El EZLN decidi&oacute; hacer su declaraci&oacute;n del D&iacute;a de A&ntilde;o Nuevo hace 10 a&ntilde;os porque ese d&iacute;a coincid&iacute;a con la fecha en que el Tratado de Libre Comercio (TLC, o NAFTA, por sus siglas en ingl&eacute;s) entraba en efecto.</P>
<P>Para los gobernantes de M&eacute;xico la membres&iacute;a en el TLC representaba la esperanza de construir una relaci&oacute;n especial--y lucrativa-- con las corporaciones estadounidenses. Pero para los campesinos ind&iacute;genas y para los agricultores que apoyaban a los Zapatistas, el TLC significaba un "certificado de defunci&oacute;n" porque socavar&iacute;a su propia producci&oacute;n agr&iacute;cola, seg&uacute;n dijo un guerrillero en una entrevista de radio.</P>
<P>En vez de celebrar la entrada de la econom&iacute;a mexicana al "primer mundo", el gobierno del entonces presidente Carlos Salinas de Gortari, desat&oacute; un ataque militar feroz sobre la poblaci&oacute;n civil de Chiapas. Pero a los pocos d&iacute;as, Salinas se vio forzado a cancelar el ataque, dado que cientos de miles de mexicanos abarrotaron el Z&oacute;calo, la plaza donde est&aacute; la sede del gobierno central, para mostrar su solidaridad con los Zapatistas. El levantamiento Zapatista revivi&oacute; una izquierda mexicana que hab&iacute;a estado inactiva por a&ntilde;os y puso sobre relieve la cuesti&oacute;n de los derechos de los 20 millones de ind&iacute;genas de M&eacute;xico.</P>
<P>Para la izquierda mundial, el levantamiento represent&oacute; el primer gran golpe contra el triunfalismo del mercado libre que hab&iacute;a reinado despu&eacute;s del colapso de la antigua URSS en 1991. Durante la pr&oacute;xima d&eacute;cada, los Zapatistas y su portavoz principal, el frecuentemente citado Subcomandante Marcos, ayudaron a popularizar la incipiente cr&iacute;tica de izquierda de la agenda librecambista de la globalizaci&oacute;n corporativa, conocida como el "neoliberalismo".</P>
<P>LANCE SELFA y STUART EASTERING examinan el levantamiento Zapatista y su impacto actual.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3"><P><I>"SOMOS UN producto de 500 a&ntilde;os de lucha: primero contra la esclavitud, entonces durante la Guerra de Independencia contra Espa&ntilde;a...Entonces para evitar ser absorbidos por el imperialismo norteamericano, entonces para promulgar nuestra constituci&oacute;n y expulsar al imperio franc&eacute;s de nuestra tierra...Despu&eacute;s la dictadura de Porfirio D&iacute;az nos neg&oacute; la justa aplicaci&oacute;n de las leyes de la Reforma, y el pueblo se rebel&oacute; y surgieron l&iacute;deres como Villa y Zapata, hombres pobres as&iacute; como nosotros".</I></P>

<P>CON ESTAS palabras de su manifiesto, los Zapatistas le anunciaron su existencia al mundo. Reclamando su "derecho inalienable" bajo la constituci&oacute;n mexicana "para alterar o modificar su forma del gobierno", ellos exigieron que el gobierno los reconociera como un beligerante en estado de guerra. Declararon su intenci&oacute;n de marchar hasta Ciudad M&eacute;xico para establecer "&aacute;reas liberadas" donde la poblaci&oacute;n obtendr&iacute;a el "derecho a elegir libre y democr&aacute;ticamente sus propias autoridades administrativas".</P>
<P>Para la mayor&iacute;a de los observadores, la aparici&oacute;n del EZLN fue una sorpresa. El EZLN surgi&oacute; de brigadas de autodefensa establecidas para defender a los campesinos del terrorismo sufrido a manos de los barones del caf&eacute; de Chiapas y de los rancheros ganaderos que usaban pistoleros para atacar a los campesinos. Marcos dijo en una entrevista que al transcurrir el tiempo, "los compa&ntilde;eros vieron que no era suficiente el hacer la autodefensa de una sola comunidad: sino el establecer alianzas con otras y para empezar a llevar a contingentes militares y paramilitares a una escala mayor".</P>
<P>Si se pudiera decir qu&eacute; acontecimiento individual empuj&oacute; a estos grupos paramilitares a embarcarse rumbo a la insurrecci&oacute;n armada esto ser&iacute;a la decisi&oacute;n del gobierno de Salinas en 1992 de revocar el Art&iacute;culo 27 de la constituci&oacute;n federal. El art&iacute;culo 27, un producto de la Revoluci&oacute;n Mexicana, garantizaba los derechos de los campesinos para peticionar la utilizaci&oacute;n de tierra privada en desuso o de la tierra del estado.</P>
<P>A partir de la Revoluci&oacute;n mexicana (acaecida casi un siglo atr&aacute;s), la calidad de la tierra distribuida bajo el Art&iacute;culo 27 hab&iacute;a ido empeorando, con s&oacute;lo cerca de una quinta parte de esta considerada como cultivable. Pero al acabar con el Art&iacute;culo 27, se esfum&oacute; la esperanza de los campesinos de alg&uacute;n d&iacute;a conseguir una parcela de tierra que pudieran considerar como suya.</P>
<P>La revocaci&oacute;n del Art&iacute;culo 27 polariz&oacute; a las comunidades ind&iacute;genas y a las organizaciones campesinas entre los que quer&iacute;an continuar con m&eacute;todos "pac&iacute;ficos" de lucha y los que escogieron la "lucha armada". La tendencia que apoyaba la "lucha armada" gan&oacute; el debate que surgi&oacute; sobre c&oacute;mo responderle al gobierno.</P>
<P>Mucho antes de que el TLC fuera aprobado por el Congreso de EE.UU., el liderato del EZLN hab&iacute;a escogido una fecha para el levantamiento. El EZLN se desarrollo a partir de los esfuerzos de la organizaci&oacute;n mao&iacute;sta Pol&iacute;tica Popular (PP). Su te&oacute;rico principal, el profesor de la Universidad Nacional Aut&oacute;noma, Adolfo Berlinguer, argument&oacute; que los estudiantes radicales y los intelectuales deb&iacute;an vivir entres las masas y organizarlas.</P>
<P>El Subcomandante Marcos ha dicho que &eacute;l fue uno de los primeros 12 activistas del PP que se trasladaron a Chiapas en 1983 para organizar una guerra de guerrillas. Los radicales operaban bajo la protecci&oacute;n de la iglesia, a menudo acompa&ntilde;ando a sacerdotes en misiones religiosas &aacute;reas rurales. Ellos exig&iacute;an "trabajo, tierra, albergue, comida, salud, educaci&oacute;n, independencia, libertad, justicia y paz" y prometieron formar un "gobierno libre y democr&aacute;tico". Mientras apelaban al nacionalismo mexicano, tambi&eacute;n hablaban a favor de la poblaci&oacute;n oprimida de ind&iacute;genas de M&eacute;xico. </P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">
<P>EL LEVANTAMIENTO de Chiapas fue el primer desaf&iacute;o guerrillero de envergadura contra el r&eacute;gimen desde los a&ntilde;os setenta. El gobierno procur&oacute; suprimir militarmente al EZLN dos veces--la primera en enero de 1994 y la otra en febrero de 1995. Ambas veces, el gobierno fue forzado a retirarse frente a protestas masivas en Ciudad M&eacute;xico, en el resto del pa&iacute;s y alrededor del mundo.</P>
<P>En mayo de 1994 los Zapatistas forzaron al gobierno a que se reuniera con sus l&iacute;deres y a que les ofreciera una serie de reformas. Estas inclu&iacute;an demandas generales que iban desde mejoras a los servicios de salud y al saneamiento hasta aumentos en los precios de productos agr&iacute;colas. El gobierno tambi&eacute;n accedi&oacute; a demandas espec&iacute;ficas dirigidas a satisfacer las necesidades de la poblaci&oacute;n ind&iacute;gena de la regi&oacute;n, tal como apoyo a emisoras de radio con programaci&oacute;n en los idiomas ind&iacute;genas.</P>
<P>El EZLN, insisti&oacute; en que la oferta del gobierno era insuficiente, y la rechaz&oacute; en junio de 1994. Desde entonces, aproximadamente 25,000 tropas rodean a los Zapatistas en las colinas de la selva del Lacand&oacute;n, mientras que el ej&eacute;rcito conduce una guerra de "baja intensidad" contra la poblaci&oacute;n de Chiapas. Despu&eacute;s de un par de a&ntilde;os de negociaciones intermitentes, el EZLN pens&oacute; que hab&iacute;a llegado a un acuerdo con los representantes del gobierno del Presidente Ernesto Zedillo en 1996. Este acuerdo, conocido como los Acuerdos de San Andr&eacute;s, establece autonom&iacute;a local para los pueblos ind&iacute;genas de M&eacute;xico, as&iacute; como nuevos derechos educativos, sociales y culturales. Este requiere cambios a las leyes federales, estatales y locales, y a la constituci&oacute;n mexicana. El acuerdo compromete al gobierno mexicano a eliminar "la pobreza, la marginalizaci&oacute;n y la participaci&oacute;n pol&iacute;tica insuficiente de millones de ind&iacute;genas mexicanos".</P>
<P>Sin embargo, despu&eacute;s de firmar los Acuerdos, el gobierno de Zedillo dio marcha atr&aacute;s y se neg&oacute; a implementar el acuerdo. Mientras tanto, el ej&eacute;rcito intensific&oacute; su "guerra sucia" contra la poblaci&oacute;n civil de Chiapas en una tentativa de socavar el apoyo a los rebeldes. El incidente m&aacute;s brutal ocurri&oacute; en diciembre de 1997, en la aldea de Acteal, donde 45 civiles, inclusive 36 mujeres y ni&ntilde;os, fueron asesinados por paramilitares apoyados por el gobierno. La masacre de Acteal tuvo como resultado la renuncia del gobierno del Ministro del Interior y del gobernador de Chiapas, que luego se supo que hab&iacute;a tenido conocimiento previo de la masacre.</P>
<P>El EZLN respondi&oacute; al impasse y al aumento en la violencia tratando de movilizar un apoyo m&aacute;s amplio del p&uacute;blico mexicano. En 1999, organiz&oacute; un consulta nacional sobre la cuesti&oacute;n de los derechos ind&iacute;genas y la implementaci&oacute;n de los Acuerdos de San Andr&eacute;s. M&aacute;s de 3 millones de mexicanos tomaron parte en la consulta, y el 95 por ciento de ellos endos&oacute; las demandas del EZLN.</P>
<P>Cu&aacute;ndo corri&oacute; como el candidato del "cambio" en 2000, el actual Presidente mexicano Vicente Fox, de la entonces oposici&oacute;n derechista del Partido de Acci&oacute;n Nacional (PAN), prometi&oacute; que resolver&iacute;a el impasse con los Zapatistas en "15 minutos". Poco despu&eacute;s de tomar el poder en diciembre de 2000, Fox se comprometi&oacute; a someter los Acuerdos de San Andr&eacute;s al Congreso en cu&aacute;l el PAN no ten&iacute;a una mayor&iacute;a. Para recaudar apoyo para la aprobaci&oacute;n de los Acuerdos, los Zapatistas y sus partidarios llevaron a cabo una caravana de 16 d&iacute;as, que llev&oacute; a Marcos y a otros comandantes del EZLN desde Chiapas hasta Ciudad M&eacute;xico entre febrero y marzo de 2001. En cada parada de la ruta, las multitudes entusiasmadas que apoyaban al EZLN y a los Acuerdos recibieron la caravana. Tanto como un cuarto de un mill&oacute;n de personas se congregaron en el Z&oacute;calo de Ciudad M&eacute;xico en solidaridad con las demandas de los Zapatistas. </P>
<P>Mas el Congreso destaj&oacute; los Acuerdos y los Zapatistas regresaron a Chiapas con las manos vac&iacute;as. Excepto por unas pocas ocasiones, desde entonces, los Zapatistas y el Subcomandante Marcos se han mantenido al margen de los acontecimientos pol&iacute;ticos. Treinta y ocho comunidades pro EZLN subsisten en Chiapas con en el apoyo de organizaciones no gubernamentales europeas y de EE.UU.</P>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">
<P>UNA D&Eacute;CADA despu&eacute;s del levantamiento, muchas de las advertencias de los Zapatistas se han convertido en realidad. Los sueldos reales de los trabajadores mexicanos han ca&iacute;do 20 por ciento desde 1994, luego de que la econom&iacute;a casi colaps&oacute; a mediados de los noventa y con una crisis internacional que comenz&oacute; a extenderse poco despu&eacute;s.</P>
<P>Cientos de miles de agricultores mexicanos han sido empujados de sus tierras y el pa&iacute;s ahora importa ma&iacute;z para sus tortillas. Estas condiciones terribles hicieron que se tiraran miles de agricultores a las calles a principios de 2003, y que las uniones m&aacute;s grandes amenazaran con una huelga general contra el plan de Fox de aumentar los impuestos a productos de primera necesidad. Las protestas culminaron en las demostraciones que ayudaron a hundir la reuni&oacute;n cumbre de la Organizaci&oacute;n Mundial del Comercio el pasado septiembre en Canc&uacute;n.</P>
<P>El levantamiento Zapatista ayud&oacute; tambi&eacute;n a forzar la apertura del sistema pol&iacute;tico mexicano. Como resultado, el partido de gobierno, el PRI, perdi&oacute; su primera elecci&oacute;n presidencial en siete d&eacute;cadas en 2000. A pesar de que no fue la &uacute;nica fuente del movimiento global contra el fundamentalismo librecambista que se extendi&oacute; a trav&eacute;s de la d&eacute;cada de los 90, el EZLN fue ciertamente parte de esa lucha.</P>
<P>Pero a pesar de todo esto, el EZLN hoy est&aacute; aislado en las monta&ntilde;as de Chiapas, incapaz de lograr que el gobierno implemente los Acuerdos de San Andr&eacute;s. Es evidente que los Zapatistas han perdido el &iacute;mpetu pol&iacute;tico que los sostuvo en los primeros a&ntilde;os despu&eacute;s de su levantamiento. Un combatiente del EZLN entrevistado durante los primeros d&iacute;as de la rebeli&oacute;n, de acuerdo a informes dijo que &eacute;l luchaba por "el socialismo como Cuba, s&oacute;lo que mejor".</P>
<P>Pero los Zapatistas no son socialistas. Al contrario, ellos mismos se sit&uacute;an expl&iacute;citamente en la tradici&oacute;n nacionalista revolucionaria mexicana de Zapata y Villa. Su "Primera Declaraci&oacute;n Selva Lacandona", publicada en la v&iacute;spera de su levantamiento, cit&oacute; la autoridad de la constituci&oacute;n mexicana para legitimizar su insurrecci&oacute;n. "Somos patriotas", declararon, "y nuestros soldados rebeldes aman y respetan nuestra bandera tricolor".</P>
<P>Cu&aacute;ndo los Zapatistas comenzaron su levantamiento, prometieron marchar hasta Ciudad M&eacute;xico y convocaron a los mexicanos a sublevarse para "deponer al dictador" Salinas. Pero a unas pocas semanas del levantamiento, el l&iacute;der del EZLN, el Subcomandante Marcos, dijo que los Zapatistas no ten&iacute;an el deseo de "tomar el poder" ni de intervenir con las elecciones planeadas para agosto de 1994.</P>
<P>Mientras todav&iacute;a hay gran simpat&iacute;a hacia los Zapatistas a lo largo del pa&iacute;s, ellos todav&iacute;a siguen aislados de la mayor&iacute;a de los mexicanos, quienes son trabajadores que viven en las &aacute;reas urbanas del pa&iacute;s y en sus inmediaciones. El EZLN ha hecho varias tentativas de establecer una red de apoyo alrededor del pa&iacute;s. Auspici&oacute; la formaci&oacute;n del Frente Zapatista de Liberaci&oacute;n Nacional (FZLN) para forjar una conexi&oacute;n con la "sociedad civil" en 1995. Desafortunadamente, una falta de enfoque claro y la deferencia excesiva hacia Marcos evitaron que el Frente creciera fuera de los confines de la izquierda existente.</P>
<P>El movimiento Zapatista ha hecho muchos cuestionamientos que desaf&iacute;an las prioridades del mercado libre. Pero ni el EZLN ni el propio Marcos creen que sea necesario deshacerse del capitalismo para lograr metas del EZLN. Aunque muchos en la izquierda de los pa&iacute;ses avanzados ensalzan a los Zapatistas como el ejemplo de una nueva clase de izquierda que "cambia al mundo sin tomar el poder", de hecho, el rechazo de los Zapatistas de "tomar el poder" indic&oacute; que ellos no estaban comprometidos a cambiar el mundo.</P>
<P>Marcos dijo a un entrevistador en 2001 que &eacute;l se consideraba "un rebelde, no un revolucionario", y que el EZLN no "piensa que todos los industrialistas son ladrones, dado que algunos han construido su riqueza por m&eacute;todos honestos y honorables...Nosotros no planeamos el regreso del comunismo primitivo, ni la implementaci&oacute;n despiadada de la igualdad".</P>
<P>Pero hoy en M&eacute;xico el sistema de libre empresa es responsable de que millones de personas est&eacute;n sumidas en la pobreza y la explotaci&oacute;n. S&oacute;lo la clase obrera de ambos lados de la frontera entre M&eacute;xico y EE.UU. tiene el poder para poner al sistema de rodillas. El derrotar las fuerzas de la globalizaci&oacute;n corporativa que aplastan a los trabajadores, campesinos e ind&iacute;genas mexicanos requerir&aacute; no s&oacute;lo una rebeli&oacute;n, sino una revoluci&oacute;n que reemplace esta sociedad cimentada sobre el lucro y la avaricia por una sociedad controlada por los trabajadores para satisfacer las necesidades humanas.</P>


<!--#include virtual="/legacy-includes/BottomNavLinksObrero.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdObrero.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
