<html>
<head>

<title>
"En todas partes, las fuerzas oficiales de socorro fueron insensibles, ineptas y racistas"</b></font> <p>
</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--#include virtual="/legacy-includes/Script.htmlf" -->
</head>

<body bgcolor="#FFFFCC" text="000000" link="990000" vlink="660000" alink="003366" leftmargin="0" topmargin="0">
<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="474"><a name="Top"></a><!--#include virtual="/legacy-includes/TopLogo.htmlf" --></td>

<td width="270"><!--#include virtual="/legacy-includes/TopAd.htmlf" -->
</td></tr></table>

<table width="744" cellspacing="0" cellpadding="0" border="0">
<tr><td width="18" bgcolor="FFCC66"></td>

<td width="108" bgcolor="FFCC66" valign=top><!--#include virtual="/legacy-includes/LeftButtons.htmlf" --></td>

<td width="18"></td>

<td width="480" valign="top">
<!--#include virtual="/legacy-includes/BodyInsert.htmlf" -->

<font face="Times New Roman, Times, serif" size="2"><b>Por Larry Bradshaw y Lorrie Beth Slonsky</b></font><br>
<font face="Times New Roman, Times, serif" size="5"><b>"En todas partes, las fuerzas oficiales de socorro fueron insensibles, ineptas y racistas"</b></font> <p>
<font face="Arial, Helvetica, sans-serif" size="2">septiembre-octubre de 2005 | p&aacute;gina 4</font><p>

<font face="Times New Roman, Times, serif" size="3">&Eacute;ste es el testimonio de dos param&eacute;dicos que asist&iacute;an a una conferencia y se vieron atrapados por el Hurac&aacute;n Katrina en Nueva Orle&aacute;ns. Esta traducci&oacute;n del testimonio original, que apareci&oacute; por primera vez en ingl&eacute;s en <i>Socialist Worker</i>, se puede encontrar en la p&aacute;gina de Web de <a href="http://www.rebelion.org" target="_blank">www.rebelion.org</a>.<p>
<p><font face="Arial, Helvetica, sans-serif" size="1">- - - - - - - - - - - - - - - -</font></p>

<font face="Times New Roman, Times, serif" size="3">Dos d&iacute;as despu&eacute;s que el Hurac&aacute;n Katrina azotara Nueva Orle&aacute;ns, la tienda Walgreen, ubicada en la esquina de las calles Royal e Iberville, permanec&iacute;a cerrada. A trav&eacute;s de los cristales, se pod&iacute;a ver claramente la vitrina de los productos l&aacute;cteos. Ya hab&iacute;an pasado 48 horas sin electricidad ni agua corriente. La leche, el yogur y los quesos estaban comenzando a deteriorarse con una temperatura de 32 grados. Los propietarios y gerentes hab&iacute;an cerrado con llave la comida, el agua, los culeros y las medicinas y hab&iacute;an huido de la ciudad. Afuera de la tienda, los residentes y turistas ten&iacute;an cada vez m&aacute;s sed y hambre.<p>
La tantas veces prometida ayuda federal, estatal y local nunca se materializ&oacute; y los cristales de la tienda Walgreen cedieron ante los saqueadores. Hab&iacute;a una alternativa. Los polic&iacute;as pod&iacute;an haber roto una peque&ntilde;a ventana y distribuido las nueces, los jugos de frutas y las botellas de agua de forma organizada y sistem&aacute;tica, pero no lo hicieron. Por el contrario, se pasaron horas jugando al rat&oacute;n y el gato, persiguiendo a ratos a los saqueadores.<p>
Finalmente, nos sacaron por aire de Nueva Orle&aacute;ns hace dos d&iacute;as y llegamos a casa ayer (domingo, el 4 de septiembre). Todav&iacute;a no hemos visto la cobertura de la televisi&oacute;n ni hemos le&iacute;do los peri&oacute;dicos. Esperamos no encontrarnos im&aacute;genes de video ni fotos en primera plana de turistas europeos o blancos opulentos saqueando la tienda Walgreen en el Distrito Franc&eacute;s.<p>
Tambi&eacute;n sospechamos que los medios de difusi&oacute;n estar&iacute;an inundados de im&aacute;genes de "h&eacute;roes" de la Guardia Nacional, el ej&eacute;rcito y la polic&iacute;a esforz&aacute;ndose por ayudar a las "v&iacute;ctimas" del Hurac&aacute;n. Lo que ustedes no ver&aacute;n, pero s&iacute; presenciamos nosotros, es a los verdaderos h&eacute;roes y hero&iacute;nas que realizaron los esfuerzos de socorro: la clase obrera de Nueva Orle&aacute;ns. Los trabajadores de mantenimiento que utilizaron un montacargas para trasladar a los enfermos y discapacitados. Los ingenieros que montaron, alimentaron y mantuvieron funcionando los generadores. Los electricistas que improvisaron gruesas extensiones de cables a lo largo de cuadras para compartir la electricidad que ten&iacute;amos a fin de liberar los autos que estaban atascados en las zonas de parqueo de los techos. Las enfermeras que se convirtieron en ventiladores mec&aacute;nicos y estuvieron muchas horas administr&aacute;ndole aire manualmente a los pacientes inconscientes para mantenerlos con vida. Los porteros que rescataron a las personas que se hab&iacute;an quedado trabadas en los elevadores.<p>
Los trabajadores de la refiner&iacute;a que entraron a la zona de los botes y los "robaron" para rescatar a sus vecinos que permanec&iacute;an en los techos en medio de las inundaciones. Los mec&aacute;nicos que ayudaron a "puentear" los carros que pudieron encontrar para sacar a la gente de la ciudad. Y los trabajadores del servicio de alimentos que fregaron las cocinas comerciales improvisando comida comunitaria para cientos de desamparados. La mayor&iacute;a de estos trabajadores hab&iacute;an perdido sus casas y no ten&iacute;an noticias de los miembros de sus familias, sin embargo, se quedaron y ofrecieron la &uacute;nica infraestructura para el 20% de Nueva Orle&aacute;ns que no estaba bajo el agua.<p>
El segundo d&iacute;a, quedamos unas 500 personas en los hoteles del Distrito Franc&eacute;s. &Eacute;ramos una mezcla de turistas extranjeros, asistentes a la conferencia como nosotros, y personas del lugar que se hab&iacute;an alojado en los hoteles para obtener seguridad y refugiarse del Katrina. Algunos ten&iacute;amos contacto mediante tel&eacute;fonos celulares con nuestros familiares y amigos fuera de Nueva Orle&aacute;ns. Nos dijeron repetidas veces que estaban entrando a la ciudad todo tipo de recursos, incluida la Guardia Nacional y muchos &oacute;mnibus. Los &oacute;mnibus y otros recursos deben haber sido invisibles porque nunca los vimos.<p>
Decidimos que ten&iacute;amos que salvarnos por nuestra cuenta. Por lo tanto, reunimos nuestro dinero y llegamos a 25,000 d&oacute;lares para pagar diez &oacute;mnibus y salir de la ciudad. Los que no ten&iacute;an los requeridos 45.00 d&oacute;lares para el pasaje fueron ayudados por otros que ten&iacute;an dinero extra. Esperamos 48 horas a que vinieran los &oacute;mnibus y estuvimos al menos 12 horas esperando afuera del hotel, compartiendo el agua, la comida y las ropas escasas que ten&iacute;amos. Creamos una zona de abordaje de prioridad para los enfermos, ancianos y reci&eacute;n nacidos. Esperamos hasta bien entrada la noche por el arribo "inminente" de los &oacute;mnibus, que nunca llegaron. Luego supimos que en cuanto llegaban a los l&iacute;mites de la ciudad eran requisados por el ej&eacute;rcito.<p>
Al cuarto d&iacute;a, los hoteles se hab&iacute;an quedado sin combustible y sin agua. Las condiciones sanitarias eran terribles. A medida que aumentaba la desesperaci&oacute;n y la angustia, comenzaron a incrementarse los cr&iacute;menes en la calle y el nivel del agua. Los hoteles nos echaron y cerraron sus puertas, dici&eacute;ndonos que los "funcionarios" dijeron que nos dirigi&eacute;ramos al centro de convenciones para esperar los &oacute;mnibus. <p>
Cuando entramos al centro de la ciudad, finalmente encontramos a la Guardia Nacional. Los guardias nos dijeron que no pod&iacute;amos entrar al Superdome ya que el refugio primario de la ciudad se hab&iacute;a convertido en un infierno humanitario y de salud. Los guardias nos informaron que el otro refugio que quedaba, el Centro de Convenciones, tambi&eacute;n se estaba sumiendo en el caos y la suciedad y que la polic&iacute;a no estaba dejando entrar a nadie. Naturalmente, nos preguntamos: "Si no podemos ir a ninguno de los dos refugios de la ciudad, &iquest;cu&aacute;l es nuestra alternativa?" Los guardias nos dijeron que ese era nuestro problema y que no ten&iacute;an agua extra para darnos. Este ser&iacute;a el comienzo de nuestros numerosos encuentros con insensibles y hostiles "funcionarios de mantenimiento del orden".<p>
Caminamos hasta el centro de mando de la polic&iacute;a de Harrah, en la calle Canal, y nos dijeron lo mismo, que est&aacute;bamos por nuestra cuenta, y que no ten&iacute;an agua para darnos. Ya sum&aacute;bamos varios centenares de personas. Celebramos una reuni&oacute;n masiva para decidir nuestro curso de acci&oacute;n. Acordamos acampar fuera del puesto de mando de la polic&iacute;a. Estar&iacute;amos bien visibles para la prensa y constituir&iacute;amos una situaci&oacute;n bien embarazosa para los funcionarios de la ciudad. La polic&iacute;a nos dijo que no nos pod&iacute;amos quedar. No obstante, comenzamos a acampar. <p>
En poco tiempo, el jefe de la polic&iacute;a cruz&oacute; la calle y se dirigi&oacute; a nuestro grupo. Nos dijo que hab&iacute;a una soluci&oacute;n: deb&iacute;amos caminar hasta la autopista de Pontchartrain y atravesar el mayor puente de Nueva Orle&aacute;ns donde la polic&iacute;a ten&iacute;a &oacute;mnibus esperando para sacarnos de la ciudad. La multitud se alegr&oacute; y comenz&oacute; a moverse. Llamamos a todos para que regresaran y le explicamos al jefe que nos hab&iacute;an desinformado mucho y le preguntamos si estaba seguro de que los &oacute;mnibus nos estaban esperando. El jefe se volvi&oacute; hacia la multitud y dijo enf&aacute;ticamente: "Les juro que los &oacute;mnibus est&aacute;n all&iacute;".<p>
Las doscientas personas nos organizamos y salimos hacia el puente con gran entusiasmo y esperanzas. Cuando pasamos por el centro de convenciones, muchas personas del lugar vieron nuestra actitud decidida y optimista y nos preguntaron hacia d&oacute;nde nos dirig&iacute;amos. Les contamos las buenas nuevas. Inmediatamente, las familias tomaron sus pocas pertenencias y nuestro grupo se duplic&oacute;, y se volvi&oacute; a duplicar. Se nos unieron beb&eacute;s en coches, personas con muletas, ancianos con bastones y en sillas de ruedas. Caminamos las 2-3 millas hasta la autopista y subimos por la pendiente hacia el puente. Comenz&oacute; a llover, pero esto no agu&oacute; nuestro entusiasmo.<p>
A medida que nos acerc&aacute;bamos al puente, los alguaciles de Gretna formaron una l&iacute;nea a lo largo del final del puente. Antes de acercarnos lo suficiente para hablar, comenzaron a disparar sobre nuestras cabezas. La multitud corri&oacute; en diferentes direcciones. Mientras la multitud se disgregaba y disipaba, algunos de nosotros nos acercamos poco a poco y logramos conversar con algunos de los alguaciles. Les contamos nuestra conversaci&oacute;n con el jefe de la polic&iacute;a y lo que nos asegur&oacute;. Los alguaciles nos informaron que no hab&iacute;a &oacute;mnibus esperando. El jefe de la polic&iacute;a nos minti&oacute; para que nos fu&eacute;ramos.<p>
Preguntamos por qu&eacute; no pod&iacute;amos cruzar el puente, especialmente si hab&iacute;a poco tr&aacute;fico en la autopista de 6 carriles. Respondieron que el West Bank no se iba a convertir en otro Nueva Orle&aacute;ns y que no habr&iacute;a Superdome en esa ciudad. Estas eran palabras en c&oacute;digo que quer&iacute;an decir que si eras pobre y negro no pod&iacute;as cruzar el R&iacute;o Mississippi y no pod&iacute;as salir de Nueva Orle&aacute;ns.<p>
Nuestro peque&ntilde;o grupo retrocedi&oacute; hacia la Autopista 90 para buscar refugio de la lluvia bajo un paso superior. Analizamos nuestras opciones y al final decidimos construir un campamento en el medio de la Autopista Ponchartrain en la divisi&oacute;n central, entre las salidas O'Keefe y Tchoipitoulas. Pensamos que estar&iacute;amos a la vista de todos, que tendr&iacute;amos alguna seguridad al estar en una autopista elevada y que podr&iacute;amos esperar y vigilar la llegada de los susodichos &oacute;mnibus.<p>
Durante todo el d&iacute;a, vimos a otras familias, individuos y grupos dirigirse a la pendiente con el fin de cruzar el puente, solo para ser rechazados. Algunos fueron dispersados a tiros, otros recibieron un no y otros fueron verbalmente vituperados y humillados. A miles de ciudadanos de Nueva Orle&aacute;ns les impidieron y les prohibieron autoevacuarse de la ciudad a pie.<p>
Mientras, los &uacute;nicos dos refugios de la ciudad se hund&iacute;an en la mugre y la desesperaci&oacute;n. La &uacute;nica forma en que se pod&iacute;a cruzar el puente era en un veh&iacute;culo. Vimos a trabajadores robar camiones, &oacute;mnibus, camiones de mudanzas, camionetas y cualquier auto que pudiera ser puenteado. Todos estaban atestados de personas que trataban de escapar de la desgracia en que hab&iacute;a ca&iacute;do Nueva Orle&aacute;ns.<p>
Nuestro peque&ntilde;o campamento comenz&oacute; a crecer. Alguien rob&oacute; un cami&oacute;n de entrega de agua y nos lo trajo. &iexcl;Que digan que fue saqueo! A una milla del lugar, en una curva muy cerrada, un cami&oacute;n del ej&eacute;rcito perdi&oacute; un par de pallets de raciones enlatadas para campa&ntilde;a. Trasladamos la comida hacia nuestro campamento en carritos de supermercados. Ya seguros con nuestras dos necesidades cubiertas, comida y agua, floreci&oacute; la cooperaci&oacute;n, la comunidad y la creatividad. Organizamos una limpieza y colgamos las bolsas de basura de los postes. Hicimos camas con los pallets de madera y cart&oacute;n. Designamos un desag&uuml;e de aguas de lluvia como ba&ntilde;o y los muchachos construyeron una estructura elaborada de pl&aacute;stico, sombrillas rotas y otros materiales de desecho para nuestra privacidad. Hasta organizamos un sistema de reciclaje de la comida para que las personas pudieran intercambiar los alimentos (compotas de manzana para los beb&eacute;s, caramelos para los ni&ntilde;os).<p>
Esto lo vimos muchas veces luego del paso de Katrina. Cuando la gente ten&iacute;a que luchar por conseguir comida o agua, ten&iacute;a que buscarla por s&iacute; misma. Hab&iacute;a que hacer lo que fuera para encontrar agua para los ni&ntilde;os o comida para los padres. Cuando estas necesidades b&aacute;sicas estaban satisfechas, la gente empezaba a preocuparse por los dem&aacute;s, a trabajar juntos y construir una comunidad.<p>
Si las organizaciones de socorro hubieran saturado la ciudad de alimentos y agua en los primeros 2 &oacute; 3 d&iacute;as, no se hubiera producido una situaci&oacute;n de desespero, frustraci&oacute;n y peligro. Satisfechas nuestras necesidades, ofrecimos comida y agua a las familias e individuos que pasaban por all&iacute;. Muchos decidieron quedarse y unirse a nosotros. Nuestro campamento creci&oacute; hasta llegar a 80 &oacute; 90 personas. Supimos por una mujer que ten&iacute;a un radio port&aacute;til que la prensa estaba hablando de nosotros. Como est&aacute;bamos a plena vista desde la autopista, todas las organizaciones de socorro y noticiosas nos vieron cuando se dirig&iacute;an a la ciudad. A los funcionarios les preguntaban qu&eacute; iban a hacer con todas las familias que estaban viviendo en la autopista. Los funcionarios respondieron que se iban a ocupar de nosotros. Algunos de nosotros sentimos una sensaci&oacute;n de hundimiento. "Ocuparse de nosotros" ten&iacute;a un tono siniestro.<p>
Desafortunadamente, nuestra sensaci&oacute;n de hundimiento (junto con la ciudad sumergida) demostr&oacute; ser cierta. Al caer la tarde, se apareci&oacute; un alguacil de Gretna, se baj&oacute; del carro patrullero, apunt&oacute; con su pistola a nuestros rostros y grit&oacute;: "Salgan de la condenada autopista". Un helic&oacute;ptero lleg&oacute; y utiliz&oacute; el aire que provocan las aspas para tumbar nuestras endebles estructuras. A medida que nos retir&aacute;bamos, el alguacil carg&oacute; un cami&oacute;n con nuestros alimentos y agua. Una vez m&aacute;s, a punta de pistola, nos obligaron a salir de la autopista. Todos los &oacute;rganos de mantenimiento del orden parec&iacute;an amenazados cuando nos congreg&aacute;bamos o form&aacute;bamos grupos de 20 o m&aacute;s. En cada congregaci&oacute;n de "v&iacute;ctimas" ellos ve&iacute;an un "tumulto" o un mot&iacute;n". Nosotros nos sent&iacute;amos seguros con el grupo. Nuestro objetivo de "tenemos que permanecer juntos" era imposible porque los &oacute;rganos policiales nos obligaban a separarnos en peque&ntilde;os grupos.<p>
En el pandemonio de la invasi&oacute;n y destrucci&oacute;n de nuestro campamento, nos dispersamos una vez m&aacute;s. Reducidos a un grupo de ocho, en la oscuridad, buscamos refugio en un &oacute;mnibus escolar abandonado, bajo la autopista de la Calle Cilo. Nos escond&iacute;amos de posibles elementos criminales, pero de igual forma, nos escond&iacute;amos de la polic&iacute;a y los alguaciles con sus pol&iacute;ticas de ley marcial, toque de queda y disparar a matar.<p>
En los d&iacute;as siguientes, nuestro grupo de ocho personas camin&oacute; la mayor parte del d&iacute;a, entr&oacute; en contacto con el Departamento de Bomberos de Nueva Orle&aacute;ns y fuimos posteriormente sacados por aire por un equipo de b&uacute;squeda y rescate urbano. Nos dejaron cerca del aeropuerto y logramos trasladarnos en veh&iacute;culos de la Guardia Nacional. Los dos guardias j&oacute;venes se disculparon por la respuesta limitada de los guardias de Louisiana. Explicaron que una gran secci&oacute;n de su unidad se encontraba en Iraq y que eso significaba que les faltaba personal y no pod&iacute;an cumplir con todas las tareas asignadas.<p>
Llegamos al aeropuerto el d&iacute;a en que comenzaba un puente a&eacute;reo de grandes proporciones. El aeropuerto se hab&iacute;a convertido en otro Superdome. Los ocho nos vimos atrapados en una multitud porque los vuelos se demoraban varias horas mientras George Bush aterriz&oacute; brevemente en el aeropuerto para tomarse unas fotos. Luego de ser evacuados en un avi&oacute;n de carga de guardafronteras, llegamos a San Antonio, Texas.<p>
All&iacute; continu&oacute; la humillaci&oacute;n y deshumanizaci&oacute;n de las fuerzas oficiales de socorro. Nos montaron en &oacute;mnibus y nos llevaron a un extenso campo donde nos obligaron a sentarnos durante horas y horas. Algunos de los &oacute;mnibus no ten&iacute;an aire acondicionado. En la oscuridad, cientos de nosotros tuvimos que compartir dos orinales sucios y desbordantes. Los que lograron traer algunas pertenencias (generalmente en bolsas pl&aacute;sticas destartaladas) eran sometidos a dos cateos diferentes con perros.<p>
La mayor&iacute;a de nosotros no hab&iacute;a comido en todo el d&iacute;a porque nos hab&iacute;an confiscado las raciones de campa&ntilde;a en el aeropuerto al desatarse la alarma de los detectores de metal. Sin embargo, no le dieron comida a los hombres, mujeres, ni&ntilde;os, ancianos, discapacitados que estuvieron horas sentados esperando a ser "examinados m&eacute;dicamente" para asegurarse de que no ten&iacute;an enfermedades contagiosas.<p>
Este tratamiento oficial contrastaba grandemente con la calurosa y sentida recepci&oacute;n que nos dieron los texanos comunes y corrientes. Vimos a una trabajadora del aeropuerto darle sus zapatos a otra persona que estaba descalza. Desconocidos en la calle nos ofrecieron dinero y art&iacute;culos de tocador con palabras de bienvenida. En todas partes, las fuerzas oficiales de socorro fueron insensibles, ineptas y racistas. Hubo m&aacute;s sufrimiento que el que deb&iacute;a haber. Se perdieron vidas que no debieron perderse.<p>

<!--#include virtual="/legacy-includes/BottomNavLinksObrero.htmlf" -->

<td width="12"></td>

<td width="108" valign="top">
<!--#include virtual="/legacy-includes/RightAdObrero.htmlf" -->
</td>
</tr>
</table>

</body>
</html>
